### ISSUE TITLE
浏览器调试，autoplay为false或者不写，出现网络连接似乎出现问题界面

### ISSUE THREAD

**Issue by imply-wh** [bytedance/xgplayer#100]
autoplay为false或者不写时出现网络连接似乎出现问题界面，刷新也没用，为true时就没问题，手机调试时这个问题不存在。

**Comment by zhangxin92** [comment]
You can try to write your xgplayer configuration code [here](http://h5player.bytedance.com/examples/?type=vod&plugin=xg-mp4) for excluding influences of other code.

**Comment by zhangxin92** [comment]
Thanks for the feedback. The problem is recurring. We will fix it soon.
