### ISSUE TITLE
在vue3+ts项目中根本无法使用啊

### ISSUE THREAD

**Issue by yhuayang233** [bytedance/xgplayer#1000]
![image](https://github.com/bytedance/xgplayer/assets/133995431/6ed2fe59-d873-491a-bd9a-5d30020ec24e)
报错提示：
![image](https://github.com/bytedance/xgplayer/assets/133995431/89d19a2f-3cae-4b2b-8efa-99d1dcc50251)
接下来把css文件也加上还是报错：
![image](https://github.com/bytedance/xgplayer/assets/133995431/3cfc2c17-7577-43f0-9325-07bfe23d4f6d)

**Comment by itchaox** [comment]
可以使用，你代码可能写的有问题

**Comment by zhongerbing666** [comment]
建议直接通过ref传递dom给Player。因为你传id过去的时候，还是setup的阶段，取不到真实dom。onMounted才能取到

**Comment by dayudada** [comment]
可以使用的，你这个貌似npm没有正确安装库，提示你没找到xgplayer的模块，如果正确安装了，不会提示找不到模块的。正确安装后在onMounted 中初始化，是没有任何问题的

**Comment by xing403** [comment]
需要在 onMounted中，在生成player时，若`<div id='vs' />`还没有渲染就会这样
> TS / JS
```ts
import { ref, onMounted } from 'vue'
import Player from 'xgplayer';
import 'xgplayer/dist/index.min.css';

const mse = ref(null);
const player = ref(null);
function createPlayer() {
  player.value = new Player({
    id: mse.value.id,
    url: '',
    height: '100%',
    width: '100%',
  });
}
onMounted(() => {
  createPlayer();
})
```html
<div ref="mse" id="mse" />
```

**Comment by shanyutongxue** [comment]
vue3 项目中可以使用的，建议参考上方回答进行验证
