### ISSUE TITLE
播放器controls、definition插件异常遮挡

### ISSUE THREAD

**Issue by JasonSubMara** [bytedance/xgplayer#1001]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
^3.0.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS 16.5.1 
All  Browser For Mobile

**如何复现问题？ How to reproduce the problem?**

因项目实际相关，暂时无法提供，如果能协助排查，可邮件联系，jie.yr127@gmail.com

**您期望的播放器正常行为是？ What did you expect to happen?**

切换清晰度后，controls 层 不被视频内容遮挡

**实际播放器的表现是？ What actually happened?**
切换清晰度后，controls 层 会被 视频内容遮住，目前已排查相关结构代码，切换清晰度后相关DOM结构未发生变化

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

相关产品业务：在线课程培训

**Comment by gemxx** [comment]
video元素是如何被业务的CSS影响的，可以贴一下具体代码吗？

**Comment by JasonSubMara** [comment]
不是业务的 CSS 影响，而是我们使用的是 uni-app 框架，在构建的时候 video 元素做了额外处理，最终css内变成 uni-video。从而导致样式异常。我们最终采取的方式，不是在播放器组件内引入 import 'xgplayer/dist/index.min.css'; 而是在 uniapp 入口文件中引入<link rel="stylesheet" href="<%= BASE_URL %>static/css/xgplayer.min.css"> ,避免其被处理。

**Comment by JasonSubMara** [comment]
![image](https://github.com/bytedance/xgplayer/assets/30927318/3bb1ef03-9223-4131-a7ef-03b6ba099ab2)
之前我们的使用方式，组件内引入 
<img width="525" alt="image" src="https://github.com/bytedance/xgplayer/assets/30927318/dc97103f-bb81-4402-a95b-7d1e98cd0109">
后来为了避免被额外处理，我们在入口文件内修改了引入
<img width="661" alt="image" src="https://github.com/bytedance/xgplayer/assets/30927318/62f0f9c1-cf17-49c7-8b26-ad7afa7cfb74">
 如此便解决了样式异常的问题，后来通过查看源码并提交了 PR，https://github.com/bytedance/xgplayer/pull/1004，给 video 加上 class，避免可能出现的其他第三方框架构建时处理 css 的情况～
