### ISSUE TITLE
建议增加：长按(向右)方向键开启三倍速播放

### ISSUE THREAD

**Issue by ktech0** [bytedance/xgplayer#1003]
而不是简单的快进进度条

**Comment by hongqx** [comment]
v3.0.9版本快捷键right支持长按倍速，目前默认倍速是2倍速，可配置，配置方式如下
new Player({
   keyboard：{
      playbackRate: 2
   }
})

**Comment by hongqx** [comment]
v3.0.9版本快捷键right支持长按倍速，目前默认倍速是2倍速，可配置，配置方式如下
`new Player({
keyboard：{
playbackRate: 2
}
})`

**Comment by hongqx** [comment]
3.0.9版本支持快进键长按倍速，目前默认是长按2倍速，可配置，具体配置方式如下

`new Player ({
    ...,
    keyboard: {
        playbackRate: 2
    }
})`
