### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by ashuicoder** [bytedance/xgplayer#1005]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
v3.0.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

macOS chrome

**如何复现问题？ How to reproduce the problem?**

问题咨询

**您期望的播放器正常行为是？ What did you expect to happen?**

我希望视频进度条未看的地方不能快进，看过的能快退，快退以后能快进到之前看过的地方

**实际播放器的表现是？ What actually happened?**

没有找到相关的功能和插件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

业务： 点播课程播放，需要记录学时，所以不能快进到未看的，但是看过的可以快退回去看

**Comment by gemxx** [comment]
这个需求比较偏向业务，播放器暂时不提供此功能。您可以单独制作插件，或者监听播放器相关时间实现。实现思路：
1. 监听播放器timeupdate事件，并维护更新一个播放过的range范围
2. 监听player seeking事件，判断是否在range内，如果不在则seek回之前播放点位
