### ISSUE TITLE
html播放器播放不了

### ISSUE THREAD

**Issue by xinsuinizhuan** [bytedance/xgplayer#1006]
<link rel="stylesheet" href="//unpkg.byted-static.com/xgplayer/{version}/dist/index.min.css"/>

<script src="//unpkg.byted-static.com/xgplayer/{version}/dist/index.min.js"></script>
<script src="//unpkg.byted-static.com/xgplayer-mp4/{version}/dist/index.min.js"></script>
<script>
  new window.Player({
    id: 'vs',
    plugins: [window.Mp4Plugin.default],
    url: {http://127.0.0.1:5088/Media/Camera1.mp4},
  });
</script>

上面是写的html文件，但是浏览器打开播放不了，vlc播放地址没问题

**Comment by gemxx** [comment]
MP4文件方便贴一下吗？需要实际看下播放文件
