### ISSUE TITLE
flv视频无法正常播放

### ISSUE THREAD

**Issue by qizhengzheng** [bytedance/xgplayer#1012]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

wionw  谷歌最新版
**如何复现问题？ How to reproduce the problem?**
视频地址https://www.zjttit.com/Service/getOssFile?key=upload/video/8-ch01_00000000115000000_20230714103222.flv

**您期望的播放器正常行为是？ What did you expect to happen?**
视频正常播放
**实际播放器的表现是？ What actually happened?**
做Flv点播时，30分钟左右视频播放三分钟左右后报
![image](https://github.com/bytedance/xgplayer/assets/59305784/cbecf68e-e2b3-45d2-8ece-1ba42c5d400f)

，视频只缓存了7分钟，后面的视频无法再进行播放
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by qizhengzheng** [comment]
视频地址https://kjkskw.czt.zj.gov.cn/Service/getOssFile?key=upload/video/8-ch01_00000000115000000_20230714103222.flv

**Comment by xiyuyizhi** [comment]
v3.0.6-alpha.6可以更新下。[bufferBehind](https://v3.h5player.bytedance.net/plugins/extension/xgplayer-flv.html#api) 配置参数控制清除历史buffer

**Comment by qizhengzheng** [comment]
![image](https://github.com/bytedance/xgplayer/assets/59305784/83eaff84-7cf5-4d2f-9edd-7a9bee7f732f)
还是一样，播放到缓存点后视频一直在转圈

**Comment by qizhengzheng** [comment]
![image](https://github.com/bytedance/xgplayer/assets/59305784/7d32ba9f-f6c7-4165-997e-84bcedcadce1)
