### ISSUE TITLE
下载demo中的视频到本地，然后在本地项目中引入使用，无法正常播放。

### ISSUE THREAD

**Issue by AtroxEzerel** [bytedance/xgplayer#1015]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.5 vue2
![impicture_20230719_113703](https://github.com/bytedance/xgplayer/assets/55567122/0098ef78-c8f5-4c8b-9fbc-c6361e49e4e9)

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows Chrome 114

**如何复现问题？ How to reproduce the problem?**

下载demo中的视频到本地，然后在本地项目中引入使用，无法正常播放。
![impicture_20230719_113556](https://github.com/bytedance/xgplayer/assets/55567122/1a01ee67-82f2-466f-af5f-7f71cb36fa1f)
![impicture_20230719_113610](https://github.com/bytedance/xgplayer/assets/55567122/fab9e77e-ace6-49e0-bbbe-6c6dd49564ec)
![image](https://github.com/bytedance/xgplayer/assets/55567122/0ffd0bc8-6f19-46ca-a5ae-9ce72827df7d)

**您期望的播放器正常行为是？ What did you expect to happen?**

正常播放

**实际播放器的表现是？ What actually happened?**

无法播放 提示不支持的格式

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by AtroxEzerel** [comment]
如果想要支持播放本地的静态资源视频，应该怎么配置？

**Comment by gemxx** [comment]
确认下配置的url地址在network中访问是否404

**Comment by hongqx** [comment]
用户使用环境问题，长时间没有回复，先关闭，后续需要请重新提issue
