### ISSUE TITLE
全屏后退出全屏显示错位

### ISSUE THREAD

**Issue by itldg** [bytedance/xgplayer#1020]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

官方演示页面

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

操作系统	Windows
系统版本	10
浏览器类型	Edge
浏览器版本	113.0.1774.42

**如何复现问题？ How to reproduce the problem?**

http://h5player.bytedance.com/examples/

**您期望的播放器正常行为是？ What did you expect to happen?**

正常的尺寸缩小

![image](https://github.com/bytedance/xgplayer/assets/13432299/bf65eeb6-e7e2-4fd7-85cf-d31d0a7c5743)

**实际播放器的表现是？ What actually happened?**

有些错位

![image](https://github.com/bytedance/xgplayer/assets/13432299/8048c127-c7ec-4c7b-89fb-37737af68bfe)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

暂无

**Comment by gemxx** [comment]
感谢反馈，已修复
