### ISSUE TITLE
是否支持rtsp

### ISSUE THREAD

**Issue by 905868332** [bytedance/xgplayer#1026]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
^3.0.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 谷歌

**如何复现问题？ How to reproduce the problem?**
播放源为 rtsp

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
不支持视频格式

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无

**Comment by gemxx** [comment]
不支持直接使用rtsp协议，在web端需要转换为websocket推flv流
