### ISSUE TITLE
视频暂停后的播放按钮在ios手机端的浏览器样式错乱，安卓端正常

### ISSUE THREAD

**Issue by unconstraint23** [bytedance/xgplayer#1036]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.2",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios16 +， 苹果手机端谷歌浏览器，微信端浏览器

**如何复现问题？ How to reproduce the problem?**
在视频播放后点击暂停，出现下边的情况
![0c57d51afc82049a2e156324c31b352](https://github.com/bytedance/xgplayer/assets/66302409/f71d7e16-1f94-40f8-987d-12be66833db9)

`
const videoRef = useRef<any>()
    useEffect(() => {
        new Player({
          el: videoRef.current,
          url: mp4Src,
        // isLive: true,
        hasVideo: true,
        hasAudio: true,
        autoplay: true,
        autoplayMuted: true,
        cors: true,
        fluid: true,
        lang: 'zh-cn',
        })
    },[])
`
`html:
         <div className='play' id='play' ref={videoRef}></div>
`
`css: 
.play {
        width: 100%;
        overflow: hidden;
    }`

**您期望的播放器正常行为是？ What did you expect to happen?**
按钮恢复为一个正常的大小

**实际播放器的表现是？ What actually happened?**
![0c57d51afc82049a2e156324c31b352](https://github.com/bytedance/xgplayer/assets/66302409/f71d7e16-1f94-40f8-987d-12be66833db9)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
可以提供下复现的demo源码吗？

**Comment by unconstraint23** [comment]
https://codesandbox.io/p/sandbox/optimistic-lehmann-6ntcvl

**Comment by unconstraint23** [comment]
> 可以提供下复现的demo源码吗？

这个codesandbox我不太会用，您可以新建一个react工程项目文件，复制我App.tsx文件里边的代码；
