### ISSUE TITLE
下载功能用不了, 播放用的config.url地址，下载用的player.src地址

### ISSUE THREAD

**Issue by yangjiechina** [bytedance/xgplayer#1041]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.1和3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows7/10

**如何复现问题？ How to reproduce the problem?**
直接点击下载按钮

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yangjiechina** [comment]
> 可以在具体描述一下吗？或者提供下复现的demo代码
在线生成那儿，开启下载。播放器出来下载图标后，点击下载就不行。
http://v2.h5player.bytedance.com/generate/

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.1和3.0.7
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** Windows7/10
> 
> **如何复现问题？ How to reproduce the problem?** 直接点击下载按钮
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

v3.0.9版本已修复
