### ISSUE TITLE
调用FlvPlugin播放Flv直播流时切到后台会导致播放暂停（由于暂停又会导致特殊场景下断流）

### ISSUE THREAD

**Issue by TianbinTobin** [bytedance/xgplayer#1044]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer: 3.0.7
xgplayer-flv: 3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
OS: Windows 11
Browser: Edge & Chrome  最新版本

**如何复现问题？ How to reproduce the problem?**
播放器配置
```
{
      url: url,
      id: playerId,
      width: '100%',
      isLive: true,
      autoplay: true,
      controls: false,
      keyboard: false,
      autoplayMuted: false,
      closeVideoClick: true,
      enableContextmenu: true,
      closeVideoDblclick: true,
      plugins: [FlvPlugin],
      flv: {
              bufferBehind: 10,
              maxJumpDistance: 3,
              retryCount: 3,
              retryDelay: 1000,
              loadTimeout: 10000,
              maxReaderInterval: 5000,
              analyzeDuration: 10000,
              maxLatency: 10,
              targetLatency: 5,
              disconnectTime: 10,
      },
 }
```
直播流播放会在页面切换到后台或者是切换tab页时触发暂停
```
if (isMediaPlaying(media)) {
      if (this._gapService) {
        this._gapService.do(media, opts.maxJumpDistance, this.isLive, 3)
      }
    } else {
      if (!media.currentTime && this._gapService) {
        this._gapService.do(media, opts.maxJumpDistance, this.isLive, 3)
        return
      }
      if (opts.isLive && bufferEnd > opts.disconnectTime) {
        this.disconnect()
      }
    }
```
由于切换到后台触发暂停，在这个逻辑中会触发this.disconnect()，导致flv直播流停止加载数据，当用户操作切换到另一个tab页，默数2秒再切换回来，会刚好进入这个逻辑而没有触发重新加载直播流，导致播放直接被中断提示需要Replay。

**您期望的播放器正常行为是？ What did you expect to happen?**
1、能够配置切换到后台不触发暂停 （没有在源码中找到切换到后台触发暂停的地方）
2、暂停后触发this.disconnect()后，切换回来能够正常触发重新加载
3、`bufferEnd > opts.disconnectTime` 这个判断逻辑感觉是不对的

**实际播放器的表现是？ What actually happened?**
播放直接被中断提示需要Replay

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@TianbinTobin 
1. 静音播放没开放过声音时，切后台，浏览器会自动暂停播放，触发pause事件，非播放代码控制
2. 暂停后停止拉流，切回后重新拉流，没有复现没拉流的情况
3. 切后台不想断流的话可以类似处理
```
player.on('pause', () => {
       if(document.visibilityState === 'hidden') {
         player.play()
       }
 })
```

**Comment by TianbinTobin** [comment]
> 2\. 暂停后停止拉流，切回后重新拉流，没有复现没拉流的情况

@xiyuyizhi 
这个是偶现的，我的操作方式是切换到另一个tab，默数2秒再切换回来，这样反复操作，很大概率出现，因为我配置的disconnectTime是10秒，只要开始静音播放超过10秒再切换tab触发了暂停就能稳定触发`bufferEnd > opts.disconnectTime` => `this.disconnect()`，这时候视频已经触发end()了，在缓冲区移除之前再切回来后由于还有缓存就不会触发重新加载而是触发恢复播放，缓冲播完就被认为是结束播放了，播放器上提示 Replay
