### ISSUE TITLE
发现视频旋转功能一个严重bug

### ISSUE THREAD

**Issue by frcoo** [bytedance/xgplayer#1045]
复现：打开西瓜视频播放器官网——在线生成——功能配置—— 视频旋转——开启，最后点“运行”；右边播放视频，再点旋转按钮，让视频旋转90°，然后视频就开始不停闪烁。。。，好像是在不停切换视频的宽高

**Comment by gemxx** [comment]
会在xgplayer@3.0.8版本内修复
