### ISSUE TITLE
播放m3u8出现crypto is not defined

### ISSUE THREAD

**Issue by ashoneyy** [bytedance/xgplayer#1046]
以下是完整的报错信息{
    "playerVersion": "3.0.5",
    "currentTime": 0,
    "duration": 287.67999999999995,
    "ended": false,
    "readyState": 0,
    "networkState": 2,
    "src": "blob:http://43.137.4.153:8888/ed7d0d52-e7a6-48bb-9899-c1011655d8a1",
    "errorType": "other",
    "errorCode": 8000,
    "message": "crypto is not defined",
    "mediaError": {},
    "originError": "Error: crypto is not defined\n    at a.<anonymous> (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:230:70396)\n    at c (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:18015)\n    at Generator.<anonymous> (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:19364)\n    at Generator.next (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:18374)\n    at Wr (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:24250)\n    at s (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:24448)\n    at http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:24509\n    at new Promise (<anonymous>)\n    at a.<anonymous> (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:223:24389)\n    at a.i (http://43.137.4.153:8888/assets/ItemDetail.9c1340c7.js:230:70760)",
    "host": "43.137.4.133:8888"
}

**Comment by gemxx** [comment]
播放加密流需要在https环境才能支持，并且 crypto 也只在HTTPS环境内才有这个对象

**Comment by ashoneyy** [comment]
可我是http环境 请问一下应该如何修改代码

**Comment by ashoneyy** [comment]
我本地启动的时候没有问题 然后部署到43那个服务器上就出现这个问题
