### ISSUE TITLE
视频一放到正式环境就跨域。大家没遇到过吗

### ISSUE THREAD

**Issue by baokuanze** [bytedance/xgplayer#1048]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

<img width="614" alt="image" src="https://github.com/bytedance/xgplayer/assets/14322761/c3f2d654-de36-4765-8e81-41d8b690d14a">

**Comment by gemxx** [comment]
视频地址看下是否配置了[cors相关的头](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
