### ISSUE TITLE
无法动态修改进度条特殊标记

### ISSUE THREAD

**Issue by teddyOOXX** [bytedance/xgplayer#1056]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
unubtu 20.04
EDGE 115.0.1901.188

**如何复现问题？ How to reproduce the problem?**
`

    const player = new Video({ url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4', id: 'vs' });

    const progressInstance = player.getPlugin('progress');

    const progressPreviewInstance = player.getPlugin('progresspreview');

    setTimeout(() => {

      progressPreviewInstance.setConfig({
        ispots: [
          {
            id: 0,
            time: 52 * 0.2,
            duration: 4,
            text: '123',
          },
          {
            id: 1,
            time: 52 * 0.4,
            duration: 4,
            text: '123',
          },
        ],
      });

      initDotsAPI(progressPreviewInstance);

      setTimeout(() => {

        progressPreviewInstance.setConfig({
          ispots: [
            {
              id: 0,
              time: 52 * 0.5,
              duration: 4,
              text: '12345',
            },
            {
              id: 1,
              time: 52 * 0.6,
              duration: 4,
              text: '12367',
            },
          ],
        });

        initDotsAPI(progressPreviewInstance);

      }, 5000);

    }, 1000);

`

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常修改进度条标记

**实际播放器的表现是？ What actually happened?**
不展示任何标记

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by itchaox** [comment]
我也想实现这样的效果，请问你是进度条没有更新吗？

**Comment by hongqx** [comment]
请参考文档站关于progresspreview插件的说明
https://v3.h5player.bytedance.com/plugins/internalplugins/progresspreview.html#api
