### ISSUE TITLE
已经关闭了视频点击播放暂停功能，但是我在第一次进入页面的时候点击视频中间还是能触发暂停，

### ISSUE THREAD

**Issue by Remington-Hunter** [bytedance/xgplayer#1057]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
操作系统windows10，浏览器是Chrome

**如何复现问题？ How to reproduce the problem?**
const { url, poster } = props

  const videoRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (videoRef.current) {
      const player = new Player({
        el: videoRef.current,
        url,
        poster,
        width: '100%',
        height: '100%',
        autoplay: true,
        autoplayMuted: true,
        loop: true,
        controls: false,
        closeVideoClick: true,
        closeVideoDblclick: true,
        closePlayVideoFocus: true,
      })
    }
  }, [poster, url])
这段是我的代码对player的配置

**您期望的播放器正常行为是？ What did you expect to happen?**
无论何时点击视频应该都不会使得视频暂停

**实际播放器的表现是？ What actually happened?**

进入页面第一次时候点击视频中间会使得视频暂停，不清楚这是bug还是什么原因
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.7
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** 操作系统windows10，浏览器是Chrome
> 
> **如何复现问题？ How to reproduce the problem?** const { url, poster } = props
> 
> const videoRef = useRef(null)
> 
> useEffect(() => { if (videoRef.current) { const player = new Player({ el: videoRef.current, url, poster, width: '100%', height: '100%', autoplay: true, autoplayMuted: true, loop: true, controls: false, closeVideoClick: true, closeVideoDblclick: true, closePlayVideoFocus: true, }) } }, [poster, url]) 这段是我的代码对player的配置
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 无论何时点击视频应该都不会使得视频暂停
> 
> **实际播放器的表现是？ What actually happened?**
> 
> 进入页面第一次时候点击视频中间会使得视频暂停，不清楚这是bug还是什么原因 **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

从你的描述推测，应该是起播之前start动画未完成的瞬间点击，触发了暂停，尝试将start的动画禁用掉试试, 配置如下
`new Player({
   ...,
  start: {
     disableAnimate: true
 }
})`

具体配置说明[内置插件>start](https://v3.h5player.bytedance.com/plugins/internalplugins/start.html#config)

以上配置如果还是不行，请在社区wx群单独联系一下我，wx昵称hqx
