### ISSUE TITLE
请问下，使用xgplayer-hls播放m3u8。如何支持对加密后的ts片段进行解密播放？

### ISSUE THREAD

**Issue by skerhub** [bytedance/xgplayer#1059]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by shih6** [comment]
这个不是根据m3u8文件中的
#EXT-X-KEY:METHOD=AES-128,URI="keyPath",IV=0x0123456789ABCDEF0123456789ABCDEF
这个来解密的吗
