### ISSUE TITLE
无法实例化video

### ISSUE THREAD

**Issue by draculapile** [bytedance/xgplayer#106]
按照文档里写法，在vue搭建的项目中，created()钩子里拿到数据后实例化播放器，打断点看到执行了const player = new Player({})，但是未挂载到DOM中，请教一下可能的原因？十分感谢

**Comment by draculapile** [comment]
1、this.$nextTick(() => {})可以了，但是无法覆盖原生的video标签controls的样式（Chrome下模拟移动设备调试的），把原生的-webkit-media-controls样式display为none之后，还是不显示样式，查看页面元素发现xgplayer-controls被display为none了，请问这个该怎么解决呢？
2、设置宽高且设置fluid属性为true时，不能响应式缩放，这又是为啥？
谢谢！！！

**Comment by zhangxin92** [comment]
需要等示例化完成，可以看下西瓜播放器的 [生命周期](http://h5player.bytedance.com/api/#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)

**Comment by zhangxin92** [comment]
流式布局功能目前只在beta版中支持，可以用xgplayer@1.1.3-beta-6 试试

**Comment by draculapile** [comment]
嗯，能挂载video了，那xgplayer-controls定义的控件为什么不会覆盖原生的样式呢？

**Comment by zhangxin92** [comment]
[白名单](http://h5player.bytedance.com/config/#%E7%99%BD%E5%90%8D%E5%8D%95)用了吗？另外在UC等移动端浏览器下会被劫持，西瓜播放器的定制样式就会无效。移动端chrome没有劫持问题

**Comment by draculapile** [comment]
十分感谢，解决了。打扰了哈哈
