### ISSUE TITLE
xgplayer-hls.js 插件的 hlsJsPlugin 

### ISSUE THREAD

**Issue by lucky-mouse-14** [bytedance/xgplayer#1060]
xgplayer-hls.js 插件的 hlsJsPlugin 配置项是参考哪里？是参考xgplayer-hls插件吗？
我想修改重试次数和重试间隔。

**Comment by xiyuyizhi** [comment]
@lucky-mouse-14 需要参考hls.js文档，https://github.com/video-dev/hls.js/blob/master/docs/API.md
