### ISSUE TITLE
3.0.1播放m3u8视频，播着播着就解码错误

### ISSUE THREAD

**Issue by skerhub** [bytedance/xgplayer#1061]
**您使用的西瓜播放器版本是多少？ 3.0.1

**您使用的操作系统和浏览器分别是？ Windows/Google

**如何复现问题？

复现代码如下：
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.css" />
  <script src="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.js"></script>
  <script src="https://unpkg.byted-static.com/xgplayer-hls/3.0.1/dist/index.min.js"></script>
  <title>Document</title>
</head>
<style>
  #mse{
    width: 100%;
    height: 100%;
  }

  .ss{
    width:800px;
    height: 600px;
  }
</style>

<body>
  <div class='ss'>
    <div  id='mse'></div>
  </div>
  <script>

  window.onload = function(){
    const config = {
      plugins: [HlsPlayer],
      isLive: false,
      id: 'mse',
      playsinline: true,
      width: '100%',
      height: '100%',
      autoplay: true,
      cssFullscreen: false,
      url: 'https://aws.ulivetv.net/v3/api/dianbo/m3u8/408131.m3u8'
    }
    var player = new window.Player(config)
    player.on('error',e => {
      console.log('播放异常',e)
    })
  }

  </script>
</body>

</html>`
实际效果：播到一分钟的时候就解码错误了，实际使用video原生就不会报错，能一直播放，m3u8链接和解析的ts没有问题，不然video原生也播放不了

**Comment by code-YuJun** [comment]
你好，请问这个问题现在解决了吗，我用了你的m3u8的地址，也可以复现这个问题

**Comment by xiyuyizhi** [comment]
@skerhub ts请求403，新提供个流地址？
