### ISSUE TITLE
master分支无法播放flv点播视频

### ISSUE THREAD

**Issue by lwb5934** [bytedance/xgplayer#1066]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
master 分支代码

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos chrom

**如何复现问题？ How to reproduce the problem?**
<script src="../../packages/xgplayer-flv/browser/index.js" charset="utf-8"></script>
var player = new FlvPlayer({
            id: 'vs',
            url: 'https://sf1-hscdn-tos.pstatp.com/obj/media-fe/xgplayer_doc_video/flv/xgplayer-demo-360p.flv',
            width:600,
            height:385,
        })
无法播放flv视频

**您期望的播放器正常行为是？ What did you expect to happen?**
能够正常播放

**实际播放器的表现是？ What actually happened?**
解析错误

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@lwb5934 main分支为v3版本主分支，建议切到这个分支
