### ISSUE TITLE
是否可以自定义右键菜单Options

### ISSUE THREAD

**Issue by Ora2** [bytedance/xgplayer#1071]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.28.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win10, FireFox

**如何复现问题？ How to reproduce the problem?**
x

**您期望的播放器正常行为是？ What did you expect to happen?**
 我想配置自己的右键菜单

**实际播放器的表现是？ What actually happened?**
没有发现右键菜单的自定义配置

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
播放器没有定制自己的右键菜单，只是禁用了右键菜单的显示，可以通过配置将右键菜单恢复正常
enableContextmenu:true, 文档参考https://v2.h5player.bytedance.com/config/#%E5%85%B6%E5%AE%83%E4%BA%A4%E4%BA%92%E9%85%8D%E7%BD%AE
