### ISSUE TITLE
你好，请问有没有参数是可以将音频关闭的

### ISSUE THREAD

**Issue by ZGQ1996** [bytedance/xgplayer#1072]
我的项目中，音频文件不用。在使用flv.js的时候有hasAudio: false,这样的参数。xgplayery文档我都过了一边，并没有找到类似的参数

**Comment by hongqx** [comment]
目前没有关闭音频的配置，但是那你可以在使用播放的时候将其设置为静音
player.muted = true
new Player({
   autoplayMuted: true
})
