### ISSUE TITLE
鼠标直接从进度条外移到进度条标记点没有显示提示文字，只是显示时间。

### ISSUE THREAD

**Issue by wscfan** [bytedance/xgplayer#1077]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win11、chrome115

**如何复现问题？ How to reproduce the problem?**
鼠标直接从进度条外移到进度条标记点没有显示提示文字，只是显示时间。
![image](https://github.com/bytedance/xgplayer/assets/20600281/dc6c3459-4a53-49e3-ad33-0fd52d076881)

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.7
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** win11、chrome115
> 
> **如何复现问题？ How to reproduce the problem?** 鼠标直接从进度条外移到进度条标记点没有显示提示文字，只是显示时间。 ![image](https://user-images.githubusercontent.com/20600281/260913804-dc6c3459-4a53-49e3-ad33-0fd52d076881.png)
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

v3.0.10版本已修复
