### ISSUE TITLE
ios16.4 播放 hls 黑屏

### ISSUE THREAD

**Issue by LingRen** [bytedance/xgplayer#1080]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    <script src="//unpkg.byted-static.com/xgplayer/2.31.6/browser/index.js" charset="utf-8"></script>
     <script src="//unpkg.byted-static.com/xgplayer-hls.js/2.2.2/browser/index.js" charset="utf-8"></script><script>

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios16.4  safari浏览器

**如何复现问题？ How to reproduce the problem?**
任何m3u8视频

[官方](https://v2.h5player.bytedance.com/examples/) 切换到直播 hls

**您期望的播放器正常行为是？ What did you expect to happen?**
有视频画面

**实际播放器的表现是？ What actually happened?**
只有声音，没有画面

**Comment by hongqx** [comment]
检查一下，是不是播放的资源是h265编码，具体h265的支持说明请参考https://v3.h5player.bytedance.com/guide/extends/about_format.html#%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81hevc-h265

**Comment by LingRen** [comment]
官方demo，
