### ISSUE TITLE
xgplayer-hls.js 3.0.8版本不支持m3u8播放，降低为2.2.2就可以播放

### ISSUE THREAD

**Issue by w578202450** [bytedance/xgplayer#1081]
"xgplayer": "^3.0.8",
"xgplayer-hls.js": "^3.0.8"

macos  chorome

import 'xgplayer';
import HlsJsPlayer from 'xgplayer-hls.js';

let player = new HlsJsPlayer({
    id: 'mse',
    url: 'xxxxxxxx.m3u8'
  });

期望正常播放，但是dom不加载，将版本替换为
"xgplayer": "^2.31.6",
 "xgplayer-hls.js": "^2.2.2"
就可以正常播放

**Comment by hongqx** [comment]
> "xgplayer": "^3.0.8", "xgplayer-hls.js": "^3.0.8"
> 
> macos chorome
> 
> import 'xgplayer'; import HlsJsPlayer from 'xgplayer-hls.js';
> 
> let player = new HlsJsPlayer({ id: 'mse', url: 'xxxxxxxx.m3u8' });
> 
> 期望正常播放，但是dom不加载，将版本替换为 "xgplayer": "^2.31.6", "xgplayer-hls.js": "^2.2.2" 就可以正常播放

3.x版本的hls建议使用xgplayer-hls替代xgplayer-hls.js
