### ISSUE TITLE
画中画pip下存在封面poster切换多个问题

### ISSUE THREAD

**Issue by ArtsXiaoLu** [bytedance/xgplayer#1089]
引用的代码链接为
https://unpkg.com/xgplayer/dist/index.min.js
https://unpkg.com/xgplayer-flv/dist/index.min.js
https://unpkg.com/xgplayer/dist/index.min.css
目前显示的版本为3.0.9

举例 1
```
//初始player 
player = new Player({
url: "1.flv",
poster:"1.png",  ... })
```

```
....
//切换视频
player.switchURL("2.flv"); 
//并切换封面
player.poster ="2.png";
....
```
此时开启pip画中画，显示的却是1.png
当我再次点击2.flv时，这时正常了，显示的是2.png
player.playNext也是一样，并且，playNext下的封面poster 切换设置似乎并不起作用，

查找原因
```
<video poster="n.png">
<xg-poster style="background: url("2.png";);" >
```
video下的poster并未与 xg-poster下的url同步
初次开启pip画中画时，只是重读了player 里的设置，而并没有直接从xg-poster读取链接

从pip.js中翻查，并设置` player.media.poster = player.poster = "2.png"; `问题依旧
偶尔因视频卡顿，会频繁显示video下的poster
因封面与播放器尺寸不一致，为避免封面黑边，我需要将xg-poster样式设置为cover
但当开启过pip画中画，此时因视频加载缓慢，会造成两次封面显示，
且video下的poster，无法用CSS样式调整，

希望修复一下，废除造成重叠的video下的poster，
或者当开启画中画pip时，直接从xg-poster调取图片链接

发帖编辑时似乎还3.0.8，写完帖子变3.0.9了，后台加油，嘻嘻

**Comment by y377** [comment]
时隔多年，我又回来搞前端了，我也不新开贴了，我怕是我自己的问题，浪费了开发者时间，所以借用一下，一楼莫生气！
> **当前js版本：3.0.8**
> **当前css版本:  3.0.8**
### 第一，请看截图；chrome和edge都有右侧黑边，我是用的bootstrap，但是改变窗口大小（断点）黑边又会消失；但是火狐浏览器没有这个问题（无论是全屏改时改变窗口大小）。
![image](https://github.com/bytedance/xgplayer/assets/58632405/c1dc8ba3-59bd-48a7-9a6b-a848b8b0f2f5)
**调试：**取消class类`.xgplayer`的`background: \#000`可以解决

### 第二，请问官方cdn库`https://unpkg.byted-static.com/......`能否给个页面什么的，默认访问这个网址没法访问，后面跟上版本号什么的可以访问，我想上去看看最新版本？

### 第三，请问样式scss源码上哪寻找，我不想用css。

# 还请开发者告知一下，谢谢！

**Comment by ArtsXiaoLu** [comment]
@y377 
1.楼主很生气，为什么不自己开贴，偏要在别人帖子下报告你的问题，
2.主站[http://h5player.bytedance.com/config/](url)下有很多配置项，fitVideoSize，videoFillMode等，外加CSS等都可以解决你的问题
3.我帖子开头有三个链接，默认访问的就是最新版为什么不试一试
4.既已多年，且来到github，为什么不尝试搜索一下，偏要在我这不懂代码写一句搜一句代码的新人下反馈你的问题
😒😒😒😒😒😒

**Comment by hongqx** [comment]
> https://unpkg.byted-static.com/

....
//切换视频
player.switchURL("2.flv"); 
//并切换封面
player.poster ="2.png";
....
 
楼主，请问这个切换语句的目的是切换另一个视频播放是么？

**Comment by ArtsXiaoLu** [comment]
@hongqx 
这个只是视频切换的简单代码，具体要复杂得多，
毕竟每个人操作需求不同，代码写法自然也不同，
具体到https://h5player.bytedance.com/config/，自己根据需要翻翻吧，
3.0的配置多是英文，可以先对比2.0页面说明，然后去3.0下找相应代码吧，
我这也写了好几个月没写完，其实我也什么都不懂，多动动脑吧，
除播放器代码本身问题反馈，在这里求助具体写法，基本找不到详细答案

**Comment by hongqx** [comment]
> @hongqx 这个只是视频切换的简单代码，具体要复杂得多， 毕竟每个人操作需求不同，代码写法自然也不同， 具体到[https://h5player.bytedance.com/config/，自己根据需要翻翻吧，](https://h5player.bytedance.com/config/%EF%BC%8C%E8%87%AA%E5%B7%B1%E6%A0%B9%E6%8D%AE%E9%9C%80%E8%A6%81%E7%BF%BB%E7%BF%BB%E5%90%A7%EF%BC%8C) 3.0的配置多是英文，可以先对比2.0页面说明，然后去3.0下找相应代码吧， 我这也写了好几个月没写完，其实我也什么都不懂，多动动脑吧， 除播放器代码本身问题反馈，在这里求助具体写法，基本找不到详细答案

哈哈 我是开发者，你在微信群中么？为在微信群中叫hqx, 具体聊一下你的需求场景，我看看怎么做支持

**Comment by ArtsXiaoLu** [comment]
@hongqx 
这播放器已经属于成品代码了，只需要填写配置代码调用就可以了，
相对于开发而言，我根本都不沾边，每句代码我都属于写一句搜十句的类型，
连单词都拼不准，单独挑出一句代码更看不懂了，
所以也没在任何群里
