### ISSUE TITLE
外挂字幕3.0.1-无法生效 接#805

### ISSUE THREAD

**Issue by kazegh** [bytedance/xgplayer#1091]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** chrome
> 
> **如何复现问题？ What did you do?**
> 
> ```
> <html>
>   <head>
>     <meta charset="utf-8">
>     <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
>     <meta name="referrer" content="no-referrer">
>     <title>xgplayer</title>
>     <style type="text/css">
>       html, body {width:100%;height:100%;margin:auto;overflow: hidden;}
>     </style>
>   </head>
>   <body>
>     <div id="mse"></div>
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.css"/>
>     <script src="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.js" charset="utf-8"></script>
>       let player = new Player({
> 		"id": "mse",
> 		"url": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4",
> 		"playsinline": true,
> 		"whitelist": [
> 				""
> 		],
> 		"textTrack": [
> 				{
> 						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-1.vtt",
> 						"label": "字幕1",
> 						"default": true
> 				},
> 				{
> 						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-2.vtt",
> 						"label": "字幕2",
> 						"default": false
> 				}
> 		],
> 		"textTrackStyle": {
> 				"font-size": "36px",
> 				"color": "#ff0000",
> 				"background-color": "transparent"
> 		}
>       });
>       
>           </script>
>   </body>
> </html>
> ```
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 样式如配置
> 
> **实际播放器的表现是？ What actually happened?** 外挂字幕样式无法生效
> 使用低版本JS才能生效  https://cdn.jsdelivr.net/npm/xgplayer@2.32.3/browser/index.min.js
> ```

**Comment by hongqx** [comment]
默认的umd包没有打包外挂字幕功能，因为这个能力场景比较少，为了减少包的体积，没有默认引入，需要使用的话，参考
[内置插件>字幕](https://v3.h5player.bytedance.com/plugins/internalplugins/texttrack.html)

**Comment by hongqx** [comment]
> > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** chrome
> > **如何复现问题？ What did you do?**
> > ```
> > <html>
> >   <head>
> >     <meta charset="utf-8">
> >     <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
> >     <meta name="referrer" content="no-referrer">
> >     <title>xgplayer</title>
> >     <style type="text/css">
> >       html, body {width:100%;height:100%;margin:auto;overflow: hidden;}
> >     </style>
> >   </head>
> >   <body>
> >     <div id="mse"></div>
> >     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.css"/>
> >     <script src="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.js" charset="utf-8"></script>
> >       let player = new Player({
> > 		"id": "mse",
> > 		"url": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4",
> > 		"playsinline": true,
> > 		"whitelist": [
> > 				""
> > 		],
> > 		"textTrack": [
> > 				{
> > 						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-1.vtt",
> > 						"label": "字幕1",
> > 						"default": true
> > 				},
> > 				{
> > 						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-2.vtt",
> > 						"label": "字幕2",
> > 						"default": false
> > 				}
> > 		],
> > 		"textTrackStyle": {
> > 				"font-size": "36px",
> > 				"color": "#ff0000",
> > 				"background-color": "transparent"
> > 		}
> >       });
> >       
> >           </script>
> >   </body>
> > </html>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **您期望的播放器正常行为是？ What did you expect to happen?** 样式如配置
> > **实际播放器的表现是？ What actually happened?** 外挂字幕样式无法生效
> > 使用低版本JS才能生效  https://cdn.jsdelivr.net/npm/xgplayer@2.32.3/browser/index.min.js

默认的umd包没有打包外挂字幕功能，因为这个能力场景比较少，为了减少包的体积，没有默认引入，需要使用的话，参考
[内置插件>字幕](https://v3.h5player.bytedance.com/plugins/internalplugins/texttrack.html)
