### ISSUE TITLE
在vue3+TS中，无法使用音乐播放器频谱吗？

### ISSUE THREAD

**Issue by mike2635** [bytedance/xgplayer#1094]
已经在index.html中引入的js
<script src="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.js" charset="utf-8"></script>
<script src="https://unpkg.byted-static.com/xgplayer-music/3.0.1/dist/index.min.js" charset="utf-8"></script>

`<template>
  <div class="music-container">
    
    <div id="canvas">
      <canvas  width="100%" height="155"></canvas>
    </div>
    
    <div id="vs"></div>
  </div>
</template>

<script setup lang="ts">
import {onMounted} from "vue";
import Player from 'xgplayer'
import 'xgplayer/dist/index.min.css'
import MusicPreset, {Analyze} from 'xgplayer-music'
import 'xgplayer-music/dist/index.min.css'
import {IAnalyzeOptions} from "xgplayer-music/es/analyze";

onMounted(async () => {
  const player = new Player({
    id: 'vs',
    url: 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/music/audio.mp3',
    volume: 0.8,
    width: window.innerWidth,
    height: 45,
    fluid: true,
    mediaType: 'audio',
    preloadNext: true, // 预加载下一首
    switchKeepProgress: false, // 切换歌曲保持进度
    presets: ['default', MusicPreset],
    ignores: ['playbackrate'],
    controls: {
      initShow: true,
      mode: 'flex'
    },
    marginControls: true,
    videoConfig: {
      crossOrigin: "anonymous"
    }
  })
  player.crossOrigin = "anonymous";

  player.on('playing', function () {
    console.log("playing")
  });

  // const canvas = document.getElementById("canvas")
  const analyzeConfig: IAnalyzeOptions = {
    bgColor: 'rgba(0,0,0,0.65)',
    stroke: 1,
    fftSize: 1024,
    mode: 'bars',
  }
  // 初始化频谱
  let analyze  = new Analyze(player, document.querySelector('canvas'), analyzeConfig)
})
</script>`

**Comment by hongqx** [comment]
频谱的使用不会受开发框架的影响，只要给的canvas容器是已经创建的可以，现在是有什么具体的报错信息么？

**Comment by KBoss174** [comment]
我这里开启频谱的话，音频好像一直发不出声音了，不配置频谱，就可以，也看到控制有错误信息打印，有点奇怪
