### ISSUE TITLE
点播hls播放m3u8文件，使用西瓜hls播放器无法播放0.2秒的ts文件，但使用hls.js可以。辛苦大侠根据我们的应用情况，给一下建议呗。谢谢

### ISSUE THREAD

**Issue by hubaoshun** [bytedance/xgplayer#1095]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2023-09-04，直接使用的 样例：
https://v2.h5player.bytedance.com/examples/

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10，chrome浏览器。

**如何复现问题？ How to reproduce the problem?**
应用场景：
我们参考了示例代码，使用：点播-hls-西瓜hls
我们使用 rtmp协议推流到流媒体服务器（使用srs4），由于网络等原因，rtmp存在断流的问题，所以保存的ts文件，时间点是不连续的（例如：两个ts之间有一段空白时间段，可能有几秒或者几百毫秒没有收到视频流）。
我们基于功能需求，把ts文件之间的空白时间段，用我们自己制作的"黑屏ts"文件填写到 m3u8文件中。
"黑屏ts"文件的长度：0.2s、0.5ms、1s、2s、5s、10s

目前遇到的问题：
用 西瓜hls 无法播放 某个m3u8文件（里面包含0.2s的 TS文件）：播放的效果：播放了第一个1秒的黑屏文件后，就卡住了。（提示：进行刷新）
但用 hls.js 可正常播放。

m3u8文件如下：

#EXTM3U
#EXT-X-VERSION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:12
#EXT-X-ALLOW-CACHE:YES
#EXT-X-DISCONTINUITY
#EXTINF:1.0, no desc
1000ms.ts
#EXT-X-DISCONTINUITY
#EXTINF:0.2, no desc
200ms.ts
#EXT-X-DISCONTINUITY
#EXTINF:0.2, no desc
200ms-2.ts
#EXT-X-DISCONTINUITY
#EXTINF:11.992, no desc
normal1.ts
#EXT-X-DISCONTINUITY
#EXTINF:2.0, no desc
2000ms.ts
#EXT-X-DISCONTINUITY
#EXTINF:11.975, no desc
normal2.ts
#ZEN-TOTAL-DURATION:27.367

#EXT-X-ENDLIST

**您期望的播放器正常行为是？ What did you expect to happen?**
期望视频能够正常播放。

**实际播放器的表现是？ What actually happened?**
使用西瓜hls播放器，无法播放。但使用 hls.js 可以播放。

我的 email:  2838844@qq.com 
可通过email发送您 ts文件和 m3u8文件。谢谢。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hubaoshun** [comment]
上面有一处笔误，更正如下："黑屏ts"文件的长度：0.2s、0.5s、1s、2s、5s、10s

**Comment by xiyuyizhi** [comment]
@hubaoshun 实现3.0正式版本 https://v3.h5player.bytedance.net/plugins/extension/xgplayer-hls.html

**Comment by hubaoshun** [comment]
好的，收到谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月19日(周二) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bytedance/xgplayer] 点播hls播放m3u8文件，使用西瓜hls播放器无法播放0.2秒的ts文件，但使用hls.js可以。辛苦大侠根据我们的应用情况，给一下建议呗。谢谢 (Issue #1095)




 
@hubaoshun 试下3.0正式版本 https://v3.h5player.bytedance.net/plugins/extension/xgplayer-hls.html

**Comment by hubaoshun** [comment]
> @hubaoshun 试下3.0正式版本 https://v3.h5player.bytedance.net/plugins/extension/xgplayer-hls.html

您给的地址我无法访问，我可以访问下面的地址：是V3版本的，初步测试，0.2s的TS文件能播放了，谢谢：
https://v3.h5player.bytedance.com/examples/
