### ISSUE TITLE
setConfig Api无效

### ISSUE THREAD

**Issue by as-alt** [bytedance/xgplayer#1098]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

示例地址：https://codepen.io/as-alt/pen/xxmgRBO

点击修改视频后无反应，无报错

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by inc904** [comment]
我也遇到同样问题,通过setConfig修改配置后, 打印 player 实例, 能看到 新传入的配置信息被接受了, 但是播放器并无任何响应变化.

**Comment by hongqx** [comment]
player.setConfig(newConfig)只是修该内置配置，内置的插件会有相应的相应，但是不会重启播放流程，如果想要单实例切换播放地址，可以入校调用
player.playNext(newConfig), 更新配置，并且播放新的url
