### ISSUE TITLE
什么时候能兼容ios端播放http-flv

### ISSUE THREAD

**Issue by nie-lei-s** [bytedance/xgplayer#1101]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios的谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
无法播放http-flv

**您期望的播放器正常行为是？ What did you expect to happen?**
ios端能正常播放http-flv

**实际播放器的表现是？ What actually happened?**
ios端不能播放http-flv

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@nie-lei-s flv播放需要依赖环境支持MediaSource API，大部分ios系统不支持此API，H5上主要以播放Hls为主
