### ISSUE TITLE
判断IOS平板的方法，希望区分mac和ipad(13.x.x)

### ISSUE THREAD

**Issue by NancyRun** [bytedance/xgplayer#1102]
`https://github.com/bytedance/xgplayer/blob/c176fc58981a5c51e6bf1b80e41190be1992a81b/packages/xgplayer/src/utils/sniffer.js#L82C10-L82C10`

const isTablet =
      /(?:iPad|PlayBook)/.test(ua) ||
      (isAndroid && !/(?:Mobile)/.test(ua)) ||
      (isFireFox && /(?:Tablet)/.test(ua))

本人测试到的情况是，在ipad某些app内的webview拿到的ua是：Mozilla/5.0 (Macintosh;Intel MacOSX10_15_7AppleWebKit/605.1.15(KHTML, like Gecko) Mobile/15E148
然后方法返回的是：{ isPC: true, isIpad: false, isTablet: false }，以至影响到音量图标的点击切换静音功能
但是在safari返回的是预期的，可以正常切换静音/非静音，希望可以增加其他webview的判断

测试机型：iPad mini，iPadOS版本：16.3 

原因：
iPadOS升级到13.2.3后，打印ipad navigator.userAgent字符串发现mac跟ipad一样

解决：

navigator.maxTouchPoints 返回当前设备能够支持的最大同时触摸的点数

ipad环境下打印 navigator.maxTouchPoints的数值是5

pc环境下打印 navigator.maxTouchPoints的数值是0

pc环境下，切换到移动端模式(Toggle device toolbar)，打印 navigator.maxTouchPoints的数值是1

isiPad = (navigator.userAgent.match(/(iPad)/) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1))

参考1：https://blog.csdn.net/qq_33040483/article/details/119186208
参考2: https://qa.1r1g.com/sf/ask/4044320101/

**Comment by shanyutongxue** [comment]
感谢建议，将在 3.0.11 中修复完成
