### ISSUE TITLE
点播较短的flv视频，比如只有一组GOP 会加载很长时间才播放。

### ISSUE THREAD

**Issue by yangjiechina** [bytedance/xgplayer#1105]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.7和3.08
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11和chrome

**如何复现问题？ How to reproduce the problem?**
点播较短的flv视频，比如只有一组GOP 会加载很长时间才播放。

视频地址如下:
http://124.71.47.21/media/106.15.8.60-209/2023-09-12/07.30.12.780.flv

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@yangjiechina 更新下最新版本

**Comment by yangjiechina** [comment]
> @yangjiechina 更新下最新版本

感谢！ 方便更新下CDN上的版本吗？ 我们项目是通道CDN引用的方式使用的。我测试看目前cdn上最新版本是3.0.9

**Comment by xiyuyizhi** [comment]
@yangjiechina done
