### ISSUE TITLE
xgplayer-hls独立使用

### ISSUE THREAD

**Issue by zqs125** [bytedance/xgplayer#1108]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10 edge116 chrome117

**如何复现问题？ How to reproduce the problem?**
我想独立使用xgplayer-hls，通过cdn的方式引入js文件：
<script src="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.js" charset="utf-8"></script>
<script src="https://unpkg.byted-static.com/xgplayer-hls/3.0.1/dist/index.min.js" charset="utf-8"></script>
然后按文档写：
<script type="text/javascript">
if (HlsPlayer.isSupported()) {
    const video = document.createElement('video')
    document.body.append(video)
    const hls = new HlsPlayer({
        media: video
    })
    hls.load('m3u8 url')
}
</script>

**您期望的播放器正常行为是？ What did you expect to happen?**
没有报错，正常播放视频

**实际播放器的表现是？ What actually happened?**
视频无法播放，浏览器报错：Uncaught TypeError: hls.load is not a function

请问下是这个插件不能通过cdn的方式单独使用吗？

**Comment by xiyuyizhi** [comment]
@zqs125 umd没有导出独立使用的hls，可以使用npm方式

```
  import { Hls } from "xgplayer-hls"
 const hls = new HlsPlayer({ media }) 
 hls.load('m3u8 url') }

```
