### ISSUE TITLE
视频显示加载成功，但页面一直显示加载

### ISSUE THREAD

**Issue by xing403** [bytedance/xgplayer#1109]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
`v3.0.9`

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10 & Chrome

**如何复现问题？ How to reproduce the problem?**
> 当我通过视频链接加载时
```js
player.on('play', () => {
  console.log('播放成功')
})
```
已经执行了，但播放器页面依旧显示加载的页面
我看了一下html渲染后的代码，原因是这个在执行播放后未隐藏的原因
![image](https://github.com/bytedance/xgplayer/assets/74746021/6e7db19b-490b-4d80-b0aa-f56e34e8b33c)

**Comment by xing403** [comment]
我的解决方法：
在视频加载成功并播放时，执行
```js
player.root.querySelector('.xgplayer-enter').style.display = 'none'
```
手动隐藏一下，目前没有出现是否会因为这个导致其他错误

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** `v3.0.9`
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** windows10 & Chrome
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> > 当我通过视频链接加载时
> 
> ```js
> player.on('play', () => {
>   console.log('播放成功')
> })
> ```
> 
> 已经执行了，但播放器页面依旧显示加载的页面 我看了一下html渲染后的代码，原因是这个在执行播放后未隐藏的原因 ![image](https://user-images.githubusercontent.com/74746021/268865296-6e7db19b-490b-4d80-b0aa-f56e34e8b33c.png)

你的播放启动方式是什么样的？是调用的autoplay: true还是其他方式？

**Comment by xing403** [comment]
版本回滚之后，再安装新版本好像就没这个问题了
