### ISSUE TITLE
小进度条不显示，缩略图只请求第一个url

### ISSUE THREAD

**Issue by viocha** [bytedance/xgplayer#1113]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.1版本的xgplayer和hls插件

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows11 edge浏览器

**如何复现问题？ How to reproduce the problem?**
miniprogress 设置为true
thumbnail.urls 设置为包含多个url的数组

**您期望的播放器正常行为是？ What did you expect to happen?**
显示小进度条。
显示所有的缩略图预览。

**实际播放器的表现是？ What actually happened?**
不显示小进度条。
只显示了第一个url的缩略图，其他url没有发起请求

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.1版本的xgplayer和hls插件
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** Windows11 edge浏览器
> 
> **如何复现问题？ How to reproduce the problem?** miniprogress 设置为true thumbnail.urls 设置为包含多个url的数组
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 显示小进度条。 显示所有的缩略图预览。
> 
> **实际播放器的表现是？ What actually happened?** 不显示小进度条。 只显示了第一个url的缩略图，其他url没有发起请求
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

thumbnail的具体配置信息是否方便发一下
