### ISSUE TITLE
xgplayer-hls 无法播放加密m3u8视频，xgplayer-hls.js可以播放-但是切换清晰度选择框未修改

### ISSUE THREAD

**Issue by sdzhongqian** [bytedance/xgplayer#1122]
**视频为-m3u8加密视频-阿里点播hls加密视频**

**Vue3安装xgplayer后，无法进行播放，使用xgplayer-hls依然无法播放，f12查看数据有返回，页面无播放提示【video is not supported】**

**因为无法播放，尝试在index.html中直接引入xgplayer-hls.js/3.0.0-alpha.1 可以播放，但是切换清晰度-可以切换成功，底部标签未改变还是显示流畅**

**最初实现的是xgplayer-hls.js2.2.2 可以正常切换，但是切换后的进度从0播放-也是存在问题。**

**期望大佬帮助解决**

**Comment by xiyuyizhi** [comment]
@sdzhongqian 提供一下测试视频？

**Comment by txmz** [comment]
3.0.0版本播放hls格式在谷歌上没有问题，为啥不能在IE11上播放。
let player = new window.Player({
            id: 'mse',
            url: url,
            autoplay: true,
            playsinline: true,
            height: window.innerHeight,
            width: window.innerWidth,
            download: true,
            pip: true,
            plugins: [window.HlsPlayer]
        });
