### ISSUE TITLE
Icon svg图标替换不生效的问题

### ISSUE THREAD

**Issue by yuanjie178** [bytedance/xgplayer#1123]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.1
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Win Chrome
**如何复现问题？ How to reproduce the problem?**
import MyPlayIcon from '../icons/my-play-icon.svg';
import MyPauseIcon from '../icons/my-pause-icon.svg';
import Player from 'xgplayer'

const player = new Player({
  el:document.querySelector('#mse'),
  icons: {
    play: MyPlayIcon,
    pause: MyPauseIcon
  }
})
**您期望的播放器正常行为是？ What did you expect to happen?**
按V3版本文档代码示例：使用import引入svg图标文件后，使用icons项配置即可替换对应的svg图标。实际情况是import导入svg文件后图标不能生效，但是导入png却可以正常替换。

**实际播放器的表现是？ What actually happened?**
svg图标显示为播放器默认图标。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by llftt** [comment]
@hongqx 帮忙解答下这个问题

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> 3.0.1 **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> Win Chrome **如何复现问题？ How to reproduce the problem?** import MyPlayIcon from '../icons/my-play-icon.svg'; import MyPauseIcon from '../icons/my-pause-icon.svg'; import Player from 'xgplayer'
> 
> const player = new Player({ el:document.querySelector('#mse'), icons: { play: MyPlayIcon, pause: MyPauseIcon } }) **您期望的播放器正常行为是？ What did you expect to happen?** 按V3版本文档代码示例：使用import引入svg图标文件后，使用icons项配置即可替换对应的svg图标。实际情况是import导入svg文件后图标不能生效，但是导入png却可以正常替换。
> 
> **实际播放器的表现是？ What actually happened?** svg图标显示为播放器默认图标。
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

检查一下MyPlayIcon和MyPauseIcon的具体格式，这里支持的格式有三种
1. html string
2. documentElement
3. () => documentElement

推测是svg的格式不对，导致创建的时候失败，或者是当前MyPlayIcon和MyPauseIcon不是以上三种格式
