### ISSUE TITLE
样式不显示

### ISSUE THREAD

**Issue by zy7747** [bytedance/xgplayer#1124]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

win11
**如何复现问题？ How to reproduce the problem?**
在vue2中导入后样式不生效
/

**您期望的播放器正常行为是？ What did you expect to happen?**
正常显示

**实际播放器的表现是？ What actually happened?**
在vue2中导入后样式不生效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
可以提供一个可复现的例子吗？

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> win11 **如何复现问题？ How to reproduce the problem?** 在vue2中导入后样式不生效 /
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常显示
> 
> **实际播放器的表现是？ What actually happened?** 在vue2中导入后样式不生效
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

确认一下是不是打包工具的cssloader之类的插件将node_moudules加入到了exclude中，如果是添加一下include配置，将xgplayer的目录加进去
