### ISSUE TITLE
未能监听到requestFullscreen进入全屏事件

### ISSUE THREAD

**Issue by 1581433801** [bytedance/xgplayer#1125]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.9
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows11 chrome
**如何复现问题？ How to reproduce the problem?**

监听进入全屏事件, 未监听到
  player.on('requestFullscreen', () => {
    console.log('进入全屏')
  })

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
请参考事件的写法指引：https://h5player.bytedance.com/api/events.html#examples

```
import Player, { Events } from 'xgplayer'

player.on(Events.FULLSCREEN_CHANGE, (isFullscreen) => {
  if (isFullscreen) {
    // 全屏TODO
  } else {
    // 退出全屏TODO
  }
})
```
