### ISSUE TITLE
3.0.9版本 视频只旋转video配置，点击旋转后旋转不回原本的方向

### ISSUE THREAD

**Issue by liuge19910224** [bytedance/xgplayer#1127]
3.0.9版本

windows 10

配置视频旋转，点击四次旋转应该是旋转回正常的视频方向 但是没有旋转回来

**Comment by hongqx** [comment]
> 3.0.9版本
> 
> windows 10
> 
> 配置视频旋转，点击四次旋转应该是旋转回正常的视频方向 但是没有旋转回来

该问题已经在3.0.10中修复
