### ISSUE TITLE
cssFullscreen: true 网页全屏按钮还是无法显示

### ISSUE THREAD

**Issue by hunnchong** [bytedance/xgplayer#1128]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
IOS14，safari

![96296391931676a7fdd138625a81294](https://github.com/bytedance/xgplayer/assets/54495130/95713bc3-36ea-4b67-af68-a3566552d984)

cssFullscreen: true
网页全屏按钮还是无法显示

**Comment by hongqx** [comment]
移动端网页全屏按钮被禁用了，你是想要用css全屏来代替系统全屏么？如果是这样的话，这么配置一下
`new Player({
    ...,
    fullscreen: {
         useCssFullscreen: true
    }
})`
这样配置之后，点击全屏的时候会用网页全屏的方式实现
具体配置说明参考[内置插件>fullscreen](https://v3.h5player.bytedance.com/plugins/internalplugins/fullscreen.html#config)

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** IOS14，safari
> 
> ![96296391931676a7fdd138625a81294](https://user-images.githubusercontent.com/54495130/273766583-95713bc3-36ea-4b67-af68-a3566552d984.jpg)
> 
> cssFullscreen: true 网页全屏按钮还是无法显示

移动端网页全屏按钮被禁用了，你是想要用css全屏来代替系统全屏么？如果是这样的话，这么配置一下
`new Player({
    ...,
    fullscreen: {
         useCssFullscreen: true
    }
})`
这样配置之后，点击全屏的时候会用网页全屏的方式实现
具体配置说明参考[内置插件>fullscreen](https://v3.h5player.bytedance.com/plugins/internalplugins/fullscreen.html#config)
