### ISSUE TITLE
请问一下，xgplayer-hls的可以使用hls.js的配置选项吗？

### ISSUE THREAD

**Issue by Tian0301** [bytedance/xgplayer#1129]
`import Player from 'xgplayer';
import HlsPlugin from 'xgplayer-hls';

const player= new Player({
  id: 'player',
  url: 'xxx',
 plugins: [HlsPlugin]，
  hls: {
    xhrSetup: (xhr, url) => {
      // 处理m3u8链接
     // 生成之后并没有执行这个方法
    }
  }
});
`
**如果xgplayer-hls无法使用hls.js配置项，想对m3u8和ts请求时更改url，应该怎么配置呢？**

**Comment by cjg1122** [comment]
看源码
xgplayer-hls 是不行的
xgplayer-hls.js 是可以的

**Comment by Tian0301** [comment]
> 看源码 xgplayer-hls 是不行的 xgplayer-hls.js 是可以的

好吧  我没找到相关的文档， fetchOptions倒是可以用一下，但是不太符合我这边的业务，还是得用回xgplayer-hls.js.

**Comment by llftt** [comment]
import { EVENT } from "xgplayer-hls"
    player.on('core_event', e => {
      if(e.eventName === EVENT.HLS_LEVEL_LOADED) {
          e.playlist.segments.forEach(seg => {
            seg.url = 'xxx'
          })
      }
    })
    可以按照这个方式修改地址

**Comment by Tian0301** [comment]
> import { EVENT } from "xgplayer-hls" player.on('core_event', e => { if(e.eventName === EVENT.HLS_LEVEL_LOADED) { e.playlist.segments.forEach(seg => { seg.url = 'xxx' }) } }) 可以按照这个方式修改地址

多谢，这种确实可以，请问一下， 如果我想想在请求TS文件的时候再去进行url的改变，这样的话需要监听哪个事件呢？

**Comment by Tian0301** [comment]
> > import { EVENT } from "xgplayer-hls" player.on('core_event', e => { if(e.eventName === EVENT.HLS_LEVEL_LOADED) { e.playlist.segments.forEach(seg => { seg.url = 'xxx' }) } }) 可以按照这个方式修改地址
> 
> 多谢，这种确实可以，请问一下， 如果我想想在请求TS文件的时候再去进行url的改变，这样的话需要监听哪个事件呢？

找到了。 EVENT.LOAD_START中每一个TS片段都会执行，可以在此

> > import { EVENT } from "xgplayer-hls" player.on('core_event', e => { if(e.eventName === EVENT.HLS_LEVEL_LOADED) { e.playlist.segments.forEach(seg => { seg.url = 'xxx' }) } }) 可以按照这个方式修改地址
> 
> 多谢，这种确实可以，请问一下， 如果我想想在请求TS文件的时候再去进行url的改变，这样的话需要监听哪个事件呢？

已找到  在EVENT.LOAD_START 中可以进行URL的更改；
