### ISSUE TITLE
play blob content

### ISSUE THREAD

**Issue by mccoysc** [bytedance/xgplayer#113]
1、是否可以支持播放blob对象或者arraybuffer对象？
2、是否可以播放过程中动态添加视频源？

**Comment by zhangxin92** [comment]
1. Yes, like this:
new Player({
  id: 'domId',
  url: URL.createObjectURL(blob)
});

2. Yes, like this:
player.src = 'new url';
player.play();

**Comment by mccoysc** [comment]
实际是这样：
我希望自己控制视频数据的加载，加载了一部分，我就播放一部分，所以，我的arraybuffer可能只是某个视频文件的一个很不规则的切片。

比如某个视频文件100M。
一开始我拿到了1MB，所以此时播放这1MB，
接着我又拿到了接下来的100KB，所以我想接着播放这100KB
。
不知道是否支持这样

**Comment by mccoysc** [comment]
player.src 应该是要求必须是完整的视频文件的，我上面说的这种不规则切片、非完整的视频文件，怎么播放？

**Comment by zhangxin92** [comment]
可以了解一下[xgplayer-mp4插件](https://techblog.toutiao.com/2018/07/09/untitled-51/) 的功能，[相关文章](https://techblog.toutiao.com/2018/07/09/untitled-51/)

**Comment by mccoysc** [comment]
而且用户如果要做直播，也能很容易实现，直接把编码过的直播数据在这个回调里返回就能实现

**Comment by mccoysc** [comment]
然后基于清晰度切换的需求，那个player.emit("resourceReady",[])这里的参数，也需要允许传回调函数，从而不同清晰度时调用不同的回调函数获取数据

**Comment by mccoysc** [comment]
还有就是，这个回调函数的行为：
player要求100字节，这个回调函数可能只返回50，这是需要特别处理的

**Comment by mccoysc** [comment]
最终如这样的效果：

new Player(
{
  url:async function(player,offset,len){
    return getBuf(offset,len);
  }
}
)

**Comment by zhangxin92** [comment]
可以实现，但属于定制化需求会晚些时候支持，着急用的话可以参考xgplayer-mp4插件的源码自己实现，欢迎提PR！

**Comment by JCqiu** [comment]
我也在寻找这个流式播放的写法,不知道你解决没有,比如100m视频也是一段一段的请求播放大概像这个链接一样http://nickdesaulniers.github.io/netfix/demo/bufferWhenNeeded.html xgplay文档我还没有找到类似的用法包括xgplay-mp4
