### ISSUE TITLE
预加载时长preloadTime设置较长后，hls ts片段拉流停止

### ISSUE THREAD

**Issue by yuanjie178** [bytedance/xgplayer#1135]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.1
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

win chrome

**如何复现问题？ How to reproduce the problem?**
      var config = {
        // id: 'video-player',
        el: document.querySelector('#video-player'),
        url: this.url,
        plugins: [HlsPlugin,Danmu],
        hls:{
          preloadTime: 600
        },
      this.player = new Player(config)
-->

**实际播放器的表现是？ What actually happened?**

使用xgplayer-hls进行点播视频拉流，预加载时长preloadTime设置较长（600s）后，视频播放过程中出现ts片段拉流停止，播放器停止播放并黑屏显示“不支持的音视频格式”。

**Comment by xiyuyizhi** [comment]
@yuanjie178 升级一下最新版
