### ISSUE TITLE
能不能添加一个能获取到第一帧初始图片的属性？

### ISSUE THREAD

**Issue by JinGuiMin** [bytedance/xgplayer#1137]
版本：2.23.5

很多的系统都有这么一个交互。
就是，显示一张图片，当点击图片的时候弹出一个弹窗进行播放视频。

可是这张视频图片虽然可以用 videoInit: true,配置。
但是这是两个DOM，所以，可不可以直接能拿到这个图片，当点击的时候播放？

**Comment by hongqx** [comment]
> 版本：2.23.5
> 
> 很多的系统都有这么一个交互。 就是，显示一张图片，当点击图片的时候弹出一个弹窗进行播放视频。
> 
> 可是这张视频图片虽然可以用 videoInit: true,配置。 但是这是两个DOM，所以，可不可以直接能拿到这个图片，当点击的时候播放？

videoInit: true的作用是初始化就开始加载视频，视频首帧加载下来视频就会有画面，但是这不是一张图片，目前也无法以图片格式拿到，且这个有画面的前提条件是**视频初始化就加载**

从你的描述来看，你的这个场景应该是用户未交互的时候用图片铺底，用户点击交互的时候开始加载视频播放，这个和上面描述的【视频初始化就加载】是冲突的。你的这种场景一般解决方案是转码的时候讲第一帧截出存储为一个海报图，前端拿到海报图和视频地址，用户点击交互之前使用海报图打底，配置如下
`
   new Player({
     ...,
    videoInit: false,
    poster: 'xxxx', // 海报图
  })
`
