### ISSUE TITLE
console.assert()会导致打包生产报错，无法加载视频

### ISSUE THREAD

**Issue by JackShijt** [bytedance/xgplayer#1143]
插件版本：2.32.2

在xgplayer-hls.js/dist/index.js和xgplayer-flv.js/dist/index.js文件里都有console.assert()

生产环境报错：i.assert is not a function

已确认删掉打印就好了

**Comment by hongqx** [comment]
> 插件版本：2.32.2
> 
> 在xgplayer-hls.js/dist/index.js和xgplayer-flv.js/dist/index.js文件里都有console.assert()
> 
> 生产环境报错：i.assert is not a function
> 
> 已确认删掉打印就好了

你使用的xgplayer-flv.js和xgplayer-hls.js的版本是多少，应该不是2.32.2

**Comment by JackShijt** [comment]
> > 插件版本：2.32.2
> > 在xgplayer-hls.js/dist/index.js和xgplayer-flv.js/dist/index.js文件里都有console.assert()
> > 生产环境报错：i.assert is not a function
> > 已确认删掉打印就好了
> 
> 你使用的xgplayer-flv.js和xgplayer-hls.js的版本是多少，应该不是2.32.2

版本是2.32.2

**Comment by hongqx** [comment]
> > > 插件版本：2.32.2
> > > 在xgplayer-hls.js/dist/index.js和xgplayer-flv.js/dist/index.js文件里都有console.assert()
> > > 生产环境报错：i.assert is not a function
> > > 已确认删掉打印就好了
> > 
> > 
> > 你使用的xgplayer-flv.js和xgplayer-hls.js的版本是多少，应该不是2.32.2
> 
> 版本是2.32.2

2.32.2是xgplayer主包的版本，xgplayer主包没有这个问题
xgplayer-flv.js@2.3.0 这是flv最新版本，我已经check过，打包产物中没有console.assert()
xgplayer-hls.js@2.6.5-alpha.0 这是hls该问题的修复版本，原来的console.assert()是hls.js中携带，该版本升级了hls.js@1.4.12，先使用一下吧
