### ISSUE TITLE
在某些安卓手机浏览器上面，播放器的层级会变得很高，覆盖掉我的弹窗页面

### ISSUE THREAD

**Issue by DongY264** [bytedance/xgplayer#1144]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer-hls.js 2.1.1
xgplayer  2.18.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
魅族18pro 自带浏览器，其余安卓也有问题

**如何复现问题？ How to reproduce the problem?**
实例播放器，下面整一个弹窗，播放器会覆盖掉弹窗

**您期望的播放器正常行为是？ What did you expect to happen?**
不覆盖掉弹窗

**实际播放器的表现是？ What actually happened?**
覆盖掉弹窗
使用 'x5-video-player-type': 'h5' 自带浏览器还是会覆盖掉，腾讯旗下的浏览器，有时候也会覆盖掉
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
这些移动端的浏览器非同层播放的问题无解

**Comment by peipei818** [comment]
@DongY264 你最后是如何解决的呢？
