### ISSUE TITLE
使用destroy(true)销毁播放器后，生成的blob url仍然在请求，没有停止请求

### ISSUE THREAD

**Issue by JToung** [bytedance/xgplayer#1157]
您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?
"xgplayer": "2.9.6",
"xgplayer-flv.js": "2.1.2",
"xgplayer-hls.js": "2.2.5",

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
操作系统：Mac
浏览器：谷歌浏览器

如何复现问题？ How to reproduce the problem?
vue2代码里，写一个组件，丢一个flv直播流进去，然后销毁组件，就会发现在播放器销毁后，flv流还是一直在请求
````
<template>
  <div ref="player" style="height:70vh" :style="rootStyle" />
</template>
<script>
import Player from 'xgplayer'
import FlvJsPlayer from 'xgplayer-flv.js'
import HlsJsPlayer from 'xgplayer-hls.js'

export default {
  name: 'VueXgplayer',
  props: {
    url: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      default: 'mp4',
    },
    rootStyle: {
      type: Object,
      default () {
        return {}
      },
    },
    controls: {
      type: Boolean,
      default: false,
    },
    autoplay: {
      type: Boolean,
      default: false,
    },
    volume: {
      type: Number,
      default: 0.6,
    },
    width: {
      type: Number,
      default: 414,
    },
    height: {
      type: Number,
      default: 736,
    },
    isLive: {
      type: Boolean,
      default: true,
    },
  },
  data () {
    return {
      player: null,
      retryNumber: 0,
    }
  },
  watch: {
    url (val) {
      console.log('watch url===>', val)
      this.retryNumber = 0
      this.resetPlayer()
    },
  },
  mounted () {
    if (!this.player) {
      this.init()
    }
  },
  beforeDestroy () {
    this.destroy()
  },
  methods: {
    resetPlayer () {
      if (this.player && typeof this.player.destroy === 'function') {
        this.player.pause()
        this.player.destroy(true)
        this.player = null
      }
      setTimeout(() => {
        this.init()
      }, 10)
    },
    playError () {
      console.log('播放出错了！！！！！！')
      if (this.retryNumber > 10) {
        return
      }
      this.retryNumber++
      this.resetPlayer()
    },
    init () {
      const that = this
      const width = this.width || 414
      const height = this.height || 736
      const obj = { el: that.$refs.player, volume: this.volume, fluid: true, isLive: this.isLive, width, height, autoplay: this.autoplay, lang: 'zh-cn', 'x5-video-orientation': 'portraint' }
      if (this.poster !== '') {
        obj.poster = this.poster
      }
      console.log(obj)
      if (this.url !== '') {
        obj.url = this.url
        if (obj.url.indexOf('.flv') > 0) {
          this.player = new FlvJsPlayer(obj)
          console.log('====== flv播放器 ======')
        } else if (obj.url.indexOf('.m3u8') > 0) {
          this.player = new HlsJsPlayer(obj)
          console.log('====== m3u8播放器 ======')
        } else {
          this.player = new Player(obj)
        }
        this.$emit('player', this.player)
        this.player.once('complete', () => {
          setTimeout(() => {
            console.log('complete')
            this.player.on('error', this.playError)
          }, 10)
        })
      }
    },
    play () {
      if (this.player && typeof this.player.play === 'function') {
        setTimeout(() => {
          this.player.play()
        }, 50)
      }
    },
    pause () {
      if (this.player && typeof this.player.pause === 'function') {
        this.player.pause()
      }
    },
    destroy () {
      if (this.player && typeof this.player.destroy === 'function') {
        this.player.destroy(true)
        this.player.once('destroy', () => {
          console.log('xgplayer - destroy')
          this.player = null
        })
      }
    },
    currentTime (val) {
      if (this.player) {
        this.player.currentTime = val
      }
    },
  },
}
</script>

````

您期望的播放器正常行为是？ What did you expect to happen?
使用销毁组件使用`destroy(true)`之后，能停止请求，让生成的Blob URL停止请求

实际播放器的表现是？ What actually happened?
使用销毁组件使用`destroy(true)`之后，生成的Blob URL一直在请求，没有停止

可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.

**Comment by JToung** [comment]
就算升级版本也不管用
    "xgplayer": "2.32.5",
    "xgplayer-flv.js": "2.3.0",
    "xgplayer-hls.js": "2.6.4",

使用this.player.src = ''会报错
vue.min.js:6 TypeError: Cannot read properties of null (reading 'removeAllListeners')
    at e.value (index.js:8:40785)
    at t.<anonymous> (index.js:1:49140)
    at t.n (index.js:1:67795)
    at t.o (index.js:1:68595)
    at t.i (index.js:1:7227)
    at t.value (index.js:1:8255)
    at a.destroy (xgplayer.vue:135:1)
    at a.beforeDestroy (xgplayer.vue:70:1)
    at He (vue.min.js:6:11397)
    at Yt (vue.min.js:6:25339)
Ue @ vue.min.js:6
Be @ vue.min.js:6
Re @ vue.min.js:6
He @ vue.min.js:6
Yt @ vue.min.js:6
e.$destroy @ vue.min.js:6
destroy @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
b @ vue.min.js:6
(anonymous) @ vue.min.js:6
e.$destroy @ vue.min.js:6
destroy @ vue.min.js:6
b @ vue.min.js:6
$ @ vue.min.js:6
(anonymous) @ vue.min.js:6
x @ vue.min.js:6
(anonymous) @ vue.min.js:6
e._update @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn.run @ vue.min.js:6
un @ vue.min.js:6
(anonymous) @ vue.min.js:6
qe @ vue.min.js:6
Promise.then (async)
ze @ vue.min.js:6
Ye @ vue.min.js:6
(anonymous) @ vue.min.js:6
fn.update @ vue.min.js:6
ce.notify @ vue.min.js:6
set @ vue.min.js:6
pn.set @ vue.min.js:6
goBack @ detail.vue:479
He @ vue.min.js:6
n @ vue.min.js:6
He @ vue.min.js:6
e.$emit @ vue.min.js:6
handleClick @ index.min.js:1
He @ vue.min.js:6
n @ vue.min.js:6
Yr.o._wrapper @ vue.min.js:6
index.js:1 Uncaught (in promise) Error: Unhandled error. (undefined)
    at o.emit (index.js:1:7502)
    at o.<anonymous> (index.js:8:44148)
    at o.emit (index.js:1:7636)
    at index.js:8:55097
o.emit @ index.js:1
(anonymous) @ index.js:8
o.emit @ index.js:1
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
o.emit @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:8
value @ index.js:8
(anonymous) @ index.js:8
o.emit @ index.js:1
value @ index.js:8
onlineCheck:1 Uncaught (in promise) e {_message: "Cannot read properties of null (reading 'flushStashedSamples')"}
Promise.catch (async)
value @ index.js:8
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
(anonymous) @ index.js:8
Promise.then (async)
value @ index.js:8
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:8
value @ index.js:8
(anonymous) @ index.js:8
o.emit @ index.js:1
value @ index.js:8
10index.js:1 Uncaught TypeError: Cannot read properties of null (reading 'currentURL')

**Comment by hongqx** [comment]
> 就算升级版本也不管用
> 
> ```
>     "xgplayer": "2.32.5",
>     "xgplayer-flv.js": "2.3.0",
>     "xgplayer-hls.js": "2.6.4",
> ```
> 
> 使用`this.player.src = ''`会报错 vue.min.js:6 TypeError: Cannot read properties of null (reading 'removeAllListeners') at e.value (index.js:8:40785) at t. (index.js:1:49140) at t.n (index.js:1:67795) at t.o (index.js:1:68595) at t.i (index.js:1:7227) at t.value (index.js:1:8255) at a.destroy (xgplayer.vue:135:1) at a.beforeDestroy (xgplayer.vue:70:1) at He (vue.min.js:6:11397) at Yt (vue.min.js:6:25339) Ue @ vue.min.js:6 Be @ vue.min.js:6 Re @ vue.min.js:6 He @ vue.min.js:6 Yt @ vue.min.js:6 e.$destroy @ vue.min.js:6 destroy @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 (anonymous) @ vue.min.js:6 e.$destroy @ vue.min.js:6 destroy @ vue.min.js:6 b @ vue.min.js:6 $ @ vue.min.js:6 (anonymous) @ vue.min.js:6 x @ vue.min.js:6 (anonymous) @ vue.min.js:6 e._update @ vue.min.js:6 r @ vue.min.js:6 fn.get @ vue.min.js:6 fn.run @ vue.min.js:6 un @ vue.min.js:6 (anonymous) @ vue.min.js:6 qe @ vue.min.js:6 Promise.then (async) ze @ vue.min.js:6 Ye @ vue.min.js:6 (anonymous) @ vue.min.js:6 fn.update @ vue.min.js:6 ce.notify @ vue.min.js:6 set @ vue.min.js:6 pn.set @ vue.min.js:6 goBack @ detail.vue:479 He @ vue.min.js:6 n @ vue.min.js:6 He @ vue.min.js:6 e.$emit @ vue.min.js:6 handleClick @ index.min.js:1 He @ vue.min.js:6 n @ vue.min.js:6 Yr.o._wrapper @ vue.min.js:6 index.js:1 Uncaught (in promise) Error: Unhandled error. (undefined) at o.emit (index.js:1:7502) at o. (index.js:8:44148) at o.emit (index.js:1:7636) at index.js:8:55097 o.emit @ index.js:1 (anonymous) @ index.js:8 o.emit @ index.js:1 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 o.emit @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:1 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:8 value @ index.js:8 (anonymous) @ index.js:8 o.emit @ index.js:1 value @ index.js:8 onlineCheck:1 Uncaught (in promise) e {_message: "Cannot read properties of null (reading 'flushStashedSamples')"} Promise.catch (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:8 value @ index.js:8 (anonymous) @ index.js:8 o.emit @ index.js:1 value @ index.js:8 10index.js:1 Uncaught TypeError: Cannot read properties of null (reading 'currentURL')

你这边是新接入xgpalyer就是用的2.x的版本，还是你之前接入过2.x的版本？如果是新接入，建议直接使用3.x的版本哈，具体接入说明https://v3.h5player.bytedance.com/

**Comment by JToung** [comment]
> > 就算升级版本也不管用
> > ```
> >     "xgplayer": "2.32.5",
> >     "xgplayer-flv.js": "2.3.0",
> >     "xgplayer-hls.js": "2.6.4",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用`this.player.src = ''`会报错 vue.min.js:6 TypeError: Cannot read properties of null (reading 'removeAllListeners') at e.value (index.js:8:40785) at t. (index.js:1:49140) at t.n (index.js:1:67795) at t.o (index.js:1:68595) at t.i (index.js:1:7227) at t.value (index.js:1:8255) at a.destroy (xgplayer.vue:135:1) at a.beforeDestroy (xgplayer.vue:70:1) at He (vue.min.js:6:11397) at Yt (vue.min.js:6:25339) Ue @ vue.min.js:6 Be @ vue.min.js:6 Re @ vue.min.js:6 He @ vue.min.js:6 Yt @ vue.min.js:6 e.$destroy @ vue.min.js:6 destroy @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 b @ vue.min.js:6 (anonymous) @ vue.min.js:6 e.$destroy @ vue.min.js:6 destroy @ vue.min.js:6 b @ vue.min.js:6 $ @ vue.min.js:6 (anonymous) @ vue.min.js:6 x @ vue.min.js:6 (anonymous) @ vue.min.js:6 e._update @ vue.min.js:6 r @ vue.min.js:6 fn.get @ vue.min.js:6 fn.run @ vue.min.js:6 un @ vue.min.js:6 (anonymous) @ vue.min.js:6 qe @ vue.min.js:6 Promise.then (async) ze @ vue.min.js:6 Ye @ vue.min.js:6 (anonymous) @ vue.min.js:6 fn.update @ vue.min.js:6 ce.notify @ vue.min.js:6 set @ vue.min.js:6 pn.set @ vue.min.js:6 goBack @ detail.vue:479 He @ vue.min.js:6 n @ vue.min.js:6 He @ vue.min.js:6 e.$emit @ vue.min.js:6 handleClick @ index.min.js:1 He @ vue.min.js:6 n @ vue.min.js:6 Yr.o._wrapper @ vue.min.js:6 index.js:1 Uncaught (in promise) Error: Unhandled error. (undefined) at o.emit (index.js:1:7502) at o. (index.js:8:44148) at o.emit (index.js:1:7636) at index.js:8:55097 o.emit @ index.js:1 (anonymous) @ index.js:8 o.emit @ index.js:1 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 o.emit @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:1 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:8 value @ index.js:8 (anonymous) @ index.js:8 o.emit @ index.js:1 value @ index.js:8 onlineCheck:1 Uncaught (in promise) e {_message: "Cannot read properties of null (reading 'flushStashedSamples')"} Promise.catch (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 (anonymous) @ index.js:8 Promise.then (async) value @ index.js:8 value @ index.js:1 value @ index.js:1 value @ index.js:1 value @ index.js:8 value @ index.js:8 (anonymous) @ index.js:8 o.emit @ index.js:1 value @ index.js:8 10index.js:1 Uncaught TypeError: Cannot read properties of null (reading 'currentURL')
> 
> 你这边是新接入xgpalyer就是用的2.x的版本，还是你之前接入过2.x的版本？如果是新接入，建议直接使用3.x的版本哈，具体接入说明https://v3.h5player.bytedance.com/

之前接入过2.x的版本，这个是个老项目，其他地方也有在用，升级怕影响到其他的
