### ISSUE TITLE
弹幕过多时，发送弹幕不显示，设置优先弹幕也无效

### ISSUE THREAD

**Issue by rongcl9219** [bytedance/xgplayer#1158]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
v3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows 10 ，Chrome  118.0.5993.89

**如何复现问题？ How to reproduce the problem?**

弹幕过多时，发送弹幕不显示，设置优先弹幕也无效 prior=true

**您期望的播放器正常行为是？ What did you expect to happen?**

发送弹幕后可以正常显示

**实际播放器的表现是？ What actually happened?**

弹幕未显示

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by aragakisyui** [comment]
你好。弹幕如何加载上去的啊？我按照文档的示例根本不显示弹幕啊

**Comment by hongqx** [comment]
弹幕插件在默认包中没有引入，需要开发的时候单独import，具体参考[内置插件>danmu ](https://v3.h5player.bytedance.com/plugins/internalplugins/danmu.html)

**Comment by hongqx** [comment]
> 你好。弹幕如何加载上去的啊？我按照文档的示例根本不显示弹幕啊

弹幕插件在默认包中没有引入，需要开发的时候单独import，具体参考[内置插件>danmu ](https://v3.h5player.bytedance.com/plugins/internalplugins/danmu.html)

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** v3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> windows 10 ，Chrome 118.0.5993.89
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> 弹幕过多时，发送弹幕不显示，设置优先弹幕也无效 prior=true
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> 发送弹幕后可以正常显示
> 
> **实际播放器的表现是？ What actually happened?**
> 
> 弹幕未显示
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

初始发送弹幕调用sendComment的时候，这些弹幕的开始时间是否都是0，或者全部一致？同一个stat弹幕很多，展示空间不够的时候，弹幕是不会一一展示的

**Comment by rongcl9219** [comment]
> > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** v3.0.9
> > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> > windows 10 ，Chrome 118.0.5993.89
> > **如何复现问题？ How to reproduce the problem?**
> > 弹幕过多时，发送弹幕不显示，设置优先弹幕也无效 prior=true
> > **您期望的播放器正常行为是？ What did you expect to happen?**
> > 发送弹幕后可以正常显示
> > **实际播放器的表现是？ What actually happened?**
> > 弹幕未显示
> > **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**
> 
> 初始发送弹幕调用sendComment的时候，这些弹幕的开始时间是否都是0，或者全部一致？同一个stat弹幕很多，展示空间不够的时候，弹幕是不会一一展示的

我们也发现了，是弹幕过多展示空间不够导致的，这个能有优化一下呢，或者有什么规避方法吗

**Comment by hongqx** [comment]
> > > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** v3.0.9
> > > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> > > windows 10 ，Chrome 118.0.5993.89
> > > **如何复现问题？ How to reproduce the problem?**
> > > 弹幕过多时，发送弹幕不显示，设置优先弹幕也无效 prior=true
> > > **您期望的播放器正常行为是？ What did you expect to happen?**
> > > 发送弹幕后可以正常显示
> > > **实际播放器的表现是？ What actually happened?**
> > > 弹幕未显示
> > > **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**
> > 
> > 
> > 初始发送弹幕调用sendComment的时候，这些弹幕的开始时间是否都是0，或者全部一致？同一个stat弹幕很多，展示空间不够的时候，弹幕是不会一一展示的
> 
> 我们也发现了，是弹幕过多展示空间不够导致的，这个能有优化一下呢，或者有什么规避方法吗

1. 对于点播，首次从服务端拿到的所有弹幕的start不应该默认是0或者全部一样，每条弹幕应该有弹幕产生的时候的播放时间点，这些时间点应该是分散的, 当视频的播放时间currentTime和start匹配的时候，弹幕才会出现；
2. 如果是直播弹幕，没有发送弹幕的时候的具体start， 那就自己设计一下start, 例如当前currentTime往后多少s, 或者加个队列定时pop, 并sendComment
以上这两个动作你先确认一下
