### ISSUE TITLE
progressDot not shown correctly

### ISSUE THREAD

**Issue by yfzhangCode** [bytedance/xgplayer#1160]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome118

**如何复现问题？ How to reproduce the problem?**
官网示例就可以复现。https://v3.h5player.bytedance.com/generate/
在功能配置里面开启进度条特殊标记， 然后鼠标hover到标记点只显示了时间，没有显示特殊标记点文字；
![image](https://github.com/bytedance/xgplayer/assets/24284536/b0ef8f79-d8bc-4ec8-9bd5-628baab20e65)

**您期望的播放器正常行为是？ What did you expect to happen?**
正确显示特殊标记内容

**实际播放器的表现是？ What actually happened?**
未正确显示特殊标记内容，只显示了进度时间

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.*i*
无

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** win10 chrome118
> 
> **如何复现问题？ How to reproduce the problem?** 官网示例就可以复现。https://v3.h5player.bytedance.com/generate/ 在功能配置里面开启进度条特殊标记， 然后鼠标hover到标记点只显示了时间，没有显示特殊标记点文字； ![image](https://user-images.githubusercontent.com/24284536/279247790-b0ef8f79-d8bc-4ec8-9bd5-628baab20e65.png)
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正确显示特殊标记内容
> 
> **实际播放器的表现是？ What actually happened?** 未正确显示特殊标记内容，只显示了进度时间
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support._i_ 无

该问题3.0.10版本已经解决，测试数据如下：
`
new Player({
  ....
  "progressDot": [
      {
                "time": 3,
                "text": "text1text1text1text1",
                duration: 2,
      },
      {
                "time": 30,
                "text": "text2text2text2text2text2",
                duration: 2,
      },
      {
                "time": 80,
                "text": "text3text3text3text3",
                duration: 2,
      },
      {
                "time": 100,
                "text": "text4text4text4text4",
                duration: 2,
      }
  ],
})
`
