### ISSUE TITLE
MP4播放报错

### ISSUE THREAD

**Issue by zzzzzzdk** [bytedance/xgplayer#1163]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

v3.0.9
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows chrome118
**如何复现问题？ How to reproduce the problem?**
播放长时间的MP4文件，放一会儿会报错，代码 加个长度判断就没问题了
![image](https://github.com/bytedance/xgplayer/assets/45683622/add81394-f45c-4486-8c80-25a37f3b4933)

![image](https://github.com/bytedance/xgplayer/assets/45683622/b28338d4-49c1-4698-8d6d-dc2822de36d0)

![image](https://github.com/bytedance/xgplayer/assets/45683622/e95dc1b0-6ec7-4dbb-a18c-d0c13c3f66d1)

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
hi ,您方便提一个PR，并且附上可复现的demo吗？
