### ISSUE TITLE
配置miniprogress为true不生效

### ISSUE THREAD

**Issue by joney888999** [bytedance/xgplayer#1167]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows系统谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
配置如下
let playerConfig = {
				  id: 'xgPlayer',
				  url: '',
				  autoplay: true,
				  playsinline: true,
				  height: this.videoHeight,
				  width: this.videoWidth,
				  plugins: [window.HlsPlayer],
				  miniprogress: true,
				  controls: {
					mode: 'normal'
				  },
				  commonStyle: {
					// 播放完成部分进度条底色
					playedColor: '#FB7299',
				  }
			}

**您期望的播放器正常行为是？ What did you expect to happen?**
出现底部进度条

**实际播放器的表现是？ What actually happened?**
未出现进度条

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无

**Comment by gemxx** [comment]
需要同时配置两个配置：
```
{
progress: true,
miniprogress: true,
}
```

**Comment by joney888999** [comment]
建议官方文档添加说明一下，以免大部分人以为配置不生效
