### ISSUE TITLE
配置url为‘’空字符串错误提示问题

### ISSUE THREAD

**Issue by joney888999** [bytedance/xgplayer#1168]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window  谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
目前的需求，先初始化播放器，后端获取播放地址后再修改src进行播放；另外设置autoplay为true或false都会显示错误界面
播放器初始化时配置如下：
let playerConfig = {
				  id: 'xgPlayer',
				  url: '',
				  autoplay: true,
				  playsinline: true,
				  height: this.videoHeight,
				  width: this.videoWidth,
				  // plugins: [window.HlsPlayer],
				  plugins: [],
				  miniprogress: true,
				  controls: {
					mode: 'normal'
				  },
				  commonStyle: {
					// 播放完成部分进度条底色
					playedColor: '#FB7299',
				  }
			}

播放器错误事件信息：
{"playerVersion":"3.0.9","currentTime":0,"duration":0,"ended":false,"readyState":0,"networkState":3,"src":"http://localhost:8080/pages/video/video-detail?id=52282","errorType":"media","errorCode":5106,"message":"empty_src","mediaError":{"code":6,"message":"empty_src"},"originError":"","host":"localhost:8080"}

**您期望的播放器正常行为是？ What did you expect to happen?**
不会显示错误界面，

**实际播放器的表现是？ What actually happened?**
<img width="159" alt="360截图17980111385754" src="https://github.com/bytedance/xgplayer/assets/48112557/aaef967a-89c6-4d0b-a4c4-ad7521822309">

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无

**Comment by gemxx** [comment]
建议没有URL不要初始化播放器。如果确实需要可以配置 `nullUrlStart: true`，但后续再设置src时，需要自己实现一下开播的逻辑，具体请参考：https://github.com/bytedance/xgplayer/blob/main/packages/xgplayer/src/player.js#L559

**Comment by joney888999** [comment]
nullUrlStart这个属性是否可以播放器内部判断实现，官方文档也没有提现。之前使用v2版本的播放器是没有报错的
