### ISSUE TITLE
播放器手机端全屏样式

### ISSUE THREAD

**Issue by draculapile** [bytedance/xgplayer#117]
![_20181102093729](https://user-images.githubusercontent.com/24435036/47889090-22c1ac00-de83-11e8-8f0b-260ba14a2a5f.jpg)
全屏之后会这样，是为什么呢？

**Comment by draculapile** [comment]
iOS跟安卓的webview都有这个问题，在Chrome下调试是可以调用全屏API -webkit-full-screen::backdrop，样式可以正常显示，放到手机里，就会是这样，不知道跟css布局有没有关系？十分感谢

**Comment by zhangxin92** [comment]
确认下使用的是xgplayer最新版本 1.1.4-alpha.7 。使用的是西瓜播放器的全屏控件吗？还是自己手动调全屏方法？

**Comment by draculapile** [comment]
我用的是1.1.3-beta-6，（我先更新一下看看），用的是xgplayer的全屏控件

**Comment by zhangxin92** [comment]
If your issue has been resolved, please close it.

**Comment by draculapile** [comment]
全屏的问题解决掉了，谢谢大佬！还有就是enterBg和enterLogo可以同时配置么，我现在同时写了以下配置，
![_20181102171644](https://user-images.githubusercontent.com/24435036/47905927-1eb57e80-dec3-11e8-8079-fd5e18f3ed57.png)
enterTips可以正常显示，自定义的enterLogo无法显示，而且位置与一个白色的转圈loading重叠，请问这个要怎么配置呢

**Comment by zhangxin92** [comment]
enterBg和enterLogo是不同的控件，可以同时配置
确认下enterLogo的url写对了么？是不是应该是 url: './static/img/video-logo.png',

**Comment by draculapile** [comment]
因为使用了webpack编译，写相对路径的时候会404找不到地址，写成去根目录下查找static静态资源里的文件可以，Chrome模拟调试下就会是正常显示的，npm run build 以后难道会出问题嘛？

**Comment by draculapile** [comment]
应该是图片的地址问题了，看了下，APP开发那边打包后static文件夹里没有这张图，可能要清一下缓存包，十分感谢！！！xgplayer好用，（上次提问题求教的时候已star），周末愉快！
