### ISSUE TITLE
移动端播放m3u8加密视频失败

### ISSUE THREAD

**Issue by joney888999** [bytedance/xgplayer#1170]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓12  小米浏览器、谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
pc端浏览器可以正常播放加密的m3u8视频
移动端播放不加密的m3u8链接可以正常播放，若是m3u8文件带#EXT-X-KEY等加密的会提示不支持的音频/视频格式
配置文件如下：
let playerConfig = {
				  id: 'xgPlayer',
				  url: this.src,
				  autoplay: true,
				  playsinline: true,
				  height: this.videoHeight,
				  width: this.videoWidth,
				  plugins: [window.HlsPlayer],
				  // 是否启用mini进度条，该选项为true，在控制栏隐藏的时候会在底部显示一个迷你进度条
				  miniprogress: true,
				  controls: {
					mode: 'normal'
				  },
				  commonStyle: {
					// 播放完成部分进度条底色
					playedColor: '#FB7299',
				  }
			}
测试用的m3u8地址：
https://v.gsuus.com/play/mbkP3jxd/index.m3u8

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常播放

**实际播放器的表现是？ What actually happened?**
播放出错
报错如下：
xgplayer error: {"playerVersion":"3.0.9","currentTime":0,"duration":2600.08,"ended":false,"readyState":0,"networkState":2,"src":"blob:http://192.168.31.110:8080/72d32c50-cc8e-458e-9d4c-4fbec026fb8e","errorType":"other","errorCode":8000,"message":"crypto is not defined","mediaError":{},"originError":"Error: crypto is not defined     at e.<anonymous> (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:165433)\n    at d (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:8684)\n    at Generator.<anonymous> (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:10043)\n    at Generator.next (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:9047)\n    at h (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:14925)\n    at a (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:15128)\n    at https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:15187\n    at new Promise (<anonymous>)\n    at e.<anonymous> (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:15068)\n    at e.<anonymous> (https://unpkg.byted-static.com/xgplayer-hls/3.0.9/dist/index.min.js:1:165797)","host":"192.168.31.110:8080"}

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
crypto 这个API只在页面是 HTTPS 的环境才支持，切到这个协议再测试一下

**Comment by joney888999** [comment]
后续发现小米浏览器、谷歌浏览器是支持m3u8的，不需要配置HlsPlayer这个plugin
