### ISSUE TITLE
"vue": "^3.3.4" + "xgplayer": "^3.0.9" 使用官方demo样式错乱

### ISSUE THREAD

**Issue by Agony95z** [bytedance/xgplayer#1172]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
^3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win11 + Chrome

**如何复现问题？ How to reproduce the problem?**
安装完成xgplayer使用官方示例，样式错乱

**您期望的播放器正常行为是？ What did you expect to happen?**
功能样式正常显示

**实际播放器的表现是？ What actually happened?**
样式布局错乱

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Agony95z** [comment]
`
<script setup lang="ts">
import {onMounted} from 'vue';
import Player from 'xgplayer';

const initPlayer = () => {
  new Player({
    id: 'mse',
    autoplay: false,
    volume: 0.3,
    url:'//sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4',
    poster: "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/poster.jpg",
    playsinline: true,
  });
};
onMounted(() => {
  initPlayer()
});
</script>

<template>
  <div id="mse"></div>
</template>

<style scoped lang="scss">
</style>
`

**Comment by Agony95z** [comment]
![xgplayer](https://github.com/bytedance/xgplayer/assets/45594186/909cf75f-d837-4cc0-9952-4438de690bea)

**Comment by gemxx** [comment]
请参考 https://h5player.bytedance.com/guide/#%E5%AE%89%E8%A3%85 这个指引，需要单独再额外引入一下CSS

`import 'xgplayer/dist/index.min.css';`
