### ISSUE TITLE
播放黑屏，啥也不显示。但是能播放就是黑屏

### ISSUE THREAD

**Issue by coder-zhangning** [bytedance/xgplayer#1177]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
有声无画问题，可能是视频的编码浏览器不支持。提供一下视频文件或者视频编码配置，以及浏览器版本
