### ISSUE TITLE
自定义图标与重播组件冲突

### ISSUE THREAD

**Issue by joney888999** [bytedance/xgplayer#1180]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows  谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
`let playerConfig = {
				  id: this.domId,
				  url: this.src,
				  autoplay: true,
				  playsinline: true,
				  height: this.playerHeight,
				  width: this.playerWidth,
				  progress: true,
				  // 是否启用mini进度条，该选项为true，在控制栏隐藏的时候会在底部显示一个迷你进度条
				  miniprogress: true,
				  // 禁用内置插件
				  ignores: ['play', 'playbackrate', 'volume'],
				  controls: {
					mode: 'flex'
				  },
				  icons: {
					startPlay: `<img style="width: 40px; height: 40px" src="/static/images/post/play.png"/>`,
					startPause: `<img style="width: 40px; height: 40px" src="/static/images/post/pause.png"/>`
				  },
				  // start插件配置
				  start: {
					  //是否禁用点击动画
					  disableAnimate: true,
					  mode: 'auto'
				  }
			}`

**您期望的播放器正常行为是？ What did you expect to happen?**
播放结束之后正常显示重播图标

**实际播放器的表现是？ What actually happened?**
播放结束之后会同时显示播放图片和重播图标，两个图标产生重叠

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无

**Comment by hongqx** [comment]
现在是播放结束之后同时显示了播放按钮和重播按钮么？如果是这样，可以个start按钮配置如下，避免其在播放结束的时候显示
new Player({
   ...,
   start: {
      isShowEnd: false
   }
}),
更多start插件的配置请看[内置插件>start](https://v3.h5player.bytedance.com/plugins/internalplugins/start.html)

**Comment by joney888999** [comment]
<img width="76" alt="360截图184811145471104" src="https://github.com/bytedance/xgplayer/assets/48112557/6bbd9fcf-11fe-44b7-85c3-616607b574af">
isShowEnd: false
配置了这个属性还是一样的
