### ISSUE TITLE
在某些机型下，提示 当解码时发生错误

### ISSUE THREAD

**Issue by wayward-man** [bytedance/xgplayer#1181]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
oppo 安卓下的 webview内

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

正常播放 或者 给出不可用的原因

**实际播放器的表现是？ What actually happened?**
<img width="433" alt="image" src="https://github.com/bytedance/xgplayer/assets/26971540/44192f88-c60e-4cda-809f-ad651634e497">

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？

**Comment by wayward-man** [comment]
> 辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？

用的是 ，wbplayer-mp4@2.0.0， 同一个视频在这个手机 微信内正常，但是自研app的 webview下异常，下面是用的手机
![image](https://github.com/bytedance/xgplayer/assets/26971540/1defd315-24c1-43f4-81f2-6c8f629101fb)

**Comment by hongqx** [comment]
> > 辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？
> 
> 用的是 ，wbplayer-mp4@2.0.0， 同一个视频在这个手机 微信内正常，但是自研app的 webview下异常，下面是用的手机 ![image](https://user-images.githubusercontent.com/26971540/283028840-1defd315-24c1-43f4-81f2-6c8f629101fb.png)

尝试直接使用xgplayer, 去掉xgplayer-mp4的使用测试一下，可能是xgplayer-mp4在移动端兼容出了问题，移动端的MSE兼容没有pc端好

**Comment by wayward-man** [comment]
> > > 辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？
> > 
> > 
> > 用的是 ，wbplayer-mp4@2.0.0， 同一个视频在这个手机 微信内正常，但是自研app的 webview下异常，下面是用的手机 ![image](https://user-images.githubusercontent.com/26971540/283028840-1defd315-24c1-43f4-81f2-6c8f629101fb.png)
> 
> 尝试直接使用xgplayer, 去掉xgplayer-mp4的使用测试一下，可能是xgplayer-mp4在移动端兼容出了问题，移动端的MSE兼容没有pc端好

请问 这里的 MSE值得是啥 ，媒体源扩展（Media Source Extensions) 还是 均方误差（Mean Squared Error），因为 目前切换架构不是特别方便，所以我想问下 有没有什么办法 通过js来判断下 MSE 兼容性问题，我这边来统计下

**Comment by hongqx** [comment]
> > > > 辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？
> > > 
> > > 
> > > 用的是 ，wbplayer-mp4@2.0.0， 同一个视频在这个手机 微信内正常，但是自研app的 webview下异常，下面是用的手机 ![image](https://user-images.githubusercontent.com/26971540/283028840-1defd315-24c1-43f4-81f2-6c8f629101fb.png)
> > 
> > 
> > 尝试直接使用xgplayer, 去掉xgplayer-mp4的使用测试一下，可能是xgplayer-mp4在移动端兼容出了问题，移动端的MSE兼容没有pc端好
> 
> 请问 这里的 MSE值得是啥 ，媒体源扩展（Media Source Extensions) 还是 均方误差（Mean Squared Error），因为 目前切换架构不是特别方便，所以我想问下 有没有什么办法 通过js来判断下 MSE 兼容性问题，我这边来统计下，然后根据情况 来看如何 处理

MSE就是Media Source Extensions

**Comment by hongqx** [comment]
> > > > > 辛苦给一下使用的具体版本，另外这个是同一个视频在当前环境下必现，还是偶现？
> > > > 
> > > > 
> > > > 用的是 ，wbplayer-mp4@2.0.0， 同一个视频在这个手机 微信内正常，但是自研app的 webview下异常，下面是用的手机 ![image](https://user-images.githubusercontent.com/26971540/283028840-1defd315-24c1-43f4-81f2-6c8f629101fb.png)
> > > 
> > > 
> > > 尝试直接使用xgplayer, 去掉xgplayer-mp4的使用测试一下，可能是xgplayer-mp4在移动端兼容出了问题，移动端的MSE兼容没有pc端好
> > 
> > 
> > 请问 这里的 MSE值得是啥 ，媒体源扩展（Media Source Extensions) 还是 均方误差（Mean Squared Error），因为 目前切换架构不是特别方便，所以我想问下 有没有什么办法 通过js来判断下 MSE 兼容性问题，我这边来统计下，然后根据情况 来看如何 处理
> 
> MSE就是Media Source Extensions

你描述的 wbplayer-mp4@2.0.0 是xgplayer-mp4么？你现在使用的xgplayer和xgplayer-mp4(如果有的话)各自的版本号是多少？

**Comment by wayward-man** [comment]
具体版本 是  xgplayer-mp4 2.0.0

**Comment by hongqx** [comment]
> 具体版本 是 xgplayer-mp4 2.0.0

去掉xgplayer-mp4的使用测试一下，如果还是报这个错，可能是当前环境不支持你这个文件格式的解码
