### ISSUE TITLE
多语言适配

### ISSUE THREAD

**Issue by zxlJustin** [bytedance/xgplayer#1182]
最新版本的西瓜，针对阿拉伯地区镜面对称问题(从右往左习惯)，导致进度条方向问题(阿拉伯地区从右往左)，右滑增加进度

**Comment by hongqx** [comment]
> 最新版本的西瓜，针对阿拉伯地区镜面对称问题(从右往左习惯)，导致进度条方向问题(阿拉伯地区从右往左)，右滑增加进度

这个需求，你可以在微信群中@我详细聊一下，我们再做具体的支持

**Comment by zxlJustin** [comment]
没进微信群，方便拉我进去吗？微信号：18970492131&nbsp; &nbsp; 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月20日(星期一) 上午10:33
收件人: ***@***.***&gt;; 
抄送: "凌@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytedance/xgplayer] 多语言适配 (Issue #1182)





  
最新版本的西瓜，针对阿拉伯地区镜面对称问题(从右往左习惯)，导致进度条方向问题(阿拉伯地区从右往左)，右滑增加进度
  
这个需求，你可以在微信群中@我详细聊一下，我们再做具体的支持

**Comment by hongqx** [comment]
> 18970492131

![image](https://github.com/bytedance/xgplayer/assets/7855356/5856a049-17a2-4774-bd12-7e3ab98286bf)
群名片，你加一下

**Comment by hongqx** [comment]
> 没进微信群，方便拉我进去吗？微信号：18970492131&nbsp; &nbsp; 谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月20日(星期一) 上午10:33 收件人: ***@***.***&gt;; 抄送: "凌@***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bytedance/xgplayer] 多语言适配 (Issue #1182) 最新版本的西瓜，针对阿拉伯地区镜面对称问题(从右往左习惯)，导致进度条方向问题(阿拉伯地区从右往左)，右滑增加进度 这个需求，你可以在微信群中@我详细聊一下，我们再做具体的支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![image](https://github.com/bytedance/xgplayer/assets/7855356/c4de8d96-c293-4231-a9d1-1baee8922011)
扫一下群名片，群里找叫hqx的人
