### ISSUE TITLE
在微信web打开浏览器，如何才能防止播放时息屏

### ISSUE THREAD

**Issue by 1103337638** [bytedance/xgplayer#1183]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

web端的播放不会阻止屏幕息屏，如果想要实现息屏，可以参考一下https://blog.csdn.net/u010716530/article/details/105199515
