### ISSUE TITLE
"Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs=hev1.1.6.L93.B0') is unsupported."

### ISSUE THREAD

**Issue by WesySu** [bytedance/xgplayer#1185]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.0-next.56",
"xgplayer-hls": "^3.0.1"
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
谷歌和edge都不行

**如何复现问题？ How to reproduce the problem?**
播放video/mp4;codecs=hev1.1.6.L93.B0类型不支持

**Comment by hongqx** [comment]
codecs=hev1.1.6.L93.B0 这个表明当前视频的h265编码，播放报这个错是因为当前浏览器不支持h265解码，具体浏览器是否支持h265视频的检测，可以参考视频封装/编码格式问题
[#](https://v3.h5player.bytedance.com/guide/extends/about_format.html#%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81hevc-h265)的说明
