### ISSUE TITLE
多播放器问题

### ISSUE THREAD

**Issue by zhaojunliing** [bytedance/xgplayer#1188]
需要一个统一的进度条和设置倍速，这个有没有demo给看看，进度条不知道怎么单独提取出来

**Comment by hongqx** [comment]
是多个播放器公用进度条和倍速？还是其他的，辛苦描述详细一点

**Comment by zhaojunliing** [comment]
多个播放器共用

**Comment by zhaojunliing** [comment]
你好，有解决方法没？ @hongqx

**Comment by hongqx** [comment]
> 你好，有解决方法没？ @hongqx

这种情况，前提条件是多个实例播放的视频时长是一致的，时长不一致，无法公公用进度条
 要实现的话方案是，只有一个播放器限制控制栏，其他播放器controls配置为空，而且需要多个实例之间状态同步控制，例如有 A,B,C三个实例， 只有A有播控，A暂停or卡顿的时候，B、C也暂停；A起播，B、C也起播
