### ISSUE TITLE
播放mp4，总是播一会儿就网络错误了

### ISSUE THREAD

**Issue by JackShijt** [bytedance/xgplayer#1191]
![image](https://github.com/bytedance/xgplayer/assets/56808243/2603a124-607f-44c4-8db0-a5afe802599c)
这是官网的demo，也是播放几秒就网络错了，但是进度还在走，点击刷新视频就会继续播放，重播的时候就没有问题了。
视频地址：http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
![image](https://github.com/bytedance/xgplayer/assets/56808243/17669179-0317-4b88-9494-6e5017ef8985)
同样在我项目里也出现了问题，官网在线生成里的demo就没有问题。

**Comment by JackShijt** [comment]
首先播放错误了，进度应该暂停；其次就是为什么mp4会播放错误？放在其他播放器上也是没有问题的

**Comment by zhaojunliing** [comment]
你网络存在问题吧

**Comment by JackShijt** [comment]
> 你网络存在问题吧

我可以确定，网络是没有问题的

**Comment by JackShijt** [comment]
我在官网的示例里试了，所有的mp4视频都是这样，到了在线生成的demo里就没事儿

**Comment by JackShijt** [comment]
![image](https://github.com/bytedance/xgplayer/assets/56808243/905950c9-a12c-4c37-96d3-7ff4f81454e8)
用原生的video也是可以的

**Comment by zhaojunliing** [comment]
> > 你网络存在问题吧
> 
> 我可以确定，网络是没有问题的

你浏览器直接播放你提供的MP4试试，这个和人家这个播放器没关系，MP4文件过大，浏览器应该是分断加载了，你请求里面有丢包，按道理说应该是网络问题

**Comment by hongqx** [comment]
> ![image](https://user-images.githubusercontent.com/56808243/283330689-905950c9-a12c-4c37-96d3-7ff4f81454e8.png) 用原生的video也是可以的

如果方便的话提供一下你这边播放异常的mp4文件吧~

**Comment by JackShijt** [comment]
> > ![image](https://user-images.githubusercontent.com/56808243/283330689-905950c9-a12c-4c37-96d3-7ff4f81454e8.png) 用原生的video也是可以的
> 
> 如果方便的话提供一下你这边播放异常的mp4文件吧~

视频地址在上面

**Comment by hongqx** [comment]
> http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

你的问题：
原因是使用官网示例中的代码播放失败是因为你的这个播放地址不支持跨域，示例中的代码默认使用mse播放mp4, 也就是Mp4Plugin插件的加入
你使用在线生成ok是因为在线生成你没有选使用MSE播放mp4

最近的版本v3.0.11-alpha.3 mp4插件添加了针对MSE播放场景跨域错误，降级到原生播放的处理，你可以测试一下
