### ISSUE TITLE
erro事件里的错误信息于文档不符合。错误吗5200，在文档里没找到。

### ISSUE THREAD

**Issue by chaosforfun** [bytedance/xgplayer#1192]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

MacOS chrome
**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
报错信息里有个错误吗 5002，文档里没有

**实际播放器的表现是？ What actually happened?**

{"playerVersion":"3.0.9","currentTime":0,"duration":0,"ended":false,"readyState":0,"networkState":2,"src":"blob:xxx","errorType":"media","errorCode":5200,"message":"Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs=hev1.1.6.L93.B0') is unsupported.","mediaError":{},"originError":"Error: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs=hev1.1.6.L93.B0') is unsupported."}

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> MacOS chrome **如何复现问题？ How to reproduce the problem?**
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 报错信息里有个错误吗 5002，文档里没有
> 
> **实际播放器的表现是？ What actually happened?**
> 
> {"playerVersion":"3.0.9","currentTime":0,"duration":0,"ended":false,"readyState":0,"networkState":2,"src":"blob:xxx","errorType":"media","errorCode":5200,"message":"Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs=hev1.1.6.L93.B0') is unsupported.","mediaError":{},"originError":"Error: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs=hev1.1.6.L93.B0') is unsupported."}

错误码说明已更新
[error](https://v3.h5player.bytedance.com/api/error.html#type)

**Comment by chaosforfun** [comment]
还是没有5200啊

**Comment by gemdeng** [comment]
好像也没有5100
