### ISSUE TITLE
请问如何禁用视频范围内拦截用户手势

### ISSUE THREAD

**Issue by FlashWo1f** [bytedance/xgplayer#1194]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.9

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS 17.1.1  Webview Safari

**如何复现问题？ How to reproduce the problem?**
H5页面从上至下平铺了若干个视频，父级设置 overflow auto 但是 手势在视频上是无法滚动的，很明显是被视频拦截了行为，有没有办法让手势在视频范围内上下能滚动页面呢

**您期望的播放器正常行为是？ What did you expect to happen?**
正常根据手势滚动

**实际播放器的表现是？ What actually happened?**
手势被视频范围拦截

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** iOS 17.1.1 Webview Safari
> 
> **如何复现问题？ How to reproduce the problem?** H5页面从上至下平铺了若干个视频，父级设置 overflow auto 但是 手势在视频上是无法滚动的，很明显是被视频拦截了行为，有没有办法让手势在视频范围内上下能滚动页面呢
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常根据手势滚动
> 
> **实际播放器的表现是？ What actually happened?** 手势被视频范围拦截
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

使用禁用手势的配置即可，配置如下：
`
  new Player({
     ...,
     mobile: {
        disableGesture： true
     }
  })
`

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.9
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** iOS 17.1.1 Webview Safari
> 
> **如何复现问题？ How to reproduce the problem?** H5页面从上至下平铺了若干个视频，父级设置 overflow auto 但是 手势在视频上是无法滚动的，很明显是被视频拦截了行为，有没有办法让手势在视频范围内上下能滚动页面呢
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常根据手势滚动
> 
> **实际播放器的表现是？ What actually happened?** 手势被视频范围拦截
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

使用禁用手势的配置即可，配置如下：
`
  new Player({
     ...,
     mobile: {
        disableGesture： true
     }
  })
`
具体插更多配置请看
[内置插件>mobile](https://v3.h5player.bytedance.com/plugins/internalplugins/mobile.html#config)
