### ISSUE TITLE
点播flv，一直在加载中

### ISSUE THREAD

**Issue by yangjiechina** [bytedance/xgplayer#1198]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11和chrome119

**如何复现问题？ How to reproduce the problem?**
测试提供的点播flv文件

[05.59.31.503.flv.zip](https://github.com/bytedance/xgplayer/files/13413435/05.59.31.503.flv.zip)

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@yangjiechina 试下3.0.11-alpha.2。对于flv 点播长视频，需要服务能支持206请求响应

**Comment by mlongv** [comment]
您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?
"xgplayer": "^3.0.17",
"xgplayer-flv": "^3.0.17"

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
macbook Pro 2015
谷歌浏览器：124.0.6367.209（正式版本） (x86_64)

如何复现问题？ How to reproduce the problem?
![WechatIMG245](https://github.com/bytedance/xgplayer/assets/25856910/6ca868df-5f1f-4106-b838-bf208dae0ead)
