### ISSUE TITLE
监听hls播放网络问题播放失败后，能否监听网络稳定后重新正常播放事件？

### ISSUE THREAD

**Issue by GHwangxingren** [bytedance/xgplayer#1206]
**您期望的播放器正常行为是？ What did you expect to happen?**
通过“HLS_ERROR”监听网络问题显示错误页面，恢复正常后重新去掉错误层，正常播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您期望的播放器正常行为是？ What did you expect to happen?** 通过“HLS_ERROR”监听网络问题显示错误页面，恢复正常后重新去掉错误层，正常播放
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

canplay事件
