### ISSUE TITLE
有画面但是一直转圈圈

### ISSUE THREAD

**Issue by bigff-0527** [bytedance/xgplayer#1217]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows edg

**如何复现问题？ How to reproduce the problem?**
我是用zlm推流的地址播放的 ，vlc播放器能播放，但是前端用西瓜播放器就会出现这样：有画面但是一直转圈圈
![image](https://github.com/bytedance/xgplayer/assets/58465932/b5a04c80-57e2-454a-8e54-2e2e6051173c)

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@bigff-0527 可以dump一份数据看下

**Comment by bigff-0527** [comment]
> @bigff-0527 可以dump一份数据看下

![image](https://github.com/bytedance/xgplayer/assets/58465932/001cd6ac-7b6d-4432-b651-2590f9e91ba2)

**Comment by xiyuyizhi** [comment]
@bigff-0527 能保持成flv文件的，上传下？

**Comment by xiyuyizhi** [comment]
@bigff-0527 能保存成flv文件的吗，上传下？
