### ISSUE TITLE
[bug]xgplaer-flv插件在Firefox和safari无法播放

### ISSUE THREAD

**Issue by pandaxba** [bytedance/xgplayer#122]
Firefox报错截图：
![image](https://user-images.githubusercontent.com/4688875/48412873-e5adc180-e780-11e8-96bc-629d589d5240.png)
safari也播放不了

**Comment by leonardoFu** [comment]
hi @pandaxba ，抱歉久等了，我在firefox上面大概定位到了问题，应该跟firefox上面video的blobURL限制有关，正在尝试修复。在safari上没有复现，可以提供一下safari的报错截图么？

**Comment by karlcow** [comment]
@leonardoFu  On https://github.com/webcompat/web-bugs/issues/22931 we got an issue with Firefox. The player fails to specify the `type=''` in `source` and so the video is not loaded.
