### ISSUE TITLE
Mp4 播放失败

### ISSUE THREAD

**Issue by LittleGhosts** [bytedance/xgplayer#1220]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Windows Chrome

**如何复现问题？ How to reproduce the problem?**

使用文档上的例子 https://h5player.bytedance.com/examples/ 
但将其中的url 替换成在线生成的 MP4 demo 链接
 "//lf3-static.bytednsdoccom/obj/eden-cn/nupenuvpxnuvo/xgplayer_doc/xgplayer-demo.mp4"
就会出现解码失败

**您期望的播放器正常行为是？ What did you expect to happen?**

正常播放

**实际播放器的表现是？ What actually happened?**

解码失败

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by shanyutongxue** [comment]
The link cannot be opened, please check the validity of the link.
