### ISSUE TITLE
播放器能监听单次播放的总时长吗？

### ISSUE THREAD

**Issue by allenzxn** [bytedance/xgplayer#1221]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
你是单次播放累计播放时长么？排除卡顿、seek、倍速因素之后用户实际的观看时长？

**Comment by hongqx** [comment]
> 你是单次播放累计播放时长么？排除卡顿、seek、倍速因素之后用户实际的观看时长？


你是单次播放累计播放时长么？排除卡顿、seek、倍速因素之后用户实际的观看时长？



> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**


你是单次播放累计播放时长么？排除卡顿、seek、倍速因素之后用户实际的观看时长？

**Comment by allenzxn** [comment]
是的，统计用户实际的观看时长

**Comment by hongqx** [comment]
> 是的，统计用户实际的观看时长

https://v3.h5player.bytedance.com/api/attribute.html#cumulatetime
这个时长是剔除了用户暂停、卡顿、错误等的实际观看时长
