### ISSUE TITLE
win7环境，hls.js在chrome上可以播放，不能在IE11上播放

### ISSUE THREAD

**Issue by txmz** [bytedance/xgplayer#1224]
3.0.1版本播放hls格式在谷歌上没有问题，为啥不能在IE11上播放。
浏览器在执行let player = new window.Player时报对象不支持此操作。

<script charset="utf-8" src="./player/3.0.1/index.min.js"></script>
 <script charset="utf-8" src="./player/3.0.1/hls/index.min.js"></script>
let player = new window.Player({
          id: 'mse',
          url: url,
          autoplay: true,
          playsinline: true,
          height: window.innerHeight,
          width: window.innerWidth,
          download: true,
          pip: true,
          plugins: [window.HlsPlayer]

**Comment by shanyutongxue** [comment]
请按照格式进行提问
Please ask questions in the format.

**Comment by gemxx** [comment]
问题同 [1226](https://github.com/bytedance/xgplayer/issues/1226)，请参考[caniuse](https://caniuse.com/?search=MSE)，MSE在win7上是完全不支持的。
