### ISSUE TITLE
V3调用screenShot方法 是不是没法配置禁止下载了

### ISSUE THREAD

**Issue by ehangwork** [bytedance/xgplayer#1225]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.10",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOs/Chorme

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
只返回截图，不自动下载图片

**实际播放器的表现是？ What actually happened?**
既返回截图，也自动下载图片

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by woxiaoyao81** [comment]
V2版支持截图后设置决定是否下载，而V3版则不支持这个设置，我也给官方反馈了！而且截图尺寸设置也是比较不方便，默认竟然不是截取视频的尺寸，却是视频默认尺寸600和337，视频全屏播放或改变一下视频尺寸，截图就尴尬了，已经建议官方调整为视频尺寸的百分比，兄弟这个建议是否可以？

**Comment by ehangwork** [comment]
@woxiaoyao81 可以的👌
