### ISSUE TITLE
chrome上可以正常播放，IE11上提示“不支持的音频/视频格式”

### ISSUE THREAD

**Issue by txmz** [bytedance/xgplayer#1226]
chrome上可以正常播放，IE11上提示“不支持的音频/视频格式”
版本2.3.5

 <script src="./packages/xgplayer/browser/index.js" charset="utf-8"></script>
    <script src="./packages/xgplayer-hls.js/browser/index.js" charset="utf-8"></script>

  <script type="text/javascript">
        var player = new HlsJsPlayer({
            id: 'vs',
            url: './video/m3u8/xgplayer-demo.m3u8',
            poster: './poster.png'
        })
    </script>

**Comment by hongqx** [comment]
> chrome上可以正常播放，IE11上提示“不支持的音频/视频格式” 版本2.3.5
> 
> <script src="./packages/xgplayer/browser/index.js" charset="utf-8"></script>
> ```
> <script src="./packages/xgplayer-hls.js/browser/index.js" charset="utf-8"></script>
> ```
> 
> <script type="text/javascript"> var player = new HlsJsPlayer({ id: 'vs', url: './video/m3u8/xgplayer-demo.m3u8', poster: './poster.png' }) </script>

检查一下视频编码是不是使用了h265

**Comment by txmz** [comment]
是IE11不支持MSE




lizhi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/xgplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月11日(星期一) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/xgplayer] chrome上可以正常播放，IE11上提示“不支持的音频/视频格式” (Issue #1226)





  
chrome上可以正常播放，IE11上提示“不支持的音频/视频格式” 版本2.3.5
 <script src="./packages/xgplayer/browser/index.js" charset="utf-8"&gt;</script&gt; <script src="./packages/xgplayer-hls.js/browser/index.js" charset="utf-8"&gt;</script&gt;  <script type="text/javascript"&gt; var player = new HlsJsPlayer({ id: 'vs', url: './video/m3u8/xgplayer-demo.m3u8', poster: './poster.png' }) </script&gt;  
检查一下视频编码是不是使用了h265

**Comment by gemxx** [comment]
@txmz 是的，IE11 MSE支持的不好，因此不建议在IE系列浏览器去用MSE播放
