### ISSUE TITLE
播放器加载视频时重复打开/关闭固定视频会出现视频一直显示加载

### ISSUE THREAD

**Issue by xing403** [bytedance/xgplayer#1228]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
version:`2.32.3`

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window11 & Chrome

**如何复现问题？ How to reproduce the problem?**
播放器加载视频时重复打开/关闭固定视频会出现视频一直显示加载

**您期望的播放器正常行为是？ What did you expect to happen?**
对于同一个视频链接播放时缓存的进度时间已经超过了当前播放的时间，此时不应该再继续显示加载的状态(使用了 autoplay 加载自动播放)

**实际播放器的表现是？ What actually happened?**
会出现视频播放几帧后一直停留在加载的状态

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** version:`2.32.3`
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** window11 & Chrome
> 
> **如何复现问题？ How to reproduce the problem?** 播放器加载视频时重复打开/关闭固定视频会出现视频一直显示加载
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 对于同一个视频链接播放时缓存的进度时间已经超过了当前播放的时间，此时不应该再继续显示加载的状态(使用了 autoplay 加载自动播放)
> 
> **实际播放器的表现是？ What actually happened?** 会出现视频播放几帧后一直停留在加载的状态

尝试切换的时候，调用一下player.video.load()，清空一下当前video的缓存
