### ISSUE TITLE
uniapp 使用 xgplayer属性  fluid: true黑屏，fluid: fasle,播放器容器比当前屏幕大很多，无法完全显示视频

### ISSUE THREAD

**Issue by vuejsstudy** [bytedance/xgplayer#1235]

**Comment by Gs19990801** [comment]
换个插件 哥哥

**Comment by woxiaoyao81** [comment]
3版视频尺寸和封面尺寸有点问题，不要使用fluid，已经给官方反馈了，目前我在uniapp中处理方式如下：
1. 视频无法充满容器，经个人测试设置fitVideoSize和videoFillMode无效，样式覆盖无效
解决方法：设置`videoAttributes:{width:'100'%,height:'100%'}`，直接修改原视频属性
2. poster封面无法充满容器，导致视频可能漏一部分，比较难看，原因是官方样式中`background-size:100% auto`
解决方法：个人测试样式覆盖无效,直接修改官方样式文件，调整为`background-size:100% 100%`

**Comment by zcj409861716** [comment]
我是根据上面大哥 也是直接给video 加原生样式了
if(this.isMobileDevice){
    videoAttributes={
      crossOrigin: "anonymous",
      style:`width:${this.width};height:${this.height};position:absolute;top:0;left:0;`
    }
  }else{
    videoAttributes={
      crossOrigin: "anonymous",
    }
  }

**Comment by yingnian** [comment]
今天排查了半天，pc 端怎么都没问题，uniapp 框架下的 h5 死活就是不行；
在 new Player({
  videoAttributes:{width:'100'%,height:'100%'}
})
按此设置可以
