### ISSUE TITLE
请问西瓜视频的移动端 Web 是如何解决 <video> 控件被浏览器劫持的？

### ISSUE THREAD

**Issue by KaygNas** [bytedance/xgplayer#1239]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
HarmonyOS 3.0.0
百度浏览器 13.40.0.10

**如何复现问题？ How to reproduce the problem?**
1. 打开网页，视频播放器未被劫持
2. 点击播放后，视频播放器被劫持

**您期望的播放器正常行为是？ What did you expect to happen?**
播放中的视频播放器未被劫持

**实际播放器的表现是？ What actually happened?**
播放中的视频播放器被劫持

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by KaygNas** [comment]
了解到移动端浏览器劫持 <video> 控件很常见，但是发现同样使用西瓜播放器，西瓜视频的 Web 却不会被劫持，请问是经过什么特别的处理吗？还是说西瓜视频特别向各个浏览器厂商沟通过，所以浏览器厂商对西瓜视频 Web 特别处理，不劫持？

**Comment by yuguaa** [comment]
应该是解决了一部分，你看看vivo原生浏览器是不是很奇怪
