### ISSUE TITLE
西瓜浏览器 播放h265 视频流数据有的pc 播放错误，有的正常

### ISSUE THREAD

**Issue by xgl198899** [bytedance/xgplayer#1248]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
 西瓜播放器3.0.4 版本 使用的 flv 插件 播放 flv h265 数据流

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 谷歌浏览器

1 请问西瓜浏览器使用的解码方式是硬解码还是软解码？
2 现象是这样的  播放同一个flv h265 编码的流数据 有的电脑（pc）播放错误，有的电脑正常播放，错误的电脑 用的环境 win10，谷歌浏览器，显卡类型 NVIDIA GeForce GT 710， 报错误打印出来时这样的
![img_v3_0263_6db1e779-e72d-4765-98c2-78697613e05g](https://github.com/bytedance/xgplayer/assets/37318865/c861e575-37e3-414d-9999-e45c5377c4c1)
查看了下 5104 错误 资源媒体不支持，具体也看不懂什么意思，请问下这种现象是什么原因呢

**Comment by gemxx** [comment]
hevc浏览器是通过硬解的方式支持的，因此需要你的显卡支持硬解hevc。GT750不支持hevc，请参考：https://bluesky-soft.com/en/dxvac/deviceInfo/decoder/nvidia.html
