### ISSUE TITLE
controls隐藏和显示抛出事件

### ISSUE THREAD

**Issue by yuguaa** [bytedance/xgplayer#1251]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.x

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome@lastest

**如何复现问题？ How to reproduce the problem?**
none

新需求

**您期望的播放器正常行为是？ What did you expect to happen?**
controls隐藏能否抛出事件

**实际播放器的表现是？ What actually happened?**
未抛出事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.x
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** chrome@lastest
> 
> **如何复现问题？ How to reproduce the problem?** none
> 
> 新需求
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** controls隐藏能否抛出事件
> 
> **实际播放器的表现是？ What actually happened?** 未抛出事件
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

可以监听
![image](https://github.com/bytedance/xgplayer/assets/7855356/991f7f2b-af76-413a-aa52-e9c5f8998d8d)
这两个事件，和controls的呼出和隐藏是同步的
