### ISSUE TITLE
动态设置poster图片链接不生效？

### ISSUE THREAD

**Issue by Agony95z** [bytedance/xgplayer#1256]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.10"；"vue": "^3.3.4"；

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win11 chrome(120.0.6099.109)
**如何复现问题？ How to reproduce the problem?**
<script setup lang="ts">
import Player from 'xgplayer';
import Progress from 'xgplayer/es/plugins/progress';
import { I18N } from 'xgplayer';
import ZH from 'xgplayer/es/lang/zh-cn'
import 'xgplayer/dist/index.min.css';
import {onMounted} from "vue";

let player = null;
let options = {
  id: 'mse',
  lang: 'zh',
  poster: '',
  url: '//media.w3.org/2010/05/sintel/trailer.mp4',
  height: '300px',
  width: '400px',
  playbackRate: [1],
  keyShortcut: false,
  plugins: [Progress,], // 传入需要组装的插件
  progress: {
    closeMoveSeek: true,
    isCloseClickSeek: true,
  }
};
// 启用中文
I18N.use(<any>ZH)

const handleClick = () => {
  player.playNext({
    url: '//vjs.zencdn.net/v/oceans.mp4',
    poster: 'http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png',
  })
};

onMounted(() => {
  player = new Player(options);
});

</script>

<template>
  <div class="video-container">
    <div id="mse"></div>
    <el-button @click="handleClick">点我</el-button>
    <div class="text-3xl">video/index</div>
  </div>
</template>

<style scoped lang="scss">
#mse {
  width: 400px;
  height: 300px;
}
</style>

**您期望的播放器正常行为是？ What did you expect to happen?**
点击切换视频，重新赋值url和poster,默认展示poster设置的图片

**实际播放器的表现是？ What actually happened?**
player.playNext({
    url: '//vjs.zencdn.net/v/oceans.mp4',
    poster: 'http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png',
  })；重新设置poster不生效；
![image](https://github.com/bytedance/xgplayer/assets/45594186/2db018df-5c9f-4a51-9d95-6a7a5b1e4f63)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Agony95z** [comment]
不小心误关了，请大佬帮忙解惑下

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** "xgplayer": "^3.0.10"；"vue": "^3.3.4"；
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** win11 chrome(120.0.6099.109) **如何复现问题？ How to reproduce the problem?**
> 
> <script setup lang="ts"> import Player from 'xgplayer'; import Progress from 'xgplayer/es/plugins/progress'; import { I18N } from 'xgplayer'; import ZH from 'xgplayer/es/lang/zh-cn' import 'xgplayer/dist/index.min.css'; import {onMounted} from "vue"; let player = null; let options = { id: 'mse', lang: 'zh', poster: '', url: '//media.w3.org/2010/05/sintel/trailer.mp4', height: '300px', width: '400px', playbackRate: [1], keyShortcut: false, plugins: [Progress,], // 传入需要组装的插件 progress: { closeMoveSeek: true, isCloseClickSeek: true, } }; // 启用中文 I18N.use(ZH) const handleClick = () => { player.playNext({ url: '//vjs.zencdn.net/v/oceans.mp4', poster: 'http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png', }) }; onMounted(() => { player = new Player(options); }); </script>
> 点我
> video/index
> <style scoped lang="scss"> #mse { width: 400px; height: 300px; } </style>
> **您期望的播放器正常行为是？ What did you expect to happen?** 点击切换视频，重新赋值url和poster,默认展示poster设置的图片
> 
> **实际播放器的表现是？ What actually happened?** player.playNext({ url: '//vjs.zencdn.net/v/oceans.mp4', poster: '[http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png](http://oss.test.train.pam21.com/train-oss/125475749472960512/%E4%BC%81%E4%B8%9A%E7%BA%A7%E5%BA%94%E7%94%A8.png)', })；重新设置poster不生效； ![image](https://private-user-images.githubusercontent.com/45594186/291526878-2db018df-5c9f-4a51-9d95-6a7a5b1e4f63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjc1MjcsIm5iZiI6MTcwMzEyNzIyNywicGF0aCI6Ii80NTU5NDE4Ni8yOTE1MjY4NzgtMmRiMDE4ZGYtNWM5Zi00YTUxLTlkOTUtNmE3YTViMWU0ZjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwN2E2NDRiODk4ZDM2ZDExMTBhMzgyMzI1MGIxNmI5ZWZkYjAyZjFhOWViYTllOTJjMjZjM2MxYmNkMmU0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnahhnLBC9nZl9hkR4DAKb95A20FITHJsZfzgMbOTUw)
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

player.playNext({
url: '//vjs.zencdn.net/v/oceans.mp4',
poster: '[http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png](http://oss.test.train.pam21.com/train-oss/125475749472960512/%E4%BC%81%E4%B8%9A%E7%BA%A7%E5%BA%94%E7%94%A8.png)',
})；
player.poster = [http://oss.test.train.pam21.com/train-oss/125475749472960512/企业级应用.png]

这样兼容一下，这个问题将在下个版本修复
