### ISSUE TITLE
截图插件改进建议，否则真心不好用

### ISSUE THREAD

**Issue by woxiaoyao81** [bytedance/xgplayer#1257]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window 11，Edge 120.0.2210.77

**如何复现问题？ How to reproduce the problem?**

问题1： 2版支持截图后设置是否保存图片，3版则移除这个设置，这样想使用截图插件截图，然后自己根据平台(APP和Electron)处理下载，H5可继续使用原下载，现在移除了想自己下载，还需要自己自定义图标或插件，明显这个是不合适的，截图中api提供了截图和下载功能，明显这个功能已经分开，希望在截图插件中支持2版这个配置

问题2：2版截图默认是根据视频尺寸，这样截图不用自己再设置什么尺寸了，而3版提供了width和height，但这个默认值实在不合适，否则视频调整后还要用户自己去计算尺寸，建议调整为视频宽度的百分比，这样更合理，写成绝对值明显是不方便使用的

问题3：顺便提一下视频和封面尺寸的问题，通过设置fitVideoSize和videoFillMode无法将视频充满容器，封面官方样式是background-size:100% auto也是比较不好体验，如果封面尺寸不当，导致封面和视频无法覆盖的尴尬

**您期望的播放器正常行为是？ What did you expect to happen?**
1. 截图支持2版saveImg参数，支持用户定义是否下载截图
2. 截图尺寸调整为视频尺寸的百分比，另外也可增加定位，单位也是以视频尺寸的百分比，这样好控制
3. 视频和封面都应该充满容器

**实际播放器的表现是？ What actually happened?**
1. 截图只支持启用和禁用，不支持截图后不下载的设置
2. 截图尺寸无法适应容器尺寸的变化
3. 视频和封面通过fitVideoSize、videoFillMode，width、height和样式覆盖均无法实现充满容器。目前视频是通过videoAttributes:{width:'100'%,height:'100%'}实现充满，封面通过修改官方样式实现

希望新版在优化功能时，尽量继承已有的好的功能！！！还有就是跨端上能支持更好，我现在适配到PC端和APP端，但微信小程序端无法适配，因为是操作DOM，这个能否作为下步方向

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.10 **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** window 11，Edge 120.0.2210.77
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> 问题1： 2版支持截图后设置是否保存图片，3版则移除这个设置，这样想使用截图插件截图，然后自己根据平台(APP和Electron)处理下载，H5可继续使用原下载，现在移除了想自己下载，还需要自己自定义图标或插件，明显这个是不合适的，截图中api提供了截图和下载功能，明显这个功能已经分开，希望在截图插件中支持2版这个配置
> 
> 问题2：2版截图默认是根据视频尺寸，这样截图不用自己再设置什么尺寸了，而3版提供了width和height，但这个默认值实在不合适，否则视频调整后还要用户自己去计算尺寸，建议调整为视频宽度的百分比，这样更合理，写成绝对值明显是不方便使用的
> 
> 问题3：顺便提一下视频和封面尺寸的问题，通过设置fitVideoSize和videoFillMode无法将视频充满容器，封面官方样式是background-size:100% auto也是比较不好体验，如果封面尺寸不当，导致封面和视频无法覆盖的尴尬
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> 1. 截图支持2版saveImg参数，支持用户定义是否下载截图
> 2. 截图尺寸调整为视频尺寸的百分比，另外也可增加定位，单位也是以视频尺寸的百分比，这样好控制
> 3. 视频和封面都应该充满容器
> 
> **实际播放器的表现是？ What actually happened?**
> 
> 1. 截图只支持启用和禁用，不支持截图后不下载的设置
> 2. 截图尺寸无法适应容器尺寸的变化
> 3. 视频和封面通过fitVideoSize、videoFillMode，width、height和样式覆盖均无法实现充满容器。目前视频是通过videoAttributes:{width:'100'%,height:'100%'}实现充满，封面通过修改官方样式实现
> 
> 希望新版在优化功能时，尽量继承已有的好的功能！！！还有就是跨端上能支持更好，我现在适配到PC端和APP端，但微信小程序端无法适配，因为是操作DOM，这个能否作为下步方向
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

建议已采纳，开发中
