### ISSUE TITLE
Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

### ISSUE THREAD

**Issue by xiaobai8023** [bytedance/xgplayer#1258]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.10",
"xgplayer-hls": "^3.0.10"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10系统，chrome浏览器120版本

**如何复现问题？ How to reproduce the problem?**
m3u8文件，播放一段时间后监听到报错事件：
![1980a13071edd316f5b302cc822953f](https://github.com/bytedance/xgplayer/assets/24408600/5b9a4a9f-ecfa-4c6c-8200-8c1c3c40fed1)
报错信息：Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@xiaobai8023 能否提供一下可复现的流以及播放器配置？

**Comment by linsendear** [comment]
> @xiaobai8023 能否提供一下可复现的流以及播放器配置？

https://chinaedu-1300303364.cos.ap-beijing.myqcloud.com/live/record/0209000149-ceshi/0209000149001.m3u8
往后跳转几次进度条，再重头播放，在40秒左右会出现报错
![f6348ad24cc8035d01a553909c1bcfbd](https://github.com/bytedance/xgplayer/assets/25631064/85c34294-f538-41b2-89c9-07c5ef50c5dc)

**Comment by xiaobai8023** [comment]
> @xiaobai8023 能否提供一下可复现的流以及播放器配置？

https://chinaedu-1300303364.cos.ap-beijing.myqcloud.com/live/record/0209000149-ceshi/0209000149001.m3u8
往后跳转几次进度条，再重头播放，在40秒左右会出现报错
f6348ad24cc8035d01a553909c1bcfbd

请问有复现吗？有没有解决方案？

**Comment by xiaobai8023** [comment]
> @xiaobai8023 能否提供一下可复现的流以及播放器配置？

![image](https://github.com/bytedance/xgplayer/assets/24408600/369db74d-67cb-45d3-add4-c62b4f21baa4)

**Comment by bbhxwl** [comment]
解决了么

**Comment by gemxx** [comment]
<img width="540" alt="image" src="https://github.com/bytedance/xgplayer/assets/576737/c1782fe6-ac1f-4c7c-9f71-fd63acdbf570">
@linsendear 提供的m3u8中ts分片时长，太大了，以这个分片进行下载很容易导致给sourceBuffer推送的数据达到上限。规范中推荐是10s以内，建议重新生产流

**Comment by EmptyEer** [comment]
有什么配置可以修改这个sourceBuffer的上限吗
