### ISSUE TITLE
iOS 17 以上，使用西瓜视频播放器播放 mp3，无法真正全屏，好像只撑满父盒子，iOS 16是好的

### ISSUE THREAD

**Issue by HelloBojack** [bytedance/xgplayer#1271]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iPhone 13 Pro - iOS 17.2.1

**如何复现问题？ How to reproduce the problem?**
iOS 17 以上，使用西瓜视频播放器播放 mp3，无法真正全屏，好像只撑满父盒子，之前是好的
https://codesandbox.io/p/sandbox/hopeful-pond-fv54dm?file=%2Findex.html%3A1%2C1-121%2C1

https://fv54dm.csb.app/

**您期望的播放器正常行为是？ What did you expect to happen?**
Phone 13 Pro - iOS 17.2.1 - 视频播放器播放 mp3，可以正常全屏

**实际播放器的表现是？ What actually happened?**
iOS 17 以上，使用西瓜视频播放器播放 mp3，无法真正全屏，好像只撑满父盒子，之前是好的

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
暂时确认播放音频时，iOS17+ 执行 video.webkitEnterFullscreen() 不起作用。未找到相关PR
