### ISSUE TITLE
xgplayer-react 不更新了么，我看了下现在xgplayer-react 的版本还是2.18.0

### ISSUE THREAD

**Issue by xiaoliu1990** [bytedance/xgplayer#1274]
我是在react环境使用的，看了官方有维护一个xgplayer-react的版本，下载下来看到版本还是2.18.0，后期有计划升级xgplayer-react么

**Comment by hongqx** [comment]
> 我是在react环境使用的，看了官方有维护一个xgplayer-react的版本，下载下来看到版本还是2.18.0，后期有计划升级xgplayer-react么
原来的xgplayer-react支持对xgplayer做了非常简单的封装，不灵活，还有很多限制，目前3.0不再支持，react下建议自己封装，在didMount阶段初始化播放器，在WillUnmount的时候调用player.destroy()即可
