### ISSUE TITLE
移动端视频点击播发后progress进度条会回退0～1s，你们的官网也有出现该问题。

### ISSUE THREAD

**Issue by peipei818** [bytedance/xgplayer#1275]
在移动端 safari浏览器中遇到了该问题，刷新点击播发后进度条会从0:00变为0:01后再回到0:00继续播放视频，在我的手机中你们官网https://h5player.bytedance.com/ 首屏视频也有这样的问题。PC端不会出现该问题。
我的手机safari浏览器版本是
![image](https://github.com/bytedance/xgplayer/assets/128784268/200c2c83-f324-4b50-ab91-88c69b521d13)

**Comment by hongqx** [comment]
> 在移动端 safari浏览器中遇到了该问题，刷新点击播发后进度条会从0:00变为0:01后再回到0:00继续播放视频，在我的手机中你们官网https://h5player.bytedance.com/ 首屏视频也有这样的问题。PC端不会出现该问题。 我的手机safari浏览器版本是 ![image](https://private-user-images.githubusercontent.com/128784268/293834532-200c2c83-f324-4b50-ab91-88c69b521d13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU3NTksIm5iZiI6MTcwNTM5NTQ1OSwicGF0aCI6Ii8xMjg3ODQyNjgvMjkzODM0NTMyLTIwMGMyYzgzLWYzMjQtNGI1MC1hYjkxLTg4YzY5YjUyMWQxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwODU3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTBhNTVmMTlkYmU4MjlhMThjODU3OTEwODk0YjI5MTE2MzZlOWM1ZjQ4OWVhYTEzNmU5NWIyMGFlM2MzMmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pm0w2oFO77rTqmOqDdOfrrzUCBw4GKF6uwQGGg1mvdM)

辛苦发一下出现该问题测媒体资源，并确定下是否使用xgplayer-mp4 xgplayer-flv xgplayer-hls这几个插件
