### ISSUE TITLE
在播放完当前视频后，使用playNext切换下一集，页面初始时显示“重播”按钮。

### ISSUE THREAD

**Issue by Agony95z** [bytedance/xgplayer#1276]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.10"；"vue": "^3.3.4"；

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

win11 chrome(120.0.6099.109)
**如何复现问题？ How to reproduce the problem?**
在当前视频播放完成之后，会自动显示“重播”按钮，此时点击切换，页面上会显示“播放”、“重播”两个功能按钮
![image](https://github.com/bytedance/xgplayer/assets/45594186/07832532-4669-489e-836e-4966d06bc0e6)

**您期望的播放器正常行为是？ What did you expect to happen?**
点击按钮切换视频，调用playNext,正常应该只显示“播放”按钮

**实际播放器的表现是？ What actually happened?**
在播放完当前视频时，点击切换下一条视频，界面会显示“重播”、“播放”
![image](https://github.com/bytedance/xgplayer/assets/45594186/0eebdd79-a822-47b6-8739-69607f489ecd)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Agony95z** [comment]
附demo代码：
<script setup lang="ts">
import Player from 'xgplayer';
import Progress from 'xgplayer/es/plugins/progress';
import { I18N } from 'xgplayer';
import ZH from 'xgplayer/es/lang/zh-cn'
import 'xgplayer/dist/index.min.css';
import {onMounted, onBeforeUnmount} from "vue";

let player = null;
let options = {
  id: 'mse',
  lang: 'zh',
  url: '//media.w3.org/2010/05/sintel/trailer.mp4',
  height: '300px',
  width: '400px',
  playbackRate: [1],
  keyShortcut: false,
  plugins: [Progress,], // 传入需要组装的插件
  // progress: {
  //   closeMoveSeek: true,
  //   isCloseClickSeek: true,
  // }
};
// 启用中文
I18N.use(<any>ZH)

const handleClick = () => {
  // player.destroy() // 销毁播放器
  // player.resetState()
  player.playNext({...options, url: '//vjs.zencdn.net/v/oceans.mp4'})
};
let timerId;
const moveText = () => {
  // 获取容器大小
  const containerWidth = document.getElementById('mse').offsetWidth;
  const containerHeight = document.getElementById('mse').offsetHeight;

  // 获取文本控件大小
  const text = document.querySelector('.water-text');
  const textWidth = text.offsetWidth;
  const textHeight = text.offsetHeight;

  // 生成随机位置
  const randomLeft = Math.floor(Math.random() * (containerWidth - textWidth));
  const randomTop = Math.floor(Math.random() * (containerHeight - textHeight));

  // 设置文本位置
  text.style.left = `${randomLeft}px`;
  text.style.top = `${randomTop}px`;

  // 定时器每隔 1 秒更新文本位置
  timerId = setTimeout(moveText, 10000);
};
const stopTimer = () => {
  clearInterval(timerId);
};
onMounted(() => {
  player = new Player(options);
  const DOM = document.createElement('div');
  DOM.setAttribute('class', 'water-text');
  DOM.innerHTML = '很简单回家撒较好的金沙江好的哈';
  DOM.style.position = 'absolute';
  DOM.style.color = 'red';
  DOM.style.zIndex = '9999';
  player.root.appendChild(DOM);
  moveText();
});
onBeforeUnmount(() => {
  stopTimer();
});
</script>

<template>
  <div class="video-container">
    <div id="mse"></div>
    <el-button @click="handleClick">点我</el-button>
    <div class="text-3xl">video/index</div>
  </div>
</template>

<style scoped lang="scss">
#mse {
  width: 400px;
  height: 300px;
}
</style>

**Comment by LiuxiboShuiShui** [comment]
代码问题 把重播配置去掉
