### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'currentURL')

### ISSUE THREAD

**Issue by leozhu9012** [bytedance/xgplayer#1277]
使用官方示例：https://h5player.bytedance.com/examples/
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos13.1  chrome 120.0.6099.129

**如何复现问题？ How to reproduce the problem?**
使用官方示例，修改url 为：wss://dev.lzz.enbo12119.com:10443/live/1742413792995708929/1_1.live.mp4?token=ae0cf53e-047a-4597-938c-412505c0ee24

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
报错

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
![1704280276066](https://github.com/bytedance/xgplayer/assets/12291955/8ebaad86-fa76-4e0b-bb19-f301aa682476)

**Comment by hongqx** [comment]
> 使用官方示例：https://h5player.bytedance.com/examples/ **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** macos13.1 chrome 120.0.6099.129
> 
> **如何复现问题？ How to reproduce the problem?** 使用官方示例，修改url 为：wss://dev.lzz.enbo12119.com:10443/live/1742413792995708929/1_1.live.mp4?token=ae0cf53e-047a-4597-938c-412505c0ee24
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常播放
> 
> **实际播放器的表现是？ What actually happened?** 报错
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.** ![1704280276066](https://private-user-images.githubusercontent.com/12291955/293897688-8ebaad86-fa76-4e0b-bb19-f301aa682476.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU2MjcsIm5iZiI6MTcwNTM5NTMyNywicGF0aCI6Ii8xMjI5MTk1NS8yOTM4OTc2ODgtOGViYWFkODYtZmE3Ni00ZTBiLWJiMTktZjMwMWFhNjgyNDc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzlkMDI2MGVmZDZmZTgyYmQwODZjOWU4N2Y5NmIwNDI2ZjY5NTAyZGY3ZTI3ZGNkMjNmNGJhMjYxZmIyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u1KwnHBUd9ZlxNCn7yJcM0HTfjmOfoX_ZwC8mzc3d_4)


> 使用官方示例：https://h5player.bytedance.com/examples/ **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** macos13.1 chrome 120.0.6099.129
> 
> **如何复现问题？ How to reproduce the problem?** 使用官方示例，修改url 为：wss://dev.lzz.enbo12119.com:10443/live/1742413792995708929/1_1.live.mp4?token=ae0cf53e-047a-4597-938c-412505c0ee24
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常播放
> 
> **实际播放器的表现是？ What actually happened?** 报错
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.** ![1704280276066](https://private-user-images.githubusercontent.com/12291955/293897688-8ebaad86-fa76-4e0b-bb19-f301aa682476.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU2MjcsIm5iZiI6MTcwNTM5NTMyNywicGF0aCI6Ii8xMjI5MTk1NS8yOTM4OTc2ODgtOGViYWFkODYtZmE3Ni00ZTBiLWJiMTktZjMwMWFhNjgyNDc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzlkMDI2MGVmZDZmZTgyYmQwODZjOWU4N2Y5NmIwNDI2ZjY5NTAyZGY3ZTI3ZGNkMjNmNGJhMjYxZmIyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u1KwnHBUd9ZlxNCn7yJcM0HTfjmOfoX_ZwC8mzc3d_4)

xgplayer-flv.js只是基于flv.js做了简单的封装，该功能我们会check，如果想要快速使用，建议使用一下xgplayer-flv

**Comment by shanyutongxue** [comment]
WebSocket protocol is not supported, please use http
