### ISSUE TITLE
Danmu组件panel参数设置无效

### ISSUE THREAD

**Issue by LuHaikun** [bytedance/xgplayer#1279]
**您使用的西瓜播放器版本是多少？**
3.0.12-alpha.1

**您使用的操作系统和浏览器分别是？ **
macos chrome

**如何复现问题？**
![image](https://github.com/bytedance/xgplayer/assets/16951645/7f85c98f-9fd0-4a13-aae7-e7fe2269cc9b)

**您期望的播放器正常行为是？**

样式正常，且panel内参数设置能够控制弹幕效果

**实际播放器的表现是？**
样式有问题，字体大小显示不全，且panel内参数设置能够控制弹幕效果，且是否没有弹幕发送输入框组件配置

**Comment by guojun-dou** [comment]
遇到相同问题，
