### ISSUE TITLE
支持flv和mp4播放，progress进度条出不来

### ISSUE THREAD

**Issue by xinSanta** [bytedance/xgplayer#1280]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.11",
    "xgplayer-flv": "^3.0.11",
    "xgplayer-hls.js": "^3.0.11",
    "xgplayer-mp4": "^3.0.11",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
谷歌，火狐、win10

**如何复现问题？ How to reproduce the problem?**
![image](https://github.com/bytedance/xgplayer/assets/86345904/4ea19fb9-d0bb-4a7d-b16f-c52fdf34d767)
![1704453812586](https://github.com/bytedance/xgplayer/assets/86345904/32c295cb-4688-4f88-9662-9d73184f3d74)
![1704453830708](https://github.com/bytedance/xgplayer/assets/86345904/7f32aaa6-1aca-449a-9cc1-9bc1d608bbcb)
![1704453845962](https://github.com/bytedance/xgplayer/assets/86345904/7c4be236-0acf-4445-9839-baf41bbd1fbd)

**您期望的播放器正常行为是？ What did you expect to happen?**
我封装的支持点播和直播的播放器，通过传入“flv”或者“mp4”来判断使用那种播放器，我在里面加了进度条配置，但是为什么进度条不出来，我只要是mp4的时候出来进度条，还需要哪个配置吗？

**实际播放器的表现是？ What actually happened?**
没有出现进度条

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** "xgplayer": "^3.0.11", "xgplayer-flv": "^3.0.11", "xgplayer-hls.js": "^3.0.11", "xgplayer-mp4": "^3.0.11",
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** 谷歌，火狐、win10
> 
> **如何复现问题？ How to reproduce the problem?** ![image](https://private-user-images.githubusercontent.com/86345904/294474657-4ea19fb9-d0bb-4a7d-b16f-c52fdf34d767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU0MDIsIm5iZiI6MTcwNTM5NTEwMiwicGF0aCI6Ii84NjM0NTkwNC8yOTQ0NzQ2NTctNGVhMTlmYjktZDBiYi00YTdkLWIxNmYtYzUyZmRmMzRkNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzljNWM2YmU5YTM1ZmMzNWFlYzgwNzY5MTM1NTllYTliNDAyNjMyOWQ4ZWQxZTI0OTExYjQwODljNGE3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L34Tp3en-Uf-CyUfgw6tfpSPn4Hqbps0zXHN6X-ZUd0) ![1704453812586](https://private-user-images.githubusercontent.com/86345904/294474744-32c295cb-4688-4f88-9662-9d73184f3d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU0MDIsIm5iZiI6MTcwNTM5NTEwMiwicGF0aCI6Ii84NjM0NTkwNC8yOTQ0NzQ3NDQtMzJjMjk1Y2ItNDY4OC00Zjg4LTk2NjItOWQ3MzE4NGYzZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MzMyMDg5ZjJjMWRkNjNjOTg1YjlhZTEwZmZhYmVlOGVkYmZlOTUxYzI4MWQ1MDE4NjE0YWQxM2Y2YmE5YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4adbPP_zTKqsUzCGK83_Tw4Cb3QmcBRdi7WO53Ml0bc) ![1704453830708](https://private-user-images.githubusercontent.com/86345904/294474792-7f32aaa6-1aca-449a-9cc1-9bc1d608bbcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU0MDIsIm5iZiI6MTcwNTM5NTEwMiwicGF0aCI6Ii84NjM0NTkwNC8yOTQ0NzQ3OTItN2YzMmFhYTYtMWFjYS00NDlhLTljYzEtOWJjMWQ2MDhiYmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNmE2MWVjY2VlZWNjMDM2ODEyYzRkNjgzMGMwZTUyODVmMGIyZGQ1NzU5ZTExMTY4NDI5YTVjZjc4ZWRiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dei4bqtA5XeCXjXct3u6hUT9GUT91lZImZ6iGfTbPBE) ![1704453845962](https://private-user-images.githubusercontent.com/86345904/294474829-7c4be236-0acf-4445-9839-baf41bbd1fbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU0MDIsIm5iZiI6MTcwNTM5NTEwMiwicGF0aCI6Ii84NjM0NTkwNC8yOTQ0NzQ4MjktN2M0YmUyMzYtMGFjZi00NDQ1LTk4MzktYmFmNDFiYmQxZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxOTk1NzA4ODVhZmMzMDU3YzBmZmRkYmJiYmIyYmIzM2I1YzcyYzg3MzY3MjVmODlmNTU2YTliZTVkNzJiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BuIUMDKjfbHGo8Yf0Hy6RxtiFhNTAaFKHOswVkI54Fw)
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 我封装的支持点播和直播的播放器，通过传入“flv”或者“mp4”来判断使用那种播放器，我在里面加了进度条配置，但是为什么进度条不出来，我只要是mp4的时候出来进度条，还需要哪个配置吗？
> 
> **实际播放器的表现是？ What actually happened?** 没有出现进度条
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

配置中isLive为true, 直播是无法确定duration的，因此直播状态下progress不会注册
