### ISSUE TITLE
MP4插件播放视频在ios浏览器未自动降级

### ISSUE THREAD

**Issue by LuHaikun** [bytedance/xgplayer#1284]
**您使用的西瓜播放器版本是多少？
3.0.11

**您使用的操作系统和浏览器分别是？ 
ios17 safari

**如何复现问题？
在使用MP4Plugin的时候，ios端浏览器·播放提示不支持的音频/视频格式，点击完刷新，走原地址播放，这个是一定要手动点刷新触发吗。不可以自动降级吗，是否可以支持一下

https://codesandbox.io/p/sandbox/xgplayer-mp4-plugin-lhdfvy?file=%2Findex.html

**您期望的播放器正常行为是？
自动降级播放

**Comment by lwy18382615414** [comment]
请问有解决方法吗
