### ISSUE TITLE
如何取消画面中 播放/暂停 的动画

### ISSUE THREAD

**Issue by SageKwun** [bytedance/xgplayer#1285]
<img width="563" alt="image" src="https://github.com/bytedance/xgplayer/assets/65765025/37ce6259-9f1d-4106-8187-887540af4f5d">

**Comment by hongqx** [comment]
[start插件配置](https://v3.h5player.bytedance.com/plugins/internalplugins/start.html)
new Player({
   start: {
       disableAnimate： true
   }
})
