### ISSUE TITLE
播放编码h265的flv流，一直加载

### ISSUE THREAD

**Issue by winkstu** [bytedance/xgplayer#1297]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win11/chrome119.0.6045.200

**如何复现问题？ How to reproduce the problem?**
使用zlm的enhanced=1配置，播放h265的flv流就会一直加载
可以参考：https://github.com/ZLMediaKit/ZLMediaKit/issues/3117

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
一直加载

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@winkstu 能dump一份flv数据吗
