### ISSUE TITLE
设置了loop为true之后，Events.ENDED无法接收

### ISSUE THREAD

**Issue by LiDevil** [bytedance/xgplayer#1298]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac os和chrome

**如何复现问题？ How to reproduce the problem?**
设置loop为true之后监听Events.ENDED

**您期望的播放器正常行为是？ What did you expect to happen?**
循环重播的时候应该可以接收到ENDED事件才对

**实际播放器的表现是？ What actually happened?**
没收到ENDED事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by LiDevil** [comment]
是不是专门这样设计的还是说bug呀，挺奇怪的，我现在暂时解决方案是关掉loop，然后在ENDED事件里面调用replay，我们的业务需求是重播之后就直接用缓存好的视频，虽然loop也是，但是我们涉及上下滑动触发视频链接刷新，如果视频播放完了的话，我们不用再去刷新新链接

**Comment by gemxx** [comment]
@LiDevil 这个是浏览器实现，当设置了`loop`时，不会发`ended`事件。我们大部分的事件都是浏览器原生事件
