### ISSUE TITLE
西瓜播放器是否支持视频裁剪？类似Media Fragment URI的#t=形式裁剪时长

### ISSUE THREAD

**Issue by Messiahhh** [bytedance/xgplayer#1301]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@Messiahhh 目前还不支持，我看到现在 [Media Fragments URI](https://www.w3.org/TR/media-frags/) 这个规范稍微有些复杂，除了时间维度控制，还有控制像素的展示范围的机制。请问你主要想实现什么样的效果？
