### ISSUE TITLE
多实例快捷键同时生效

### ISSUE THREAD

**Issue by zhaowenjie** [bytedance/xgplayer#1303]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac, chrome浏览器

**如何复现问题？ How to reproduce the problem?**
同一个页面渲染多个视频播放器，按空格键所有视频都播放，按快进键，所有视频都被快进，尝试过配置disableBodyTrigger，然后键盘事件就没有任何效果了，然后尝试配置isIgnoreUserActive，发现播放暂停都只对第一个播放器生效，其他播放器无法控制。
尝试升级过sdk至，3.0.12和3.1.0版本，问题无法得到解决。
调试源码发现，源码中无 https://github.com/bytedance/xgplayer/blob/main/packages/xgplayer/src/instManager.js 文件，所以觉得是isUserActive管理有问题，但是看git提交记录说是已经修复了多个播放器控制的问题，麻烦大佬看下是不是我使用的姿势不对？
?

**您期望的播放器正常行为是？ What did you expect to happen?**
能和v2版本一样，控制当前激活的播放器

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by SuperKieran** [comment]
碰到了同样的问题
