### ISSUE TITLE
当播放器同时设置了音量为0并且自动播放时，页面会自动滚动到播放器的位置。

### ISSUE THREAD

**Issue by chenwanzhao** [bytedance/xgplayer#1306]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows,chrome

**如何复现问题？ How to reproduce the problem?**

https://codepen.io/chenwanzhao/pen/gOEeMyj

**您期望的播放器正常行为是？ What did you expect to happen?**
当播放器同时设置了音量为0并且自动播放时，页面不要自动滚动到播放器的位置，或者增加一个配置字段让使用者决定要不要自动滚动。
{
  volume: 0,
  autoplay: true
}

**实际播放器的表现是？ What actually happened?**
当播放器同时设置了音量为0并且自动播放时，页面会自动滚动到播放器的位置。如果播放器在页面的最底部，每次进入页面，页面都会自动滚动到最底部，导致页面浏览体验很不好。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@chenwanzhao xgplayer默认播放时聚焦，有[配置](https://h5player.bytedance.com/config/#closefocusvideofocus)可以进行关闭。请参考 closeFocusVideoFocus 、closePauseVideoFocus 、closePlayVideoFocus 

`{
closePlayVideoFocus: true
}`
