### ISSUE TITLE
使用webp格式的图片作为视频封面图无法正确显示封面

### ISSUE THREAD

**Issue by PoliWen** [bytedance/xgplayer#1307]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.12

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10 64位系统，chrome 121.0.6167.140

**如何复现问题？ How to reproduce the problem?**
使用webp格式的图片作为视频封面图无法正确显示封面
例如：我使用了这个可访问的 "http://sns-webpic-qc.xhscdn.com/202402041046/ad82bc85be99441bf1f0baf512555dea/1040g00830uj2pqc656005pa0bjg11aulm9nlis8!nd_dft_wlteh_webp_3"  webp格式的图片地址作为视频封面的图片路径
实现代码如下：
```
const player=new Player({
    id: 'xhs-video',
    autoplay: false,
    volume: 0.3,
    url: 'https://sns-video-hw.xhscdn.com/stream/110/259/01e5b9bef90650a4010376038d5d923f43_259.mp4',
    poster:''http://sns-webpic-qc.xhscdn.com/202402041046/ad82bc85be99441bf1f0baf512555dea/1040g00830uj2pqc656005pa0bjg11aulm9nlis8!nd_dft_wlteh_webp_3',
    playsinline: true,
    height: '100%',
    width: '100%',
});
```

**您期望的播放器正常行为是？ What did you expect to happen?**
webp格式的图片作为封面图能够正常显示

**实际播放器的表现是？ What actually happened?**
webp格式的图片作为封面图不能正常显示

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@PoliWen 访问这个WebP地址403，http://sns-webpic-qc.xhscdn.com/202402041046/ad82bc85be99441bf1f0baf512555dea/1040g00830uj2pqc656005pa0bjg11aulm9nlis8!nd_dft_wlteh_webp_3

**Comment by PoliWen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到。记得常联系哦
