### ISSUE TITLE
移动端视频层级问题

### ISSUE THREAD

**Issue by peipei818** [bytedance/xgplayer#1311]
在红米自带浏览器中，存在了移动端视频层级不正确的问题，如未播放视频，向上滑动，不会覆盖在固定header上，如开始播放视频，向上滑动，视频层级会在header上面，其他安卓浏览器未出现该问题。

**Comment by gemxx** [comment]
@peipei818 部分android机器播放时，采用系统播放器进行播放，无法控制层级
