### ISSUE TITLE
安卓 webview 里无法像 iOS webview一样全屏

### ISSUE THREAD

**Issue by draculapile** [bytedance/xgplayer#132]
混合开发，在iOS的webview里表现如下
![_20181206095058](https://user-images.githubusercontent.com/24435036/49555889-859fda80-f93c-11e8-8acc-d8e4415acbae.jpg)
安卓的webview里点击全屏，仅右下角全屏按钮变化，视频并未全屏，配置如下：
![_20181206095835](https://user-images.githubusercontent.com/24435036/49556150-900ea400-f93d-11e8-818c-3bbd3c7cce76.png)

**Comment by zhangxin92** [comment]
西瓜播放器版本是多少？升级到最新版试下

**Comment by draculapile** [comment]
已升级到最新版 1.1.4-beta.10，还是不行

**Comment by zhangxin92** [comment]
安卓客户端有对webview的video全屏做了相应支持吗？[可参考](https://www.jianshu.com/p/d70a73594b71)

**Comment by draculapile** [comment]
好的，我先跟安卓那边沟通一下吧，意思是如果安卓没有写相关代码，那么在安卓的webview里就无法全屏么？iOS的 WKWebView 是不是在这方面支持性较好，不用特别去写相关的代码？如了解的话望告知，十分感谢！

**Comment by draculapile** [comment]
您好，安卓那边写了支持全屏的代码，现在可以了！谢谢答疑
