### ISSUE TITLE
HLS插件后播放mp4文件问题

### ISSUE THREAD

**Issue by ashuicoder** [bytedance/xgplayer#1326]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11、chrome

**如何复现问题？ How to reproduce the problem?**

我引入了hls插件后，播放MP4视频i会导致必须等待视频下载完成才能播放。

**您期望的播放器正常行为是？ What did you expect to happen?**

能同时播放m3u8h和mp4文件
**实际播放器的表现是？ What actually happened?**
MP4文件必须等待加载完才能播放，不能边播边下载
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@ashuicoder 在播放MP4时，不能引入hls插件。应该引入xgplayer-mp4或者直接用xgplayer播放即可。目前xgplayer还没有引入探测格式的能力

**Comment by gemxx** [comment]
#1310 相似问题
