### ISSUE TITLE
flv直播下，页面切换会暂停播放，然后页面切回时恢复播放，但是不会追帧，导致直播延迟

### ISSUE THREAD

**Issue by BZBZ271** [bytedance/xgplayer#1338]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.14",
    "xgplayer-flv.js": "^3.0.14"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 谷歌浏览器

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
我希望页面切换的时候不暂停播放直播 或者切换后再切回能进行追帧

**实际播放器的表现是？ What actually happened?**
页面切换会暂停播放，然后页面切回时恢复播放，但是不会追帧，导致直播延迟

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@BZBZ271 集成的flv.js暂时没有开放直播场景下暂停后的追帧配置，建议切换下[xgplayer-flv](https://v3.h5player.bytedance.net/plugins/extension/xgplayer-flv.html)试试

**Comment by BZBZ271** [comment]
> @BZBZ271 集成的flv.js暂时没有开放直播场景下暂停后的追帧配置，建议切换下[xgplayer-flv](https://v3.h5player.bytedance.net/plugins/extension/xgplayer-flv.html)试试

`    const config = {
        id: 'player-' + props.deviceSn,
        url: url,
        playsinline: true,
        plugins: [FlvPlayer],
        isLive: true,
        autoplay: true,
        autoplayMuted: true,
        playbackRate: [
            null
        ],
        marginControls: false,
        controls: {
            autoHide: false
        },
        time: true,
        keyboard: {
            keyCodeMap: {
                'space': {              //空格键，播放/暂停切换
                    code: 32,             //对应快捷键索引
                    action: 'playPause',  //具体触发的业务操作，如果为字符串，则执行keyborad对应接口
                    disable: true        // 是否禁用
                },
                'up': {                 // 向上键，上调音量
                    code: 38,
                    action: 'upVolume',
                    disable: true
                },
                'down': {               // 向下键，下调音量
                    code: 40,
                    action: 'downVolume',
                    disable: true
                },
                'left': {               // 向左键，后退
                    code: 37,
                    action: 'seekBack',
                    disable: true
                },
                'right': {              // 向右键，快进
                    code: 39,
                    action: 'seek',
                    disable: true
                },
                'esc': {               // esc键，退出全屏
                    code: 27,
                    action: 'exitFullscreen',
                    disable: false
                }
            }
        },
        ignores: ['cssfullscreen', 'play', 'volume'],
        closeVideoClick: true,
        flv: {
            targetLatency: 2, // 直播目标延迟，默认 5 秒
            maxLatency: 4, // 直播允许的最大延迟，默认 10 秒
            disconnectTime: 3 // 直播断流时间，默认 0 秒，（独立使用时等于 maxLatency）
        }
    }`
   我用的就是xgplayer-flv，我的场景对延迟需求比较高，有时候播放卡顿后，能明显看出延迟变大了

**Comment by xiyuyizhi** [comment]
@BZBZ271 模拟弱网没有复现你这种情况，配置了targetLatency、maxLatency延迟大后是会自动追帧的
