### ISSUE TITLE
flv拉流时，控制台打印很多日志

### ISSUE THREAD

**Issue by BZBZ271** [bytedance/xgplayer#1339]
您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?
"xgplayer": "^3.0.14",
"xgplayer-flv.js": "^3.0.14"

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
windows 谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
![image](https://github.com/bytedance/xgplayer/assets/115618615/0dea1e9f-3454-475c-9b3a-20a1e0f82ba4)

**您期望的播放器正常行为是？ What did you expect to happen?**
不打印日志，或者能否告知这个打印的原因，谢谢

**实际播放器的表现是？ What actually happened?**
一直在打印日志

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
@BZBZ271 xgplayer-flv.js@3.0.15-alpha.0 关闭log
