### ISSUE TITLE
使用3.0.14版本，执行命令npx xgplayer eject ./ custom报错

### ISSUE THREAD

**Issue by startjava** [bytedance/xgplayer#1346]
C:\Users\Administrator\Desktop\xgplayer\xgplayer>npx xgplayer eject ./ custom
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-03-20T10_57_42_820Z-debug-0.log

----------------------------------
我在idea中基于Vite创建的vue项目中使用xgplayer，项目结构如下：
![image](https://github.com/bytedance/xgplayer/assets/49554320/6c97c271-61b3-4a5f-b4d4-cc4456904d3e)

**Comment by 775822253** [comment]
我也是，找到解决方法了吗

**Comment by X-u-W-e-n** [comment]
> 我也找到了解决办法

怎么做，大佬
