### ISSUE TITLE
hls插件播放m3u8视频异常

### ISSUE THREAD

**Issue by ashuicoder** [bytedance/xgplayer#1354]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplaer 3.0.14
xgplayer-hls 3.0.14

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win11  chrome 120

**如何复现问题？ How to reproduce the problem?**

```ts
import Player, { I18N, langZhCn, Events } from 'xgplayer';
import 'xgplayer/dist/index.min.css';
import HlsPlugin from "xgplayer-hls";
import Start from "xgplayer/es/plugins/start";
import PC from "xgplayer/es/plugins/pc";
import Progress from "xgplayer/es/plugins/progress";
import Time from "xgplayer/es/plugins/time";
import Play from "xgplayer/es/plugins/play";
import Error from "xgplayer/es/plugins/error";
import FullScreen from "xgplayer/es/plugins/fullscreen";
import Volume from "xgplayer/es/plugins/volume";
import Loading from "xgplayer/es/plugins/loading";

const player = new Player({
    id: playerId,
    url: 'https://video.kmqakj.com/f08d2ae7e9cc71ee9d875420848c0102/31924de8cc4b0173a2799000e47d0538-ld-encrypt-stream.m3u8',
    lang: "zh",
    isLive:false,
    width: '100%',
    // poster: options.coverURL,
    miniprogress: true,
    plugins: [
      Start,
      PC,
      Progress,
      Play,
      Time,
      Error,
      FullScreen,
      Volume,
      Loading,
     HlsPlugin
    ],
  })
```

**您期望的播放器正常行为是？ What did you expect to happen?**
能正常播放

**实际播放器的表现是？ What actually happened?**
{
  "playerVersion": "3.0.14",
  "currentTime": 0,
  "duration": 0,
  "ended": false,
  "readyState": 0,
  "networkState": 2,
  "src": "blob:http://localhost:8005/b099b286-20d2-4adc-a419-516f9c9d9f82",
  "errorType": "manifest",
  "errorCode": 1100,
  "message": "encrypt AES-128/undefined is not supported",
  "mediaError": {},
  "originError": "Error: encrypt AES-128/undefined is not supported\n    at parseMediaPlaylist (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:12966:19)\n    at Function.parse2 (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:13023:16)\n    at ManifestLoader2._callee$ (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:13158:39)\n    at tryCatch (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:108:17)\n    at Generator.<anonymous> (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:197:22)\n    at Generator.next (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:135:21)\n    at asyncGeneratorStep (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:402:24)\n    at _next (http://localhost:8005/node_modules/.vite/deps/xgplayer-hls.js?v=9130a3f8:420:9)",
  "host": "localhost:8005"
}
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by ashuicoder** [comment]
3.0.13版本是正常的，希望在发版之前严格测试一下

**Comment by gemxx** [comment]
@ashuicoder 感谢反馈，我们会在3.0.15版本修复这个问题

**Comment by gemxx** [comment]
@ashuicoder 3.0.15正式版本已经发布，此问题已解决

**Comment by ashuicoder** [comment]
> @ashuicoder 3.0.15正式版本已经发布，此问题已解决

好的，感谢
