### ISSUE TITLE
官网的音乐播放器demo实现之后为什么是视频播放器的样式？

### ISSUE THREAD

**Issue by bruce-zhang932** [bytedance/xgplayer#1357]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
v3.0.14

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
h5端

import { onMounted } from 'vue'
import Player from 'xgplayer'
// @ts-ignore
import MusicPreset from 'xgplayer-music'
import 'xgplayer-music/dist/index.min.css'

onMounted(() => {
  const player = new Player({
    id: 'vs',
    url: 'http://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/music/audio.mp3',
    poster: 'http://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/music/audio.mp3',
    title: '林宥嘉·脆弱一分钟',
    mediaType: 'audio',
    preset: [MusicPreset],
    ignores: ['playbackrate'],
    marginControls: true,
    videoConfig: {
      crossOrigin: "anonymous"
    },
    music: {
        list: [{
        src: 'http://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/music/audio.mp3',
        title: '林宥嘉·脆弱一分钟',
        vid: '000001',
        poster: 'http://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/music/poster-small.jpeg'
      },
      {
        src: 'https://fs.zhx.su/d/fs/share/SamoyedPlayer/yourname.mp3',
        title: '前前前世',
        vid: '000002',
        poster: 'https://fs.zhx.su/d/fs/share/SamoyedPlayer/yourname.jpg'
      }],
    },
  })
})`

![image](https://github.com/bytedance/xgplayer/assets/11385973/e4e28c8a-6a58-4b66-9329-a06f0aed9bdc)
官网的音乐播放器demo实现之后为什么是视频播放器的样式？不是这种样式呢？
![image](https://github.com/bytedance/xgplayer/assets/11385973/6672a625-1def-4874-86a1-408ec70ae331)

**Comment by lytdev** [comment]
我也是，按照官方文档，设置出来的就是视频的播放效果
