### ISSUE TITLE
通过　api 调用 rotate　无法执行，player.rotate方法已不存在！

### ISSUE THREAD

**Issue by codedart2018** [bytedance/xgplayer#1385]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
```
3.0.17-alpha.6
3.0.16
```

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos

**如何复现问题？ How to reproduce the problem?**

<img width="443" alt="image" src="https://github.com/bytedance/xgplayer/assets/12706830/af46d69f-1cc2-4b2f-88a8-71812ca39e4b">

文档
<img width="849" alt="image" src="https://github.com/bytedance/xgplayer/assets/12706830/bcd9af2d-1ee9-4519-9949-e68df413fa62">

```
                      player.setConfig({
                        rotate: {
                          innerRotate: true,
                          clockwise: false,
                          rotateDeg: 270,
                        },
                      });
                      player.setRotateDeg(270);
                      player.rotate(true, true, 270);
```

**您期望的播放器正常行为是？ What did you expect to happen?**
期望通过API去旋转视频

**实际播放器的表现是？ What actually happened?**
实际api没有效果

**Comment by ShengInBig** [comment]
这个问题还是没有解决
