### ISSUE TITLE
lastPlayTime 记忆播放配置项失效

### ISSUE THREAD

**Issue by beginnerSong** [bytedance/xgplayer#1386]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.16

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome

**如何复现问题？ How to reproduce the problem?**
this.player && this.player.destroy();
      this.player = new Player({
        id: 'xPlayer',
        url: this.showWorks.video,
        fluid: true,
        videoInit: true,
        autoplay,
        lastPlayTime: 10,
      });

**您期望的播放器正常行为是？ What did you expect to happen?**
根据后端返回时间 设置视频起始时间

**实际播放器的表现是？ What actually happened?**
打印播放器实例  lastPlayTime确实为设置时间 但是还是从头开始播放的

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by 3246567702** [comment]
player.value.currentTime = 这里写起始时间
