### ISSUE TITLE
在HLS格式下录播结束重播时会出现视频帧错乱

### ISSUE THREAD

**Issue by yveeven** [bytedance/xgplayer#1389]
可直接使用官方在线播放能力复现，https://h5player.bytedance.com/generate/

**Comment by gemxx** [comment]
@yveeven 请问还有可复现的视频流地址吗？用官网视频demo未复现到描述的问题 https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8

**Comment by xuecuncun** [comment]
我也在我们自己的直播流中复现了，我们将每个ts切成大概2s的分段，在播放过程中声音正常，但是视频卡顿，并且很频繁。我与hlsjs做了对比，发现不是视频源的问题。

**Comment by yveeven** [comment]
> @yveeven 请问还有可复现的视频流地址吗？用官网视频demo未复现到描述的问题 https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8

因为是基于工作中的，所以我这边暂时可能没有办法提供，我看到有其他回复遇到了相似问题
