### ISSUE TITLE
saveScreenShot  不支持 qiankun 

### ISSUE THREAD

**Issue by liu-collab** [bytedance/xgplayer#1396]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.16
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome 

**如何复现问题？ How to reproduce the problem?**
```js 
const { saveScreenShot } = playerRef.getPlugin('screenshot')
    playerRef
      .getPlugin('screenshot')
      .shot()
      .then((res) => {
        saveScreenShot(res, '截图.png')
      })
```

**您期望的播放器正常行为是？ What did you expect to happen?**
在qiankun中可以支持下载

**实际播放器的表现是？ What actually happened?**
![image](https://github.com/bytedance/xgplayer/assets/63389142/ebf888d8-348e-4b8b-8fb7-4e6da126ff60)  

 

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by liu-collab** [comment]
暂时可以这么解决  
```js 
 playerRef
      .getPlugin('screenshot')
      .shot()
      .then((res) => {
        // 下载截图 saveScreenShot 播放器 不支持qiankun
        const saveLink = document.createElement('a')
        saveLink.href = res
        saveLink.download = '截图.png'
        document.body.appendChild(saveLink)
        saveLink.click()
        window.URL.revokeObjectURL(saveLink)
      })
```

**Comment by gemxx** [comment]
@liu-collab 请问您的chrome浏览器版本具体是多少？我看你的提的是和华为乾坤有关，这是车机系统里的问题吗？

**Comment by liu-collab** [comment]
> @liu-collab 请问您的chrome浏览器版本具体是多少？我看你的提的是和华为乾坤有关，这是车机系统里的问题吗？

微前端：https://qiankun.umijs.org/zh
