### ISSUE TITLE
进度条禁用失效

### ISSUE THREAD

**Issue by 3246567702** [bytedance/xgplayer#1401]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.10",
    "xgplayer-mp4": "3.0.10"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win11 chrome

**如何复现问题？ How to reproduce the problem?**

  player.value.usePluginHooks('progress', 'dragstart', (_plugin: any, _event: any, data: any) => {
    // 当点击开始的位置计算出来的时间data.currentTime大于当前播放过的时间，则阻止默认行为
    if (data.currentTime > player.value.currentTime && data.currentTime > time) {
      return false
    }
    return true
  })

  player.value.usePluginHooks('progress', 'drag', (_plugin: any, _event: any, data: any) => {
    // return false
    // 当拖拽的位置计算出来的时间data.currentTime大于当前播放过的时间，则阻止默认行为
    if (data.currentTime > player.value.currentTime && data.currentTime > time) {
      return false
    }
    return true
  })
  需求：学习视频，不可前拖进度条 ，可以回拖进度条
  问题： 若直接前托到达指定范围可以禁止拖动 是ok的
  若先后拖在前拖  ， 进度条样式是禁止状态， 松手后禁止状态失效 ，依然可以拖动到指定位置

**您期望的播放器正常行为是？ What did you expect to happen?**
禁止后拖进度条

**实际播放器的表现是？ What actually happened?**
先后拖 在前拖 禁用效果失效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
![bug](https://github.com/bytedance/xgplayer/assets/118590769/db852871-9d31-4194-9f28-f389451ab953)

**Comment by 3246567702** [comment]
![bug](https://github.com/bytedance/xgplayer/assets/118590769/01da3b20-bce3-4536-bee0-31a1db98cf22)
![Uploading bug.gif…]()

**Comment by 3246567702** [comment]
直接 后拖  禁止拖动成功
先触发一次前拖 在后拖  样式禁止  实际禁止失效

**Comment by 3246567702** [comment]
![bug](https://github.com/bytedance/xgplayer/assets/118590769/6df5e934-d464-47d1-b198-22e43a44b7de)

**Comment by 3246567702** [comment]
不能发图吗
![bug](https://github.com/bytedance/xgplayer/assets/118590769/3c7d7e2d-b85e-4eca-917e-6950b5e6877d)

**Comment by All8926** [comment]
> **您使用的西瓜播放器版本是多少？您使用的西瓜播放器是什么版本？** "xgplayer": "^3.0.10", "xgplayer-mp4": "3.0.10"
> 
> **您使用的网络和浏览器分别是？您使用什么网络和浏览器？** win11 Chrome
> 
> **如何更换问题？**
> 
> player.value.usePluginHooks('progress', 'dragstart', (_plugin:any, _event:any,data:any) => { // 当点击开始的位置计算出来的时间 data.currentTime 大于当前播放过的时间，则阻止默认行为 if (data.currentTime > player.value.currentTime && data.currentTime > time) { return false } return true })
> 
> player.value.usePluginHooks('progress', 'drag', (_plugin:any, _event:any,data:any) => { // return false //拖拽的位置出来计算的时间data.currentTime大于当前播放经过的时间，则阻止行为 if (data.currentTime > player.value.currentTime && data.currentTime > time) { return false } return true }) 需求：学习视频默认，不可拖前进度条，可以拖后进度条条条 问题：若直接前托到达指定范围可以禁止拖动 是ok的 若前置拖在前拖 ，进度条样式是禁止状态，松手后禁止状态无效可以 ，等同拖动到指定位置
> 
> **您期望的播放器的正常行为是？您期望发生什么？** 禁止后图纸条
> 
> **实际播放器的表现是？到底发生了什么？前置** 拖板在前拖取消效果失效
> 
> **可填写您所在的公司及相关产品业务，方便我们提供更好的技术支持您可以填写您所在的公司及产品使用的xgplayer，以帮助我们提供更好的技术支持。** ![漏洞](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM0MDEsIm5iZiI6MTcxNTc4MzEwMSwicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDljM2VlNGU0YzhmYmM4NGQyMGNiMzk3ZmUxYmIyM2RkOWQwMDlhMmNlNDlmYzIzM2EwODQ0MTAzMmEyNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nB2xpTufNEUC4-PIdw5PmQ2k9sUGnfkne41Mw2SOKXc) [ ![漏洞](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM0MDEsIm5iZiI6MTcxNTc4MzEwMSwicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDljM2VlNGU0YzhmYmM4NGQyMGNiMzk3ZmUxYmIyM2RkOWQwMDlhMmNlNDlmYzIzM2EwODQ0MTAzMmEyNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nB2xpTufNEUC4-PIdw5PmQ2k9sUGnfkne41Mw2SOKXc) ](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM0MDEsIm5iZiI6MTcxNTc4MzEwMSwicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDljM2VlNGU0YzhmYmM4NGQyMGNiMzk3ZmUxYmIyM2RkOWQwMDlhMmNlNDlmYzIzM2EwODQ0MTAzMmEyNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nB2xpTufNEUC4-PIdw5PmQ2k9sUGnfkne41Mw2SOKXc) [ ](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM0MDEsIm5iZiI6MTcxNTc4MzEwMSwicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDljM2VlNGU0YzhmYmM4NGQyMGNiMzk3ZmUxYmIyM2RkOWQwMDlhMmNlNDlmYzIzM2EwODQ0MTAzMmEyNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nB2xpTufNEUC4-PIdw5PmQ2k9sUGnfkne41Mw2SOKXc)

请问解决了吗，我也有这个业务场景

**Comment by All8926** [comment]
> **您使用的西瓜播放器版本是多少？ 您使用的西瓜播放器是什么版本？** "xgplayer": "^3.0.10", "xgplayer-mp4": "3.0.10"
> 
> **您使用的操作系统和浏览器分别是？ 您使用什么操作系统和浏览器？** win11 铬
> 
> **如何重现问题？**
> 
> player.value.usePluginHooks('progress', 'dragstart', (_plugin:any, _event:any,data:any) => { // 当点击开始的位置计算出来的时间data.currentTime大于当前播放过的时间，则阻止默认行为 if (data.currentTime > player.value.currentTime && data.currentTime > time) { return false } return true })
> 
> player.value.usePluginHooks('progress', 'drag', (_plugin:any, _event:any,data:any) => { // return false //拖拽的位置出来计算的时间data.currentTime大于当前播放过的时间，则阻止默认行为 if (data.currentTime > player.value.currentTime && data.currentTime > time) { return false } return true }) 需求：学习视频，不可前拖进度条，可以拖回进度条条 问题：若直接前托到达指定范围可以禁止拖动 是ok的 若前置拖在前拖 ，进度条样式是禁止状态，松手后禁止状态无效可以 ，依然拖动到指定位置
> 
> **您期望的播放器的正常行为是？您期望发生什么？** 禁止后拖图纸条
> 
> **实际播放器的表现是？ 到底发生了什么？ 前置** 拖板在前拖取消效果失效
> 
> **可填写您所在的公司及相关产品业务，方便我们提供更好的技术支持 您可以填写您所在的公司及产品使用的xgplayer，以帮助我们提供更好的技术支持。** ![漏洞](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM2MTcsIm5iZiI6MTcxNTc4MzMxNywicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc2MThmNGQzODE4MTI5NmM0ODFmZTMyMjAyMjc4Y2I4ZWE5ZjIzNDVjMWIzYjFlMjA5ZGUyN2MzODA5NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vl1yYpWhHDXEh_4k-SaCIYVKDfDZFBEivS7vuuESCpc) [ ![漏洞](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM2MTcsIm5iZiI6MTcxNTc4MzMxNywicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc2MThmNGQzODE4MTI5NmM0ODFmZTMyMjAyMjc4Y2I4ZWE5ZjIzNDVjMWIzYjFlMjA5ZGUyN2MzODA5NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vl1yYpWhHDXEh_4k-SaCIYVKDfDZFBEivS7vuuESCpc) ](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM2MTcsIm5iZiI6MTcxNTc4MzMxNywicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc2MThmNGQzODE4MTI5NmM0ODFmZTMyMjAyMjc4Y2I4ZWE5ZjIzNDVjMWIzYjFlMjA5ZGUyN2MzODA5NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vl1yYpWhHDXEh_4k-SaCIYVKDfDZFBEivS7vuuESCpc) [ ](https://private-user-images.githubusercontent.com/118590769/324404172-db852871-9d31-4194-9f28-f389451ab953.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM2MTcsIm5iZiI6MTcxNTc4MzMxNywicGF0aCI6Ii8xMTg1OTA3NjkvMzI0NDA0MTcyLWRiODUyODcxLTlkMzEtNDE5NC05ZjI4LWYzODk0NTFhYjk1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc2MThmNGQzODE4MTI5NmM0ODFmZTMyMjAyMjc4Y2I4ZWE5ZjIzNDVjMWIzYjFlMjA5ZGUyN2MzODA5NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vl1yYpWhHDXEh_4k-SaCIYVKDfDZFBEivS7vuuESCpc)

请问解决了吗，我也有这个业务场景

**Comment by zhcsyncer** [comment]
基于官方示例添加一个 `dragend` 事件就完备了

**Comment by zhcsyncer** [comment]
基于官方示例添加一个 `dragend` 事件就完备了

**Comment by shawyw** [comment]
以前的版本有allowSeekPlayed 现在没有了
