### ISSUE TITLE
uniapp接入西瓜视频播放器字幕按钮难点击 以及 iOS H5环境一点击播放就进入设备自带的全屏模式

### ISSUE THREAD

**Issue by qmkl30** [bytedance/xgplayer#1402]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
<script src="//unpkg.byted-static.com/xgplayer/2.31.6/browser/index.js" charset="utf-8"></script>
<script src="//unpkg.byted-static.com/xgplayer-hls/2.5.2/dist/index.min.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/xgplayer@2.31.2/browser/index.js" charset="utf-8"></script>
<script src="//unpkg.byted-static.com/xgplayer-hls.js/2.2.2/browser/index.js" charset="utf-8"></script>

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Macos13.0.1   谷歌浏览器

**如何复现问题？ How to reproduce the problem?**
uniapp开发，做上下滑动切换视频，在移动端以及移动端的H5环境 字幕按钮很难点击，pc端hover模式字幕则是正常。iOS H5环境，点击播放就进入设备自带的全屏模式，测试手机系统16.3。

**您期望的播放器正常行为是？ What did you expect to happen?**
有字幕，“字幕”按钮能显示，并能正常被点击；
iOS设备上播放就正常播放。

**实际播放器的表现是？ What actually happened?**
uniapp开发，做上下滑动切换视频，在移动端以及移动端的H5环境 字幕按钮很难点击，pc端hover模式字幕则是正常。iOS H5环境，点击播放就进入设备自带的全屏模式，测试手机系统16.3。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by woodyRoyal** [comment]
点击播放就进入设备自带的全屏模式， playsinline:true,  加上这个试试
