### ISSUE TITLE
官网示例代码 playBackrate 拼写错误

### ISSUE THREAD

**Issue by MoreCodeByTR** [bytedance/xgplayer#1414]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.16

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

西瓜视频官网 https://h5player.bytedance.com/plugins/internalplugins/playbackrate.html#config
**如何复现问题？ How to reproduce the problem?**
<img width="1376" alt="image" src="https://github.com/bytedance/xgplayer/assets/51108500/c0b40ea7-8f35-4172-921d-6d7bbf247357">

**您期望的播放器正常行为是？ What did you expect to happen?**
官网的 playbackRate demo 里面的示例代码拼写错误为 playBackrate

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
感谢反馈，已经修复
