### ISSUE TITLE
华为 麦芒 20 5G - “解码错误，请重试”

### ISSUE THREAD

**Issue by Hubmeat** [bytedance/xgplayer#1416]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
<img width="394" alt="image" src="https://github.com/bytedance/xgplayer/assets/25141100/291338f3-414e-4d77-89f0-21ba1ff66d89">

**如何复现问题？ How to reproduce the problem?**
<img width="302" alt="image" src="https://github.com/bytedance/xgplayer/assets/25141100/c6282905-ebb1-4c4f-ab23-b9baa9f59c2a">
实例化播放器进行播放，报错如图

<img width="302" alt="image" src="https://github.com/bytedance/xgplayer/assets/25141100/c6282905-ebb1-4c4f-ab23-b9baa9f59c2a">
实例化播放器进行播放，报错如图

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
提示解码错误

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@Hubmeat 方便提供下播放地址吗？或者demo？

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hubmeat** [comment]
https://dyanyapi.elecottech.com/mini_comm_img/hichina/video/dehong_new.mp4

**Comment by gemxx** [comment]
@Hubmeat 这个MP4视频的264 Codec编码参数有些高 AVC High Level 5 [avc1.640032/]，中低端手机一般不支持。建议对用户提供 High Level 3左右的编码

> https://dyanyapi.elecottech.com/mini_comm_img/hichina/video/dehong_new.mp4

**Comment by Hubmeat** [comment]
但是a

> @Hubmeat 这个MP4视频的264 Codec编码参数有些高 AVC High Level 5 [avc1.640032/]，中低端手机一般不支持。建议对用户提供 High Level 3左右的编码
> 
> > https://dyanyapi.elecottech.com/mini_comm_img/hichina/video/dehong_new.mp4

但是用户设备本身通过浏览器直接播放这个 Mp4 应该可以，造成编码解析差异的原因是设备原因还是组件原因呢？

**Comment by gemxx** [comment]
@Hubmeat 提供一下播放器的配置我再看一下。由于我手边没有这个机型做测试，你那里有的话，可以试试直接用原生video直接播放这个视频地址，看看能否播放？如果不能播放的话，就是浏览器在实际实现的时候有特殊处理。
