### ISSUE TITLE
如何播放ws-flv直播流

### ISSUE THREAD

**Issue by liaojinlanlwjian** [bytedance/xgplayer#1417]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.16

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window chorm

**如何复现问题？ How to reproduce the problem?**
播放wss-flv流

ws://183.3.128.75:18938/jessica/live/7CTDLCR00B941P_out.flv这个是流地址，在官网的demo也播放不了

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常播放wss-flv

**实际播放器的表现是？ What actually happened?**
"ws" is not supported

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无人机相关

**Comment by xiyuyizhi** [comment]
@liaojinlanlwjian 暂时不支持ws拉流

**Comment by xiyuyizhi** [comment]
@liaojinlanlwjian 暂时还没计划哈

**Comment by liaojinlanlwjian** [comment]
@xiyuyizhi 可以定制开发么

**Comment by chuxin-cs** [comment]
> [@liaojinlanlwjian](https://github.com/liaojinlanlwjian) 暂时还没计划哈

现在2025年了  3.0 目前暂时还是不支持 wss+flv的拉流方式嘛 目前用的是2.0的版本
