### ISSUE TITLE
url为数组，视频格式为hls，如何配置才能播放

### ISSUE THREAD

**Issue by ko-yuki** [bytedance/xgplayer#1420]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.13

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 
chrome 版本 109.0.5414.120（正式版本） （64 位）

**如何复现问题？ How to reproduce the problem?**
如何配置hls格式的播放列表，即url为数组，视频格式是hls，试了很多方法都不行

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放hls格式列表

**实际播放器的表现是？ What actually happened?**
无法播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@ko-yuki 使用的xgplayer-hls插件吗?
