### ISSUE TITLE
能支持header里面添加授权吗，token直接放URL有泄漏的风险

### ISSUE THREAD

**Issue by talksmallice** [bytedance/xgplayer#1428]
能支持header里面添加授权吗？token直接放URL有泄漏的风险

**Comment by gemxx** [comment]
@talksmallice 请问使用的是xgplayer还是xgplayer的插件？xgplayer直接使用video播放，只能通过同源设置请求cookie的方式去携带信息，不支持修改其他请求header。如果是xgplayer的插件（xgplayer-hls/xgplayer-flv/xgplayer-mp4），采用JS的方式下载是可以修改的
