### ISSUE TITLE
edge浏览器不能播放hls格式的视频，chrome可以

### ISSUE THREAD

**Issue by gemdeng** [bytedance/xgplayer#1429]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.17",
    "xgplayer-hls": "^3.0.17",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win10：Microsoft Windows版本 21H2(操作系统内部版本 19044.1415)
edge：版本 124.0.2478.80 (正式版本) (64 位)
chrome：版本 124.0.6367.202（正式版本） （64 位）
**如何复现问题？ How to reproduce the problem?**
import Player from "xgplayer";
import "xgplayer/dist/index.min.css";
import HlsPlugin from "xgplayer-hls";
let player = new Player({
    id: "xgVideo",
    lang: "zh",
    autoplay: false,
    plugins: [HlsPlugin ],
    url: "/xxx.m3u8",
  });

**您期望的播放器正常行为是？ What did you expect to happen?**
edge浏览器能够播放hls格式的视频

**实际播放器的表现是？ What actually happened?**
chrome可以播放，edge显示格式错误

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
方便提供下视频地址吗？或者测试的页面吗？
