### ISSUE TITLE
苹果手机在微信内置浏览器打开h5后播放器音量设置未生效

### ISSUE THREAD

**Issue by Smallcarve** [bytedance/xgplayer#1436]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios，微信内置浏览器

**如何复现问题？ How to reproduce the problem?**
用微信打开h5链接

**您期望的播放器正常行为是？ What did you expect to happen?**
代码中配置播放器静音，播放时静音

**实际播放器的表现是？ What actually happened?**
代码中配置播放器静音，播放时仍有声音

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@Smallcarve 提供一下你的播放器配置，以及iOS的版本

**Comment by Smallcarve** [comment]
player = new Player({
      id,
      url,
      autoplay,
      volume: 0,
      height: "95%",
      width: '95%',
      controls: {
        root: document.getElementById('controls_new_root'), // 指定播放器之外挂载dom
      },
    });

ios 16.1

**Comment by gemxx** [comment]
@Smallcarve iOS 无法通过程序调整声音，你试试配置 muted: true 或者 defaultMuted: true，看看能否解决你的问题
https://h5player.bytedance.com/api/#muted

**Comment by yutao721** [comment]
也遇到同样的问题，播放音频 ios端微信浏览器没有声音
