### ISSUE TITLE
移动端第一次单击进入一定要先进入聚焦状态，然后单击暂停单击播放才能生效果吗

### ISSUE THREAD

**Issue by woodyRoyal** [bytedance/xgplayer#1442]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.16",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 11    chrome  124.0.6367.208

**如何复现问题？ How to reproduce the problem?**
正常使用就行

**您期望的播放器正常行为是？ What did you expect to happen?**
不管是否在聚焦状态，单机暂停单机播放都立即生效

**实际播放器的表现是？ What actually happened?**
点一下后会先进入聚焦状态，上下有一层阴影，此时单击双击才能触发暂停播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by woodyRoyal** [comment]
如果自己把点击事件绑定到播放器的容器上去手动操控暂停启用，会影响切换清晰度，切换倍速等功能，点击切换的时候视频暂停播放也被暂停了

**Comment by gemxx** [comment]
@woodyRoyal 看看 [closefocusvideofocus](https://h5player.bytedance.com/config/#closefocusvideofocus) 这个配置是否能满足你的需求
