### ISSUE TITLE
mobile插件 开启长按倍速调整 手指轻微移动该事件就结束了 怎么解决

### ISSUE THREAD

**Issue by kangkangBit** [bytedance/xgplayer#1443]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
 3.0.17

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios 微信浏览器端

**如何复现问题？ How to reproduce the problem?**
开启长按倍速调整

**您期望的播放器正常行为是？ What did you expect to happen?**
长按的时候 手指可以轻微移动 而不结束长按倍速调整事件

**实际播放器的表现是？ What actually happened?**
手指轻微移动该事件就结束了

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by kangkang-project** [comment]
@gemxx
