### ISSUE TITLE
自动播放问题

### ISSUE THREAD

**Issue by greation** [bytedance/xgplayer#145]
自动播放兼容性不行，基本只能在pc端

**Comment by zhangxin92** [comment]
静音了吗？

**Comment by zhangxin92** [comment]
这是关于自动播放的一些资料可以参考下
https://webkit.org/blog/6784/new-video-policies-for-ios/
https://developers.google.com/web/updates/2016/07/autoplay
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by xchz** [comment]
我看了一下斗鱼也是用mse直播的，却能不静音自动播放，大佬知道是怎么实现吗

**Comment by zhangxin92** [comment]
@xchz 和网站在浏览器的Media Engagement Index指数有关系
