### ISSUE TITLE
发现一个问题，就是在IE浏览器中出现如下问题

### ISSUE THREAD

**Issue by sunmouren** [bytedance/xgplayer#146]
![image](https://user-images.githubusercontent.com/30149424/50835768-91931800-1392-11e9-95b9-ccaa29c3f14c.png)
原因是在.xgplayer-enter-logo中的background-image。

**Comment by zhangxin92** [comment]
请问是什么操作系统和浏览器？

**Comment by sunmouren** [comment]
补充一点，开发环境是在Django中。

**Comment by sunmouren** [comment]
> 请问是什么操作系统和浏览器？

win10 自带浏览器，开发环境 Django。

**Comment by sunmouren** [comment]
> 请问是什么操作系统和浏览器？

后面我把background-image给删了就没事了。

**Comment by zhangxin92** [comment]
感谢反馈！
