### ISSUE TITLE
播放控件 UI 优化建议

### ISSUE THREAD

**Issue by lushfe** [bytedance/xgplayer#1460]
**您使用的西瓜播放器版本是多少？**
v3.x

**您使用的操作系统和浏览器分别是？**
windows+chrome

**建议优化的内容？**
![image](https://github.com/bytedance/xgplayer/assets/24297820/522ffd73-6d9e-42b5-9611-9ca9174f4d12)
希望控件的 Tooltip 边缘做位置计算禁止溢出，推荐 Tooltip 最低距离边距为 5px，具体实现思路可参考：[右键菜单位置的抉择](https://www.bilibili.com/video/BV1vK411x78G/?spm_id_from=333.788&vd_source=9cf9f43561ef378b940581483ff2df31)

**Comment by gemxx** [comment]
`lang: 'EN'` 或者其它国际化语言时，考虑一下TIP边界
