### ISSUE TITLE
手机端在个别手机自带浏览器 出现配置失效 video标签顶级显示 出现下载按钮问题

### ISSUE THREAD

**Issue by JWZJ** [bytedance/xgplayer#1465]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Android MIUI 手机自带浏览器

**如何复现问题？ How to reproduce the problem?**

new Player({
        id: "video-player",
        autoplay: true,
        download: false,
        "x5-video-player-type": "h5",
        'x5-video-player-fullscreen': false,
        'x5-video-orientation': 'portraint',
        playsinline: true,
        url: "",
        playbackRate: [1, 1.5, 2],
        startTime: 0,
        width: "100%",
        height: 249,
      });
需求：在手机浏览器 显示预设倍速，同层播放，禁止下载

**您期望的播放器正常行为是？ What did you expect to happen?**
 视频播放在同层播放 可以被弹窗覆盖 控制栏按照配置正常显示

**实际播放器的表现是？ What actually happened?**
 视频播放会在顶层 无法被弹窗覆盖 且控制栏变为浏览器自带控制栏 出现下载按钮图标 倍速设置失效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
![微信图片_20240528154736](https://github.com/bytedance/xgplayer/assets/29419576/ba8a20dc-47ef-4308-82a1-ae0724c7d77f)

**Comment by JWZJ** [comment]
![微信图片_20240528154832](https://github.com/bytedance/xgplayer/assets/29419576/f582acda-6acc-4bc7-93fe-5ee81403aac8)
这个是HUAWEI Mate60 Pro自带浏览器的显示效果 是正常的 问题里的截图是Redmi K30S Ultra上的自带浏览器

**Comment by gemxx** [comment]
@JWZJ 有些移动端浏览器劫持了UI，video无法自定义UI，这个无法破解
