### ISSUE TITLE
ios 微信打开显示不支持格式

### ISSUE THREAD

**Issue by Rookie-zrx** [bytedance/xgplayer#1466]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**
同样的视频微信打开显示格式不支持，但在pc端和 ios 浏览器上正常显示，视频格式是mp4
![252c92a19e930e5bc9cbf01e9f813cd](https://github.com/bytedance/xgplayer/assets/54833166/8f4c0c9e-1db3-4428-9dce-5010e15998b3)
![image](https://github.com/bytedance/xgplayer/assets/54833166/58eb6d04-0f9d-4de2-9fde-d3cbc21ad045)

**您期望的播放器正常行为是？ What did you expect to happen?**
都能正常播放视频

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Tajigaqzh** [comment]
try to remove the http: or https: prefix

**Comment by Tajigaqzh** [comment]
Check your developers and if you find that some post requests and options requests have cross domain errors, try removing the http: or https: prefix from the URL. if you URL contains http: or https: and use mp4 mode,xgplayer will send some post request and options request which can`t be  understand by the backend,error will occur.           important !!! remember to configure cross domain on  the backend

**Comment by Rookie-zrx** [comment]
> Check your developers and if you find that some post requests and options requests have cross domain errors, try removing the http: or https: prefix from the URL. if you URL contains http: or https: and use mp4 mode,xgplayer will send some post request and options request which can`t be understand by the backend,error will occur. important !!! remember to configure cross domain on the backend

经过测试不是这个的问题（After our tests, we found that this was not the problem）
