### ISSUE TITLE
QQ 浏览器会将播放器给重置成qq浏览器内置的样子，包括操作限制

### ISSUE THREAD

**Issue by Rookie-zrx** [bytedance/xgplayer#1472]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
 qq 浏览器  ios 17.4

**如何复现问题？ How to reproduce the problem?**
将我们本身自己的视频用qq 浏览器打开，发现qq浏览器会重置掉西瓜播放器，播放器所做的操作限制，被qq 浏览器完全无视，

![60a24e80a36a4e5128e65718dd23dfd](https://github.com/bytedance/xgplayer/assets/54833166/0829c602-ba8b-4da8-9825-4b0d4fd57874)
![Uploading 60a24e80a36a4e5128e65718dd23dfd.png…]()

**您期望的播放器正常行为是？ What did you expect to happen?**
正常显示西瓜播放器本身的样子和操作限制

**实际播放器的表现是？ What actually happened?**
被qq 浏览器重置成他自定义的样式和操作

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by itchaox** [comment]
浏览器劫持，无法解决

**Comment by gemxx** [comment]
如楼上回复，劫持问题无解。
