### ISSUE TITLE
如何在播放m3u8的时候关闭视频轨道仅仅播放音频

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#1473]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@pocketChao 目前所有转封装的插件，没有提供可以单独忽略某个track的能力。请问这是为了满足什么样的需求场景？

**Comment by pocketChao** [comment]
> @pocketChao 目前所有转封装的插件，没有提供可以单独忽略某个track的能力。请问这是为了满足什么样的需求场景？

感谢回复，项目有音视频切换关闭视频轨道的需求

**Comment by gemxx** [comment]
@pocketChao 你是在用xgplayer-hls插件吗？版本是多少？

**Comment by pocketChao** [comment]
> @pocketChao 你是在用xgplayer-hls插件吗？版本是多少？

是的    "xgplayer-hls.js": "^2.6.4"

**Comment by gemxx** [comment]
你在用的不是自研的xgplayer-hls，是第三方的hls.js能力。目前 xgplayer-hls.js 我们仅仅是提供了对接能力，但要深度定制还得去看下 https://github.com/video-dev/hls.js 这个的配置

**Comment by pocketChao** [comment]
> @pocketChao 你在用的不是自研的xgplayer-hls，是第三方的hls.js能力。目前 xgplayer-hls.js 我们仅仅是提供了对接能力，但要深度定制还得去看下 https://github.com/video-dev/hls.js 这个的配置

好 感谢
