### ISSUE TITLE
关于hls插件的onPreM3U8Parse参数

### ISSUE THREAD

**Issue by YadOwO** [bytedance/xgplayer#1481]
你们这个onPreM3U8Parse这个参数能用嘛？我看文档没有，但是源码里面有

版本：
 "xgplayer": "^3.0.18",
 "xgplayer-hls": "^3.0.18"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS14.5，Google浏览器

**Comment by gemxx** [comment]
@YadOwO 可以用。在hls config中的都可以使用
