### ISSUE TITLE
国际化能支持泰文吗

### ISSUE THREAD

**Issue by zhengcongqi** [bytedance/xgplayer#1484]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@zhengcongqi 支持泰语，可以参考一下国际化的接入方式 https://h5player.bytedance.com/guide/i18n.html#%E5%90%AF%E7%94%A8%E9%A2%84%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E5%8C%85

`import TH from 'xgplayer/es/lang/th'`
