### ISSUE TITLE
自定义样式是不是有版本要求，3.0.18以上的版本执行npx xgplayer eject ./  custom 报错

### ISSUE THREAD

**Issue by zhengcongqi** [bytedance/xgplayer#1485]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Windows 谷歌
**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@zhengcongqi 您可能还在看的是V2的文档站，请使用V3文档自定义UI的方式 https://h5player.bytedance.com/plugins/icons.html#%E5%8F%AF%E9%85%8D%E7%BD%AE%E5%9B%BE%E6%A0%87%E5%88%97%E8%A1%A8

**Comment by zhengcongqi** [comment]
修复
