### ISSUE TITLE
使用FlvPlugin播放直播流时使用ignores属性禁用loading内置插件的问题

### ISSUE THREAD

**Issue by dyxweb** [bytedance/xgplayer#1486]
您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?
v3

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
windows Chrome

如何复现问题？ How to reproduce the problem?

使用FlvPlugin播放直播流时，使用ignores属性禁用loading内置插件时，当推流较慢时会显示start内置插件。

您期望的播放器正常行为是？ What did you expect to happen?

当禁用loading内置插件时，推流较慢不显示loading插件也不显示start内置插件。

实际播放器的表现是？ What actually happened?
当禁用loading内置插件时，推流较慢不显示loading插件但是会显示start内置插件。

可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.

**Comment by gemxx** [comment]
@dyxweb 将loading和start都忽略掉 `ignores:['loading', 'start']`，能否满足你的需求？

**Comment by dyxweb** [comment]
目前是这么处理的，但是在暂停时也就没有办法通过播放器中间的start内置插件进行继续播放操作了，希望可以解决一下只忽略loading时的问题。
