### ISSUE TITLE
srt 格式字幕无法正常显示

### ISSUE THREAD

**Issue by jasoncoke** [bytedance/xgplayer#1487]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1 

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
版本支持 srt 格式字幕吗？

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@jasoncoke 目前仅支持webvtt格式
