### ISSUE TITLE
官方的xgplayer-hls插件解析m3u8 不支持默认起播时间startTime并且自动播放

### ISSUE THREAD

**Issue by woodyRoyal** [bytedance/xgplayer#1488]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
        "xgplayer": "3.0.16",
        "xgplayer-hls": "3.0.16",
        "xgplayer-hls.js": "3.0.16"
        新版本都试过，都有同样的问题
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
        ios safari 
**如何复现问题？ How to reproduce the problem?**
        ios safari 等所有浏览器使用官方的xgplayer-hls设置静音，startTime，并且自动播放后，视频会还是从0秒开始播，
       并且滚动条还出现异常，会停留在原点不动

**您期望的播放器正常行为是？ What did you expect to happen?**
    能够正常从设置的startTime中起播

**实际播放器的表现是？ What actually happened?**
   视频会还是从0秒开始播，并且滚动条还出现异常，会停留在原点不动

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by woodyRoyal** [comment]
补充说明: 使用第三方的包 xgplayer-hls.js 功能表现是正常的，但是我们做类似抖音那种视频滑动交互，发现 xgplayer-hls.js 在销毁播放器到下一个都时候太卡了，动画都掉帧了，官方的 xgplayer-hls 功能表现不正常，但是不会出现这个性能问题

**Comment by gemxx** [comment]
@woodyRoyal 测试的iOS版本是多少？
