### ISSUE TITLE
西瓜播放器可以任意时间段进行预加载吗？例如当前播放第3秒，然后加载第30-35秒的视频数据，达到跳转的时候不卡顿的效果

### ISSUE THREAD

**Issue by Happy66688** [bytedance/xgplayer#1494]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows Chrome

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
可以对任意时间段进行预加载

**实际播放器的表现是？ What actually happened?**
播放器不能对任意时间段进行预加载

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@Happy66688 目前不支持
