### ISSUE TITLE
苹果手机播放MP4视频提示不支持的视频格式，刷新后正常播放

### ISSUE THREAD

**Issue by cuilinna** [bytedance/xgplayer#1502]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios17 safari

**如何复现问题？ How to reproduce the problem?**
在使用MP4Plugin的时候，ios端浏览器,播放提示不支持的音频/视频格式，点击完刷新，正常播放，这个是一定要手动点刷新触发吗。不可以自动降级吗，是否可以支持一下

**您期望的播放器正常行为是？ What did you expect to happen?**
打开即正常播放，不需要手动刷新

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
暂时iOS下不加载MP4Plugin
