### ISSUE TITLE
拖动音量控制条松开会触发播放器的播放、暂停。

### ISSUE THREAD

**Issue by wscfan** [bytedance/xgplayer#1508]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer3.0.10

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows11、Chrome126

**如何复现问题？ How to reproduce the problem?**
拖动音量控制条按住不松开，然后在音量控制条外的播放器区域松开鼠标左键，会触发播放器的播放或者暂停。

**您期望的播放器正常行为是？ What did you expect to happen?**
不应该触发播放器的播放或暂停功能，这个问题在xgplayer2.x版本是正常的。

**实际播放器的表现是？ What actually happened?**
会触发播放器的播放或者暂停。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by mrchongzi** [comment]
拖动进度条同样会触发这个问题
