### ISSUE TITLE
在 chrome的移动的模拟器上 提示 network is offline，please try to refresh

### ISSUE THREAD

**Issue by highmind** [bytedance/xgplayer#151]
在 chrome的移动的模拟器上 提示 network is offline，please try to refresh，  
chrome的 非模拟器模式没有问题
![qq 20190212163858](https://user-images.githubusercontent.com/19481942/52622732-7f524f80-2ee5-11e9-8900-54f78f3cf927.png)

**Comment by zhangxin92** [comment]
播的什么格式视频？除了xgplayer有用到其它西瓜播放器插件吗？

**Comment by highmind** [comment]
不好意思 忘说了使用的 hls模式，xgplayer-hls.js这个插件，  没有使用其他播放器， 但是我看了 chimee-player 的hls方式 是没有问题的

**Comment by zhangxin92** [comment]
移动端环境(或safari)的原生video本来就支持播放hls，而PC环境(非safari)需要额外的hls解析代码。
xgplayer-hls.js插件会通过navigator.userAgent检测，判断是PC环境(非safari)就调用hls的解析功能播放，判断是移动端环境(或safari)就直接用video播放。
你在PC的chrome手机模拟器上，xgplayer-hls.js插件判断是移动端环境就会用video直接播放hls，但实际的PC环境不支持直接播放hls，导致出现错误提示。

**Comment by highmind** [comment]
谢谢，在 安卓的移动端的 chrome浏览器 也有同样的错误提示
![qq 20190212171620](https://user-images.githubusercontent.com/19481942/52624547-effb6b00-2ee9-11e9-8a31-383a2e8781d8.png)

**Comment by zhangxin92** [comment]
hls地址发我试下，可以qq私我 815743082
