### ISSUE TITLE
xgplayer-hls.js插件能否支持多分辨率的m3u8自动添加分辨率切换

### ISSUE THREAD

**Issue by lvzhenbo** [bytedance/xgplayer#1510]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

win11
chrome126

**如何复现问题？ How to reproduce the problem?**

和官网给出的一样，但是链接是多分辨率的m3u8

**您期望的播放器正常行为是？ What did you expect to happen?**

多分辨率的m3u8能够播放但是默认是最高画质，希望能够有分辨率选择

**实际播放器的表现是？ What actually happened?**

没有分辨率选择

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@lvzhenbo 多分辨率的m3u8是指 [master playlist](https://developer.apple.com/documentation/http-live-streaming/creating-a-multivariant-playlist) 的方式吗？

**Comment by lvzhenbo** [comment]
是的，我看hls.js是支持解析的

**Comment by miroku-y** [comment]
![Image](https://github.com/user-attachments/assets/140c335c-1880-4b5f-aa0e-609d54c1ac1f)
文档上也没有见hls 插件 播放m3u8 文件，配置分辨率切换的api , 是不支持吗？如上图这种。
