### ISSUE TITLE
全屏播放字幕不显示

### ISSUE THREAD

**Issue by YDJSZY** [bytedance/xgplayer#1511]
使用xgplayer-subtitles插件添加字幕，当全屏播放时字幕不显示了

**Comment by gemxx** [comment]
@YDJSZY 请问有可复现的demo或者页面地址吗？

**Comment by YDJSZY** [comment]
@gemxx 没有，我是在tg小程序播放的。当全屏时就看不到字幕了

**Comment by YDJSZY** [comment]
在ios chrome浏览器播放视频也是一样，全屏后就看不到字幕了

**Comment by gemxx** [comment]
@YDJSZY 全屏后是系统播放器，任何H5 UI都覆盖不上
