### ISSUE TITLE
是否支持vue3+TS环境下使用本项目

### ISSUE THREAD

**Issue by kelvaer** [bytedance/xgplayer#1512]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

xgplayer@2.0.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10  edge

**如何复现问题？ How to reproduce the problem?**

在vue3+TS环境下使用本项目

**您期望的播放器正常行为是？ What did you expect to happen?**

支持vue3+TS环境下使用本项目

**实际播放器的表现是？ What actually happened?**

引入依赖后报错无法启动

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@kelvaer 请试试 xgplayer@3.x 版本

**Comment by eunrui** [comment]
> [@kelvaer](https://github.com/kelvaer) 请试试 [xgplayer@3.x](mailto:xgplayer@3.x) 版本，https://h5player.bytedance.com/guide/#%E5%AE%89%E8%A3%85

该版本启动报错呀，icon的js文件没有

"xgplayer": "^3.0.22",
"xgplayer-flv": "^3.0.22",
"xgplayer-hls": "^3.0.22"

`✘ [ERROR] Could not resolve "../assets/loading.js"

    node_modules/xgplayer/es/plugins/loading/index.js:3:24:
      3 │ import loadingIcon from "../assets/loading.js";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/play.js"

    node_modules/xgplayer/es/plugins/play/index.js:8:21:
      8 │ import PlayIcon from "../assets/play.js";
        ╵                      ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/pause.js"

    node_modules/xgplayer/es/plugins/play/index.js:9:22:
      9 │ import PauseIcon from "../assets/pause.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/volumeLarge.js"

    node_modules/xgplayer/es/plugins/volume/index.js:7:27:
      7 │ import volumeLargeSvg from "../assets/volumeLarge.js";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/volumeSmall.js"

    node_modules/xgplayer/es/plugins/volume/index.js:8:27:
      8 │ import volumeSmallSvg from "../assets/volumeSmall.js";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/requestFull.js"

    node_modules/xgplayer/es/plugins/fullscreen/index.js:10:26:
      10 │ import FullScreenSvg from "../assets/requestFull.js";
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/exitFull.js"

    node_modules/xgplayer/es/plugins/fullscreen/index.js:11:30:
      11 │ import ExitFullScreenSvg from "../assets/exitFull.js";
         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/play.js"

    node_modules/xgplayer/es/plugins/miniScreen/index.js:7:21:
      7 │ import PlayIcon from "../assets/play.js";
        ╵                      ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/pause.js"

    node_modules/xgplayer/es/plugins/miniScreen/index.js:8:22:
      8 │ import PauseIcon from "../assets/pause.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/back.js"

    node_modules/xgplayer/es/plugins/fullscreen/backicon.js:5:20:
      5 │ import BackSVG from "../assets/back.js";
        ╵                     ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/volumeMuted.js"

    node_modules/xgplayer/es/plugins/volume/index.js:9:27:
      9 │ import volumeMutedSvg from "../assets/volumeMuted.js";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/replay.js"

    node_modules/xgplayer/es/plugins/replay/index.js:6:22:
      6 │ import ReplaySvg from "../assets/replay.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/play.js"

    node_modules/xgplayer/es/plugins/start/index.js:7:21:
      7 │ import PlayIcon from "../assets/play.js";
        ╵                      ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/pause.js"

    node_modules/xgplayer/es/plugins/start/index.js:8:22:
      8 │ import PauseIcon from "../assets/pause.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/rotate.js"

    node_modules/xgplayer/es/plugins/rotate/index.js:8:22:
      8 │ import RotateSvg from "../assets/rotate.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/seekicon.js"

    node_modules/xgplayer/es/plugins/mobile/index.js:10:24:
      10 │ import SeekTipIcon from "../assets/seekicon.js";
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/pipIcon.js"

    node_modules/xgplayer/es/plugins/pip/index.js:8:20:
      8 │ import PipIcon from "../assets/pipIcon.js";
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/pipIconExit.js"

    node_modules/xgplayer/es/plugins/pip/index.js:9:24:
      9 │ import PipIconExit from "../assets/pipIconExit.js";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/playNext.js"

    node_modules/xgplayer/es/plugins/playNext/index.js:8:17:
      8 │ import Next from "../assets/playNext.js";
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/requestCssFull.js"

    node_modules/xgplayer/es/plugins/cssFullScreen/index.js:8:28:
      8 │ import CssFullSceenSvg from "../assets/requestCssFull.js";
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/exitCssFull.js"

    node_modules/xgplayer/es/plugins/cssFullScreen/index.js:9:32:
      9 │ import ExitCssFullSceenSvg from "../assets/exitCssFull.js";
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/panel.js"

    node_modules/xgplayer/es/plugins/danmu/danmuPanel.js:6:22:
      6 │ import PanelIcon from "../assets/panel.js";
        ╵                       ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../assets/download.js"

    node_modules/xgplayer/es/plugins/download/index.js:8:24:
      8 │ import DownloadSvg from "../assets/download.js";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~
`
