### ISSUE TITLE
西瓜播放器ios系统下在微信内置浏览器播放hls视频流，只有声音没有画面

### ISSUE THREAD

**Issue by 1502343zhou** [bytedance/xgplayer#1520]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
能否提供一下播放器版本、配置，以及测试流？

**Comment by 1502343zhou** [comment]
已经可以了，是因为视频流编码格式是H265，但之前因为在安卓系统下能正常播放所以就没有往这方面想
