### ISSUE TITLE
播放器全屏播放时，不出现控制栏

### ISSUE THREAD

**Issue by bowei200888** [bytedance/xgplayer#1522]
播放器版本是3.0.17

使用的是谷歌浏览器 版本 125.0.6422.142（正式版本） （64 位）

就是播放有的mp4视频时，播放器全屏时，鼠标在播放器上移动时，播放器控制栏不出现，只有鼠标出现在进度条，才出现控制栏，而且视频有闪动。
但是用官网提供视频就不会出现这些问题。

这个是实现的代码

http://kjxxbz.xadade.com/mse.html

**Comment by gemxx** [comment]
@bowei200888 我用您提供的这个demo + chrome 125版本，并未复现反馈的问题！
请问是否还有其他的条件可以提供？有试过其他的浏览器以及机器吗？

**Comment by bowei200888** [comment]
@gemxx 之后测试了，发现火狐、360、QQ浏览器都是正常的，win11上的同版本浏览器也是正常的，

出问题的win10上，而且还是部分win10操作系统上。
同时Microsoft Edge版本 123.0.2420.97 (正式版本) (64 位)浏览器也是同样的问题

![企业微信截图_17212069235631](https://github.com/user-attachments/assets/1d416236-a950-4ecf-992c-f077b05c2237)
这是出问题的操作系统截图

https://github.com/user-attachments/assets/24a38122-8eb8-484b-9bb0-b167e7ba137d
这个是具体表现的问题

如果还是不能具现问题麻烦告知，我会关闭这个问题。等后面找到规律再说。
