### ISSUE TITLE
FLV插件在点播时只可以播放10M内容

### ISSUE THREAD

**Issue by maxid** [bytedance/xgplayer#1524]
您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?
3.0.10

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
win11 & macos 、 chrome 100+

如何复现问题？ How to reproduce the problem?
设置 isLive 为 false，因CORS原因，播放器不能读取Accept-Ranges,Content-Range响应头，导致只能读取10M内容
![image](https://github.com/bytedance/xgplayer/assets/927429/f8b0bce7-7712-443d-990d-9db1d4fe705c)
<img width="1214" alt="image" src="https://github.com/bytedance/xgplayer/assets/927429/f0981305-821f-43b9-94d5-bfda2e80f034">
<img width="1523" alt="image" src="https://github.com/bytedance/xgplayer/assets/927429/19d01170-5ef7-478a-932c-8e7658ea1e4c">

您期望的播放器正常行为是？ What did you expect to happen?
期望开放给用户设置_acceptRanges，解决以上点播异常问题，通过测试，注释掉 347、348行后正常

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhuguibiao** [comment]
快速解决方案是：在资源响应头设置 Access-Control-Expose-Headers : "Accept-Ranges,Content-Range"
或者等后续升级修复这个问题

**Comment by maxid** [comment]
点播源不是我们的，期待后续版本，目前暂时强制设置 _acceptRanges 为 true 解决使用问题
