### ISSUE TITLE
playbackRate 能否设置负数

### ISSUE THREAD

**Issue by DaikonX** [bytedance/xgplayer#1526]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 、chrome

**如何复现问题？ How to reproduce the problem?**
playbackRate 设置负数 没有反应，

**您期望的播放器正常行为是？ What did you expect to happen?**
playbackRate 设置负数 实现倒放 

**实际播放器的表现是？ What actually happened?**
playbackRate 设置负数 没有效果，无任何倍速效果

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
规范定义上是可以设置负数的，但浏览器目前没有实现倒放的能力，所以设置后无效
