### ISSUE TITLE
https网站使用xgplayer显示您与此网站之间建立的连接并非完全安全

### ISSUE THREAD

**Issue by lzou** [bytedance/xgplayer#153]
因为xgplayer调用了http://s2.pstatp.com 这个站里面的资源，所以导致https的站使用xgplayer，在Chrome地址栏前面就会打感叹号，而不是一把小锁。建议换成https的资源，这样显示就能正常了。

**Comment by lzou** [comment]
![wechatimg391](https://user-images.githubusercontent.com/2950642/53862639-f5e4f780-4022-11e9-8daf-faa6e0867ef6.jpeg)
西瓜视频官网也是如此，也不是安全的

**Comment by zhangxin92** [comment]
西瓜播放器调用资源时会写作 //s2.pstatp.com，根据域名自动判断http、https，你再检查下是不是页面其它资源引起的？

**Comment by lzou** [comment]
> 西瓜播放器调用资源时会写作 //s2.pstatp.com，根据域名自动判断http、https，你再检查下是不是页面其它资源引起的？

![image](https://user-images.githubusercontent.com/2950642/53877908-613fc100-4045-11e9-822b-6223ff4cede1.png)
西瓜视频官网都是http的，看截图红框

**Comment by zhangxin92** [comment]
好的，那是旧版本播放器，新版没有这个问题，谢谢提醒！

**Comment by lzou** [comment]
> 好的，那是旧版本播放器，新版没有这个问题，谢谢提醒！

![image](https://user-images.githubusercontent.com/2950642/53878181-2b4f0c80-4046-11e9-8179-88130a497c3a.png)
嗯，看出来了，有用//的，也有用http://的。那只要升级下就行了吧？

**Comment by zhangxin92** [comment]
是的，可以升级到xgplayer@1.1.4
