### ISSUE TITLE
H265格式的MP4不能播放

### ISSUE THREAD

**Issue by 457775987** [bytedance/xgplayer#1535]
**您使用的西瓜播放器版本是多少？ 3.0

**您使用的操作系统和浏览器分别是？ windows+谷歌浏览器

H265视频录制的MP4片段无法播放。（另外后续会支持软解吗？）

**Comment by syjf** [comment]
> **您使用的西瓜播放器版本是多少？ 3.0
> 
> **您使用的网络浏览器和浏览器分别是？ windows+谷歌浏览器
> 
> H265视频录制的MP4片段无法播放。（后续会支持软解吗？）

请问有解决方案吗？我看官网的示例用xgplayer-mp4播放h265格式的视频会直接提示不支持，但我用他会报不支持的错，但还是会播放，但视频是黑屏的有声音，你用过xgplayer-mp4吗

**Comment by gemxx** [comment]
@457775987 暂时不提供软解能力。关于265无法播放的问题，需要提供一下源视频文件或者可访问的环境
