### ISSUE TITLE
progessDot标记点，在快播放完时，会产生偏移

### ISSUE THREAD

**Issue by huzhiweikop** [bytedance/xgplayer#1536]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac chrome

**如何复现问题？ How to reproduce the problem?**

在官网demo就可以复现，贴入以下配置
```
        let player = new Player({
      id: 'mse',
      autoplay: true,  
      volume: 0.3,
      url: 'https://yeying-gateway.apps-fp.danlu.netease.com/xiyin/20240608184006924be6_-7023379938254508171_1799386742403502081_231188_1717842204939_1717842214956_top_final.mp4%3FExpires%3D1717928636%26OSSAccessKeyId%3DLTAIj4fGNSOImbLq%26Signature%3DBN%252FJEeAEN8WTv%252BUOWULw9D0SdU0%253D?Signature=9zGwVJ8WVvzHLuBoQrH1LaH4Eck%3D&Expires=4871443207&AWSAccessKeyId=HU4J73EY50QM95RMYOGM',
      progressDot:[{id:8,time:8,duration:1,style:{backgroundColor:'green'}},{id:1,time:1,duration:1}],
      playsinline: true,
      videoInit:true,
      height: window.innerHeight,
      width: window.innerWidth,
    });
```

会发现进度点一开始显示不正确，快播放完时才发生偏移，显示正确

**您期望的播放器正常行为是？ What did you expect to happen?**
进度点始终显示正确

**实际播放器的表现是？ What actually happened?**
进度点一开始显示不正确，快播放完时才显示正确

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.18
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** mac chrome
> 
> **如何复现问题？ How to reproduce the problem?**
> 
> 在官网demo就可以复现，贴入以下配置
> 
> ```
>     let player = new Player({
>       id: 'mse',
>       autoplay: true,  
>       volume: 0.3,
>       url: 'https://hiboxhz.oss-cn-hangzhou.aliyuncs.com/shopping_video/top_mp4_video/193632975_155377_1721311046024_1721311060464_top_final.mp4?Expires=1721397468&OSSAccessKeyId=LTAIj4fGNSOImbLq&Signature=581zbj54mWHE28dVa47AWQW1wtI%3D',
>       progressDot:[{id:10,time:10,duration:0,style:{backgroundColor:'green'}},{id:1,time:1,duration:0}],
>       playsinline: true,
>       videoInit:true,
>       height: window.innerHeight,
>       width: window.innerWidth,
>     });
> ```
> 
> 会发现进度点一开始显示不正确，快播放完时才发生偏移，显示正确
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 进度点始终显示正确
> 
> **实际播放器的表现是？ What actually happened?** 进度点一开始显示不正确，快播放完时才显示正确

视频时长是多少？duration是指这个点显示的时候的对应时长，不能为0， 修改一下1s以上

**Comment by huzhiweikop** [comment]
> > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.18
> > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** mac chrome
> > **如何复现问题？ How to reproduce the problem?**
> > 在官网demo就可以复现，贴入以下配置
> > ```
> >     let player = new Player({
> >       id: 'mse',
> >       autoplay: true,  
> >       volume: 0.3,
> >       url: 'https://hiboxhz.oss-cn-hangzhou.aliyuncs.com/shopping_video/top_mp4_video/193632975_155377_1721311046024_1721311060464_top_final.mp4?Expires=1721397468&OSSAccessKeyId=LTAIj4fGNSOImbLq&Signature=581zbj54mWHE28dVa47AWQW1wtI%3D',
> >       progressDot:[{id:10,time:10,duration:0,style:{backgroundColor:'green'}},{id:1,time:1,duration:0}],
> >       playsinline: true,
> >       videoInit:true,
> >       height: window.innerHeight,
> >       width: window.innerWidth,
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会发现进度点一开始显示不正确，快播放完时才发生偏移，显示正确
> > **您期望的播放器正常行为是？ What did you expect to happen?** 进度点始终显示正确
> > **实际播放器的表现是？ What actually happened?** 进度点一开始显示不正确，快播放完时才显示正确
> 
> 视频时长是多少？duration是指这个点显示的时候的对应时长，不能为0， 修改一下1s以上



> > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 3.0.18
> > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** mac chrome
> > **如何复现问题？ How to reproduce the problem?**
> > 在官网demo就可以复现，贴入以下配置
> > ```
> >     let player = new Player({
> >       id: 'mse',
> >       autoplay: true,  
> >       volume: 0.3,
> >       url: 'https://hiboxhz.oss-cn-hangzhou.aliyuncs.com/shopping_video/top_mp4_video/193632975_155377_1721311046024_1721311060464_top_final.mp4?Expires=1721397468&OSSAccessKeyId=LTAIj4fGNSOImbLq&Signature=581zbj54mWHE28dVa47AWQW1wtI%3D',
> >       progressDot:[{id:10,time:10,duration:0,style:{backgroundColor:'green'}},{id:1,time:1,duration:0}],
> >       playsinline: true,
> >       videoInit:true,
> >       height: window.innerHeight,
> >       width: window.innerWidth,
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会发现进度点一开始显示不正确，快播放完时才发生偏移，显示正确
> > **您期望的播放器正常行为是？ What did you expect to happen?** 进度点始终显示正确
> > **实际播放器的表现是？ What actually happened?** 进度点一开始显示不正确，快播放完时才显示正确
> 
> 视频时长是多少？duration是指这个点显示的时候的对应时长，不能为0， 修改一下1s以上

跟duration好像没关系，设成1s页还是有这个情况，可以在官网demo，贴以下配置重现

```
```
        let player = new Player({
      id: 'mse',
      autoplay: true,  
      volume: 0.3,
      url: 'https://yeying-gateway.apps-fp.danlu.netease.com/xiyin/20240608184006924be6_-7023379938254508171_1799386742403502081_231188_1717842204939_1717842214956_top_final.mp4%3FExpires%3D1717928636%26OSSAccessKeyId%3DLTAIj4fGNSOImbLq%26Signature%3DBN%252FJEeAEN8WTv%252BUOWULw9D0SdU0%253D?Signature=9zGwVJ8WVvzHLuBoQrH1LaH4Eck%3D&Expires=4871443207&AWSAccessKeyId=HU4J73EY50QM95RMYOGM',
      progressDot:[{id:8,time:8,duration:1,style:{backgroundColor:'green'}},{id:1,time:1,duration:1}],
      playsinline: true,
      videoInit:true,
      height: window.innerHeight,
      width: window.innerWidth,
    });
```
```
