### ISSUE TITLE
danmu.js功能异常

### ISSUE THREAD

**Issue by nyaruhodoo** [bytedance/xgplayer#1544]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.19

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11
Chrome  127.0.6533.73

**如何复现问题？ How to reproduce the problem?**
https://codesandbox.io/p/sandbox/danmu-fjz927?file=%2Fsrc%2FApp.tsx%3A4%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz82rpfh0006356jiaobpsg5%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz82rpfh0002356juza82rpo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz82rpfh0003356jtl2jnbuw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz82rpfh0005356jwwsm4c3q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz82rpfh0002356juza82rpo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz82rpfh0001356j876v06qy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz82wy3j0002356jlvteosqp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz82rpfh0002356juza82rpo%2522%252C%2522activeTabId%2522%253A%2522clz82wy3j0002356jlvteosqp%2522%257D%252C%2522clz82rpfh0005356jwwsm4c3q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz82rpfh0004356j6sr1yg0y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz82rpfh0005356jwwsm4c3q%2522%252C%2522activeTabId%2522%253A%2522clz82rpfh0004356j6sr1yg0y%2522%257D%252C%2522clz82rpfh0003356jtl2jnbuw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz82rpfh0003356jtl2jnbuw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**您期望的播放器正常行为是？ What did you expect to happen?**
弹幕正常响应事件

**实际播放器的表现是？ What actually happened?**
无法响应鼠标事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
在线流媒体

**Comment by gemxx** [comment]
@nyaruhodoo danmu.js 这两个开关（）加上去后， 现在内部并没有实现暂停的能力，而是开放了一个事件。可以在这个事件里进行暂停
```
danmu.on('bullet_hover', (e) => {
  danmu.freezeComment(e.bullet.id)

  setTimeout(function () {
    danmu.restartComment(e.bullet.id)
  }, 4000)
})
```
