### ISSUE TITLE
ios 中播放 m3u8 的问题

### ISSUE THREAD

**Issue by trry-hub** [bytedance/xgplayer#1545]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer@3.0.19

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios 16.3.1
wechat 8.0.50

**如何复现问题？ How to reproduce the problem?**
问题一：直播地址 m3u8 404时，错误提示 “不支持的音频/视频格式”
问题二：我监听了player.on(Events.ERROR ，重新设置播放地址，但m3u8 从 404 到 200状态时，一直loading，无法播放。

https://github.com/trry-hub/issues/tree/xgplayer

**您期望的播放器正常行为是？ What did you expect to happen?**

问题一：期望能跟pc 保持一致
问题二：重连后应该要能正常播放

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** xgplayer@3.0.19
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** ios 16.3.1 wechat 8.0.50
> 
> **如何复现问题？ How to reproduce the problem?** 问题一：直播地址 m3u8 404时，错误提示 “不支持的音频/视频格式” 问题二：我监听了player.on(Events.ERROR ，重新设置播放地址，但m3u8 从 404 到 200状态时，一直loading，无法播放。
> 
> https://github.com/trry-hub/issues/tree/xgplayer
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 
> 问题一：期望能跟pc 保持一致 问题二：重连后应该要能正常播放
> 
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**

移动端不会使用mse播放m3u8, 因此报错中不会细分是否是链接404，建议自己处理一下，可以把error提示面板禁用，自己实现一个，在移动端报错的时候对cdn地址发起一个fetch请求，确定其返回的httpcode,根据httpcode给用户做出直播流断开或者王阔异常的错误提示

**Comment by trry-hub** [comment]
> > **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** xgplayer@3.0.19
> > **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** ios 16.3.1 wechat 8.0.50
> > **如何复现问题？ How to reproduce the problem?** 问题一：直播地址 m3u8 404时，错误提示 “不支持的音频/视频格式” 问题二：我监听了player.on(Events.ERROR ，重新设置播放地址，但m3u8 从 404 到 200状态时，一直loading，无法播放。
> > https://github.com/trry-hub/issues/tree/xgplayer
> > **您期望的播放器正常行为是？ What did you expect to happen?**
> > 问题一：期望能跟pc 保持一致 问题二：重连后应该要能正常播放
> > **实际播放器的表现是？ What actually happened?**
> > **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**
> 
> 移动端不会使用mse播放m3u8, 因此报错中不会细分是否是链接404，建议自己处理一下，可以把error提示面板禁用，自己实现一个，在移动端报错的时候对cdn地址发起一个fetch请求，确定其返回的httpcode,根据httpcode给用户做出直播流断开或者王阔异常的错误提示

在ios 中使用判断url 为404（断流状态时），使用 switchURL 重新加载, 会一直loading。
