### ISSUE TITLE
无法消除播放器自带的按钮样式

### ISSUE THREAD

**Issue by jeff9571** [bytedance/xgplayer#1551]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.19", "xgplayer-hls": "^3.0.19"，vue2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11，chrome

**如何复现问题？ How to reproduce the problem?**
```
UI:
<div id="tx">
   <div id="player"></div>
</div>
#tx {
    grid-area: tx;
    border-radius: 4px;
    background: #37383B;
}
JS:
mounted() {
        this.player = new Player({
            id: "player",
            autoplayMuted: true,
            autoplay: true,
            url: 'http://localhost:8888/hls?url=rtsp://admin:12319@192.168.1.253/Streaming/Channels/102',
            plugins: [HlsPlugin],
            width:'100%',
            height:'100%',
        });
    },
```

**您期望的播放器正常行为是？ What did you expect to happen?**
应该像官方demo的播放器一样

**实际播放器的表现是？ What actually happened?**
<img width="503" alt="image" src="https://github.com/user-attachments/assets/fe6f1ecd-ef81-46c1-b7ad-0d8d934e8e93">

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@jeff9571 按[官网的步骤](https://h5player.bytedance.com/guide/)，引入一下CSS： 
```
import Player from 'xgplayer';
import 'xgplayer/dist/index.min.css';

let player = new Player({
  id: 'mse',
  url: '//abc.com/**/*.mp4',
  height: '100%',
  width: '100%',
});
```
