### ISSUE TITLE
初始化音乐插件后，是undefined， 无法调用文档写的add等属性和方法

### ISSUE THREAD

**Issue by wusp1994** [bytedance/xgplayer#1553]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
  "xgplayer": "^3.0.19",
    "xgplayer-music": "^3.0.19"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10

**如何复现问题？ How to reproduce the problem?**
```
import Player from 'xgplayer'
// 现在music作为一个固定的preset使用，不再继承player, 解决耦合性过大问题 ，垃圾框架，add 都调用失败
import MusicPreset, { Analyze } from 'xgplayer-music'
import 'xgplayer/dist/index.min.css'
import 'xgplayer-music/dist/index.min.css'
let player: Player;
  // 定义一个变量来存储 player 实例
  player = new Player({
    id: 'wu-music',
    mediaType: 'audio',
    url: 'D:\\WuWorkSpace\\testMusic.mp3',
    volume: 0.8,
    width: 900,
    height: 50,
    // 音乐播放控制模块配置
    music: {
      list: [],
      preloadNext: true, // 预加载下一首
      switchKeepProgress: false, // 切换歌曲保持进度
      abCycle: {
        // AB段循环播放
        start: 3,
        end: 9,
        loop: true
      }
    },
    preset: [MusicPreset] // 如果要同时使用默认preset，那么配置是['default', MusicPreset]
  })
  player.plugins.music.mode = 'random'
```

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**
![image](https://github.com/user-attachments/assets/ccc46287-cce1-43e8-8d3c-e694cd644bdf)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@wusp1994 配置写错了，应该是复数的形式 `presets`，不是 `preset`
```
{
  presets: [MusicPreset]
}
```

**Comment by wusp1994** [comment]
![image](https://github.com/user-attachments/assets/04b1cc34-c8be-467f-aee5-0f814f087490)
官方文档就是这样写的哦。截图来自官方文档

**Comment by gemxx** [comment]
@wusp1994 我更新一下文档，文档确实写错了。感谢指正
