### ISSUE TITLE
播放http-flv直播流有问题，会绿屏、暂停、黑屏转圈圈

### ISSUE THREAD

**Issue by Dpandaz** [bytedance/xgplayer#1556]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.19",
    "xgplayer-flv": "^3.0.20-beta.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11
版本 127.0.6533.89（正式版本） （64 位）

**如何复现问题？ How to reproduce the problem?**
使用播放器播放http-flv直播流时，当网络情况不好时会出现

**您期望的播放器正常行为是？ What did you expect to happen?**
希望当网络不好时播放器不要绿屏和暂停，当网络稍微好点之后可以自己追帧追上去，当网络不好加载不出来时停留在之前最后能加载出来的页面。
还希望有个方法可以监控这个直播流，可以知道这个流的具体情况，看是不是因为这个地址现在推流断了。
例如下面的这些参数：
【流状态统计，流开始播放后回调，每秒1次，1个回调参数
s:{
  buf: 当前缓冲区时长，单位毫秒,
  fps: 当前视频帧率,
  abps: 当前音频码率，单位bit,
  vbps: 当前视频码率，单位bit，
  ts:当前视频帧pts，单位毫秒
}】

**实际播放器的表现是？ What actually happened?**
当网络不好时播放器一直转圈圈，有时候会绿屏，有时候会被暂停显示retry

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

代码如下：
```
<template>
  <div>
    Home Page
    <div id="dom-id" class="artplayer-app"></div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue';
import Player from 'xgplayer'
import FlvPlugin from 'xgplayer-flv'
import "xgplayer/dist/index.min.css"

onMounted(() => {
  if (FlvPlugin.isSupported()) {
    const player = new Player({
      id: 'dom-id',
      url: 'XXX',
      isLive: true,
      playsinline: true,
      plugins: [FlvPlugin],
      autoplay: true,
      autoplayMuted: true,
      flv: {
        targetLatency: 2, // 直播目标延迟，默认 5 秒
        maxLatency: 4, // 直播允许的最大延迟，默认 10 秒
        disconnectTime: 0, // 直播断流时间，默认 0 秒，（独立使用时等于 maxLatency）
      }
    })
    player.on('error', (error) => {
      console.log(error)
      // TODO
    })
  }
})

</script>
<style scoped>
.artplayer-app {
  width: 400px;
  height: 300px;
}
</style>
```

情况如下：
![image](https://github.com/user-attachments/assets/e02f3681-3fed-4378-9ead-982a2d6f13cf)
![1723015233205_2F0BE782-7406-4207-819D-8968BAD7D1F8](https://github.com/user-attachments/assets/adc8efed-ce3c-452f-921a-e2127779b9f7)

**Comment by gemxx** [comment]
@Dpandaz 
1. 现在按您提供的配置（maxLatency & targetLatency）是可以实现追帧功能的。
2. 弱网时不希望重拾（暂停），可以配置  `disconnectRetryCount: Infinity` 不进行重连的尝试
3. 绿屏的问题如果有直播流提供，可以尝试看看。
