### ISSUE TITLE
H5上不能默认全屏播放吗？设置了不生效

### ISSUE THREAD

**Issue by zhengcongqi** [bytedance/xgplayer#1561]
fullScreen: true设置了不生效

**Comment by bree323** [comment]
是默认全屏还是有全屏按钮，全屏按钮不生效吖？

**Comment by zhengcongqi** [comment]
可以全屏了，怎么默认横屏播放呀

**Comment by Road-sun** [comment]
> 可以全屏了，怎么默认横屏播放呀
rotateFullscreen
![image](https://github.com/user-attachments/assets/ddae9ff7-4353-4231-8b67-5d88f8bd9700)

**Comment by gemxx** [comment]
@zhengcongqi 全屏插件支持 ScreenOrientation 这个方式锁定屏幕方向。可以配置增加如下参数：
```
{
  fullscreen: {
    useScreenOrientation: true,
    lockOrientationType: 'landscape'
  }
}
```

**Comment by gemxx** [comment]
见官网中fullscreen插件对于 useScreenOrientation 的说明：https://h5player.bytedance.com/plugins/internalplugins/fullscreen.html#usescreenorientation

**Comment by zhengcongqi** [comment]
修复
