### ISSUE TITLE
播放结束时 设置显示控制条

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#1567]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos 13.2.1   chrome  127.0.6533.101

**如何复现问题？ How to reproduce the problem?**
css 旋转全屏 player 监听 ended 事件的回调 调用 player.util.removeClass(player.root, 'xgplayer-inactive'); 报错  
Cannot read properties of undefined (reading 'removeClass')

**您期望的播放器正常行为是？ What did you expect to happen?**
样式全屏可以在播放结束后显示controls 

**实际播放器的表现是？ What actually happened?**
报错Cannot read properties of undefined (reading 'removeClass')

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
目前V2版本不在维护了，请迁移至V3尝试。默认支持ended显示控制条
