### ISSUE TITLE
xgplayer-mp4为什么提示了不兼容，视频还在播放，官网的示例都会直接提示

### ISSUE THREAD

**Issue by syjf** [bytedance/xgplayer#1572]
![image](https://github.com/user-attachments/assets/0fe4821b-55f8-4cb4-b89c-aafc5b2976f8)
![image](https://github.com/user-attachments/assets/066e3eee-934a-4fee-b0aa-c997a685a015)

**Comment by gemxx** [comment]
你的设备不支持HEVC或者浏览器版本太低（chromium version < 108），能播放是音频在播，视频不行

**Comment by syjf** [comment]
> 你的设备不支持HEVC或者浏览器版本太低（chromium version < 108），能播放是音频在播，视频不行

我知道是不支持，我的意思是为什么提示了不支持还能播放，而不会像官网示例那样直接提示不支持不让播放，地址是一样的

**Comment by syjf** [comment]
> 你的设备不支持HEVC或者浏览器版本太低（chromium version < 108），能播放是音频在播，视频不行

而且，这个报错为什么没有触发error事件

**Comment by gemxx** [comment]
你可能是直接用了xgplayer，没有使用xgplayer-mp4? 可以弄个可以访问的环境我看下，目前我只能提供一些猜想

**Comment by syjf** [comment]
> 你可能是直接用了xgplayer，没有使用xgplayer-mp4？可以弄个可以访问的环境我看下，目前我只能提供一些猜想

![image](https://github.com/user-attachments/assets/f1f4f578-4a0e-48bb-8686-2c8ea2fc000c)
我是按文档写的那样用的
![image](https://github.com/user-attachments/assets/1733f904-c1c6-493a-acbf-2c77950be7a2)
zhe'y'g这应该算是用了xgplayer-mp4吧

**Comment by syjf** [comment]
> 你可能是直接用了xgplayer，没有使用xgplayer-mp4？可以弄个可以访问的环境我看下，目前我只能提供一些猜想

![2ce9eaf805a08707a9ff612c888dbdd](https://github.com/user-attachments/assets/51da71e1-4bb5-43b3-b921-998514f236aa)
我的代码，他报不兼容也没有走error

**Comment by gemxx** [comment]
嗯，这确实是走了MP4的插件了，但从源码看不出问题。还得结合视频文件和网络请求一起看，能提供线上环境吗？

**Comment by syjf** [comment]
> 嗯，这确实是走了MP4的插件了，但从源码看不出问题。还得结合视频文件和网络请求一起看，能提供线上环境吗？

提供不了-.-...能告知一下xgplayer-mp4是怎么得知视频的编码信息的吗

**Comment by gemxx** [comment]
可以看下xgplayer-transmuxer mp4 部分
