### ISSUE TITLE
好奇一个 使用 xgplayer-mp4 画面旋转了的问题

### ISSUE THREAD

**Issue by F-howk** [bytedance/xgplayer#1574]
是因为 moov 盒子在最后  并且 range 播放的  视频带有旋转信息的话 就会出现画面旋转了的问题吗

**Comment by gemxx** [comment]
moov -> trak -> tkhd box 中有个matrix 会描述旋转的信息，可以看下。和moov放在视频中的位置无关

**Comment by gemxx** [comment]
> 我的意思就是 matrix 是有效旋转（90°） 使用了 xgplayer-mp4 但是画面没有修正。

了解，现在MP4 remux的时候确实没有读源文件的数据。而是写死了一个值 https://github.com/bytedance/xgplayer/blob/b388c2dca370ed56a3daa6e4f4e86a49e4d07d7a/packages/xgplayer-transmuxer/src/mp4/mp4.js#L294

@F-howk 您方便提供一下测试文件吗？我们尝试修复一下，或者也可以提PR给我们
