### ISSUE TITLE
player.getPIP()

### ISSUE THREAD

**Issue by WaveStill** [bytedance/xgplayer#158]
求指点：
在react中 怎么自定义处罚画中画功能，出发的方法应该怎么调用

**Comment by zhangxin92** [comment]
自定义控件，通过控件上的事件（点击等）出发画中画API

**Comment by WaveStill** [comment]
试着调用了，但是没有出现画中画，只有内置了才会出现，能不能麻烦贴段调用的代码 给参考一下？谢谢了

**Comment by zhangxin92** [comment]
使用最新版本试下 xgplayer@1.1.5-beta.18

**Comment by WaveStill** [comment]
不是版本的问题，我是不知道那几个方法应该怎么调用， 是在事件里面吗？ 事件触发的时候，在事件里面调方法？

**Comment by zhangxin92** [comment]
<div id="mse"></div>
    <script src="//cdn.jsdelivr.net/npm/xgplayer/browser/index.js" charset="utf-8"></script>
    <script type="text/javascript">
      let player=new Player({
        id: 'mse',
        url:'url',
      });
      player.on('pause', () => {
      	player.getPIP()
      })
    </script>

**Comment by zhangxin92** [comment]
贴了段代码，视频暂停的时候调用getPIP

**Comment by WaveStill** [comment]
谢谢

**Comment by WaveStill** [comment]
let player = new Player({
      id: 'mse',
      url: './sheji.mp4',
      pip: true,
      
    });
    player.on('pause',()=>{
      player.getPIP();
    })

index.html:35 Uncaught TypeError: player.getPIP is not a function
    at t.player.on (index.html:35)
    at t.a (index.js:1)
    at HTMLVideoElement.<anonymous> (index.js:1)

**Comment by WaveStill** [comment]
又在react上试了试，和在原生上的结果一样，在方法中的报错一样，player.getPIP is not a function

**Comment by zhangxin92** [comment]
你用的xgplayer版本是?

**Comment by WaveStill** [comment]
"xgplayer": "^1.1.5-beta.18",
    "xgplayer-react": "^1.1.4-beta.4"
l老哥，我刚才用你贴的代码的cdn试了一下，原生上可以了，react上，我用的这版本，不行，我查了npm 好像是最新版本了。

**Comment by zhangxin92** [comment]
用xgplayer吧，xgplayer-react同步更新会慢一些

**Comment by WaveStill** [comment]
谢谢，老哥优秀~
