### ISSUE TITLE
xgplayer-flv.js是否可以兼容到ie11

### ISSUE THREAD

**Issue by AboyL** [bytedance/xgplayer#159]
我们的项目需要兼容使用ie11，使用了m3u8
但是不能播放，在chrome上可以正常播放
看到华为的心声社区使用的是video.js
http://xinsheng.huawei.com/cn/video/index.html
可以再ie11上播放(同一台机器)
想问下这个插件能否兼容到ie11
这样我可以确定一下问题是后端切片导致的，还是前端的问题，需要更换播放器

**Comment by zhangxin92** [comment]
win8以上的IE11可以使用xgplayer-flv.js
华为的心声社区在IE11上用的是flash，不是h5播放器

**Comment by AboyL** [comment]
> win8以上的IE11可以使用xgplayer-flv.js
> 华为的心声社区在IE11上用的是flash，不是h5播放器

qwq说错了，是xgplayer-hls.js

**Comment by zhangxin92** [comment]
一样的，win8以上的IE11可以使用xgplayer-hls.js，都是需要mse支持 ，可以看下兼容性https://caniuse.com/#feat=mediasource

**Comment by AboyL** [comment]
> 一样的，win8以上的IE11可以使用xgplayer-hls.js，都是需要mse支持 ，可以看下兼容性https://caniuse.com/#feat=mediasource

非常感谢
https://github.com/videojs/video.js/issues/4603
在我把video.js的版本降低到6以后加载了flash就解决问题了
