### ISSUE TITLE
移动端全屏事件无效

### ISSUE THREAD

**Issue by huangyingyy** [bytedance/xgplayer#161]
在移动端点击全屏，没有触发requestFullscreen事件，反而进入全屏和退出全屏都触发的是exitFullscreen退出全屏事件是怎么回事呢？

**Comment by zhangxin92** [comment]
什么手机和浏览器

**Comment by huangyingyy** [comment]
> 什么手机和浏览器

用的是谷歌浏览器手机端的iphone7

**Comment by zhangxin92** [comment]
描述问题无法复现
