### ISSUE TITLE
移动端不支持websocket-flv

### ISSUE THREAD

**Issue by iLinuxs** [bytedance/xgplayer#162]
websocket-flv在PC端可以，希望移动端也可以支持一下websocket-flv

**Comment by zhangxin92** [comment]
移动端对mse兼容性不好，不适合使用flv格式

**Comment by iLinuxs** [comment]
> 移动端对mse兼容性不好，不适合使用flv格式

有个nodePlayer，他们好像支持flv，是直接绘制到canvas，不过要收费，商用版体验还是挺不错的
