### ISSUE TITLE
播放m3u8文件，有画面无声音；

### ISSUE THREAD

**Issue by guojun-dou** [bytedance/xgplayer#1641]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.19

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10,chrome

**如何复现问题？ How to reproduce the problem?**
播放m3u8文件，有画面无声音；
文件地址： https://vrar-obs-production.obs.cn-north-4.myhuaweicloud.com:443/ssc-develop/video/4071176613332864/1702431672067/阿里互动如何让用户吃的更有趣.m3u8

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放m3u8文件；

**实际播放器的表现是？ What actually happened?**
缺少音频播放；

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by divikshrivastava** [comment]
Can I work on fixing this issue ?

**Comment by divikshrivastava** [comment]
@gemxx @leecade @leeight

**Comment by guojun-dou** [comment]
找到原因了，音频编码不是AAC的就无法解析播放；
