### ISSUE TITLE
xgplayer-flv插件已配置 preferMMS: true ，是否能在ios接收http-flv流直播?

### ISSUE THREAD

**Issue by jaelys** [bytedance/xgplayer#1651]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.20

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios 17.6 、 18.1  浏览器 : Safari  、 微信端

**如何复现问题？ How to reproduce the problem?**
直播 http-flv 流 h.264 + aac , 使用xgplayer-flv插件，配置flv : { preferMMS: true }

**您期望的播放器正常行为是？ What did you expect to happen?**
我以为插件已支持 ios 7.1 mms ，应该可以正常播放http-flv直播流(受控的mse)

**实际播放器的表现是？ What actually happened?**
显示未支持的音视频格式，尝试刷新

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@jaelys flv插件是支持的iOS MMS的，播放器配置发一下或者有没有可以线上看的demo？

**Comment by jaelys** [comment]
> @jaelys flv插件是支持的iOS MMS的，播放器配置发一下或者有没有可以线上看的demo？

我使用官网示例修改为3.0.20版本
```
<script src="https://unpkg.byted-static.com/xgplayer/3.0.20/dist/index.min.js" charset="utf-8"></script>  
 <script src="https://unpkg.byted-static.com/xgplayer-flv/3.0.20/dist/index.min.js" charset="utf-8"></script>
```

设置中加入 
```
url: 'https://xxx.xxx.xxx/123456789/main.live.flv', 
flv: { perferMMS: true },
```
 PC端没问题，使用ios手机端浏览器或微信端就会报不支持的格式，请刷新
 流地址是没问题的，使用过其他wasm解决机制的播放器是能播放的

**Comment by gemxx** [comment]
方便发一下示例中的flv文件吗？iOS硬解播放对编码有一定的要求

**Comment by gemxx** [comment]
@jaelys flv 配置 perferMMS  修改为 preferMMS

**Comment by jaelys** [comment]
> @jaelys flv 配置 perferMMS 修改为 preferMMS

已在 ios 17.6  18.1 微信 Safari  都能正常顺畅的播放，感谢大佬及伟大的项目
