### ISSUE TITLE
读取NALu单元数据的问题

### ISSUE THREAD

**Issue by none110** [bytedance/xgplayer#166]
直播的时候需要计算推流端和拉流端的时间差
请问，可以读取H264的SEI信息嘛？
如何读取？谢谢

**Comment by zhangxin92** [comment]
目前播放器没有这个功能，近期会支持

**Comment by none110** [comment]
您好，请问，有规划时间点吗？

**Comment by leonardoFu** [comment]
可以监听播放器事件player.on('SEI_PARSED')获取到
