### ISSUE TITLE
请问如何使控制栏常驻，之前有closeInactive配置，V3版本代码里并没有这个配置

### ISSUE THREAD

**Issue by newbeea** [bytedance/xgplayer#1661]
请问如何使控制栏常驻，之前有closeInactive配置，V3版本代码里并没有这个配置
播放前和播放中几秒后blur后都常驻
谢谢

**Comment by newbeea** [comment]
找到了这个 closeDelayBlur ，可以播放后常驻
初始显示播放还没找到

**Comment by gemxx** [comment]
@newbeea 看一下controls的配置： `
      controls: {
      	initShow: true,
        autoHide: false,
      },
`

**Comment by newbeea** [comment]
可以了感谢

**Comment by newbeea** [comment]
> 请问如何使控制栏常驻，之前有closeInactive配置，V3版本代码里并没有这个配置 播放前和播放中几秒后blur后都常驻 谢谢

额。。原来看成v2文档了
