### ISSUE TITLE
前端使用xgplayer-hls.js播放m3u8时。参数指定startTime，仍会下载第一个切片，然后才下载startTime所在的切片。这个能处理下吗？

### ISSUE THREAD

**Issue by schwinnn** [bytedance/xgplayer#1664]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.10

**Comment by gemxx** [comment]
@schwinnn 可以处理，我会在3.0.21版本进行适配。hls.js 支持配置下载的开始时间 [startPosition](https://github.com/video-dev/hls.js/blob/master/docs/API.md#startposition)
