### ISSUE TITLE
浏览器中切换为移动端模式后不能正常播放视频(浏览器pc模式下可以正常显示播放)

### ISSUE THREAD

**Issue by 343058360** [bytedance/xgplayer#167]
浏览器中切换为移动端模式后不能正常播放视频,Xgplayer元素中video一直在转圈,浏览器console中无报错

**Comment by zhangxin92** [comment]
移动端使用需要添加白名单和内联模式
http://h5player.bytedance.com/config/#%E7%99%BD%E5%90%8D%E5%8D%95
http://h5player.bytedance.com/config/#%E5%86%85%E8%81%94%E6%A8%A1%E5%BC%8F

**Comment by 343058360** [comment]
> 移动端使用需要添加白名单和内联模式
> [http://h5player.bytedance.com/config/#%E7%99%BD%E5%90%8D%E5%8D%95 ](http://h5player.bytedance.com/config/#%E7%99%BD%E5%90%8D%E5%8D%95)
> [http：//h5player.bytedance。 COM /配置/＃％E5％86％85％E8％81％94％E6％A8％A1％E5％BC％8F](http://h5player.bytedance.com/config/#%E5%86%85%E8%81%94%E6%A8%A1%E5%BC%8F)

添加了白名单和内联样式,移动端仍然不能正常显示视频.  [我的环境是vue,然后使用了清晰度切换配置],在浏览器下可以正常显示和播放视频.

**Comment by zhangxin92** [comment]
播放器什么版本？播什么格式的视频
