### ISSUE TITLE
vue环境下添加清晰度配置后, 移动端不能获取视频地址(pc端可以正常播放)

### ISSUE THREAD

**Issue by 343058360** [bytedance/xgplayer#168]
this.$api.getVido().then(data => {
      let mvdetails = data;
      for (let [key, val] of Object.entries(mvdetails.brs)) {
        this.config.url.push({src: val, type: 'video/mp4'});
        this.resourceReady.push({name: key, url: val})
      }
    });

watch: {
    resourceReady(newValue) {
      this.Player.emit('resourceReady', newValue);
    }
  },

**Comment by zhangxin92** [comment]
清晰度切换可以参考http://h5player.bytedance.com/examples/ 实现
