### ISSUE TITLE
关于以视频第一帧为封面图的需求

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#169]
在未配置封面图的时候，可否以视频第一帧为默认封面。
效果可参考：https://www.runoob.com/try/try.php?filename=tryhtml5_video_all

**Comment by myseemylife** [comment]
播放第一个I帧，然后停在那里？客户点进去就继续播？

**Comment by wj20160318** [comment]
官网说的是，初始化不会生成video和拉取数据，所以不会有这个效果。
如果初始化就生成video，并且拉取部分数据填给video（mse buffer），应该就是这个效果了，这个应该是浏览器对视频的处理。
这个东西可否开放给开发者选择，仅仅是提个意见。

**Comment by bethe-light** [comment]
> 在未配置封面图的时候，可否以视频第一帧为默认封面。
> 效果可参考：https://www.runoob.com/try/try.php?filename=tryhtml5_video_all

针对该需求，未配置封面图时，我们添加了一个配置项 设置 videoInit: ture 即可满足了哈

**Comment by bethe-light** [comment]
> 官网说的是，初始化不会生成video和拉取数据，所以不会有这个效果。
> 如果初始化就生成video，并且拉取部分数据填给video（mse buffer），应该就是这个效果了，这个应该是浏览器对视频的处理。
> 这个东西可否开放给开发者选择，仅仅是提个意见。

好提议，目前已添加  videoInit 配置项， 默认为false，可选 true| false

**Comment by wj20160318** [comment]
非常感谢。

**Comment by jinsom** [comment]
> > 官网说的是，初始化不会生成video和拉取数据，所以不会有这个效果。
> > 如果初始化就生成video，并且拉取部分数据填给video（mse buffer），应该就是这个效果了，这个应该是浏览器对视频的处理。
> > 这个东西可否开放给开发者选择，仅仅是提个意见。
> 
> 好提议，目前已添加 videoInit 配置项， 默认为false，可选 true| false

请问这个是 哪个版本可以使用了，我刚刚试了最新版本的但是还是不行。
