### ISSUE TITLE
如何监听自动播放 已经失败了

### ISSUE THREAD

**Issue by JohnApache** [bytedance/xgplayer#170]
在不静音的情况 ，我尝试监听这个error 事件 ， 当自动播放失败的时候 再去静音播放， 但是代码并没有执行到这个 事件监听函数里面，
player.on('error', (e) => {
        console.log(e);
})
我该如何 监听 自动播放已经失败了？

**Comment by wj20160318** [comment]
自动播放失败应该不会触发error事件，我看了下源码，自动播放失败会触发'autoplay was prevented'事件，可以自己加一个插件。

import Player from 'xgplayer'

function fn () {
  this.on('autoplay was prevented', () => {
    console.log('test')
  })
}

Player.install('fn', fn)

我试了下，是可以的

**Comment by JohnApache** [comment]
> 自动播放失败应该不会触发error事件，我看了下源码，自动播放失败会触发'autoplay was prevented'事件，可以自己加一个插件。
> 
> import Player from 'xgplayer'
> 
> function fn () {
> this.on('autoplay was prevented', () => {
> console.log('test')
> })
> }
> 
> Player.install('fn', fn)
> 
> 我试了下，是可以的

我尝试了 一下你的方法  在chrome 环境下的确是可以的  但是 在 mac 的 safari 环境下  不会触发 这个 'autoplay was prevented'事件， safari 对于autoplay 是更底层的报错

**Comment by zhangxin92** [comment]
safari下暂时无法监听

**Comment by huangjiaxing** [comment]
我自己是这么做的，先设置
```
autoplay: true,
autoplayMuted: true,
```
然后尝试在complete事件中
```
adPlayer.once('complete', () => {
      try {
        adPlayer.play()  // 尝试再次执行播放
        setTimeout(() => {  // 500毫秒收检测
          if (!adPlayer.hasStart && adPlayer.currentTime === 0) {  // hasStart返回false，并且播放时间还是0，那么就可以认为自动播放失效了
            isAutoPlay = false;
          }
        }, 500)
      } catch (e) {
        alert(e)
      }
    })
```

目前在主流浏览器中运行还可以
