### ISSUE TITLE
下一集或切换播放地址会使实际播放倍速与ui显示倍速不一致

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#171]
1、非x1倍速播放视频
2、点击播放下一集或手动切换播放地址
3、下一集或切换后的视频会以x1倍速播放，但是ui显示倍速会是之前的值

建议：切换视频地址后，重置ui显示倍速为x1，或者设置实际播放速度为之前的值

**Comment by zhangxin92** [comment]
已做相应修改，感谢issue!

**Comment by ynzy** [comment]
你是如何做手动切换播放的,可以看一下代码吗
