### ISSUE TITLE
xgplayer-flv.js 提供的switchUrl方法不能生效

### ISSUE THREAD

**Issue by JohnApache** [bytedance/xgplayer#172]
切换视频直播流  的时候，我使用挂载再player上面的切换地址的方法
flvplayer.switchURl('some.flv'); 

 switchURL (url) {
    const player = this
    const flvPlayer = player.__flv__
    player.config.url = url
    if (!player.config.isLive) {
      flvPlayer.onDefinitionChange(url, player.config.retryTimes)
    } else {
      const tempFlvPlayer = Flv.createPlayer(player.flvOpts)
      flvPlayer.destroy()
      player.createInstance(tempFlvPlayer)
      player.__flv__ = tempFlvPlayer
    }
  }

我从源码里 找到 了player.switchUrl的这个动态切换视频地址的方法  发现并不能生效  而且这个代码也是有问题的  createPlayer传入的 配置文件 是flvOpts  但是 前面改的却是config对象的url ，我尝试了 将flvOpts的url 也修改成正确的url，
 switchURL (url) {
    const player = this
    const flvPlayer = player.__flv__
    player.config.url = url;
    player.flvOpts.url = url;
    if (!player.config.isLive) {
      flvPlayer.onDefinitionChange(url, player.config.retryTimes)
    } else {
      const tempFlvPlayer = Flv.createPlayer(player.flvOpts)
      flvPlayer.destroy()
      player.__flv__ = tempFlvPlayer
      player.createInstance(tempFlvPlayer)
      
    }
  }

 页面能够正常运行  但是视频 却没有切换成功 ， 依旧是旧的视频， 希望能够修复一下 这个api 。另外我该如何优雅的切换直播视频地址呢？

**Comment by zhangxin92** [comment]
清晰度切换方法 [参见](http://h5player.bytedance.com/config/#%E6%B8%85%E6%99%B0%E5%BA%A6%E5%88%87%E6%8D%A2%E9%85%8D%E7%BD%AE)
flv切换清晰度不成功问题已在源码中修复，感谢issue!
