### ISSUE TITLE
启动弹幕后，click触发视频暂停/播放功能失效

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#174]
启用弹幕功能后，click到的是弹幕容器。
参考https://github.com/bytedance/danmu.js/blob/master/src/danmu.js源码43-64行，
此时，将由video主动触发一次click事件，
但是经我测试，这个主动触发click事件的行为并不会改变document.activeElement为video。
参考https://github.com/bytedance/xgplayer/blob/master/packages/xgplayer/src/control/pc.js源码127-130行，
if (document.activeElement !== player.video) {
      player.video.focus()
      return
    }
click触发视频暂停/播放功能将会失效

**Comment by wj20160318** [comment]
dblclick之所以可以，是因为dblclick在触发之前会先触发两次click
参考pc.js源码
第一次click，焦点不在video，主动将焦点放在video
第二次click，video又失去焦点，又主动将焦点放在video
此时触发dblclick，焦点也正好在video

**Comment by zhangxin92** [comment]
已做修改，感谢issue！
