### ISSUE TITLE
使用xgplayer-hls.js时，希望可以提供选择是否使用hls.js的配置项

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#175]
`if ((Player.sniffer.device === 'mobile' && navigator.platform !== 'MacIntel' && navigator.platform !== 'Win32') || this.browser.indexOf('Safari') > -1) 
{
      return
}`
该插件通过此条件来判断是否使用hls.js。
希望可以提供配置项，只要浏览器支持mse就使用hls.js，如果不支持，才用原生video播放。
希望有这个配置的原因是，有些移动端浏览器既支持mse，又支持hls协议，上面的条件基本都会导致使用原生播放，但是原生的容错率可能比hls.js低，就会造成使用hls.js能播，原生却不能播的情况。
正好我这边在小米6（其他小米系列未测试）原生浏览器遇到了这种情况。

**Comment by zhangxin92** [comment]
感谢建议！已在xgplayer-hls.js@1.1.7支持，使用方式：
设置 useHls: true 使用hls.js
设置 useHls: false 不使用hls.js
不设置useHls时由代码内部判断决定
