### ISSUE TITLE
mp4的视频没有发送xhr请求，而是发送原生的media请求

### ISSUE THREAD

**Issue by jialuLiu** [bytedance/xgplayer#177]
默认都是 media请求，在示例中选的是西瓜mp4,没有选web原生
而且request里的 【Range: bytes=2195456-  】 end内容一直是空。
是有什么配置或者对mp4视频有要求吗？ 视频我已经用FFmpeg转成fmp4格式了

**Comment by zhangxin92** [comment]
视频源用普通mp4就好，不用转成fmp4

**Comment by jialuLiu** [comment]
> fmp4

是跨域的问题么。我用普通mp4都是发送的media请求，请问有什么特殊的配置么？我是在示例的界面上配置的。目前还没有找到怎么解决~

**Comment by zhangxin92** [comment]
需要配跨域，官网插件说明处有写 http://h5player.bytedance.com/plugins/#xgplayer-mp4

**Comment by jialuLiu** [comment]
> 需要配跨域，官网插件说明处有写 http://h5player.bytedance.com/plugins/#xgplayer-mp4

我觉得我这边已经处理了跨域问题。我再尝试一下本地构建服务播放会不会有问题

**Comment by jialuLiu** [comment]
本地测试可以发送xhr请求。跨域出现问题还在尝试研究
