### ISSUE TITLE
使用player.src切换播放地址后，player.config.url未跟随变化

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#178]
当使用xgplayer-hls.js，并且满足使用hls.js插件的条件时，改变播放地址，源码中有重新设置player.config.url，其他地方暂时没看到。希望各个地方保持一致，要么都不重新设置，要么都重新设置

**Comment by zhangxin92** [comment]
"其他地方"是指?

**Comment by wj20160318** [comment]
比方说官网MP4的例子，延时改变src，然后输出player.config.url，会是src改变之前的值，而不是之后的值

**Comment by zhangxin92** [comment]
已对齐，不会重新设置
