### ISSUE TITLE
window 7 64bit demo启动问题

### ISSUE THREAD

**Issue by liyang007700** [bytedance/xgplayer#18]
win7 64bit执行babel-node app.js, 会报missing message.js错误。
npm i -save-dev @babel/core 和 npm i -save-dev @babel/node后，问题解决。难道头条的前端全部配mac吗。。。

**Comment by LinFeng1997** [comment]
Question Translate：
win7 64bit run `babel-node app.js`,then throw a error missing message.js.

If run 
`npm i -save-dev @babel/core @babel/node`,the problem solved.
