### ISSUE TITLE
在部分机型上存在需要下载多个ts文件后才会开始播放的情况

### ISSUE THREAD

**Issue by AboyL** [bytedance/xgplayer#180]
场景:webview

描述:使用xgplayer-hls.js开发webview,在大部分机型中可以正常播放，在vivo x7上，播放很慢
经过抓包分析，发现获取的数据包的速度大致一样，但是vivo x7下，需要获取超过3个ts文件后，才会进行播放。
每个ts文件的下载速度都在3s内，第一个ts文件下载速度一般都在2s左右可以下载完毕。
目前只发现这一款机型存在这个问题，测试过wifi与移动，电信的多种流量网络环境，均存在次问题

xgplayer版本:
1.1.5

xgplayer-hls.js
1.1.5@beta-1

希望可以给一个解答或者思路，谢谢！！！

**Comment by zhangxin92** [comment]
移动端原生video支持直接播放hls，所以xgplayer-hls.js在移动端环境下关闭了相关解析功能；可以用配置项 useHls: true 打开hls解析功能尝试 (xgplayer-hls.js@1.1.7)

**Comment by AboyL** [comment]
> 移动端原生video支持直接播放hls，所以xgplayer-hls.js在移动端环境下关闭了相关解析功能；可以用配置项 useHls: true 打开hls解析功能尝试 (xgplayer-hls.js@1.1.7)

非常感谢！
