### ISSUE TITLE
[BUG] xgplayer-flv.js 不支持 flv.js 参数 

### ISSUE THREAD

**Issue by Pingren** [bytedance/xgplayer#182]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

1.1.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Mac & Chrome

**如何复现问题？ What did you do?**

传入 flv.js 支持的参数（例如 **enableStashBuffer:false**)，未生效。

**您期望的播放器正常行为是？ What did you expect to happen?**

根据文档：https://h5player.bytedance.com/plugins/#xgplayer-flv-js
其中：xgplayer-flv.js插件在xgplayer播放器基础配置的基础上还具有一些可选的特殊配置项。

**实际播放器的表现是？ What actually happened?**

查看 xgplayer-flv.js 源码

in index.js:
```
    player.once('complete', () => {
      player.__flv__ = Flv.createPlayer(this.flvOpts)
      player.createInstance(player.__flv__)
    })
```

in flv.js:
```
function createPlayer(mediaDataSource, optionalConfig) {
...
        case 'flv':
            return new FlvPlayer(mds, optionalConfig);
...
}
```

in flv-player.js:

```
class FlvPlayer {
  constructor (mediaDataSource, config) {
  ...
    this._config = createDefaultConfig()
    if (typeof config === 'object') {
      Object.assign(this._config, config)
    }
  ...
  }
}
```

Flv.createPlayer 内只传入一个参数，因此 optionalConfig 和 config 始终为 undefined。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
已在xgplayer-flv.js@1.1.7支持，使用可参考：

let player = new FlvJsPlayer({
  id: 'xg',
  url: '//abc.com/**/*.flv',
  hasVideo: true,
  hasAudio: true,
  flvOptionalConfig: {
    enableWorker: true
  }
})

**Comment by Pingren** [comment]
感谢！
