### ISSUE TITLE
xgplayer-vue灰色的静止画面能取消吗

### ISSUE THREAD

**Issue by freeblockLuxe** [bytedance/xgplayer#185]
xgplayer-vue 在点击播放或自动播放前会有一个灰色的静止画面，然后才是红色主题的等待动画
可否直接显示主题等待动画，以免用户不知所措

**Comment by zhangxin92** [comment]
可配置封面图或初始化显示视频首帧
http://h5player.bytedance.com/config/#%E5%B0%81%E9%9D%A2%E5%9B%BE
http://h5player.bytedance.com/config/#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%98%BE%E7%A4%BA%E8%A7%86%E9%A2%91%E9%A6%96%E5%B8%A7
