### ISSUE TITLE
初始化显示视频首帧无法生效

### ISSUE THREAD

**Issue by jinsom** [bytedance/xgplayer#187]
如题，配置了videoInit: true，无法生效。没有配置poster

**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
1.15

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows  谷歌浏览器

**Comment by zhangxin92** [comment]
可在1.1.7或2.0.0版本使用该功能
