### ISSUE TITLE
如何支持无缝切换多个视频？

### ISSUE THREAD

**Issue by spademan** [bytedance/xgplayer#188]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
指不同清晰度之间进行切换吗？xgplayer对mp4、flv、hls、dash都实现了无缝切换清晰度，可以尝试一下

**Comment by spademan** [comment]
@zhangxin92 不是清晰度，是比如说我有a视频，b视频，我想播放完a视频马上播b视频，用户无感知那种切换

**Comment by zhangxin92** [comment]
应用场景较少，暂时没有这个功能的支持计划

**Comment by insane018** [comment]
请问怎么解决的 我现在也有这个应用场景

**Comment by zhanglei1032** [comment]
我也需要这个功能

**Comment by Eric124120** [comment]
> @zhangxin92 不是清晰度，是比如说我有a视频，b视频，我想播放完a视频马上播b视频，用户无感知那种切换

请问这个功能实现了么？

**Comment by XiaotaoTTTtian** [comment]
这个功能实现了吗，楼主
