### ISSUE TITLE
xgplayer-mp4下载来不及播放会暂停且无法接着播放

### ISSUE THREAD

**Issue by w611363303798** [bytedance/xgplayer#189]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
^1.1.4-beta.43

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos  chrome

**如何复现问题？ What did you do?**
network可以下载看到来不及播放时自动暂停，请求会继续下载之后未完成的，但没有新资源请求，需要点击播放重新触发。还有range区间太小了，目前播放体验远不及原生media请求

**Comment by zhangxin92** [comment]
自动暂停需重新触发问题已在xgplayer-mp4@1.1.6进行了优化。欢迎贡献PR！
