### ISSUE TITLE
rotate

### ISSUE THREAD

**Issue by XinJiangQingMang** [bytedance/xgplayer#190]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新版

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios  safari

**如何复现问题？ What did you do?**
``` 
"rotate": {   //视频旋转按钮配置项
        innerRotate: false, //只旋转内部video
        clockwise: false // 旋转方向是否为顺时针
    },
```
**您期望的播放器正常行为是？ What did you expect to happen?**
如果配置视频旋转后 ，控制条可见或者有按钮恢复旋转

**实际播放器的表现是？ What actually happened?**
旋转后无法操作恢复

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by mcmf** [comment]
还有直播  配置islive无效  intfy

**Comment by zhangxin92** [comment]
试下 xgplayer@2.1.8 xgplayer-flv.js@2.0.0，优化了相关问题

**Comment by lizy0329** [comment]
> 试下 xgplayer@2.1.8 xgplayer-flv.js@2.0.0，优化了相关问题

2.3.7 版 用了 player.rotate(true, true, 1); 视频是旋转了，但是控制条却没跟着旋转，这个要怎么解决？采用了样式全屏的方案

**Comment by yexinjia** [comment]
> 
> 
> > 试下 xgplayer@2.1.8 xgplayer-flv.js@2.0.0，优化了相关问题
> 
> 2.3.7 版 用了 player.rotate(true, true, 1); 视频是旋转了，但是控制条却没跟着旋转，这个要怎么解决？采用了样式全屏的方案

我也出现了同样的问题，请问要怎么解决？

**Comment by lizy0329** [comment]
> > > 试下 xgplayer@2.1.8 xgplayer-flv.js@2.0.0，优化了相关问题
> > 
> > 
> > 2.3.7 版 用了 player.rotate(true, true, 1); 视频是旋转了，但是控制条却没跟着旋转，这个要怎么解决？采用了样式全屏的方案
> 
> 我也出现了同样的问题，请问要怎么解决？

只能检测旋转的同时，切换一下样式

**Comment by gemxx** [comment]
在V2的版本[2.32.6](https://www.npmjs.com/package/xgplayer/v/2.32.6)完成了修复，修复内容主要是限制旋转时的宽高不超出浏览器视口宽高
