### ISSUE TITLE
What's the difference between 1.1.7 (github)and 2.0(npm)

### ISSUE THREAD

**Issue by levi0214** [bytedance/xgplayer#191]
I noticed that xgplayer on npm is version `2.0.3`, so what's the difference between `1.1.7` and `2.0.3` and which one should I use? I can't find it in documents.

**Comment by zhangxin92** [comment]
2.0开始支持开发者自定义样式 http://h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
