### ISSUE TITLE
自定义皮肤引用白屏

### ISSUE THREAD

**Issue by mcmf** [bytedance/xgplayer#192]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.0.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome / 微信浏览器

**如何复现问题？ What did you do?**
自定义皮肤问题

**您期望的播放器正常行为是？ What did you expect to happen?**
如何使用

**实际播放器的表现是？ What actually happened?**
白屏

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

```
使用 `npx xgplayer eject src/themes`创建自定义皮肤，然后引用的时候也不报错，但是播放页面白屏

 - 引用方法 
`import Player from 'xgplayer';
import '@themes/.xgplayer/skin/index.js';`
```

**Comment by mcmf** [comment]
样式没有引入进来是什么情况

**Comment by zhangxin92** [comment]
svg和sass的loader有配置吗？

**Comment by mcmf** [comment]
就是@import index.scss的样式无效  单独在模板文件里写scss是好的

**Comment by mcmf** [comment]
我在vue cli3里使用的  求指导

**Comment by zhangxin92** [comment]
你没有回答我的问题，svg和sass的webpack loader有做配置吗？不配置不行哈，因为eject出来的样式文件里有这两种文件，没有相应loader是没法正常运行的

**Comment by mcmf** [comment]
> 你没有回答我的问题，svg和sass的webpack loader有做配置吗？不配置不行哈，因为eject出来的样式文件里有这两种文件，没有相应loader是没法正常运行的
我只是执行了安装   配置不太会

**Comment by mcmf** [comment]
svg不知道如何配置但是有报错  刚搜了一圈没有

**Comment by mcmf** [comment]
```
  // css相关配置
  css: {
    // 是否使用css分离插件 ExtractTextPlugin
    extract: isProd() ? true : false,
    // 开启 CSS source maps?
    sourceMap: isProd() ? true : false,
    // css预设器配置项
    loaderOptions: {
      sass: {
        data: `@import '~@/themes/.xgplayer/skin/style/index.scss';`,
      },
    },
    // 启用 CSS modules for all css / pre-processor files.
    modules: false,
  },
```

**Comment by mcmf** [comment]
```
  chainWebpack: (config) => {
    // module

    // style-resources-loader
    const types = ['vue-modules', 'vue', 'normal-modules', 'normal'];
    types.forEach((type) =>
      addStyleResource(config.module.rule('less').oneOf(type))
    );

```
