### ISSUE TITLE
iPhone Safari上无法点击全屏和音量

### ISSUE THREAD

**Issue by levi0214** [bytedance/xgplayer#193]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.0.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS 12.3, Safari

**如何复现问题？ What did you do?**
点击全屏

**您期望的播放器正常行为是？ What did you expect to happen?**
全屏

**实际播放器的表现是？ What actually happened?**
没有反应

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

 相关代码：

```html
<script src="//cdn.jsdelivr.net/npm/xgplayer/browser/index.js" charset="utf-8"></script>
<script src="//cdn.jsdelivr.net/npm/xgplayer-mp4/browser/index.js" charset="utf-8"></script>
```

```javascript
let player = new Player({
  id: "xg",
  url: "/demo.mp4",
  poster: "/demo.jpg",
  playsinline: true,
  fluid: true,
  enterLogo: {
    url: '/logo.png',
    width: 150,
    height: 150
  },
  enterBg: { //视频加载页背景
    color: 'rgba(0,0,0,0.87)'
  },
  enterTips: { //视频加载页加载特效
    background: 'linear-gradient(to right, rgba(0,0,0,0.87), #3D96FD, rgba(86,195,248), #3D96FD, rgba(0,0,0,0.87))'
  },
  whitelist: [""]
});
```

**Comment by levi0214** [comment]
在版本1.1.7 下正常

**Comment by zhangxin92** [comment]
可以再试下全屏功能，我们这边测试是正常的。另外，移动端建议通过ignores: ['volume'] 关闭音量控件

**Comment by huangjiaxing** [comment]
遇到了同样的问题，全屏和声音等 controls上的按钮都没有效果

**Comment by huangjiaxing** [comment]
> 可以再试下全屏功能，我们这边测试是正常的。另外，移动端建议通过ignores: ['volume'] 关闭音量控件

你们测试的时候，是在safari里面，并且设置了playsinline: true吗

**Comment by Nekosandesu** [comment]
> 遇到了同样的问题，全屏和声音等 controls上的按钮都没有效果

音量是鼠标悬浮上去才会显示音量条，点击是切换静音的，所以移动端根本调不出音量条，目前没找到改变这种交互方式的配置。

**Comment by zhangxin92** [comment]
> > 遇到了同样的问题，全屏和声音等 controls上的按钮都没有效果
> 
> 音量是鼠标悬浮上去才会显示音量条，点击是切换静音的，所以移动端根本调不出音量条，目前没找到改变这种交互方式的配置。

移动端一般使用硬件按钮调节音量，手机上使用音量条交互不友好哈
