### ISSUE TITLE
mp4预加载时间控制，在iOS Safari上没有生效

### ISSUE THREAD

**Issue by levi0214** [bytedance/xgplayer#194]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.0.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS 12.3, Safari

**如何复现问题？ What did you do?**
通过CDN引用xgplayer/xgplayer-mp4，配置preloadTime: 15，白名单为空，点击播放MP4格式的视频

**您期望的播放器正常行为是？ What did you expect to happen?**
预加载15秒左右

**实际播放器的表现是？ What actually happened?**
全部加载完了视频（3分钟）

**Comment by levi0214** [comment]
有人吗

**Comment by zhangxin92** [comment]
iOS系统不支持MSE，无法使用xgplayer-mp4的预加载时间功能

**Comment by levi0214** [comment]
@zhangxin92 

谢谢！
当我在iOS safari中使用原生的<video>元素（没有用播放器）时，我发现视频一旦开始播放，即使暂停，也会被全部加载完，请问我有什么办法避免吗？

**Comment by zhangxin92** [comment]
可以用下原生video的preload参数
