### ISSUE TITLE
对白名单的疑问

### ISSUE THREAD

**Issue by levi0214** [bytedance/xgplayer#195]
官方文档说：

> 移动端使用西瓜播放器需要配置 白名单。

> 播放器在手机上会关掉自定义UI功能，开发者可以通过白名单的方式开启此项功能。

我觉得有点困惑，想问一下：

1. 是否所有移动端都要配置白名单才能使用西瓜视频？还是说只有在自定义UI的时候才需要？
2. 哪些行为算自定义UI？配置loading画面算不算？
3. 白名单的定义方式可否给一些例子？譬如如果我想让所有移动端生效，我是不是可以配置成：`whitelist: [(ua)=>{ return /Android|webOS|iPhone|iPad/gi.test(ua); }]` ？

**Comment by wj20160318** [comment]
说下我的个人使用经验：
1.只有在使用自定义UI时需要配置白名单
2.所有外观包括loading都算自定义UI
3.whitelist: [(ua)=>{ return true }]就都开启了白名单

**Comment by levi0214** [comment]
@wj20160318  谢谢！

**Comment by lizy0329** [comment]
> 说下我的个人使用经验：
> 1.只有在使用自定义UI时需要配置白名单
> 2.所有外观包括loading都算自定义UI
> 3.whitelist: [(ua)=>{ return true }]就都开启了白名单

如果不开启白名单是不是就无法运行这个播放器？还是说可以运行，只不过是自定义UI不生效而已？

**Comment by zhangxin92** [comment]
@lizy0329 移动端不开启白名单会默认采用原生video样式

**Comment by guairenke** [comment]
whitelist: [(ua)=>{ return true }] 
加完之后安卓手机不好用啊
但是ios不设置也会生效！！！

**Comment by guairenke** [comment]
@levi0214  请问白名单为题解决了吗？ 我的是ios自定义样式会出现可以使用 但是安卓怎么都不管用！！！

**Comment by zhangxin92** [comment]
> @levi0214 请问白名单为题解决了吗？ 我的是ios自定义样式会出现可以使用 但是安卓怎么都不管用！！！

在安卓上播放器会被部分浏览器劫持，可以了解下相关资料
