### ISSUE TITLE
使用过程中没有样式,界面全部变样

### ISSUE THREAD

**Issue by chenlongcheck** [bytedance/xgplayer#197]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
能详细描述下使用过程吗？使用了自定义样式？

**Comment by chenlongcheck** [comment]
直接按照官网的步骤下的包并使用,而且官网的音乐播放器也没有样式http://h5player.bytedance.com/examples/?type=vod&plugin=xg-music,
官网步骤中也没有提示是否需要手动引入样式

**Comment by chenlongcheck** [comment]
直接按照官网的步骤下的包并使用，而且官网的音乐播放器也没有样式http://h5player.bytedance.com/examples/?type=vod&plugin=xg-music , 
官网步骤中也没有提示是否需要手动引入样式






------------------ 原始邮件 ------------------
发件人: "zhangxin92"<notifications@github.com>;
发送时间: 2019年7月18日(星期四) 晚上7:07
收件人: "bytedance/xgplayer"<xgplayer@noreply.github.com>;
抄送: "往往"<1026907274@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bytedance/xgplayer] 使用过程中没有样式,界面全部变样 (#197)




能详细描述下使用过程吗？使用了自定义样式？

**Comment by zhangxin92** [comment]
最新版本是xgplayer@2.1.12  xgplayer-music@2.0.0  可以再试下

**Comment by BObo-come** [comment]
请问这个问题解决了吗，我也遇到了
