### ISSUE TITLE
m3u8视频播放总时间不显示

### ISSUE THREAD

**Issue by DQSLILI** [bytedance/xgplayer#199]
官方演示是可以显示总时间的，但自己使用不显示，将播放器js版本换到1.1.7,总时间显示正常,1.1.7以上版本总时间不显示
![5ad4ca67fc6c4b0d](https://user-images.githubusercontent.com/39544944/61178565-e190b700-a621-11e9-9f15-e7c2f75f4c67.jpg)

**Comment by zhangxin92** [comment]
能提供下测试用的m3u8点播流吗？

**Comment by DQSLILI** [comment]
> 能提供下测试用的M3U8点播流吗？

http://1717.0ju.cc/data/migu/8b6eb25166ec4446d3f71a8de2243171.m3u8

**Comment by zhangxin92** [comment]
可以试下xgplayer@2.1.1版本

**Comment by DQSLILI** [comment]
> 可以试下xgplayer@2.1.1版本

可以了
我有个建议，如果把进度条长度缩短点，别让他横向充满整个播放器，就好看多了。大部分播放器的进度条都是短于播放器宽度的

**Comment by zhangxin92** [comment]
好的，感谢建议，我们评估后进行优化
