### ISSUE TITLE
关于手机端 控制条问题。请大佬进来看看

### ISSUE THREAD

**Issue by yanghuiqi** [bytedance/xgplayer#20]
whitelist: [/iPhone/gi,/Android/gi], 
 我是这样配置的白名单。
在微信中，原生controls  和播放器 controls 会两个同时存在。
是否我这个白名单配置有问题呢？好困惑。
还是这个有待修复？

**Comment by cucygh** [comment]
白名单不是这样用的哈，在移动端自定义UI很多设备兼容性不好处理，为了保证功能可用，只要自己测试过没问题的可以开启白名单，后续我们也会给大家提供一套白名单供参考

**Comment by yanghuiqi** [comment]
恩 有参考就好多了。目前测试在微信 IOS 11.3版本， 还不知道其他版本兼容如何。感谢大佬

**Comment by cucygh** [comment]
安卓设备众多，在video事件上兼容性迥异，所以自定义UI很难做到100%完美，通过白名单机制可以保证我们测试过设备用白名单，没测试过的使用原生的video，这样在功能上是完备的，我们逐渐丰富白名单列表就好了，我们一起来维护，棒棒哒

**Comment by liyang007700** [comment]
大部分安卓播放器video被托管，播控面板无法控制。在IOS上，可以参考爱奇艺m.iqiyi.com的做法
.hideControls::-webkit-media-controls-panel {
    display: none !important;
    -webkit-appearance: none
}

.hideControls::--webkit-media-controls-play-button {
    display: none !important;
    -webkit-appearance: none
}

.hideControls::-webkit-media-controls-start-playback-button {
    display: none !important;
    -webkit-appearance: none
}，先隐藏webkit原生controls，再定制自己的controls。

**Comment by cucygh** [comment]
对的，移动端劫持的问题暂时没有好的方法，问题同 #28

**Comment by guairenke** [comment]
问题同上，安卓手机显示的是原生的控制器！ ios 的可以用！！！
http://wangchaoke.cn/
