### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by w611363303798** [bytedance/xgplayer#202]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.1.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS10.14.4  Chrome

**实际播放器的表现是？ What actually happened?**
接入xgplayer-mp4播放mp4文件时，报错Uncaught (in promise) DOMException，自动降级到media请求。
![image](https://user-images.githubusercontent.com/24557962/61424899-aa831400-a947-11e9-97c5-10bed5c0f31e.png)

接入xgplayer-hls播放m3u8文件时，警告[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/， 请求到m3u8文件，视频一直loading
查看调用栈也是xg-start.onClick触发

**Comment by zhangxin92** [comment]
在西瓜播放器官网的示例页中也会有这样的问题吗？
