### ISSUE TITLE
如何支持视频同时有m3u8和f4v格式的播放

### ISSUE THREAD

**Issue by nabaonan** [bytedance/xgplayer#203]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.1.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac chrome75

**如何复现问题？ What did you do?**
现在视频格式是m3u8和f4v格式一起返回的，这个播放器如何支持

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常播放，不知怎么设置

**实际播放器的表现是？ What actually happened?**
只穿m3u8无法播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by bethe-light** [comment]
对你的问题我理解是，并没有插件同时支持这两种格式播放哈，需要同时安装 hls和flv，然后对你播放视频的格式做判断，使用相应的插件即可

**Comment by nabaonan** [comment]
> 对你的问题我理解是，并没有插件同时支持这两种格式播放哈，需要同时安装 hls和flv，然后对你播放视频的格式做判断，使用相应的插件即可

我们公司封装的播放器就是同时传f4v格式的链接和m3u8的链接就才可以播放，不知里面是怎么实现，那还想问下，这个播放器假如一页初始化好几个，来回切换播放源，内存占用会不会一直增长

**Comment by zhangxin92** [comment]
播放器和相关插件内部做了性能优化处理，不会造成内存一直增长
