### ISSUE TITLE
怎么做到动态切换视屏啊

### ISSUE THREAD

**Issue by caotianhua** [bytedance/xgplayer#204]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
pc   谷歌

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by bethe-light** [comment]
建议是，在不用destroy player 的情况下， 触发 player.src =  newUrl 即可切换视频，或者使用playNext 功能也是可以的。
