### ISSUE TITLE
请问能支持ie9吗

### ISSUE THREAD

**Issue by CLiangs** [bytedance/xgplayer#205]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
1.1.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by CLiangs** [comment]
ie9下点击暂停按钮页面会被enterlogo覆盖
![image](https://user-images.githubusercontent.com/24502999/62258675-ecc74d80-b43d-11e9-9872-86d2266c9f2a.png)

**Comment by zhangxin92** [comment]
播放器兼容性请参考 http://h5player.bytedance.com/gettingStarted/#%E5%85%BC%E5%AE%B9%E6%80%A7
播放器点播兼容到IE10+
