### ISSUE TITLE
[Bug] xgplayer-flv.js 中 switchUrl 失效以及修复方法

### ISSUE THREAD

**Issue by Pingren** [bytedance/xgplayer#206]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
1.1.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Mac & Chrome

**如何复现问题？ What did you do?**
使用 xgplayer-flv.js 创建 player (直播流)，对 player 实例调用 switchURL(url)

**您期望的播放器正常行为是？ What did you expect to happen?**
正确切换直播流，并保留 flvOptionalConfig 的配置。

**实际播放器的表现是？ What actually happened?**

无法切换直播流，无法保留 flvOptionalConfig。

[relevant code](https://github.com/bytedance/xgplayer/blob/rebuild/packages/xgplayer-flv.js/src/index.js):
```
switchURL (url) {
    const player = this
    const flvPlayer = player.__flv__
    player.config.url = url
    if (!player.config.isLive) {
      flvPlayer.onDefinitionChange(url, player.config.retryTimes)
    } else {
      const tempFlvPlayer = Flv.createPlayer(player.flvOpts)
      flvPlayer.destroy()
      player.createInstance(tempFlvPlayer)
      player.__flv__ = tempFlvPlayer
    }
  }
```

无法切换直播流可以通过修改 url 解决，实际播放地址最终由 segments 属性控制，即：
```
     player.flvOpts.segments[0].url = newUrl
```
无法保留 flvOptionalConfig 可以通过传入 option 解决，即：
```
     Flv.createPlayer(this.flvOpts, this.optionalConfig)
```

related issue: #172 #182

**Comment by Pingren** [comment]
@zhangxin92 你好，能麻烦你确认+解决一下这个 issue 吗？或我也可以提 Pull Request，谢谢！

**Comment by zhangxin92** [comment]
感谢反馈， xgplayer-flv.js@2.0.0 版本做了修复，现在可以通过 player.src = 'new url' 来切换直播流

**Comment by Pingren** [comment]
> 感谢反馈， xgplayer-flv.js@2.0.0 版本做了修复，现在可以通过 player.src = 'new url' 来切换直播流

安装了     "xgplayer": "^2.1.8",    "xgplayer-flv.js": "^2.0.0",

通过 player.src = 'new url' 或是 switchUrl 依然无法切换直播流

**Comment by zhangxin92** [comment]
把播放器配置和直播流地址贴一下

**Comment by Pingren** [comment]
> 把播放器配置和直播流地址贴一下

播放器配置：
>
            let config = {
            isLive: true,
            autoplay: true,
            autoplayMuted: true,
            controls: false,
            closeVideoClick: true,
            closeVideoDblclick: true,
            closeVideoTouch: true,
            volume: 1,
            keyShortcut: 'off',
            fluid: true,
            flvOptionalConfig: {
              enableStashBuffer: false,
            },
          }

直播流地址在内网，可能不太方便分享出来。

刚刚随便找了个 Bilibili 直播的地址测试，发现可以切换...
但是切换完居然有声音（autoplayMuted 失效），enableStashBuffer 应该也没生效。

**Comment by Pingren** [comment]
@zhangxin92 你好，能看看这个问题吗，需要再开一个 issue?

**Comment by zhangxin92** [comment]
autoplayMuted只在播放器初始化时生效，这个符合预期。
enableStashBuffer不生效的问题在xgplayer-flv.js@2.0.1修复了

**Comment by Pingren** [comment]
@zhangxin92 
> autoplayMuted只在播放器初始化时生效，这个符合预期。

那我的内网直播流无法重新播放的问题，有办法调试或者解决吗？我如何提供内网的直播流给你？

是否可以通过推流配置使其支持重新播放？

**Comment by Pingren** [comment]
进一步调试了下，灵机一动把 `mediaDataSource.hasAudio = true `改成了 false，可以切换流了。
视频流没有音源导致的切换卡住的，是否考虑 config 里支持 hasAudio 配置来解决这个问题?

relavant code: 
```javascript
  flv_load (newUrl) {
    let mediaDataSource = this.flvOpts
    mediaDataSource.segments = [
      {
        cors: true,
        duration: undefined,
        filesize: undefined,
        timestampBase: 0,
        url: newUrl,
        withCredentials: false
      }
    ]
    mediaDataSource.cors = true
    mediaDataSource.hasAudio = true
    mediaDataSource.hasVideo = true
    mediaDataSource.isLive = true
    mediaDataSource.url = newUrl
    mediaDataSource.withCredentials = false
    this.flv_load_mds(mediaDataSource)
  }
```

```javascript
    isComplete() {
        let audioInfoComplete = (this.hasAudio === false) ||
                                (this.hasAudio === true &&
                                 this.audioCodec != null &&
                                 this.audioSampleRate != null &&
                                 this.audioChannelCount != null);

        let videoInfoComplete = (this.hasVideo === false) ||
                                (this.hasVideo === true &&
                                 this.videoCodec != null &&
                                 this.width != null &&
                                 this.height != null &&
                                 this.fps != null &&
                                 this.profile != null &&
                                 this.level != null &&
                                 this.refFrames != null &&
                                 this.chromaFormat != null &&
                                 this.sarNum != null &&
                                 this.sarDen != null);

        // keyframesIndex may not be present
        return this.mimeType != null &&
               this.duration != null &&
               this.metadata != null &&
               this.hasKeyframesIndex != null &&
               audioInfoComplete &&
               videoInfoComplete;
    }
```

**Comment by Pingren** [comment]
@zhangxin92 视频流没有音源导致切换视频流失败。是否能修复一下？谢谢～

考虑 config 提供hasAudio 配置来解决这个问题? flv.js 文档里有这个配置。

**Comment by zhangxin92** [comment]
@Pingren 直接在播放器配置里使用 hasAudio 就可以，文档上写了
http://h5player.bytedance.com/plugins/#xgplayer-flv-js

**Comment by Pingren** [comment]
@zhangxin92 这个配置我试过了没用。观察切换视频流的源码，也可以发现 `mediaDataSource.hasAudio = true` 是写死的。

**Comment by Pingren** [comment]
@zhangxin92 请问，有计划解决这个问题吗？🙏

**Comment by zhangxin92** [comment]
@Pingren  试下xgplayer-flv.js@2.0.2  ，有问题欢迎提PR
