### ISSUE TITLE
视频正在加载中，加载特效(loading)缺失一段CSS，导致无法loading！

### ISSUE THREAD

**Issue by yinbanghui** [bytedance/xgplayer#207]
**您使用的西瓜播放器版本是多少？
2.1.3

**您使用的操作系统和浏览器分别是？ 
windows 10  Google Chrome   版本 76.0.3809.100（正式版本） （64 位）

**如何复现问题？
[官网上复现](https://h5player.bytedance.com/gettingStarted/#%E5%AE%89%E8%A3%85)
在网速比较慢的情况下,模拟网速慢:
![image](https://user-images.githubusercontent.com/10389726/62613183-8b224a00-b93b-11e9-8b2b-6f11b0599335.png)
在网络比较慢的时候，视频处于加载中如图所示：
![image](https://user-images.githubusercontent.com/10389726/62613284-bc9b1580-b93b-11e9-816a-bda422934d95.png)
这个loading的图片并未旋转，准确表示正在加载中；

官网[在线生成](https://h5player.bytedance.com/generate/)功能正常，能正确的loading
对比了下css，无法正确loading是因为少了一段CSS
```
@keyframes loadingRotate {
	0% {
		-webkit-transform: rotate(0);
		transform: rotate(0)
	}

	to {
		-webkit-transform: rotate(1turn);
		transform: rotate(1turn)
	}
}
```

**Comment by wj20160318** [comment]
播放/暂停等动画也没了，
有些地方的css没有加animation属性

**Comment by zhangxin92** [comment]
感谢反馈，loading动画已修复
