### ISSUE TITLE
西瓜视频有没有上一级播放插件和如何记录视频有效播放时长

### ISSUE THREAD

**Issue by changbb** [bytedance/xgplayer#208]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.1.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10

**如何复现问题？ What did you do?**
新功能和新需求

**您期望的播放器正常行为是？ What did you expect to happen?**
新功能和新需求，既然有播放下一集，那么是否应该自然有播放上一集处理呢？
另外，视频的播放有效时长（实际播放时间，非拖动进度条），进行业务处理，所以这个也很有必要

**实际播放器的表现是？ What actually happened?**
没有播放上一集和记录有效播放时长的配置

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
在线学习

**Comment by zhangxin92** [comment]
有效播放时长可以通过 player.played 获取，详见 https://www.w3school.com.cn/tags/av_prop_played.asp

播放上一集功能我们这周安排支持下
