### ISSUE TITLE
如何解决在ios上播放h264编码的视频

### ISSUE THREAD

**Issue by aWhver** [bytedance/xgplayer#214]
ios不支持h264编码的视频播放，我们上传的视频都是解码成mp4格式的，但是h264的播放不了。看了官网的案例https://h5player.bytedance.com/examples/，有一个//cdn.jsdelivr.net/npm/xgplayer-mp4/browser/index.js的文件，觉得应该是解决这个问题的，但是没生效。有解决方案吗

**Comment by zhangxin92** [comment]
ios支持h264编码的视频，不能播的话找找其它原因
