### ISSUE TITLE
为什么要发mcs.snssdk.com，sgali-mcs.byteoversea.com，maliva-mcs.byteoversea.com这些请求

### ISSUE THREAD

**Issue by hthmh** [bytedance/xgplayer#215]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.1.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10  ie11

**如何复现问题？ What did you do?**
刷新页面偶发

**您期望的播放器正常行为是？ What did you expect to happen?**
不要带有任何其他请求

**实际播放器的表现是？ What actually happened?**
带有了其他请求

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by stfenjobs** [comment]
可能是为了偷用户的数据

**Comment by zhangxin92** [comment]
This is an advanced and experimental function for optimizing our internal project. You can config 'noLog: true' to close this function.

**Comment by peizh** [comment]
都是字节跳动的域名
