### ISSUE TITLE
移动端不显示第一帧

### ISSUE THREAD

**Issue by basd1995** [bytedance/xgplayer#216]
2.1.12

开发环境mac os
运行环境移动端safari，微信浏览器

配置项videoInit: true时，在PC端Chrome中可以显示视频默认第一帧，但是在移动端初次进入都是黑屏。

videoInit: true这个对于移动端是不是无效的?如果是的话，是不是需要自己写一些处理函数？

**Comment by zhangxin92** [comment]
移动端不支持videoInit: true使用，主要是受到环境不支持自动播放的限制
