### ISSUE TITLE
希望能禁用 mcs.snssdk.com 的访问

### ISSUE THREAD

**Issue by fatelei** [bytedance/xgplayer#219]
观察到使用 xgplayer 后，会通过 `mcs.snssdk.com` 进行数据上报：
![image](https://user-images.githubusercontent.com/961094/64107807-f0882000-cdad-11e9-90eb-8a9a6d2c83aa.png)
希望能够禁用该功能

**Comment by zhangxin92** [comment]
This is an advanced and experimental function for optimizing our internal project. You can config 'noLog: true' to close this function.
