### ISSUE TITLE
shaka协议的方式会出现无法播放问题

### ISSUE THREAD

**Issue by LinXiNotDream** [bytedance/xgplayer#221]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
大于1.1.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 + chrome

**如何复现问题？ What did you do?**
直接官方网站内的示例，选择dash，点击播放，资源正常加载但视频并未播放

**您期望的播放器正常行为是？ What did you expect to happen?**
期望视频正常播放

**实际播放器的表现是？ What actually happened?**
实际出现loading，但是视频实际并未被播放，在UI展示上左下角播放按钮已经是播放中状态，但是点击一下暂停按钮，视频才真正开始播放？？？这是什么鬼？
我监听play事件、playing事件和pause事件发现，在最开始视频加载完成之时点击窗口中心的播放按钮虽然触发了paly事件但是并未触发playing事件，因此一直处于loading页面，再次左下角点击“暂停”按钮这次会依次触发play和playing事件，视频这时候才正常播放

**Comment by zhangxin92** [comment]
在最新版本没有复现，感谢反馈！
