### ISSUE TITLE
怎么获取当前的播放速度？怎么在改变播放速度的时候，执行自定义的代码

### ISSUE THREAD

**Issue by stfenjobs** [bytedance/xgplayer#225]
谢谢，很不错的项目

 1.怎么用js获取当前的播放速度？

2.怎么在改变播放速度的时候，执行自定义的js代码？

3.怎么用js控制播放速度？

谢谢

**Comment by zhangxin92** [comment]
1. player.video.playbackRate
2. You can define your custom plugin following the xgplayer source code
3. player.video.playbackRate = 2

**Comment by stfenjobs** [comment]
tks
