### ISSUE TITLE
xg-flv中isLive为true时，跨域的视频不会报错，一直在loading

### ISSUE THREAD

**Issue by amhoho** [bytedance/xgplayer#240]
如题，而isLive:false时会出现`不支持的音频/视频`

**Comment by amhoho** [comment]
并且如果vod视频，islive:true也是无限loading ，这样意味着每次都需要判断点播还是直播，显得有些死板。

**Comment by amhoho** [comment]
经过在测试，发现xgplayer-flv无法播放直播，存在两问题。
1.当配置为`isLive: false`,console中提示跨域，但该视频源本身不存在跨域问题，在flv.js中正常播放。
2.1.当配置为`isLive: true`,无限loading播放不了。

**Comment by zhangxin92** [comment]
直播请使用 xgplayer-flv.js
xgplayer-flv对直播的支持正在开发中，感谢反馈！

**Comment by amhoho** [comment]
@zhangxin92 
flv.js版本的存在累积延迟问题，播放几分钟后延迟越堆积很高，从1s可以延迟1分钟。
经过我刚才的测试，xgplayer-flv在这样的配置下可以播放，但不能`autoplayer:true`否则提示`不支持的视频、音频`:
```
      let player = new FlvPlayer({
          id: 'mse',
          isLive:true,
          autoplay:true,
          url: 'https://tliveplay.mogujielive.com/live/198511961_11340132.flv',
          playsinline: true,
          height: window.innerHeight,
          width: window.innerWidth
      });
```

**Comment by Venustar-ZL** [comment]
> 经过在测试，发现xgplayer-flv无法播放直播，存在两问题。 1.当配置为`isLive: false`,console中提示跨域，但该视频源本身不存在跨域问题，在flv.js中正常播放。 2.1.当配置为`isLive: true`,无限loading播放不了。

老哥 请问这个问题你解决了吗
