### ISSUE TITLE
网页全屏模式

### ISSUE THREAD

**Issue by wangyingjie123** [bytedance/xgplayer#242]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.1.17

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**
网页全屏后没有给body设置overflow:hidden，按esc无法退出网页全屏

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
已在最新版本（2.17.0）支持
