### ISSUE TITLE
css全屏模式为啥直播类型的不支持？

### ISSUE THREAD

**Issue by Mjingling** [bytedance/xgplayer#243]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新版

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome模拟手机

**如何复现问题？ What did you do?**
CSS全屏的按钮在hls直播时，不显示，

**您期望的播放器正常行为是？ What did you expect to happen?**
直播时也支持CSS全屏模式
能监听到CSS全屏事件和系统全屏事件

**实际播放器的表现是？ What actually happened?**
hls直播时，css全屏的按钮没有显示，无法监听到CSS全屏后的回调事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Mjingling** [comment]
cssFullscreen这个选项我开启了，但是直播时不显示相应的控制控件

**Comment by zhangxin92** [comment]
Fixed in xgplayer@2.1.18

**Comment by Mjingling** [comment]
能监听到全屏事件了么？

**Comment by zhangxin92** [comment]
requestCssFullscreen  exitCssFullscreen
