### ISSUE TITLE
xgplayer-mp4存在重复请求和无缓存再次请求的情况，一个10M的视频可累计请求100MB的接收数据

### ISSUE THREAD

**Issue by amhoho** [bytedance/xgplayer#244]
我使用了一个demo.mp4(9999kb)的示例视频，播放和重播的过程中，观察firebug中的网络面板。
结果：
GET demo.mp4 206 Partial Content 1.6 MB 4.69s
这样的请求存在并行的重复请求（有时候1次，有时候2次）
而只要播放未结束，就不断有这样的请求。（接收的demo.mp4数据可以累计达到100MB）
当重复播放后，又继续这样的请求，没有任何缓存。

**Comment by amhoho** [comment]
经过几次测试，应该是xgplayer-mp4,xgplayer-hls,xgplayer-flv的task或xhr都是有问题的
在原生mp4,flv.js和hls.js都流畅播放的源，在它们中都是不停的卡顿，还多出了大量的流量。

**Comment by amhoho** [comment]
在mp4中发现这样一个队列顺序错乱的情形：
按xhr顺序，
Content-Range bytes 0-390625/3255507
`Content-Range bytes 3232855-3255506/3255507`
//先加载首尾片段，再按顺序加载。这是出于什么考虑。
Content-Range	bytes bytes 48-117188/3255507
Content-Range	bytes bytes 116900-437043/3255507

**Comment by lizy0329** [comment]
> 在mp4中发现这样一个队列顺序错乱的情形：
> 按xhr顺序，
> Content-Range bytes 0-390625/3255507
> `Content-Range bytes 3232855-3255506/3255507`
> //先加载首尾片段，再按顺序加载。这是出于什么考虑。
> Content-Range bytes bytes 48-117188/3255507
> Content-Range bytes bytes 116900-437043/3255507

在原生mp4,flv.js和hls.js都流畅播放的源，在它们中都是不停的卡顿，还多出了大量的流量。还存在黑屏，无法播放完整卡住的问题

**Comment by wqkwqk** [comment]
我遇到了同样的问题 请问怎么解决的
