### ISSUE TITLE
有没有主动退出全屏和css样式全屏的api

### ISSUE THREAD

**Issue by Mjingling** [bytedance/xgplayer#246]
版本 2.1.18

问题描述：当用户css全屏播放时，如果视频播放完成，则播放器会显示”重播“按钮，此时视频的控制菜单（即最底下的视频控制栏）已经消失，用户无法手动退出全屏，此时需要监听视频播放结束事件，通过代码退出全屏模式，但文档中找不到退出css全屏的api,

期望：请提供此api，万分谢谢哈

**Comment by Mjingling** [comment]
类似这样调用的 player.exitCssFullscreen()

**Comment by zhangxin92** [comment]
已在xgplayer@2.1.19版本支持，文档见 http://h5player.bytedance.com/api/#getcssfullscreen
