### ISSUE TITLE
特定情况下，一直发送m3u8请求（且成功返回）但是没有ts请求发送

### ISSUE THREAD

**Issue by tonyload** [bytedance/xgplayer#247]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

xgplayer-hls.js@2.1.0-beta.1
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
谷歌，或者任意其他浏览器均可重现

**如何复现问题？ What did you do?**
两种方式重现：
1、推流端 断流  ， 隔一段时间（一般1分钟稳定重现），再重新推流
2、360对浏览器进行限流，隔一段时间之后，再恢复

**您期望的播放器正常行为是？ What did you expect to happen?**
任何情况下，当m3u8请求正常返回的时候，就应该发送ts请求 而不是现在这样，一直反复发送m3u8请求

**实际播放器的表现是？ What actually happened?**
一直发送m3u8请求

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
中移物联网-视频能力组
![bugforxgplayer](https://user-images.githubusercontent.com/53110897/66384532-82103080-e9f1-11e9-8993-8add0400daed.png)

**Comment by leonardoFu** [comment]
m3u8中没有新的ts分片地址，就不会发ts请求
