### ISSUE TITLE
progressDot

### ISSUE THREAD

**Issue by littlegreay** [bytedance/xgplayer#253]
progressDot属性下，希望能跟danmu属性一样comments支持style自定义

**Comment by zhangxin92** [comment]
可以在项目代码中覆盖样式 .xgplayer-progress-dot
也可以使用自定义样式实现 https://v2.h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
