### ISSUE TITLE
screenShot

### ISSUE THREAD

**Issue by littlegreay** [bytedance/xgplayer#254]
screenShot属性可以添加一个自定义属性，就是提供展示字段，目前默认展示“screenShot”，希望可以做到自定义

**Comment by zhangxin92** [comment]
可以在播放器实例化完成后修改相关DOM文字
player.once('complete', () => {

})
也可以通过自定义样式功能实现
https://v2.h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
