### ISSUE TITLE
xgplayer自定义样式报TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by tutuchang** [bytedance/xgplayer#257]
`<script>
import Player from 'xgplayer'
import '../../.xgplayer/skin/index.js'
export default {
  mounted () {
    this.initPlayer()
  },
  methods: {
    initPlayer () {
      const player = new Player({
        id: 'player',
        url: 'http://s2.pstatp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4'
      })
    }
  }
}
</script>`

**Comment by taozhipeng1990** [comment]
可能是svg loader没有处理好吧
我现在也是这个问题

**Comment by boy-yan** [comment]
这个有配置吗， 同样的问题出现了

**Comment by boy-yan** [comment]
{
        test: /\.svg$/,
        use: [
          'raw-loader'
        ]
      }, 
加上这个还是不行啊

**Comment by zhangxin92** [comment]
使用的vue cli4 吗？可以在vue.config.js文件里作如下修改：
module.exports = {
    chainWebpack: config => {
        const svgRule = config.module.rule('svg')

        svgRule.uses.clear()

        svgRule
            .use('raw-loader')
            .loader('raw-loader')
    }
}

**Comment by loveXS** [comment]
请问nuxt如何配置？

**Comment by zyf540860996** [comment]
> 

1

**Comment by zyf540860996** [comment]
> 

安装后，必须通过require('xgplayer')
如果通过npx xgplayer eject [targetDir] [skinName] 自定样式，会提示 TypeError: Cannot read property 'addEventListener' of null
简单办法：
1、安装@nuxtjs/svg
2、nuxt.config.js 中添加 buildModules: ["@nuxtjs/svg"]
3、在生成自定义样式的文件夹中找到js引入.svg所有文件，然后替换 "../assets/xx.svg"  =>  "../assets/xx.svg?raw"
