### ISSUE TITLE
关于播放器加载动画的问题

### ISSUE THREAD

**Issue by growthworld** [bytedance/xgplayer#26]
希望之后的版本可以加上一个配置项

**Comment by LinFeng1997** [comment]
能详细描述下你的需求吗？

**Comment by growthworld** [comment]
我们公司这边是在做一个运营的一个项目，里面用到了很多的video标签，公司这边说加载的动画想替换成自己的动画。

**Comment by zhaozhuoboy** [comment]
## 这个可以配置吗
![image](https://user-images.githubusercontent.com/15223986/42791606-07f4bc5c-89a4-11e8-9ba7-2dbf92d0e38d.png)

**Comment by zhangxin92** [comment]
The next release will support configuration of video loading background. Now you can replace the background of the DOM element with CSS overlay. @growthworld @zhaozhuoboy

**Comment by zhaozhuoboy** [comment]
@zhangxin92   ok  thanks

**Comment by zhaozhuoboy** [comment]
hope the next version comes soon

**Comment by liyadong0211** [comment]
播放器在移动端使用的时候，点击全屏按钮，希望能自动判断视频宽高全屏显示，以视频的宽高的最大值填充
