### ISSUE TITLE
关于直播的自动清晰度切换的问题

### ISSUE THREAD

**Issue by dante1977** [bytedance/xgplayer#274]
https://github.com/bytedance/xgplayer/blob/1021d21657bd457ee763e783ae09bad8fbb20efd/packages/xgplayer-flv/src/Flv.js#L110-L115

这里113行，为啥判断是直播就跳过了呢？

**Comment by leonardoFu** [comment]
请更新一下flv版本，目前已经针对点播和直播分别进行处理了
