### ISSUE TITLE
直播支持切换清晰度吗

### ISSUE THREAD

**Issue by Erik5169** [bytedance/xgplayer#275]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

我在线上的demo中，配置直播的清晰度切换流， 但是每次切换都会绿屏，想问下直播是否支持清晰度切换呢

**Comment by dante1977** [comment]
老哥，我也有这方面的疑问

**Comment by Erik5169** [comment]
> 老哥，我也有这方面的疑问

可以切的， 我已经实现了， 不过用插件的时候要用 xgplayer-flv.js xgplayer-hls.js这两个插件，xgplayer-flv，xgplayer-hls这两个插件有很多问题

**Comment by dante1977** [comment]
@Erik5169 老哥，有没有样例代码，能不能发我一份学习一下 dante1977@163.com

**Comment by Erik5169** [comment]
> @Erik5169 老哥，有没有样例代码，能不能发我一份学习一下 [dante1977@163.com](mailto:dante1977@163.com)

我的案例是Vue版本的， 你要的话， 我发你一份

**Comment by Erik5169** [comment]
> > @Erik5169 老哥，有没有样例代码，能不能发我一份学习一下 [dante1977@163.com](mailto:dante1977@163.com)
> 
> 我的案例是Vue版本的， 你要的话， 我发你一份
发你了， 你看下邮箱
