### ISSUE TITLE
canPlayType内部调用video.canPlayType时没有传入参数

### ISSUE THREAD

**Issue by chillyond** [bytedance/xgplayer#277]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.3.0

**如何复现问题？ What did you do?**
`player.canPlayType('video/mp4')`

**实际播放器的表现是？ What actually happened?**
Uncaught TypeError: Failed to execute 'canPlayType' on 'HTMLMediaElement': 1 argument required, but only 0 present.
![image](https://user-images.githubusercontent.com/11400674/68574359-9dfd6b00-04a4-11ea-9e52-0dde3d9b8f7a.png)

**Comment by zhangxin92** [comment]
Fixed by xgplayer@2.3.1
Thanks!
