### ISSUE TITLE
在UC浏览器video视频窗口悬浮，有解决方案吗？

### ISSUE THREAD

**Issue by cheaprYang** [bytedance/xgplayer#28]

**Comment by cucygh** [comment]
移动端劫持的问题暂时没有解决方案，除非我们不依赖video，可以研究下jsffmpeg+canvas的方式

**Comment by cheaprYang** [comment]
但是我发现 在 斗鱼 熊猫 相关平台设置 在某些浏览器下 可以正常 设置，并没有被层级影响，这就很郁闷了
