### ISSUE TITLE
安卓手机，微信浏览器，退出全屏exitFullscreen事件未生效。

### ISSUE THREAD

**Issue by Angle-bo** [bytedance/xgplayer#280]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?** 
2.3.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓红米node +微信内置浏览器

**您期望的播放器正常行为是？ What did you expect to happen?**
player.on 注册exitFullscreen事件， 当退出全屏的时候执行自己的逻辑。

**实际播放器的表现是？ What actually happened?**
exitFullscreen事件，未触发

**Comment by Angle-bo** [comment]
查看渲染之后的element，播放使用的是原生的video标签，监听原生video的退出全屏事件，可以实现理想效果。

**Comment by guairenke** [comment]
请问大佬有好的解决办法吗？我也遇到了这个问题！！！
在Android 和 ios 都监听不到！！！

**Comment by Angle-bo** [comment]
> 请问大佬有好的解决办法吗？我也遇到了这个问题！！！
> 在Android 和 ios 都监听不到！！！

移动端西瓜视频好像默认使用的是原生的video。所以我这边使用原生的video退出全屏的事件做的监听。。

**Comment by zhangxin92** [comment]
安卓微信环境全屏下会被劫持，导致相关监听事件无效
