### ISSUE TITLE
http://h5player.bytedance.com/examples/?type=vod&plugin=flv demo无法播放

### ISSUE THREAD

**Issue by youminxue** [bytedance/xgplayer#282]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
我们这边可以播放，请问你那边是什么系统和浏览器呢？

**Comment by youminxue** [comment]
Mac 10.15.1 (19B88) chrome浏览器

**Comment by youminxue** [comment]
显示“网络连接似乎出现了问题，请刷新试试“

**Comment by youminxue** [comment]
主要是flv，通过地址获取flv地址可以下载

**Comment by youminxue** [comment]
http://203.187.160.132:9011/h5player.bytedance.com/c3pr90ntc0td/video/flv/xgplayer-demo-360p.flv

**Comment by youminxue** [comment]
http://h5player.bytedance.com/video/flv/xgplayer-demo-360p.flv

**Comment by youminxue** [comment]
http://h5player.bytedance.com/generate/这个地址的demo可以

**Comment by zhangxin92** [comment]
This issue cannot reoccur. Thank you for your contributions.
