### ISSUE TITLE
安卓微信中右上角的全屏按钮有没有办法隐藏呀？

### ISSUE THREAD

**Issue by 95sunny** [bytedance/xgplayer#283]
安卓端微信内置浏览器中，右上角有个全屏俩字的按钮，有没有办法去掉或者隐藏呀

**Comment by zhangxin92** [comment]
那是播放器被劫持了，我们没法控制

**Comment by 95sunny** [comment]
噢噢，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhangxin92"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上8:01
收件人:&nbsp;"bytedance/xgplayer"<xgplayer@noreply.github.com&gt;;
抄送： &nbsp;“ Sun” <1181456498@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/xgplayer] 安卓微信中右上角的全屏按钮有没有办法隐藏呀？ (#283)




那是播放器被劫持了，我们没法控制
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by lizy0329** [comment]
可以使用 object-position 来调整视频位置，撑“全屏”到外面，不过视频有点裁剪便是
