### ISSUE TITLE
西瓜视频白名单问题， iOS 自定义ui 可以展示， 但是安卓白名单怎么配置都不显示！！！

### ISSUE THREAD

**Issue by guairenke** [bytedance/xgplayer#285]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

^2.3.5
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Android 和 ios 微信中

**如何复现问题？ What did you do?**
把插件引入在vue中 配置好 
whitelist: ['iPhone','Android']

**您期望的播放器正常行为是？ What did you expect to happen?**
在安卓环境下显示 西瓜视频自定义ui 去除原生control ui

**实际播放器的表现是？ What actually happened?**
西瓜视频自定义ui  闪一下 变成 原生 ui

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
移动端视频播放

**Comment by guairenke** [comment]
是不是白名单配置的问题呢？
可否给一个 安卓机型 可配置的白名单方案！！！

**Comment by zhangxin92** [comment]
和白名单无关，安卓部分浏览器下播放器会被劫持，目前没有成熟的解决方案

**Comment by guairenke** [comment]
我测试了两个主流机型 一个是 **vivo** 一个是 **华为** 都是闪一下 就变成原生的video标签
哪怕样式乱也没关系，怎么把西瓜自定义 ui 不支持的机型判断给去掉呢？

**Comment by pgh147** [comment]
我的IOS上面也会变成原生UI啊，需要配置什么属性吗？
