### ISSUE TITLE
视频切换和自动播放

### ISSUE THREAD

**Issue by ynzy** [bytedance/xgplayer#288]
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
  windows,chrome
**如何复现问题？ What did you do?**
  通过`player.destroy()`实现视频切换,创建的新实例没有参数,立即执行`player.play()`无法实现切换的视频立即播放,一直处于加载中
```js
if (player) {
  player.destroy();
}
setTimeout(function () {
  player = null;
  player = new Player({
    id: 'mse',
    url: course.videoSrc,
    fluid: true,
  });
  player.play()
}, 0);
```
**您期望的播放器正常行为是？ What did you expect to happen?**
  切换视频立即播放

**Comment by zhangxin92** [comment]
播放器销毁并再次初始化后，需要先调用start方法
