### ISSUE TITLE
ERROR TypeError: Failed to execute 'canPlayType' on 'HTMLMediaElement': 1 argument required, but only 0 present.

### ISSUE THREAD

**Issue by laixiangran** [bytedance/xgplayer#29]
调用 canPlayType 方法应该是需要传入一个参数，但是查看你们源码在调用 `this.video.canPlayType()` 时没有传入参数：
```
{
            key: "canPlayType",
            value: function() {
                this.video.canPlayType()
            }
        }
```

**Comment by zhangxin92** [comment]
Indeed a problem. It will be fixed by [fcf7cd8](https://github.com/bytedance/xgplayer/commit/fcf7cd8d480e34934d6736db1ffd82926ad22b37) . Thanks.
