### ISSUE TITLE
配置playNext播放下一集,是否可以监听到

### ISSUE THREAD

**Issue by ynzy** [bytedance/xgplayer#290]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows,chrome
**如何复现问题？ What did you do?**
配置了播放下一集,我想在点击下一集时监听到我此事件,api中好像没有

**您期望的播放器正常行为是？ What did you expect to happen?**
监听播放下一集事件,如果有的话是哪个api

**实际播放器的表现是？ What actually happened?**
点击播放下一集切换到下一集,无法监听此动作

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Hunlongyu** [comment]
楼主解决了么? 我也想自定义播放下一集, 或者监听下一集事件.

**Comment by zhangxin92** [comment]
player.on('playNextBtnClick', () => {

})
