### ISSUE TITLE
切换url 停止但是进度条没有回到开始位置，播放器中心没有显示暂停按钮

### ISSUE THREAD

**Issue by datongkaze** [bytedance/xgplayer#295]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.3.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
 macOS + chrome

**您期望的播放器正常行为是？ What did you expect to happen?**
切换url 停止 进度条回到开始位置，播放器中心显示暂停按钮

**实际播放器的表现是？ What actually happened?**
切换url 停止但是进度条没有回到开始位置，播放器中心没有显示暂停按钮

**Comment by zhangxin92** [comment]
切换url后需要你自己设置下播放时间，示例代码如下：
player.once('canplay', () => {
    player.currentTime = 0
})
player.src = 'new url'

**Comment by datongkaze** [comment]
> 切换url后需要你自己设置下播放时间，示例代码如下：
> player.once('canplay', () => {
> player.currentTime = 0
> })
> player.src = 'new url'

更换url之后播放器不显示播放按钮怎么解决

**Comment by datongkaze** [comment]
我是这么解决的：
player.pause()
setTimeout(() => {
    player.once('canplay', () => {
        player.currentTime = 0
    })
    player.src = 'new url'
})
希望可以改一下，体验会好一点
