### ISSUE TITLE
安装xgplayer-hls插件，vue打包报错

### ISSUE THREAD

**Issue by MaJiaXuan** [bytedance/xgplayer#296]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.1.13",
 "xgplayer-hls": "^2.2.0-alpha.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
操作系统：win10，浏览器：谷歌浏览器77.0.3865.120

**如何复现问题？ What did you do?**
安装xgplayer-hls插件后，vue打包报错，

**您期望的播放器正常行为是？ What did you expect to happen?**
vue2.5.16+webpack2.6.1
ERROR in static/js/0.ccd34c70beeddb5bbe62.js from UglifyJs
Unexpected token: name (s) [static/js/0.ccd34c70beeddb5bbe62.js:23823,1985]

ERROR in static/js/1.c60a8373d7353a837e1e.js from UglifyJs
Unexpected token: name (s) [static/js/1.c60a8373d7353a837e1e.js:26348,1985]

ERROR in static/js/44.97cae847b8bdf9d0d5c8.js from UglifyJs
Unexpected token: name (s) [static/js/44.97cae847b8bdf9d0d5c8.js:528,1985]

ERROR in static/js/51.afb88baab0185a3d23e7.js from UglifyJs
Unexpected token: name (s) [static/js/51.afb88baab0185a3d23e7.js:410,1985]

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
xgplayer-hls默认已经被压缩，二次压缩可能出现异常，建议调整webpack打包方式。
