### ISSUE TITLE
x5-playsinline="true" 对华为手机并不生效

### ISSUE THREAD

**Issue by lizy0329** [bytedance/xgplayer#298]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.3.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
华为 EUI 全系列

**如何复现问题？ What did you do?**
使用华为手机 - 播放器配置内联模式，点击播放视频

**您期望的播放器正常行为是？ What did you expect to happen?**
预期的播放行为是：视频可以正常内联播放

**实际播放器的表现是？ What actually happened?**
华为手机播放时会采用全屏播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by jiechud** [comment]
@lizy0329 `x5-playsinline` 是怎么加的呢，我看文档上没有说是怎么加的

**Comment by jiechud** [comment]
`x5-video-player-type='h5-page'` 改成这个试试

**Comment by lizy0329** [comment]
> `x5-video-player-type='h5-page'` 改成这个试试

现在弄清了，x5-playsinline 是 IOS 端专用的，而在安卓端，大部分机型默认全屏播放

h5-page 参数也就是说采用 X5 的同层播放能力，可以做到内联播放。
