### ISSUE TITLE
vue项目可以实现进入页面初始化后自动直播吗？

### ISSUE THREAD

**Issue by Chinegoodman** [bytedance/xgplayer#300]
vue项目可以实现进入页面初始化后自动直播吗？
现在我尝试在vue项目中 点击模拟按钮播放。但是默认的paly按钮不消失。而且也不显示直播界面

**Comment by zhangxin92** [comment]
自动播放参考 http://h5player.bytedance.com/config/#%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE
另外自动播放会受到浏览器限制 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by Chinegoodman** [comment]
> 自动播放参考 http://h5player.bytedance.com/config/#%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE
> 另外自动播放会受到浏览器限制 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

谢谢您的回复。我加了无效果。看来是浏览器限制的原因了。但是怎样自定义那个播放啊？我调用播放事件后。自带的播放按钮没有消失也没有播放

**Comment by zhangxin92** [comment]
> > 自动播放参考 http://h5player.bytedance.com/config/#%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE
> > 另外自动播放会受到浏览器限制 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> 
> 谢谢您的回复。我加了无效果。看来是浏览器限制的原因了。但是怎样自定义那个播放啊？我调用播放事件后。自带的播放按钮没有消失也没有播放

试下 
player.start()
player.play()

**Comment by Chinegoodman** [comment]
> > > 自动播放参考 http://h5player.bytedance.com/config/#%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE
> > > 另外自动播放会受到浏览器限制 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> > 
> > 
> > 谢谢您的回复。我加了无效果。看来是浏览器限制的原因了。但是怎样自定义那个播放啊？我调用播放事件后。自带的播放按钮没有消失也没有播放
> 
> 试下
> player.start()
> player.play()

谢谢。已解决！！！您是官方开发人员吗？ 666
