### ISSUE TITLE
IE11使用flv协议播放报错

### ISSUE THREAD

**Issue by iyanghui** [bytedance/xgplayer#306]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
以`<script src="//cdn.jsdelivr.net/npm/xgplayer/browser/index.js" charset="utf-8"></script>
    <script src="//cdn.jsdelivr.net/npm/xgplayer-hls.js/browser/index.js" charset="utf-8"></script>`形式引入，没有版本号。

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows8/Windows10 + IE11

**如何复现问题？ What did you do?**
IE11下使用flv协议播放

**您期望的播放器正常行为是？ What did you expect to happen?**
能够正常播放，Windows8+支持mse

**实际播放器的表现是？ What actually happened?**
控制台打印报错信息：SCRIPT7002: XMLHttpRequest: 网络错误 0x2eff, 由于出现错误 00002eff 而导致此项操作无法完成。播放器显示：network is offline,please try to refresh，点击refresh后提示： audio/video is not suppoort .

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
视频监控业务，已对接阿里云视频监控，输出flv流。

**Comment by leonardoFu** [comment]
建议看下是不是脚本加载有误，此外flv播放应该用xgplayer-flv
