### ISSUE TITLE
flv 流媒体播放不能 画中画(pip)模式

### ISSUE THREAD

**Issue by jiechud** [bytedance/xgplayer#311]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Mac chrome

**如何复现问题？ What did you do?**

![image](https://user-images.githubusercontent.com/9709396/71578284-76d12a80-2b32-11ea-8154-cac3ec96d068.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
加pip 有画中画模式

**Comment by zhangxin92** [comment]
播放flv能正常支持画中画，您那边具体出现了什么问题呢

**Comment by jiechud** [comment]
@zhangxin92 
这是 flv 直播流，播放器底部没哟出现画中画
![image](https://user-images.githubusercontent.com/9709396/71607985-ac205b80-2bb8-11ea-9344-562df16c7d18.png)

这是播放的一个 mp4 文件，是有画中画模式
![image](https://user-images.githubusercontent.com/9709396/71608028-f6094180-2bb8-11ea-8db9-f9746a741963.png)

**Comment by zhangxin92** [comment]
直播默认会隐藏画中画控件，可通过样式打开 .xgplayer-pip {display:block !important;}
