### ISSUE TITLE
倍速按钮不隐藏

### ISSUE THREAD

**Issue by huyu6** [bytedance/xgplayer#312]
我切换了倍速，但是选择器一直在那，点不掉也不会自动隐藏
![)E_ J}W3ZBJHTX6$4ZT3L0I](https://user-images.githubusercontent.com/30172659/71713646-89ef3d80-2e45-11ea-98d2-c103dbadd9fc.png)

**Comment by zhangxin92** [comment]
感谢反馈，试下xgplayer@2.4.5版本

**Comment by fengqinxingtao** [comment]
我尝试了2.4.7版本，移动端这个问题依然存在

**Comment by fengqinxingtao** [comment]
原因找到了，自定义样式，修改某些样式 导致了这个问题
