### ISSUE TITLE
flv 视频流回复的时候报错

### ISSUE THREAD

**Issue by jiechud** [bytedance/xgplayer#313]
flv 视频流中断，恢复之后报错，报错如下
```
Offset is outside the bounds of the DataView 
```
![image](https://user-images.githubusercontent.com/9709396/71970145-0ff2f600-3243-11ea-80f3-0652ec1ebb83.png)

**Comment by leonardoFu** [comment]
请提供一下使用的flv插件版本？

**Comment by leonardoFu** [comment]
用户长时间未回复，暂时关闭issue
