### ISSUE TITLE
官网flv.js 直播事例，当直播地址有问题后出现的刷新按钮失效

### ISSUE THREAD

**Issue by chenxiaoqiang1988** [bytedance/xgplayer#315]
http://h5player.bytedance.com/examples/?type=vod&plugin=flv
![image](https://user-images.githubusercontent.com/7124274/72031701-27c08d80-32c8-11ea-9a03-1796ce09bcb8.png)

**Comment by leonardoFu** [comment]
期望的现象是？如果播放地址异常，刷新也是无法播放的。
