### ISSUE TITLE
小米8，安卓系统10，微信内点击无法全屏

### ISSUE THREAD

**Issue by 1303434374** [bytedance/xgplayer#317]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.4.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
小米8，miui11，安卓系统10，微信内置浏览器

**如何复现问题？ What did you do?**
点击全屏按钮

**您期望的播放器正常行为是？ What did you expect to happen?**
正常全屏

**实际播放器的表现是？ What actually happened?**
非全屏，上下有黑边，视频只有中间一小块

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
这是系统行为，xgplayer默认调用系统环境提供的全屏API
