### ISSUE TITLE
使用官网demo，在小米note7 淘宝环境出现解码错误

### ISSUE THREAD

**Issue by Aric-sky** [bytedance/xgplayer#318]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
这个cdn没写版本号，cdn.jsdelivr.net/npm/xgplayer/browser/index.js

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
小米note7 淘宝环境

**如何复现问题？ What did you do?**
扫码打开项目

**您期望的播放器正常行为是？ What did you expect to happen?**
扫码打开页面

**实际播放器的表现是？ What actually happened?**
提示解码错误

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
麻烦提供下视频源

**Comment by Aric-sky** [comment]
http://pano-public-images.oss-cn-hangzhou.aliyuncs.com/pano_src/100070-111904/hotspot/video/20秒内.mp4

**Comment by Aric-sky** [comment]
> 麻烦提供下视频源

http://pano-public-images.oss-cn-hangzhou.aliyuncs.com/pano_src/100070-111904/hotspot/video/20秒内.mp4

**Comment by Aric-sky** [comment]
> 麻烦提供下视频源

http://pano-public-images.oss-cn-hangzhou.aliyuncs.com/pano_src/100070-100618/video/video.mp4

**Comment by zhangxin92** [comment]
视频解码错误由浏览器原生video触发，和相关环境的能力有关

**Comment by choukin** [comment]
遇到了一样部分不了的问题，发现 不支持单声道 同样的视频编辑成立体声就能正常播放，
