### ISSUE TITLE
当切换直播视频源l时,不能正常播放,必须要在视频中先点击播放按钮再切换直播视频源才能正常播放

### ISSUE THREAD

**Issue by lipc22** [bytedance/xgplayer#324]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.4.7",
"xgplayer-hls.js": "^2.1.6"
测试直播源:  http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10   Google

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
页面加载完,初始直播源为空字符串, 点击切换直播源可以正常播放

**实际播放器的表现是？ What actually happened?**
点击切换直播源可以不能播放,(只有先点击视频中播放,才能切换直播源播放)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by lipc22** [comment]
`  componentDidMount() {
    const player = new HlsJsPlayer({
      id: 'mse',
      hasVideo: true,
      hasAudio: true,
      url: ''
    })
    setTimeout(()=>{
      this.setState({
        player,
      })
    }, 0)
  }

  changeUrl = () => {
    const { player} = this.state
    setTimeout(()=>{
      player.src = '/live/cctv1_2/index.m3u8'
      player.play()
    }, 0)
  }`

**Comment by zhangxin92** [comment]
给播放器加上自动播放试下 autoplay: true

**Comment by lipc22** [comment]
加上自动播放我试过,功能是可以,但播放器当中一直处于loading状态

**Comment by zhangxin92** [comment]
需要用户与页面产生交互(点击)后，才能自动播放成功

**Comment by ccz-Eric** [comment]
同样踩坑，不知道答主是否解决了。如果设置autoplay：true，在微信浏览器下会一直转圈圈。所以该值肯定要提前设为false。然后就出现了上面的问题

**Comment by zhangxin92** [comment]
建议有直播源信息后再初始化播放器，不要设置为空字符串

**Comment by ccz-Eric** [comment]
没有设置为空，autoplay初始值为false时，第一个视频不点击播放，第二个视频会黑屏。折腾一下午，心累，换个插件好了

**Comment by ccz-Eric** [comment]
在微信浏览器下必现。设置autoplay为true，loading菊花码一直在转

**Comment by ccz-Eric** [comment]
这种情况，无论我是设置为true还是false，都是无解

**Comment by ccz-Eric** [comment]
我想我已经定位到原因了。autoPlay为false时，不会创建video标签。此时通过play方法播放视频，不会出现画面。需要通过start方法去动态添加DOM。
![image](https://user-images.githubusercontent.com/14230248/75785225-59bd1000-5d9e-11ea-9044-75d66390bc8a.png)
文档是否能补全，若autoplay为false，需要提前通过start方法去添加，后续再使用src去修改。

**Comment by ccz-Eric** [comment]
我觉得这更像个bug，期待你的修复

**Comment by zhangxin92** [comment]
@ccz-Eric 已补充文档，感谢反馈！

**Comment by iamwwc** [comment]
确实有这个bug，某些情况下需要先start再play

这是我写的一个小玩具，希望对来到这里的人解决问题有所帮助，不要再踩到这个坑

https://github.com/iamwwc/webplayer
