### ISSUE TITLE
清晰度切换一直在waiting

### ISSUE THREAD

**Issue by daoxincc** [bytedance/xgplayer#325]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?** 
1.1.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win10 Chrome

**如何复现问题？ What did you do?**
播放mp4视频时 切换清晰度的时候，我试了一下官方示例就有问题
http://h5player.bytedance.com/examples/
点播 MP4 西瓜mp4

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放，不会卡住不动

**实际播放器的表现是？ What actually happened?**
有时会一直在waiting浏览器也不在发送视频range请求，点击时间轴之后就会恢复

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
参考文档使用试下最新版本 xgplayer@2.31.2  xgplayer-mp4@2.0.0
https://v2.h5player.bytedance.com/plugins/#xgplayer-mp4
