### ISSUE TITLE
HlsJsPlayer播放点播hls，显示的直播样式

### ISSUE THREAD

**Issue by yefusheng** [bytedance/xgplayer#332]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
//cdn.jsdelivr.net/npm/xgplayer/browser/index.js
//cdn.jsdelivr.net/npm/xgplayer-hls.js/browser/index.js
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
android，企业微信

**如何复现问题？ What did you do?**
在企业微信中，使用HlsJsPlayer，观看多分辨率的点播视频。界面样式是直播，含有“live”样式

**您期望的播放器正常行为是？ What did you expect to happen?**
播放点播的m3u8，有进度条，没有直播样式

**实际播放器的表现是？ What actually happened?**

没有有进度条，展示的直播样式

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
这是m3u8格式不标准导致。
可以添加下面代码试下
player.once('playing', () => {
    Player.util.removeClass(player.root, 'xgplayer-is-live')
})
