### ISSUE TITLE
单条外挂字幕时，没有关闭选项。

### ISSUE THREAD

**Issue by Tridagger** [bytedance/xgplayer#333]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
ver1.1.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 10 和 chrome

**如何复现问题？ What did you do?**
在官网的在线生成中，删掉一条字幕，如果剩下的是默认字幕，则这个字幕无法关闭，如果剩下这条是非默认字幕，则这个字幕无法显示。

**您期望的播放器正常行为是？ What did you expect to happen?**
单个字幕时可以有按钮选择关闭和开启

**实际播放器的表现是？ What actually happened?**
如果剩下的是默认字幕，则这个字幕无法关闭，如果剩下这条是非默认字幕，则这个字幕无法显示。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
收到，我们做下优化，感谢反馈！

**Comment by zhangxin92** [comment]
Fixed in xgplayer@2.5.2
