### ISSUE TITLE
如何在视频中随机位置添加水印?

### ISSUE THREAD

**Issue by hhxiaohei** [bytedance/xgplayer#334]
如何在视频中随机位置添加水印?防止用户录屏

**Comment by hbynlsl** [comment]
我是使用 弹幕 形式进行发送的，隔一定时间显示一条弹幕

**Comment by zhangxin92** [comment]
播放器初始化前将自定义水印加入播放器容器
player.root.appendChild(DOM)

定时修改DOM的css位置
