### ISSUE TITLE
视频进度条placeholder的时间Bug

### ISSUE THREAD

**Issue by HeLuchao** [bytedance/xgplayer#336]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
V2.5.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS

**如何复现问题？ What did you do?**
视频播放器添加progressDot之后，视频进度条placeholder的时间有误，基本必现

**您期望的播放器正常行为是？ What did you expect to happen?**
播放器添加progressDot之后，视频进度条placeholder的时间显示正常

**实际播放器的表现是？ What actually happened?**
播放器添加progressDot之后，视频进度条placeholder的时间有误

**Comment by zhangxin92** [comment]
Fixed in xgplayer@2.5.4
Tnanks!
