### ISSUE TITLE
功能优化点：有关于视频弹幕的相关功能

### ISSUE THREAD

**Issue by HeLuchao** [bytedance/xgplayer#337]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
V2.5.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS

**如何复现问题？ What did you do?**
 视频弹幕开启后传入一个自定义 dom 元素，元素上添加的自定义事件不生效

**您期望的播放器正常行为是？ What did you expect to happen?**
 视频弹幕开启后传入一个自定义 dom 元素，元素上添加的自定义事件能够生效

**实际播放器的表现是？ What actually happened?**
 视频弹幕开启后传入一个自定义 dom 元素，元素上添加的自定义事件不生效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以试下 xgplayer@2.17.9
支持弹幕项传入自定义DOM监听事件
eventListeners: [{
    event: 'click',
    listener: function (e) {
        console.log('click')
    },
    useCapture: false,
}]
