### ISSUE TITLE
视频切换还未加载出来时拖拽进度条 bug

### ISSUE THREAD

**Issue by ifanday** [bytedance/xgplayer#338]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.5.2",
"xgplayer-mp4": "^1.1.8"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓 qq浏览器

**如何复现问题？ What did you do?**
点击列表切换视频 url  正在加载时  点击进度条快进   进度条在点击快进位置,  视频 从0s 开始

**您期望的播放器正常行为是？ What did you expect to happen?**
切换 url 时 不应该出现进度条

**实际播放器的表现是？ What actually happened?**

![image](https://user-images.githubusercontent.com/19605184/75978517-a5e08f80-5f19-11ea-8a48-ad6ebeeac88a.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以在切换前设置播放器处于加载UI，监听到切换完成后移除加载UI
Player.util.addClass(player.root, 'xgplayer-is-enter')

player.once('playing', () => {
  Player.util.removeClass(player.root, 'xgplayer-is-enter')
})

**Comment by ifanday** [comment]
@zhangxin92 感谢

playing 视频加载完成时的瞬间   点击还是会出现这样的情况

换成 canplaythrough 事件 看起来可以了
