### ISSUE TITLE
有支持手机端投屏的计划么？

### ISSUE THREAD

**Issue by zephyr-y** [bytedance/xgplayer#339]
微信和腾讯浏览器自带的视频播放都有此功能。
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
v2.3.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
增加手机投屏功能

**实际播放器的表现是？ What actually happened?**
无此功能

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
最新版本（2.16.2）支持在iOS系统通过设置 airplay: true 参数实现投屏功能
