### ISSUE TITLE
长时间播放之后出现无法播放的问题

### ISSUE THREAD

**Issue by gonglilyy** [bytedance/xgplayer#340]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.2.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows10，Google
**如何复现问题？ What did you do?**

播放视频差不多2个小时左右，然后页面上所有的视频都无法播放了。
**您期望的播放器正常行为是？ What did you expect to happen?**

可以正常的进行视频播放。
**实际播放器的表现是？ What actually happened?**

![image](https://user-images.githubusercontent.com/47593648/76378149-b49acc80-6387-11ea-9e1c-e39208f7cbda.png)
如果我单独把返回栏的url拿到浏览器中是可以播放的。
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
普通的mp4吗？是不是视频地址有时效过期了呢？

**Comment by gonglilyy** [comment]
> 普通的mp4吗？是不是视频地址有时效过期了呢？

对的，普通的MP4，视频地址没有过期呢，我直接把视频地址copy到浏览器中，是可以播放的。

**Comment by zhangxin92** [comment]
> > 普通的mp4吗？是不是视频地址有时效过期了呢？
> 
> 对的，普通的MP4，视频地址没有过期呢，我直接把视频地址copy到浏览器中，是可以播放的。

使用了xgplayer-mp4插件吗？

**Comment by gonglilyy** [comment]
> > > 普通的mp4吗？是不是视频地址有时效过期了呢？
> > 
> > 
> > 对的，普通的MP4，视频地址没有过期呢，我直接把视频地址copy到浏览器中，是可以播放的。
> 
> 使用了xgplayer-mp4插件吗？

没有，就用的xgplayer，没有插入其他插件。

**Comment by zhangxin92** [comment]
> > > > 普通的mp4吗？是不是视频地址有时效过期了呢？
> > > 
> > > 
> > > 对的，普通的MP4，视频地址没有过期呢，我直接把视频地址copy到浏览器中，是可以播放的。
> > 
> > 
> > 使用了xgplayer-mp4插件吗？
> 
> 没有，就用的xgplayer，没有插入其他插件。

只使用xgplayer的话，我们没有对视频加载做其它处理，可能是原生video内部的逻辑导致，我们关注下这个问题，感谢反馈！
