### ISSUE TITLE
清晰度切换

### ISSUE THREAD

**Issue by Erik5169** [bytedance/xgplayer#343]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

"xgplayer-flv": "^2.2.0-beta.22"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

 macOS系统  chorm 浏览器  
**如何复现问题？ What did you do?**

清晰度切换， 超清 高清 普通， 相互切换的时候，指示不正确，比如： 我从高清切换到超清后，过了一会，清晰度指示自动返回到高清

**您期望的播放器正常行为是？ What did you expect to happen?**

希望清晰度的指示准确，不是跳来跳去
**实际播放器的表现是？ What actually happened?**
指示不准确

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
直播

**Comment by leonardoFu** [comment]
可以提供下flv播放地址，切换/返回的逻辑应该是清晰度插件在维护，可以升级到xgplayer-flv的2.4.1版本试试。此外可以看下切换到的清晰度是否拉流成功
