### ISSUE TITLE
进度条隐藏

### ISSUE THREAD

**Issue by zyr0901** [bytedance/xgplayer#344]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

2.5.5
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓

**如何复现问题？ What did you do?**
'x5-video-player-type': 'h5-page'
ignores: ['progress']
进度条还是回显示

**您期望的播放器正常行为是？ What did you expect to happen?**
进度条不显示

**实际播放器的表现是？ What actually happened?**
进度条还会显示，不设置'x5-video-player-type': 'h5-page'，就会隐藏，但是在安卓全屏的时候又会显示

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
视频教育

**Comment by zhangxin92** [comment]
请问是什么手机和浏览器环境？

**Comment by zyr0901** [comment]
安卓都这样   华为 p10  企业微信

**Comment by zhangxin92** [comment]
> 安卓都这样 华为 p10 企业微信

那是播放器被劫持了，显示的进度条不是xgplayer的，我们无法控制
