### ISSUE TITLE
iOS微信端显示loading，打印complete回调显示视频加载完成，pad端同样

### ISSUE THREAD

**Issue by leehave** [bytedance/xgplayer#347]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
iOS所有端

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS微信内置浏览器，Safari预览正常

**如何复现问题？ What did you do?**
option中设置x5-video-player-fullscreen无效，初次尝试设置preload:auto后视频可以播放，刷新后又无法播放一直显示loading

**您期望的播放器正常行为是？ What did you expect to happen?**
iOS微信端点击播放时加上x5-video-player-fullscreen

**实际播放器的表现是？ What actually happened?**
1、在已配置x5-video-player-fullscreen:false情况下点击播放还是全屏
2、初始化后video无preload属性且iOS端一直显示loading

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zxh126** [comment]
我也遇到同样的问题，在ios版微信中一直转圈圈，在safari浏览器中正常。

**Comment by zxh126** [comment]
解决办法，将xgplayer的版本降级到2.1.6就没问题了。
至于从哪个版本开始有问题的，我没有逐一测试。
https://cdn.jsdelivr.net/npm/xgplayer@2.1.6/browser/index.js

**Comment by zhangxin92** [comment]
> 解决办法，将xgplayer的版本降级到2.1.6就没问题了。
> 至于从哪个版本开始有问题的，我没有逐一测试。
> https://cdn.jsdelivr.net/npm/xgplayer@2.1.6/browser/index.js

这是微信环境的自动播放阻止策略比较特殊导致，在 xgplayer@2.6.15 版本做了兼容，可以试下

**Comment by lizy0329** [comment]
> > 解决办法，将xgplayer的版本降级到2.1.6就没问题了。
> > 至于从哪个版本开始有问题的，我没有逐一测试。
> > https://cdn.jsdelivr.net/npm/xgplayer@2.1.6/browser/index.js
> 
> 这是微信环境的自动播放阻止策略比较特殊导致，在 xgplayer@2.6.15 版本做了兼容，可以试下

你这个版本做了那些改动？我在github源码找不到这个版本
