### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by zyr0901** [bytedance/xgplayer#348]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.5.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
OPPO A59 系统6.0.1 企业微信环境

**如何复现问题？ What did you do?**
https://yongling8808.github.io/test/video_demo/video_gesture.html

**您期望的播放器正常行为是？ What did you expect to happen?**
点击播放，正常播放

**实际播放器的表现是？ What actually happened?**
点击播放，视频不播放，点击暂停，在点击播放，视频才开始播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以截图看下吗？安卓企业微信下播放器可能会被劫持

**Comment by zyr0901** [comment]
可以的，我录制了视频，要怎么给你

**Comment by zyr0901** [comment]
![111111](https://user-images.githubusercontent.com/26737486/77736540-5c322300-7047-11ea-9f7c-c4f7b2e0f74b.png)

**Comment by zhangxin92** [comment]
这里支持发截图

**Comment by zhangxin92** [comment]
可做如下配置使不劫持播放器
'x5-video-player-type': 'h5',
playsinline: false
