### ISSUE TITLE
要支持 mp4 和 flv 格式的视频，该怎么配置呀？

### ISSUE THREAD

**Issue by zhgt1997** [bytedance/xgplayer#349]
xgpalyer 默认支持 mp4 的，但是换成 flv 就不支持了，而且 视频链接都是从后台接口获取的，是需要做哪些配置吗？

**Comment by zhangxin92** [comment]
flv播放见文档 http://h5player.bytedance.com/plugins/#xgplayer-flv-js

**Comment by zhgt1997** [comment]
> flv播放见文档http://h5player.bytedance.com/plugins/#xgplayer-flv-js

你好，我试的就是这个插件，还是播放不了
![image](https://user-images.githubusercontent.com/39938981/78005392-14c0d500-736e-11ea-927e-0b8799cb5f46.png)

**Comment by zhangxin92** [comment]
控制台有报什么错吗？方便的话发下视频流地址

**Comment by zhgt1997** [comment]
> 控制台有报什么错吗？方便的话发下视频流地址

你好，有报错，好像是跨域的问题，图片好像放不上来，我先复制一份错误信息在这里：

Access to fetch at 'http://10.255.21.67:8080/file/static/Newfile/2019/2/1553682255355_%E8%B5%B0%E5%A5%BD%E4%BA%BA%E7%94%9F%E6%AF%8F%E4%B8%80%E6%AD%A5.flv' from origin 'http://localhost:5053' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![image](https://user-images.githubusercontent.com/39938981/78009168-32446d80-7373-11ea-9fdf-2b33b5abe7f3.png)

**Comment by zhangxin92** [comment]
那需要视频源的服务端支持下跨域

**Comment by zhgt1997** [comment]
> 那需要视频源的服务端支持下跨域

那用不用前台做一些配置，就像下面我配的那样，不知道配置的对不对
`dp = new FlvJsPlayer({
            el: that.$refs.dplayer,
            width: "75%",
            height: "450",
            url: viodeUrl,
            poster: picUrl, // 封面
            cssFullscreen: true, // 网页全屏
            hasVideo: true, // 指示流是否有音频轨道
            hasAudio: true, // 指示流中是否有视频轨道
            isLive: false, // 是否直播
            preloadTime: 15, // 预加载时间
            cors: true, // 是否支持跨域
            // flv.js 配置
            flvOptionalConfig: {
              enableWorker: true
            }
          });`

**Comment by zhangxin92** [comment]
服务端支持下cors就好

**Comment by zhgt1997** [comment]
> 服务端支持下cors就好

你好，根据你的答案视频已经解析成功了，但是 使用 xgplayer-flv.js 插件，ie11 和其他浏览器的解析地址不一样，我在 issus 上又提了问题，请问您有遇到过这类问题吗？

**Comment by zhangxin92** [comment]
> > 服务端支持下cors就好
> 
> 你好，根据你的答案视频已经解析成功了，但是 使用 xgplayer-flv.js 插件，ie11 和其他浏览器的解析地址不一样，我在 issus 上又提了问题，请问您有遇到过这类问题吗？

已答复，不影响使用
