### ISSUE TITLE
为什么 xgplayer-flv.js 插件在 ie11 和其他浏览器的解析地址不一样？如何解决？

### ISSUE THREAD

**Issue by zhgt1997** [bytedance/xgplayer#352]
谷歌解析后的地址：
```
<video mediatype="video" tabindex="2" src="blob:http://localhost:5053/4c841950-a668-4e55-9265-8145482d5e9c"></video>
```

ie11 解析后的地址：
```
<video mediatype="video" tabindex="2" src="blob:BDDE0F04-4128-4088-9D5C-35C282451D49"></video>
```

为什么 ie11 就没有服务地址呀?

**Comment by zhangxin92** [comment]
ie11下用MediaSource生成的blob地址就是不太一样，不影响使用

**Comment by zhangxin92** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/MediaSource
可以自己在不同浏览器下参考文档试下

**Comment by zhgt1997** [comment]
> ie11下用MediaSource生成的blob地址就是不太一样，不影响使用

你好，我在项目本地调试，ie11 中是没有问题，但是 使用 nginx 部署到服务器上 ie11 就播放不了视频，其他浏览器都是播放，这应该是 服务的问题吧。。。

**Comment by leonardoFu** [comment]
应该是服务问题。建议使用xgplayer-flv
