### ISSUE TITLE
hls断流后不会触发ended或者error,会一直请求然后404

### ISSUE THREAD

**Issue by JustGogoing** [bytedance/xgplayer#354]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.6.14",
    "xgplayer-hls.js": "^2.1.6",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows  chrome

**如何复现问题？ What did you do?**
hls获取直播流  然后断流就可

**您期望的播放器正常行为是？ What did you expect to happen?**
一直获取不到流的信息 触发ended时间

**实际播放器的表现是？ What actually happened?**
触发wait之后一直在获取流

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by dancci** [comment]
有解决办法了吗？？

**Comment by leonardoFu** [comment]
建议使用xgplayer-hls代替xgplayer-hls.js

**Comment by anfenglei9527** [comment]
请问问题解决了吗 我也遇到相同问题

**Comment by leonardoFu** [comment]
使用xgplayer-hls可以解决这个问题
