### ISSUE TITLE
直播地址使用srcObject直接赋值给video的，如何使用xgplayer

### ISSUE THREAD

**Issue by a761208** [bytedance/xgplayer#356]

**Comment by a761208** [comment]
是否可以直接使用现有的<video...>

**Comment by a761208** [comment]
`new Player({
  video: document.getElementById('video'),
})`

**Comment by zhangxin92** [comment]
xgplayer特殊版本(1.1.8-canary.2)支持这种用法，试下满足需求不
配置 videoDOM: document.getElementById('video')

**Comment by a761208** [comment]
@zhangxin92 能提供以下地址吗

**Comment by zhangxin92** [comment]
> 地址

是指cdn地址吗？
<script src="//cdn.jsdelivr.net/npm/xgplayer@1.1.8-canary.2/browser/index.js" charset="utf-8"></script>
