### ISSUE TITLE
火狐下 不可以切换字幕

### ISSUE THREAD

**Issue by lotofbadcode** [bytedance/xgplayer#357]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
使用在线的工具测试 ：http://h5player.bytedance.com/generate/
本机使用CDN //cdn.jsdelivr.net/npm/xgplayer/browser/index.js

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
WIN10 火狐75.0

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen
正常切换字幕
**实际播放器的表现是？ What actually happened?**
火狐下 没有切换字幕的按钮 Google下正常

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by LRithe** [comment]
@zhangxin92  同问  第一个问题：火狐下 没有切换字幕的按钮 Google下正常，火狐如下图
![image](https://user-images.githubusercontent.com/23411858/81819497-f996d700-9561-11ea-95e2-2ce60f3f7e4e.png)

第二个问题：Google的字幕样式和火狐的还不一样，谷歌如下图
![Uploading image.png…]()

**Comment by lotofbadcode** [comment]
感谢作者的帮助 用/xgplayer@2.6.22 版本就可以了
