### ISSUE TITLE
是否可以通过动态设置参数来使控制条动态显示与隐藏？

### ISSUE THREAD

**Issue by ctrlands** [bytedance/xgplayer#358]
我看文档中通过设置controls的值可以控制控制条的显示与隐藏，是否可以通过动态设置这个值来控制控制条的显示与隐藏呢？我目前是通过xgplayer-controls这个dom节点设置它的display属性可以动态设置显示与隐藏。

**Comment by zhangxin92** [comment]
显示
Player.util.removeClass(player.root, 'xgplayer-inactive')
隐藏
Player.util.addClass(player.root, 'xgplayer-inactive')
