### ISSUE TITLE
APICloud 开发的APP 里使用此播放器，全屏不会自动横屏显示

### ISSUE THREAD

**Issue by jacky8466** [bytedance/xgplayer#359]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**2.3.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?** android10，apicloud内置浏览器

**如何复现问题？ What did you do?**
直接在APICloud 内写html代码即可，然后使用APPLoader 通过手机预览

**您期望的播放器正常行为是？ What did you expect to happen?**
点击全屏后，自动横屏

**实际播放器的表现是？ What actually happened?**
点击全屏后，没有自动横屏

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
全屏是调用系统API，具体全屏表现是由app客户端能力决定

**Comment by jacky8466** [comment]
> 全屏是调用系统API，具体全屏表现是由app客户端能力决定

好的，谢谢
