### ISSUE TITLE
api 中play()方法使用遇到的问题

### ISSUE THREAD

**Issue by jacky8466** [bytedance/xgplayer#360]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?** 2.3.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?** win10 chrome最新版

**如何复现问题？ What did you do?**
正常初始化，自动播放属性关闭，然后通过自定义按钮 调用play()方法，代码如下
`<div id="mse"></div>
		<br />
		<button  onclick="click1()">
			播放
		</div>`
`function click1(){
				player.play();
			}`
**您期望的播放器正常行为是？ What did you expect to happen?**

视频能够正常播放
**实际播放器的表现是？ What actually happened?**
一直显示加载中，如果直接点击自带的播放图标，能正常播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by dongxiaoyong009** [comment]
+1
