### ISSUE TITLE
Why send my site data to your server without my permission？

### ISSUE THREAD

**Issue by wenjichen** [bytedance/xgplayer#361]
I use xgplayer in my vblog. But recently I find a xhr post request send from my site to your server. You can find the request by Chrome DevTools.

![image](https://user-images.githubusercontent.com/20740624/80961337-55b07b80-8e3d-11ea-908a-95e55a814375.png)

I want to know why do this without user permission?  I get the project with **MIT** license. And I also dived into your `Agreement Terms `  which was declaration on README.

Yes I authorize you to place my site LOGO in your website, BUT NOT WITH MY USER'S BROWSER INFO.

I am sorry to say I will remove the package from my site and see other better.

**Comment by zhangxin92** [comment]
This is an advanced and experimental function for optimizing our internal project. You can config 'noLog: true' to close this function.
