### ISSUE TITLE
点击全屏按钮时不是横屏播放

### ISSUE THREAD

**Issue by websrookie** [bytedance/xgplayer#362]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
^2.5.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
小米8 MUI 11.0.6稳定版 微信浏览器

**如何复现问题？ What did you do?**
按照官网步骤实现

**您期望的播放器正常行为是？ What did you expect to happen?**
需要横屏播放功能

**实际播放器的表现是？ What actually happened?**
无法横屏播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
全屏是调用系统API，安卓微信环境下播放器会被劫持，具体全屏表现是由微信提供能力决定
