### ISSUE TITLE
是否支持 SRT 格式的外挂字幕 ？

### ISSUE THREAD

**Issue by lynings** [bytedance/xgplayer#363]
您好，我看[文档](http://h5player.bytedance.com/config/#%E5%A4%96%E6%8C%82%E5%AD%97%E5%B9%95)里提到 播放器支持加载多条WebVTT格式的外挂字幕，但是没有明确提到支不支持 SRT 格式的字幕文件，请问支持 SRT 吗？

**Comment by zhangxin92** [comment]
不支持，github有一些开源的srt转webvtt的工具，可以自己找一下

**Comment by lynings** [comment]
> 不支持，github有一些开源的srt转webvtt的工具，可以自己找一下

了解了解，谢谢
