### ISSUE TITLE
希望能支持各种图标自定义

### ISSUE THREAD

**Issue by mulianju** [bytedance/xgplayer#364]
希望能支持各种图标自定义
还有皮肤自定义的一些options

**Comment by zhangxin92** [comment]
可以通过自定义样式功能实现
http://h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by mulianju** [comment]
谢谢，开始没找到文档，抱歉
