### ISSUE TITLE
切换视频后视频画面会出现短暂的黑屏，没有loading动画

### ISSUE THREAD

**Issue by mogody** [bytedance/xgplayer#365]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.6.19

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome上的iphonex模拟器

**如何复现问题？ What did you do?**
播放视频，然后切换视频 url

**您期望的播放器正常行为是？ What did you expect to happen?**
切换视频后视频画面会出现短暂的黑屏，但是有loading动画，而且加载成功后默认处于暂停状态并且显示播放按钮

**实际播放器的表现是？ What actually happened?**
切换视频后视频画面会出现短暂的黑屏，没有loading动画，而且加载成功后默认处于暂停状态但是没有显示播放按钮，用户就不知道下一步该如何操作才能继续播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以在切换前这样处理
player.autoplay = true
Player.util.addClass(player.root, 'xgplayer-is-enter')
player.src = 'new url'
