### ISSUE TITLE
去何去掉字幕的半透明黑色背景

### ISSUE THREAD

**Issue by LRithe** [bytedance/xgplayer#367]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.6.18", "xgplayer-hls.js": "^2.2.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac 谷歌

**如何复现问题？ What did you do?**
const mp4player = new Player({
        id: 'mp',
        definitionActive: 'click',
        url: 'https://subplayer.js.org/sample.mp4',
        fluid: true,
        fitVideoSize: 'auto',
        textTrack: [
          {
            src: 'https://subplayer.js.org/sample.vtt',
            kind: "subtitles",
            label: "sample",
            srclang: "zh",
            default: true
          },
        ],
        textTrackStyle: {
          "background-color": "transparent",
          "color": "#fff",
          "font-size": "30px",
        },
      })

**您期望的播放器正常行为是？ What did you expect to happen?**
通过配置样式，去掉字幕的背景色

**实际播放器的表现是？ What actually happened?**
修改字幕的背景色（ "background-color": "transparent"），无效果

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
浏览器自带的外挂字幕功能在样式方面自定义能力较弱。
目前xgplayer在开发自研外挂字幕，会支持这方面的能力
