### ISSUE TITLE
请问支持加密drm的mp4和hls视频播放吗?

### ISSUE THREAD

**Issue by HugoLipeng** [bytedance/xgplayer#369]
之前issue有提到：https://github.com/bytedance/xgplayer/issues/71
xgplayer has the ability to play HLS encryption videos(AES and DRM).
方便提供下示例吗？

**Comment by zhangxin92** [comment]
可以用这个链接试下加密HLS播放 https://cdn.theoplayer.com/video/big_buck_bunny_encrypted/stream-800/index.m3u8
