### ISSUE TITLE
import 'xgplayer-mp4'; 后对视频播放的影响很大

### ISSUE THREAD

**Issue by lizy0329** [bytedance/xgplayer#370]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.3.7",
"xgplayer-mp4": "^1.1.8"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome 80

**如何复现问题？ What did you do?**
import 'xgplayer-mp4'; 与 不 import 查看影响

**您期望的播放器正常行为是？ What did you expect to happen?**
跟没有 import 'xgplayer-mp4'; 一样流畅

**实际播放器的表现是？ What actually happened?**
1. 视频流加载经常卡主，无法播放视频
2. 点击全屏，需要黑屏一阵子才能显示画面
3. 播放视频前几秒，会一卡一卡的

测试机器：华为 p30

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
移动端建议直接使用xgplayer

**Comment by lizy0329** [comment]
> 移动端建议直接使用xgplayer

能否写在文档上？不然在移动端使用这个会有很大问题，困扰开发者。

**Comment by zhangxin92** [comment]
> > 移动端建议直接使用xgplayer
> 
> 能否写在文档上？不然在移动端使用这个会有很大问题，困扰开发者。

好的，感谢反馈和建议！
