### ISSUE TITLE
设置currentTime后播放时长正确进度条无效果

### ISSUE THREAD

**Issue by websrookie** [bytedance/xgplayer#372]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
 最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
在webapp中

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
最新版本（2.16.2）没有复现，可以试下
