### ISSUE TITLE
禁止用户快进播放

### ISSUE THREAD

**Issue by littleants707** [bytedance/xgplayer#373]
最近开发一个课程培训的项目，课程视频不希望用户快进播放，防止刷课时。
添加一个配置字段，实现禁止用户快进播放。目前我下载了源码，修改了一段代码后功能实现了。请问修改符合规范吗？另外如何集成到线上？
修改位置：packages/xgplayer/src/control/progress.js 148行 、180行
`
let fastNow = Number(now).toFixed(1)
// 允许快进/后退播放
if (player.config.fastForward) {
    player.currentTime = fastNow
} else { // 禁止快进播放,但是可以后退
    if (player.currentTime >= fastNow) {
         player.currentTime = fastNow
    }
 }
`

**Comment by zhangxin92** [comment]
目前最新版本播放器已支持该功能，设置disableProgress: true
http://h5player.bytedance.com/config/#%E5%85%B6%E5%AE%83%E4%BA%A4%E4%BA%92%E9%85%8D%E7%BD%AE

**Comment by zhangxin92** [comment]
同时关闭键盘快捷键  keyShortcut: 'off'

**Comment by littleants707** [comment]
我现在使用version 2.6.20，是不是版本还是比较低，应该用那个版本，另外用户不能快进但是可以快退，现在只是拖拽，那点击进度条快进播放呢

**Comment by zhangxin92** [comment]
需求比较定制化，建议用自定义样式功能解决 http://h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by littleants707** [comment]
好的，这样是不是就可以修改代码了

**Comment by zhangxin92** [comment]
嗯是的，可以修改UI样式代码
