### ISSUE TITLE
"autoplay": true,设置自动播放无效！

### ISSUE THREAD

**Issue by aruoop** [bytedance/xgplayer#374]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

1.14
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

360极速浏览器
**如何复现问题？ What did you do?**

使用西瓜播放器作为m3u8的解析，点击任何视频都需要手动点击下播放按钮!
**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以试下最新版本（xgplayer@2.16.2 xgplayer-hls.js@2.3.0），所描述问题没有复现
