### ISSUE TITLE
 部分安卓手机不支持playbackRate

### ISSUE THREAD

**Issue by sdliuzhen** [bytedance/xgplayer#375]
player.video.playbackRate = 2 部分安卓手机不支持

**Comment by zhangxin92** [comment]
倍速播放是系统提供的能力，系统本身不支持的话目前没办法解决

**Comment by sdliuzhen** [comment]
那有没有方法判断是否支持playbackRate，这样把不支持的机型，倍速播放按钮给隐藏

**Comment by zhangxin92** [comment]
可以在起播时修改playbackRate（比如player.playbackRate = 1.1），再获取playbackRate看有没有变化，有变化则支持playbackRate
