### ISSUE TITLE
设置了disableProgress禁止进度条拖动交互，在移动端谷歌上好使，QQ浏览器上不好使。

### ISSUE THREAD

**Issue by Counterrr** [bytedance/xgplayer#376]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.7.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
小米 谷歌 QQ浏览器

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
QQ浏览器也能实现disableProgress禁止进度条拖动交互

**实际播放器的表现是？ What actually happened?**
QQ浏览器不能实现disableProgress禁止进度条拖动交互

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
QQ浏览器中播放器会被系统劫持，目前实现不了

**Comment by Counterrr** [comment]
您好 我还想问下，如果我不加这个api，我只给进度条css加个pointer-events: none; 也能实现移动端谷歌浏览器禁止进度条拖动交互，只是QQ浏览器还是实现不了

**Comment by zhangxin92** [comment]
> 您好 我还想问下，如果我不加这个api，我只给进度条css加个pointer-events: none; 也能实现移动端谷歌浏览器禁止进度条拖动交互，只是QQ浏览器还是实现不了

也是因为劫持问题导致
