### ISSUE TITLE
多个视频如何互斥播放呢？

### ISSUE THREAD

**Issue by ywyhero** [bytedance/xgplayer#377]
多个视频如果互斥播放呢？

**Comment by zhangxin92** [comment]
PC端吗？可以自己设置变量记录和更改播放状态

**Comment by ywyhero** [comment]
> PC端吗？可以自己设置变量记录和更改播放状态

手机端，如何监听点击播放时间呢？在文档里面没有找到监听的方法

**Comment by zhangxin92** [comment]
手机端本身支持多视频互斥播放，不用额外处理

**Comment by Counterrr** [comment]
不对手机端谷歌浏览器的话 就可以多视频同时播放了

**Comment by jinsom** [comment]
> 手机端本身支持多视频互斥播放，不用额外处理

安卓不支持，安卓端可以多个视频同时播放，希望官方出一个设置，开启之后，播放下个视频的时候自动停止播放上一个视频，这个真的很重要，现在的用户都很懒

**Comment by zhangxin92** [comment]
> > 手机端本身支持多视频互斥播放，不用额外处理
> 
> 安卓不支持，安卓端可以多个视频同时播放，希望官方出一个设置，开启之后，播放下个视频的时候自动停止播放上一个视频，这个真的很重要，现在的用户都很懒

播放器只应控制自身实例，这个需要具体使用播放器的业务来实现

**Comment by jinsom** [comment]
> > > 手机端本身支持多视频互斥播放，不用额外处理
> 
> > 
> 
> > 安卓不支持，安卓端可以多个视频同时播放，希望官方出一个设置，开启之后，播放下个视频的时候自动停止播放上一个视频，这个真的很重要，现在的用户都很懒
> 
> 
> 
> 播放器只应控制自身实例，这个需要具体使用播放器的业务来实现

一个列表有很多个视频，每个视频都有唯一的id，请问有什么逻辑可以指点一下。通常通过怎么处理。

**Comment by 1414044032** [comment]
我是通过监听scroll 事件，然后判断每个视频组件到页面顶部的距离来实现类似功能，因为一个用户视图中，一般只能看见一个视频
