### ISSUE TITLE
暂停按钮不生效问题

### ISSUE THREAD

**Issue by Rashomon511** [bytedance/xgplayer#379]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
使用最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

ios微信环境下

**如何复现问题？ What did you do?**

ios13版本微信环境下可复现

**您期望的播放器正常行为是？ What did you expect to happen?**

暂停按钮可以暂停视频

**实际播放器的表现是？ What actually happened?**

暂停按钮不生效，

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zwmmm** [comment]
解决了么

**Comment by AkatQuas** [comment]
这里也遇到了，在网页上打开，暂停按钮失效。网页f12 模拟手机的时候就可以了。

**Comment by zhangxin92** [comment]
我这里没有复现，请问有测试链接吗？

**Comment by AkatQuas** [comment]
[测试视频地址](https://play-test3.yunxi.tv/pages/bac95a513d8a4db5862673118fa2ab1d#/)

相关问题原因，[duplicate click and touchend](https://www.google.com.hk/search?safe=strict&hl=zh-CN&sxsrf=ALeKk03qVGEYvEds5GlwnoPY0iQ4CbpVtg%3A1594781353988&source=hp&ei=qW4OX4-6Opv99QOTirW4Bw&q=duplicate+click+and+touchend&oq=duplicate+click+and+touchend&gs_lcp=CgZwc3ktYWIQAzoFCAAQywE6BAgAEB46BggAEAgQHjoGCAAQBRAeOggIABAIEAoQHjoFCCEQoAE6BwghEAoQoAFQrAFYp01ghU9oAHAAeAGAAd0HiAG-PpIBDjAuMTQuMi4xLjEuMy4zmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjPsuPAn87qAhWbfn0KHRNFDXcQ4dUDCAc&uact=5)

可以在这个[`src/control/play.js`](https://github.com/bytedance/xgplayer/blob/master/packages/xgplayer/src/control/play.js#L38) 的函数调用时，增加一个控制变量。
