### ISSUE TITLE
HLS加密视频，第一次播放，点击暂停，视频会自动回退到最开始重新播放，后续再点击暂停就没有这个问题了

### ISSUE THREAD

**Issue by Qsnh** [bytedance/xgplayer#380]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.6.15

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓，微信浏览器

**如何复现问题？ What did you do?**
第一次点击暂停播放

**您期望的播放器正常行为是？ What did you expect to happen?**
暂停应该就停止再哪里了，而不是回退。

**实际播放器的表现是？ What actually happened?**
第一次点击播放，播放进度回退到最开始。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
meedu

**Comment by lushh** [comment]
解决了么？我也遇到了同样的问题~我是PC Chrome

**Comment by zhangxin92** [comment]
最新版本(xgplayer@2.17.12  xgplayer-hls.js@2.4.1)没有复现，感谢反馈！
