### ISSUE TITLE
直播场景下，使用xgplayer-flv插件播放flv。主播关闭直播，flv播放中断，会报错。

### ISSUE THREAD

**Issue by Wan-xh** [bytedance/xgplayer#381]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer-flv": "^2.3.9",
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome

**如何复现问题？ What did you do?**

拉flv流，然后推流端中断，xgplayer-flv播放器报错。
xgplayer-transmuxer-demux-flv/es/index.js: 222
error: Cannot read property 'duration' of undefined

**Comment by Wan-xh** [comment]
![1590211589](https://user-images.githubusercontent.com/24729021/82722408-0e5d3280-9cf9-11ea-9539-bfba24a2d82f.jpg)

**Comment by leonardoFu** [comment]
请升级xgplayer-flv到最新版本，已经对相关行为进行优化，改为触发ended事件
