### ISSUE TITLE
移动端动态生成的 video 会被X5浏览器劫持，导致自定义控制条被原生控制

### ISSUE THREAD

**Issue by lizy0329** [bytedance/xgplayer#383]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.7.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win 10 chrome 80

**如何复现问题？ What did you do?**
配置 'x5-video-player-type': 'h5-page',
正常播放视频

**您期望的播放器正常行为是？ What did you expect to happen?**
自定义控制条正常
（基本上动态生成的 video 都有这个问题）

**实际播放器的表现是？ What actually happened?**
正常播放视频，自定义控制条会被原生代替

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
播放器劫持目前还没有成熟的解决方案

**Comment by lizy0329** [comment]
> 播放器劫持目前还没有成熟的解决方案

是有的，只要在渲染阶段让浏览器知道 video 标签存在即可（属性带上  'x5-video-player-type': 'h5-page'）

同时，你们的 xgPlayer-mp4 v1.1.8  每当 import ‘xgPlayer-mp4’ 就会出现 unhandle Promise rejection: TypeError {}

**Comment by zhangxin92** [comment]
xgplayer-mp4官网上也是用的这个版本 http://h5player.bytedance.com/examples/?type=vod&plugin=xg-mp4，没有报错，看看是不是其它问题？

**Comment by lizy0329** [comment]
> xgplayer-mp4官网上也是用的这个版本 [http://h5player.bytedance.com/examples/?type=vod&plugin=xg-mp4，没有报错，看看是不是其它问题？](http://h5player.bytedance.com/examples/?type=vod&plugin=xg-mp4%EF%BC%8C%E6%B2%A1%E6%9C%89%E6%8A%A5%E9%94%99%EF%BC%8C%E7%9C%8B%E7%9C%8B%E6%98%AF%E4%B8%8D%E6%98%AF%E5%85%B6%E5%AE%83%E9%97%AE%E9%A2%98%EF%BC%9F)

因为我用 react 不知道是否是 react 的渲染机制问题，这个播放器有 react 版本么？

**Comment by zhangxin92** [comment]
也有可能是跨域的问题，需要你排查下
react版本： https://github.com/bytedance/xgplayer-react

**Comment by lizy0329** [comment]
> 也有可能是跨域的问题，需要你排查下
> react版本： https://github.com/bytedance/xgplayer-react

好，谢谢~
