### ISSUE TITLE
安卓部分手机 xgplayer-hls播放不了m3u8格式

### ISSUE THREAD

**Issue by sdliuzhen** [bytedance/xgplayer#384]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.6.5",
    "xgplayer-hls.js": "^2.1.6"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?* *
安卓6 oppo r9s

**如何复现问题？ What did you do?**
视频播放就 请刷新试试

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放视频

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
移动端用xgplayer就可以播放m3u8

**Comment by DarcyXf** [comment]
> 移动端用xgplayer就可以播放m3u8

 移动端iOS直接使用xgplayer没有问题
 安卓端部分浏览器如UC、百度播放不了：
- 机型与系统： 小米8~安卓10
- 同机型下QQ浏览器浏览器、搜狗浏览器可以
- 使用xgplayer、xgplayer+xgplayer-hls、xgplayer+xgplayer-hls.js 均不可以
- 使用aliplayer可以
