### ISSUE TITLE
xgplayer-flv.js在安卓手机正常，苹果不正常

### ISSUE THREAD

**Issue by PoorBE** [bytedance/xgplayer#385]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

2.8.0
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iso

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
fly格式直播可在苹果正常播放

**实际播放器的表现是？ What actually happened?**

安卓机正常，苹果机不能
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
iOS系统对MediaSource兼容性不好，播不了flv

**Comment by PoorBE** [comment]
> iOS系统对MediaSource兼容性不好，播不了flv

好的，晓得了，谢谢

**Comment by EricLye** [comment]
> iOS系统对MediaSource兼容性不好，播不了flv

@zhangxin92 有解决方案吗？xgplayer自家的flv插件能解决吗?
