### ISSUE TITLE
问一下移动端怎么显示音量控制条啊

### ISSUE THREAD

**Issue by PoorBE** [bytedance/xgplayer#386]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

点击音量显示音量控制条可以控制音量
**实际播放器的表现是？ What actually happened?**
只可控制静音和有声音

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
移动端一般都用手机音量按键控制音量
