### ISSUE TITLE
播放视频时点击两次才能播放，第一次点击中间的三角，第二次点击视频，然后才能播放

### ISSUE THREAD

**Issue by wangyupo** [bytedance/xgplayer#388]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
我使用hls.js插件
"xgplayer": "^2.8.2",
 "xgplayer-hls.js": "^2.2.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows10 chrome浏览器

**如何复现问题？ What did you do?**
这个是视频地址：https://record.zhuanwangtong.com/record_hls/agency_10/jzyd_bj_hyl_t_01/2020/06/jzyd_bj_hyl_t_01-20200601144907-20200601160107/video.m3u8?sign=1591090451-8d6JPTuebjchoKXWEKJVpU7vu3L6PG2xHTbJkyBGd38JH3GCW14lo83gURako3pCXrxVGkp6uqP-0-8b80ed4b4e7858c0b6b371bca6de162c

**您期望的播放器正常行为是？ What did you expect to happen?**
点击中间播放后立即播放

**实际播放器的表现是？ What actually happened?**
点击中间三角后，还需要点击视频，需要点击两次才能播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
试下 xgplayer-hls.js@2.2.3 版本

**Comment by wangyupo** [comment]
> xgplayer-hls.js@2.2.3

没有2.2.3版本

![Uploading image.png…]()

**Comment by wangyupo** [comment]
> 试下 xgplayer-hls.js@2.2.3 版本

没有2.2.3版本，请问2.2.3版本什么时候发布？

**Comment by wangyupo** [comment]
> 试下 xgplayer-hls.js@2.2.3 版本

2020.06.04 yarn升级hls.js@2.2.3，点击播放正常，感谢升级。
