### ISSUE TITLE
设置相应id后报错 container id can't be empty

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#389]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.8.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOs chrome

**如何复现问题？ What did you do?**
vue.js 集成报错 container id can't be empty  视频找不到相应id的div
<template>
  <div class="page">
    <div id="player"></div>
    <div class="play-btn" @click="playVideo">播放</div>
  </div>
</template>

<script>
import Player from "xgplayer";
export default {
  name: "VideoPlayPage",
  data() {
    return {
      player: null
    };
  },
  created() {
    this.player = new Player({
      id: "player",
      url:
        "http://s2.pstatp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4",
      playsinline: true,
      autoplay: true,
      muted: true
   });
  },
  methods: {
    playVideo() {
      console.log("player:");
      console.log(this.player);
      this.player.play().then(
        res => {
          console.log(res);
        },
        err => {
          console.log("error: ");
          console.log(err);
        }
      );
    }
  }
};
</script>

<style lang="scss" scoped>
.page {
  width: 100vw;
  height: 100vh;
  background: greenyellow;
  #player {
    width: 750px;
    height: 421px;
    background: white;
  }
  .play-btn {
    width: 200px;
    height: 100px;
    background: dodgerblue;
  }
}
</style>
**您期望的播放器正常行为是？ What did you expect to happen?**
能够正常播放

**实际播放器的表现是？ What actually happened?**
视频画面无法播放 偶尔有声音播放  视频挂在不到相应id的div上

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
在mounted生命周期里实例化播放器

**Comment by pocketChao** [comment]
> 在mounted生命周期里实例化播放器

👍

**Comment by zhuzeliang** [comment]
同样遇到这种问题，vue，当options url发生改变情况下，销毁后，重新new player 会container id can't be empty
