### ISSUE TITLE
关于回调的顺序问题想要请教下

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#390]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer 2.8.3  xgplayer-hls.js 2.2.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS chrome

**如何复现问题？ What did you do?**
![屏幕快照 2020-06-08 下午4 28 30](https://user-images.githubusercontent.com/21028807/84010420-314d3f00-a9a7-11ea-9488-6c6d9b8fcab3.png)
![屏幕快照 2020-06-08 下午4 28 08](https://user-images.githubusercontent.com/21028807/84010428-34482f80-a9a7-11ea-99fc-10cf310661d5.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
本人小白 播放m3u8视频  预期以为的回调顺序是： play  -> canplay、canplaythrough -> timeupdate

**实际播放器的表现是？ What actually happened?**
实际的回调顺序是 play -> timeupdate -> canplay、canplaythrough -> play-> playing
有些疑问为什么初始化ready后只按了一次播放按钮为什么还会走play、playing  感谢大神😆

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以试下最新版本（xgplayer@2.16.2  xgplayer-hls.js@2.3.0），所描述问题没有复现
