### ISSUE TITLE
部分FLV无法播放

### ISSUE THREAD

**Issue by ctck1995** [bytedance/xgplayer#393]
@zhangxin92 请教一下，这里发现有部分的FLV无法正常播放，比如这个：http://natt.yimed.cn:11111/trtc/record/out-av-linenum-110029254-110029254_rec-f-1592210140096-t-1592210174510.flv  非跨域的问题。但是在VLC中是可以正常播放的，这是什么原因呢？

**Comment by jobsofferings** [comment]
@ctck1995 请问这个有解决了吗？

**Comment by jobsofferings** [comment]
现在也出现了这个问题，表现是在这个播放器上间隔性出现error
