### ISSUE TITLE
全屏时iOS系统app套壳、微信公众号获取player.fullscreen结果为false 

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#394]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer-hls.js": "^2.2.3",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS13.0

**如何复现问题？ What did you do?**
全屏时在timeupdate回调 获取player.fullscreen状态，iOS返回false  进入全屏时的requestFullscreen事件也不走   
安卓微信、MacOs Chrome、safari 测试均无问题

**您期望的播放器正常行为是？ What did you expect to happen?**
能正常判断player.fullscreen状态 能正常走进入全屏的事件

**实际播放器的表现是？ What actually happened?**
iPhone原生套壳、微信均不获取不到全屏状态 进入全屏事件也不走

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
试下 xgplayer@2.17.8 版本，没有复现你说的问题
