### ISSUE TITLE
希望视频在播放中，父级可以加上一个唯一的class用于区分，

### ISSUE THREAD

**Issue by jinsom** [bytedance/xgplayer#396]
xgplayer-playing这个class无论暂停还是播放中都会有。
xgplayer-pause 只有暂停的时候有

**Comment by zhangxin92** [comment]
具体是用于区分什么哈？

**Comment by jinsom** [comment]
> 具体是用于区分什么哈？

想获取当前正在播放中的视频的实例。互斥播放我找不到更好的思路，每个视频id都是 “video-唯一id”

**Comment by zhangxin92** [comment]
可以在实例化后自己添加class
Player.util.addClass(player.root, 'video-xxx')
