### ISSUE TITLE
关闭内置控件 start 后,报错

### ISSUE THREAD

**Issue by zhuo-xiang** [bytedance/xgplayer#397]
在初始化 播放器时 想关闭默认的播放按钮, 
但是配置 ignores: ['replay']后 
样式全乱套了

以下是正常状态
<img width="301" alt="WX20200622-011505@2x" src="https://user-images.githubusercontent.com/61954852/85230965-08588f80-b426-11ea-99ce-e7aaeedc62ef.png">
![WX20200622-011439](https://user-images.githubusercontent.com/61954852/85230969-11496100-b426-11ea-8e67-7cffb8670e11.png)

以下是不正常状态
<img width="306" alt="WX20200622-011547@2x" src="https://user-images.githubusercontent.com/61954852/85230977-1dcdb980-b426-11ea-9644-bc109a713ead.png">
![WX20200622-011532](https://user-images.githubusercontent.com/61954852/85230978-21614080-b426-11ea-97ff-8d6dfc97f8c4.png)

**Comment by zhangxin92** [comment]
start控件不支持ignore，可以用css覆盖方式隐藏

**Comment by zhuo-xiang** [comment]
![WX20200623-154112](https://user-images.githubusercontent.com/61954852/85374896-0a2a6c00-b568-11ea-90cb-ef1d251fc78c.png)
![WX20200623-154123](https://user-images.githubusercontent.com/61954852/85374905-0dbdf300-b568-11ea-8535-1bf79fd47ce7.png)
那这个文档里面就应该去除 start控件了. 可以做一下特别说明

**Comment by zhangxin92** [comment]
收到，感谢反馈！
