### ISSUE TITLE
求助：怎么实现从某时间节点开始播放

### ISSUE THREAD

**Issue by PandaAdiz** [bytedance/xgplayer#399]

**Comment by zhangxin92** [comment]
player.once('playing', () => {
  player.currentTime = 3
})

**Comment by PandaAdiz** [comment]
> player.once('playing', () => {
> player.currentTime = 3
> })

感谢，我刚看了进度条控件的源码就知道了。

**Comment by PandaAdiz** [comment]
最后，我是采用监听ready后直接修改进度
player.once("ready", () => {
       player.currentTime = 3
})
