### ISSUE TITLE
how to resolve the problem that Chrome 66 turning off autoplay released in April 2018

### ISSUE THREAD

**Issue by zhangzs000** [bytedance/xgplayer#40]
when i new a xgplayer instance that has a config autoplay: true, but it not auto at chrome.
so i switch the browsers to use firefox. it works.
how to resolve this problem
after i use the play method referencing api documents
player.play()
then chrome has a error:
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first

**Comment by zhangxin92** [comment]
The first question, in Chrome, muted autoplay is always allowed. [See](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)  So autoplay is available in xgplayer with config "volume: 0".

**Comment by zhangzs000** [comment]
operating environment：
mac
chrome 68.0.3440.84（正式版本） （64 位）
i set the config
new Player({
    autoplay: true,
    volume: 0
})
it does not work.
then i add config muted: true,
new Player({
    autoplay: true,
    volume: 0,
   muted: true
})
it still does not work.
when i use firefox
版本 	61.0.1
版本 ID 	20180704003137
at macOS High Sierra
only this config,it can auto play.
new Player({
  autoplay: true
})

**Comment by zhangzs000** [comment]
In my project my video still cant auto play at chrome 68.0.3440.84 on macOS High Sierra, i suspect It be effected the warning message:
Failed to load http://img-test.aixuexi.com/B:1005:K/1532448000/0caeb04be45a4447b9896015eb1bf02c.mp4: Request header field Range is not allowed by Access-Control-Allow-Headers in preflight response.
i add the config: crossOrigin: true
it still has warning
official demo can auto play. it url: http://h5player.bytedance.com/examples/

**Comment by zhangxin92** [comment]
@zhangzs000  If you are trying to use xgplayer with xgplayer-mp4 plugin, your video server should support **range request**. With **range request**, the warning will not happen again. 
The config "crossOrigin: true" is  unnecessary.

**Comment by zhangzs000** [comment]
operating environment：
 mac chrome 68.0.3440.84（正式版本） （64 位）

i remove the the plugin xgplayer-mp4,  no warning "Request header field Range is not allowed by Access-Control-Allow-Headers in preflight response." in chrome now. but it still cant auto play.

so i suspect the reason is asynchronous request then i change the ajax to synchronization，It still cant auto play.

now i dont know why it cant auto play on chrome?

i use xgplayer "version": "1.0.5"  in vue project

**Comment by zhangxin92** [comment]
@zhangzs000  Did you config "volume: 0"?

**Comment by zhangzs000** [comment]
config volume: 0 also didnt work

**Comment by zhangxin92** [comment]
Autoplay in Chrome is supported by [a30892](https://github.com/bytedance/xgplayer/commit/a30892a3caccf46acf717c5c5c892c8e77b97dc4). You can try with the branch now or wait for v1.0.8 as soon as possible.

**Comment by zhangzs000** [comment]
wa, you are  great. Why can official examples auto play in chrome? 
official examples:
http://h5player.bytedance.com/examples/
but it cant autoplay in my project.

**Comment by zhangxin92** [comment]
Chrome calculates MEI score for sites. [policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) [autoplay](https://www.chromium.org/audio-video/autoplay)  When MEI is high enough, media playback without muted is allowed to autoplay on desktop only. Maybe the official site of xgplayer in your Chrome gets a high MEI. 
The autoplay MEI computation method of Chrome is inexplicit for users, so we suggest that you should give up the plan that autoplay without muted.

**Comment by zhangxin92** [comment]
[See your MEI](chrome://media-engagement/)

**Comment by xchz** [comment]
@zhangxin92 `**Chrome calculates MEI score for sites. policy autoplay When MEI is high enough, media playback without muted is allowed to autoplay on desktop only.** `
原来如此....
