### ISSUE TITLE
切换src之后destroy 报错

### ISSUE THREAD

**Issue by zhangwang9li** [bytedance/xgplayer#400]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.5.6和2.9.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 
google浏览器

**如何复现问题？ What did you do?**
直播播放flv
然后切换直播流地址 player.src = newUrl
之后destroy 报错
Cannot read property 'removeAllListeners' of null
    at FlvPlayer.destroy (index.js:7061)

**您期望的播放器正常行为是？ What did you expect to happen?**
正常的destroy

**实际播放器的表现是？ What actually happened?**
不能被终止，直播卡主
报错
Cannot read property 'removeAllListeners' of null
    at FlvPlayer.destroy (index.js:7061)

**Comment by kunkkaliu** [comment]
同样的问题

**Comment by jobsofferings** [comment]
请问现在有解决方案吗？

**Comment by zhangxin92** [comment]
使用的flv插件是xgplayer-flv还是xgplayer-flv.js ？
