### ISSUE TITLE
bug: 音频控制条点击调节音量功能在全屏下点击后切换正常屏幕下出现点击位置错位或失效

### ISSUE THREAD

**Issue by Geekhyt** [bytedance/xgplayer#401]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
^2.9.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS Catalina 10.15.5 
Google Chrome 83.0.4103.116（正式版本）

**如何复现问题？ What did you do?**
音频控制条点击调节音量功能bug

在全屏下点击调节音量大小后切换正常屏幕下出现点击位置错位或失效

**您期望的播放器正常行为是？ What did you expect to happen?**

在全屏和正常屏幕下都可以正常通过点击音频控制条调节音量

**实际播放器的表现是？ What actually happened?**

在全屏下点击调节音量大小后切换正常屏幕下出现点击位置错位或失效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以试下最新版本（2.16.2），我们测试没有复现

**Comment by Geekhyt** [comment]
> 可以试下最新版本（2.16.2），我们测试没有复现

好，有机会试下新版，刚试了下现在西瓜官网没有复现。
