### ISSUE TITLE
当 前一个视频播放ended切换到下一个视频重新new player时 中间的播放按钮不见了 按需求不能设置autoplay：true

### ISSUE THREAD

**Issue by TJX666666** [bytedance/xgplayer#402]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome
**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
正常新建播放器

**实际播放器的表现是？ What actually happened?**
重新构建的播放器 播放按钮不见了 无法播放  
 如果上一个视频没有播放结束就切换的话 是可以正常重构播放器的 如果上一个视频播放ended再切换就不行了
![image](https://user-images.githubusercontent.com/51389459/86113028-4bd48d00-bafb-11ea-8da6-80a5d4ef6c09.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by FrankFan** [comment]
同遇到

Mac + chrome

**Comment by wahxf** [comment]
同问

**Comment by zhangxin92** [comment]
destroy后需要再次实例化的话至少要在下个宏任务里执行实例化操作
