### ISSUE TITLE
chrome 浏览器不支持 flv 播放

### ISSUE THREAD

**Issue by geograous** [bytedance/xgplayer#403]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
1.1.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos 10.15.1
windows

**如何复现问题？ What did you do?**
在 http://h5player.bytedance.com/generate/ 中输入 http://pili-live-hdl.iyundong.me/iyundong-live/5ef80052bad7cf223b58a1d4.flv 不能成功播放
![image](https://user-images.githubusercontent.com/9160851/86226476-5015ae80-bbbe-11ea-8e00-55ddd2d8b127.png)
在 windows 中的edge（非 chrome 内核）能播放，但是延迟会越来越高，一开始几秒，到后来十几秒

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放 flv 视频，延迟不会增加

**实际播放器的表现是？ What actually happened?**
提示解码时发生错误
![image](https://user-images.githubusercontent.com/9160851/86226637-85220100-bbbe-11ea-9de3-014e52ec4f54.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
控制台有什么报错吗？
