### ISSUE TITLE
player.danmu.sendComment 只能送出一条弹幕，而不能多次触发

### ISSUE THREAD

**Issue by X-H-siwan** [bytedance/xgplayer#405]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.3.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows   google

**如何复现问题？ What did you do?**
引入播放器插件后实例化播放器，配置弹幕样式，button点击发送弹幕，弹幕id值自增保证id唯一，

**您期望的播放器正常行为是？ What did you expect to happen?**
可以多次发送弹幕

**实际播放器的表现是？ What actually happened?**
弹幕只有刷新浏览器的第一条才会在弹幕区域显示

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by X-H-siwan** [comment]
`document.getElementById('danmu').onclick = function () {
            let v = document.getElementById('danmutxt').value
            id++;
            console.log(id)
            // player.danmu.play()
            player.danmu.sendComment({
                duration: 5000,
                id: id,
                start: 3000,
                txt: v,
                style: {
                    color: "#ff9500",
                    fontSize: "15px",
                    border: "solid 1px #ff9500",
                    borderRadius: "50px",
                    padding: "5px 11px",
                    backgroundColor: "rgba(255, 255, 255, 0.1)"
                }
            })
        }`
这是我触发弹幕的方式，加上player.danmu.play()的话可以触发两次，不加弹幕就只有一次

**Comment by zhangxin92** [comment]
可以在最新版本播放器（2.16.2）给弹幕项start参数赋值player.currentTime试下
