### ISSUE TITLE
播放器渲染出自己设置的poster图片前显示一个很大的灰色背景色播放图，怎么去掉？

### ISSUE THREAD

**Issue by 1648045459** [bytedance/xgplayer#406]
图片参考百度网址：http://baijiahao.baidu.com/s?id=1670831995947547256&wfr=spider&for=pc
网址中往下数第四张图：大的黑色三角，黑色三角形外面有个黑色圈，背景色为灰色矩形。（统称：灰色背景色播放图）

如果显示播放按钮，播放按钮和灰色背景色播放图同时出现。渲染出自己设置的poster图片后，灰色背景色播放图消失，页面显示播放按钮和poster自定义图。
问题：怎么去掉灰色背景色播放图

H5 播放器嵌入app(安卓，IOS)

**Comment by 1648045459** [comment]
H5使用vue开发。手机 华为mate9 ，IOS 6 系统默认华为浏览器或者设置默认Google浏览器。H5在手机浏览器直接打开没有看到灰色背景色播放图，开发app后点击app链接打开H5播放页面，H5加载数据并渲染后出现，香港服务器，重复出现100%。

**Comment by 1648045459** [comment]
"xgplayer": "^2.9.8",
"xgplayer-hls": "^2.3.12"

**Comment by zhangxin92** [comment]
这是安卓webview默认的播放器背景图，需要app客户端的同学配合修改

**Comment by 1648045459** [comment]
播放器是在H5开发的，不是在app开发的，app是调用H5的页面展示的，这个产生的图片是app的？H5分为上下两部分，上部分是播放器展示部分，下部分展示的是自己数据库返回的数据文本。这个灰色背景图也只是展示在播放器那部分。

**Comment by zhangxin92** [comment]
嗯是app的webview默认带的

**Comment by 1648045459** [comment]
请问这个要怎么改，网上搜索不到对应的资源

**Comment by zhangxin92** [comment]
https://stackoverflow.com/questions/35220624/android-webview-gray-play-button

**Comment by 1648045459** [comment]
好的，我试试。请问这个 出现错误后显示“请刷新试试”这个有对应的事件触发吗？
![image](https://user-images.githubusercontent.com/55174404/86568427-6eedb980-bf9f-11ea-9292-56c7229631dd.png)

**Comment by 1648045459** [comment]
好的，非常感谢 ^_^，我试试

**Comment by Z-web747** [comment]
问题本质是video 标签没设置poster属性，解决方法是增加配置项videoAttributes:{
    poster: 'xxxx'
  }

**Comment by Z-web747** [comment]
设置hideCanplay 可以解决poster:{
          hideCanplay: true,
          poster: 'https://img.moviebox.ltd/img/202411291741498.png'
        }

**Comment by Z-web747** [comment]
import { Events, Plugin, STATES } from 'xgplayer'
const { POSITIONS,  } = Plugin
import './index.less'
export default class ReConect extends Plugin {
  // 插件的名称，将作为插件实例的唯一key值
  static get pluginName() {
    return 'reConect'
  }

  static get defaultConfig () {
      return {
        // 挂载在controls的右侧，如果不指定则默认挂载在播放器根节点上
      }
  }

  constructor (args) {
    super(args)
  }
  
 
  afterCreate () {
    // 对当前插件根节点绑定click事件
    //TODO 插件实例化之后的一些逻辑

    this.player.on(Events.LOAD_START, () => {
        if(this.player.state === STATES.RUNNING) {
        // 已经成功起播进入播放流程
          this.show()
        }
    })

    this.player.on(Events.LOADED_DATA, () => {
        if(this.player.state === STATES.RUNNING) {
        // 已经成功起播进入播放流程
          this.hide()
        }
    })
  }

  destroy () {
  }

  render () {
    return `<div class="xgplayer-load">直播加载中</div>`
  }
} 还可以监听播放器事件 通过插件覆盖
