### ISSUE TITLE
"xgplayer": "^2.9.5",     "xgplayer-hls.js": "^2.2.3"            win10  chrome浏览器   问题：xgplayer destroy 应调用以释放已使用的资源并销毁hls上下文；表现为  多个m3u8的视频切换，切换时我首先destroy掉当前的player  然后 在创建一个 player 进行播放下一个视频 ，发现视频推流有上一个视频和本视频的。播放的是上一个视频。  期望的播放器正常行为：正常播放下一个视频

### ISSUE THREAD

**Issue by wangchuankai** [bytedance/xgplayer#410]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
可以直接使用player.src = newHLS 来切换视频播放的地址

凯撒 <notifications@github.com> 于2020年7月8日周三 上午9:53写道：
