### ISSUE TITLE
同一个m3u8视频源使用hls，生产环境无法播放，其他地址却可以播放

### ISSUE THREAD

**Issue by TJX666666** [bytedance/xgplayer#411]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.8",
"xgplayer-hls": "^2.3.12"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome win10

**如何复现问题？ What did you do?**
同一个m3u8视频源使用hls，生产环境无法播放，其他地址却可以播放 
生产环境无法播放：![image](https://user-images.githubusercontent.com/51389459/86894542-c887ec80-c135-11ea-9655-fcd53e9c7418.png)
在线测试网站可以播放：
![image](https://user-images.githubusercontent.com/51389459/86894603-df2e4380-c135-11ea-8a65-9d2c333894ac.png)

生产环境控制台报错：
![image](https://user-images.githubusercontent.com/51389459/86894665-f79e5e00-c135-11ea-8134-38439a09af28.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
生产环境无法播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
升级下版本到2.3.13试试？

>

**Comment by TJX666666** [comment]
> 升级下版本到2.3.13试试？
> […](#)

升级没用 。。还是报这个错。

**Comment by TJX666666** [comment]
替换成xgplayer-hls.js解决了这个问题
