### ISSUE TITLE
使用xgplayer-flv直播 切换src时切换页面，componentWillUnMount中的destroy失效。

### ISSUE THREAD

**Issue by wuleiGitHub** [bytedance/xgplayer#412]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.8",  "xgplayer-flv": "^2.3.13"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome版本 81.0.4044.138（正式版本）（64 位）

**如何复现问题？ What did you do?**
在和react结合使用时，修改实例src，新的视频流在pending时，切换前端路由，在componentWillUnMount的函数中执行了实例的destroy，页面切换完成后，新的视频流没有正确的被destroy掉，并且出现js报错：TypeError: Cannot read property 'readyState' of null
![企业微信截图_20200709154815](https://user-images.githubusercontent.com/30522437/87012300-a9ec2900-c1fb-11ea-9b8a-7e248969d6a3.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
切换实例的src时切换前端路由，在页面切换完成后，新的视频流正确的被destroy掉

**实际播放器的表现是？ What actually happened?**
触发上述场景后新的视频流没有正确的被destroy掉

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
请升级到xgplayer-flv最新版本，我们引入了AbortController解决了此问题
