### ISSUE TITLE
如何在视频播放前获取视频时长

### ISSUE THREAD

**Issue by Maxfengyan** [bytedance/xgplayer#414]
如何在视频播放前获取视频时长，我在complete监听里获取不到duration，显示NAN，用了settimeout不太准确

**Comment by zhangxin92** [comment]
可以监听canplay或playing

**Comment by Maxfengyan** [comment]
> 可以监听canplay或playing

感谢百忙之中回复，确实好使，但是为啥没在文档里查到这个。。。

**Comment by H-Sven** [comment]
> 可以监听canplay或playing

这两个事件必须点击了播放才会触发， 如何在点击播放前获取到视频duration
