### ISSUE TITLE
部分华为手机微信端 无法全屏播放视频

### ISSUE THREAD

**Issue by hhxiaohei** [bytedance/xgplayer#416]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新版

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓EMUI 10.1.0  微信最新版浏览器

**如何复现问题？ What did you do?**
http://gcs.zjfazhi.com/xg.html 点击这个链接即可复现 苹果和部分安卓手机可以直接全屏播放

**您期望的播放器正常行为是？ What did you expect to happen?**
华为P30,P20 也可以全屏播放

**实际播放器的表现是？ What actually happened?**
华为P30,P20 只可以普通播放 设置配置项和api调用都 无法进入全屏 

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
视频播放

**Comment by hhxiaohei** [comment]
@zhangxin92

**Comment by zhangxin92** [comment]
点击播放器本身全屏按钮不生效吗？另外你这个测试页面在华为P30微信下无法正常打开

**Comment by hhxiaohei** [comment]
现在测试页面在P30显示正常了,点击播放器本身按钮可以全屏,但是无法用api
```js
player.getFullscreen(player.root)
和
player.getCssFullscreen()
```

在 P30 实现自动全屏,有什么办法吗?

**Comment by hhxiaohei** [comment]
全屏的问题我解决了 但是现在退不出去全屏了

**Comment by dyf-0609** [comment]
有人解决了吗，有什么好的解决方案

**Comment by woSihaizi** [comment]
点击本身的全屏按钮不生效怎么解决的？

**Comment by woSihaizi** [comment]
> 全屏的问题我解决了 但是现在退不出去全屏了

怎么解决的

**Comment by woSihaizi** [comment]
> 点击播放器本身全屏按钮不生效吗？另外你这个测试页面在华为P30微信下无法正常打开

红米手机点击播放器本身全屏按钮不生效

**Comment by chaegumi** [comment]
我刚好在做播放时自动全屏，开始方法不对不行，然后这样做就可以，荣耀v30

```

                            player.on('play', function(){
                                player.getFullscreen(player.root)
                            })
```
