### ISSUE TITLE
ios 全屏事件未触发

### ISSUE THREAD

**Issue by nightmaring** [bytedance/xgplayer#417]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.8.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iphone8 IOS 13.5.1  微信自带浏览器

**如何复现问题？ What did you do?**
player.on('requestCssFullscreen',function(){
  console.log(1)
})

**您期望的播放器正常行为是？ What did you expect to happen?**
触发全屏事件

**实际播放器的表现是？ What actually happened?**
未触发

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by nightmaring** [comment]
![image](https://user-images.githubusercontent.com/18131312/87496740-c4ecec00-c686-11ea-8615-94b4e8ca102e.png)

**Comment by zhangxin92** [comment]
试下最新版本（2.16.2），调用系统全屏的话是监听requestFullscreen和exitFullscreen事件
