### ISSUE TITLE
能够实现视频卡顿事件吗？

### ISSUE THREAD

**Issue by tinn2015** [bytedance/xgplayer#419]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
 "xgplayer": "^2.9.5",
  "xgplayer-flv": "^2.3.10",
  "xgplayer-hls": "^2.3.10"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window 10
chrome 83.0.4103.116（正式版本） （64 位）

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

希望能够检测到直播的卡顿
**实际播放器的表现是？ What actually happened?**

无法感知直播过程中卡顿
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
公司内部直播培训

**Comment by zhangxin92** [comment]
可以监听waiting获取播放卡顿情况

**Comment by tinn2015** [comment]
@zhangxin92 确实可以， 谢谢

**Comment by leolei032** [comment]
> @zhangxin92 确实可以， 谢谢

亲测发现waiting在视频完全顺畅反复循环播放也会持续触发

**Comment by leolei032** [comment]
video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 52925.30000001192, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 54495.90000000596, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 56672, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 59125.40000000596, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 66271.69999998808, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 78132.90000000596, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 89247.90000000596, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 93727.09999999404, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 111305.5, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 128883.69999998808, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 146461.69999998808, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 164040.09999999404, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 181618.5, …}
vconsole.min.js:10 video WAITING!! {player: Player2, eventName: 'waiting', originalEvent: Event, detail: {…}, timeStamp: 331906.6999999881, …}

**Comment by leolei032** [comment]
我发现唯一需要注意的是，视频开始播放一定会触发一次waiting，如果是loop 就每次重新开始播放都会触发一次waiting
