### ISSUE TITLE
播放器后台加载一个网址，发生没法连接的错误

### ISSUE THREAD

**Issue by Henry14all** [bytedance/xgplayer#420]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
目前最新版本，CDN加载

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win10 1803  Chrome 85.0.4165.0

**如何复现问题？ What did you do?**
直接加载一个Xgplayer应该就可以复现

**您期望的播放器正常行为是？ What did you expect to happen?**
............

**实际播放器的表现是？ What actually happened?**
.............

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
免了

问题是这样的：
![image](https://user-images.githubusercontent.com/59821569/88245049-41577e80-ccc8-11ea-8070-42cacce4e964.png)
看不到上面图片看这个链接：https://s1.ax1x.com/2020/07/23/Uq1HDP.png
可以看到该资源没法正常加载
我的代码里没有这东东，是不是播放器加载时的东西？
有点拖慢速度

**Comment by zhangxin92** [comment]
是最新版本吗？可以升级到最新版本试下 xgplayer@2.9.10

**Comment by Henry14all** [comment]
换了最新版本，问题解决。
但是西瓜播放器官网的生成器还是老旧的1.1.4版本，最好尽快更新！
