### ISSUE TITLE
播放器 横屏时  控制条为什么不对应改变位置？

### ISSUE THREAD

**Issue by yexinjia** [bytedance/xgplayer#421]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可以在最新版本（2.16.2）试下配置 rotateFullscreen: true 使触发全屏时实现样式全屏横屏，此时不用配置rotate和cssFullscreen
