### ISSUE TITLE
please try to refresh

### ISSUE THREAD

**Issue by lizy0329** [bytedance/xgplayer#424]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.11",
"xgplayer-mp4": "^1.1.8",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓10 
小米 k30 
chrome 84

**如何复现问题？ What did you do?**
移动端正常播放即出现

**您期望的播放器正常行为是？ What did you expect to happen?**
播放视频呢

**实际播放器的表现是？ What actually happened?**
please try to refresh

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by lizy0329** [comment]
回退到 "xgplayer": "^2.6.12" 正常播放

**Comment by lizy0329** [comment]
xgplayer-mp4 也是有问题的，加入后会出现 n.handleReqHeadersSet is not a function 错误，导致无法初始化视频

**Comment by zhangxin92** [comment]
方便提供下视频链接吗？

**Comment by zhangxin92** [comment]
在最新版本(xgplayer@2.17.12  xgplayer-mp4@1.2.2)没有复现，感谢反馈！
