### ISSUE TITLE
m3u8直播模式下，time控件不显示 “正在直播”

### ISSUE THREAD

**Issue by H-Sven** [bytedance/xgplayer#426]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.11",
 "xgplayer-hls": "^2.3.19",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows/chrome

**如何复现问题？ What did you do?**

```
import React, { useState, useEffect } from 'react'
import 'xgplayer'
import HlsPlayer from 'xgplayer-hls'

const XgPlayer = (props) =>  {
  const { id = 'mse', url, isLive = true, autoplay = true, volume = 0, width = '3.7rem', height = '2.12rem' } = props
  const [player, setPlayer] = useState()

  useEffect(() => {
    const xgPlayer = new HlsPlayer({
      id, url, isLive, autoplay, volume, height, width,
    })
    setPlayer(xgPlayer)
  }, [])

  return (
    <div className="xg_player" style={{ width, height, border: 'solid 2px #3862ea' }}>
      <div id={id}>{}</div>
    </div>
  )
}

export default React.memo(XgPlayer)

```

**您期望的播放器正常行为是？ What did you expect to happen?**

time显示正在直播

**实际播放器的表现是？ What actually happened?**

![Snipaste_2020-08-06_16-05-42](https://user-images.githubusercontent.com/26042365/89507210-ca110700-d7fe-11ea-9c07-030aa6918ce5.png)

![1](https://user-images.githubusercontent.com/26042365/89507224-cd0bf780-d7fe-11ea-888d-eeeb369401de.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by TJX666666** [comment]
可以检查下你的m3u8视频源数据是否有结束标签，前端可以尝试通过css本地样式控制显示隐藏

**Comment by H-Sven** [comment]
@TJX666666  m3u8文件没有结束标签

![Snipaste_2020-08-07_12-02-44](https://user-images.githubusercontent.com/26042365/89607881-2713c800-d8a6-11ea-85c0-29a0019a9984.png)


我目前的做法是如果在isLive模式下，就隐藏了time控件,但如果一定要显示的话，这是否是一个BUG
```
ignores: isLive ? ['time', 'progress'] : []
```

**Comment by leonardoFu** [comment]
建议手动传入isLive参数，因为涉及UI的显示、隐藏我们更倾向于放在业务侧来控制。建议升级xgplayer-hls，已经不会自动添加"正在直播"

**Comment by Hnnphone** [comment]
> 建议手动传入isLive参数，因为涉及UI的显示、隐藏我们更倾向于放在业务侧来控制。建议升级xgplayer-hls，已经不会自动添加"正在直播"

isLive: true 并不好使
