### ISSUE TITLE
通过cdn引入xgplayer-hls,报错 'Cannot read property 'util' of undefined'

### ISSUE THREAD

**Issue by H-Sven** [bytedance/xgplayer#427]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

'https://cdn.jsdelivr.net/npm/xgplayer@2.9.12/dist/index.min.js',
'https://cdn.jsdelivr.net/npm/xgplayer-hls@2.3.21/dist/index.min.js'

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows/chrome

**如何复现问题？ What did you do?**

通过cdn引入地址后。播放错误，提示 
 'Cannot read property 'util' of undefined'

**您期望的播放器正常行为是？ What did you expect to happen?**

正常播放直播

**实际播放器的表现是？ What actually happened?**

控制台报错

 'Cannot read property 'util' of undefined'
![Snipaste_2020-08-07_11-11-47](https://user-images.githubusercontent.com/26042365/89606655-1b72d200-d8a3-11ea-8c49-2299e42a5bd8.png)

![2](https://user-images.githubusercontent.com/26042365/89606658-20d01c80-d8a3-11ea-8f8f-9865a2c7b292.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
请检查Player地址的正确加载，升级hls到最近版本，此问题已经解决。
