### ISSUE TITLE
使用xgplayer和xgplayer-hls.js插件，遇到m3u8的视频源解码错误，如何跳过错误，继续下一个ts文件的播放？

### ISSUE THREAD

**Issue by ForestHo** [bytedance/xgplayer#429]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.14","xgplayer-hls.js": "^2.2.3",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

操作系统目前是MacOS，浏览器是Chrome 84.0.4147.105
**如何复现问题？ What did you do?**

就是播放点播的m3u8视频源，遇到解码错误希望能够正确跳过错误的ts片段，继续后面正常ts流的播放，实际播放器停留在"请刷新试试"的页面
**您期望的播放器正常行为是？ What did you expect to happen?**

跳过解码错误
**实际播放器的表现是？ What actually happened?**

显示 请刷新试试
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
就是播放点播的m3u8视频源，遇到解码错误希望能够正确跳过错误的ts片段，继续后面正常ts流的播放，实际播放器停留在"请刷新试试"的页面，

**Comment by ForestHo** [comment]
"xgplayer": "^2.9.14","xgplayer-hls.js": "^2.2.3",这是使用的版本，操作系统目前是MacOS，浏览器是Chrome  84.0.4147.105，就是播放点播的m3u8视频源，遇到解码错误希望能够正确跳过错误的ts片段，继续后面正常ts流的播放，实际播放器停留在"请刷新试试"的页面，我们公司做的在线教育相关，做课堂直播产品的，目前设置currentTime，但是还是不理想，希望你们能够提供解码错误的处理示例代码

**Comment by leonardoFu** [comment]
目前不支持，如果解码错误了，MSE会处于异常状态，建议从视频源角度修复。

**Comment by hongrunhui** [comment]
不能跳过吗？或者暴露请求的hook让我们来判断是否可以跳过

**Comment by zzzzzzdk** [comment]
还不能跳过吗

**Comment by kubbo** [comment]
还不能跳过吗
