### ISSUE TITLE
在Vue项目中接入flv视频流，无法播放视频 

### ISSUE THREAD

**Issue by zoe-996** [bytedance/xgplayer#432]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.14",
"xgplayer-flv.js": "^2.1.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10
chrome/edge/火狐

**如何复现问题？ What did you do?**
使用vue-cli创建vue项目,
![image](https://user-images.githubusercontent.com/58900169/90308736-a6437480-df14-11ea-938c-079e6d41d214.png)
运行后，无法播放。
原生js写的可以正常播放。

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
一直转圈圈

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
建议使用xgplayer-flv播放直播流

**Comment by leonardoFu** [comment]
感觉应该与直播流本身有关，请提供直播流地址我们看看
