### ISSUE TITLE
AES-128 加密 hls视频 播放解密报错

### ISSUE THREAD

**Issue by 657348260** [bytedance/xgplayer#433]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

cdn引用文件版本
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

macos    google浏览器
**如何复现问题？ What did you do?**

100% 出错
**您期望的播放器正常行为是？ What did you expect to happen?**

正常解密播放视频
**实际播放器的表现是？ What actually happened?**
在 http://cdn.jsdelivr.net/npm/xgplayer-helper-utils/es/crypto/index.js 文件中 报错
 Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
解密hls的播放可以暂时使用xgplayer-hls.js，后续xgplayer-hls会完善这块儿的实现🙏
