### ISSUE TITLE
使用hls.js插件 切换清晰度后无法重播

### ISSUE THREAD

**Issue by yanchenning** [bytedance/xgplayer#434]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer 2.9.6
xgplayer-hls.js 2.2.3
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

macos chrome
**如何复现问题？ What did you do?**

切换清晰度后，视频播放完毕后点重播
**您期望的播放器正常行为是？ What did you expect to happen?**
继续以当前清晰度重播

**实际播放器的表现是？ What actually happened?**
不会重播

这个问题我本地修复了，请确认下，这是否是问题，是否属于bug，我这个是否可以提交pr

**Comment by leonardoFu** [comment]
可以提交一个PR我们看下，谢谢！
