### ISSUE TITLE
xgplayer-hls@2.3.21及以上版本，视频播放结束后无法重播

### ISSUE THREAD

**Issue by H-Sven** [bytedance/xgplayer#436]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.14",
 "xgplayer-hls": "^2.3.21",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows/chrome

**如何复现问题？ What did you do?**
使用"xgplayer-hls": "^2.3.21"及以上版本，在视频播放结束后，点击重播按钮，无法重播

使用2.3.19版本是正常的

**您期望的播放器正常行为是？ What did you expect to happen?**

正常重播

**实际播放器的表现是？ What actually happened?**

点击重播按钮，无法重播

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by H-Sven** [comment]
修复了麻烦告知一声

**Comment by leonardoFu** [comment]
已经修复，请升级xgplayer-hls版本~
