### ISSUE TITLE
视频剩余几秒无法加载

### ISSUE THREAD

**Issue by H-Sven** [bytedance/xgplayer#437]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.9.14",
 "xgplayer-hls": "^2.3.19",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows/chrome

**如何复现问题？ What did you do?**
视频缓存条会有几秒无法缓存，导致最后几秒无法播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
视频缓存条会有几秒无法缓存，导致最后几秒无法播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Nibbbbbbbb** [comment]
请教一下，这个问题找到原因了吗

**Comment by leonardoFu** [comment]
已经解决了，可以升级xgplayer-hls版本试试
