### ISSUE TITLE
继承了flv.js的BUG

### ISSUE THREAD

**Issue by samao** [bytedance/xgplayer#438]
版本号失效
https://github.com/bytedance/xgplayer/blob/9298e27841be66b9eb7a018f9b37cc27dfc056d3/packages/xgplayer-flv.js/src/flv/flv.js#L83

worker失效
https://github.com/bytedance/xgplayer/blob/9298e27841be66b9eb7a018f9b37cc27dfc056d3/packages/xgplayer-flv.js/src/flv/core/transmuxer.js#L35

**Comment by samao** [comment]
不支持相对路径

**Comment by leonardoFu** [comment]
建议使用xgplayer-flv，对于flv播放不是很有必要使用web-worker
