### ISSUE TITLE
xgplayer-react unexpected reset Player coursed by the following code

### ISSUE THREAD

**Issue by LPegasus** [bytedance/xgplayer#439]
https://github.com/bytedance/xgplayer/blob/96a30f4668316633df2ab184e44df74e60957b39/packages/xgplayer/src/control/playbackRate.js#L10

This code will change the sort of input config.playbackRate array, which will course xgplayer-react compare code never be true.

It's suggested to copy config before use it.

**Comment by zhangxin92** [comment]
Supported in xgplayer-react@2.3.1 and xgplayer@2.17.10. Thank you for your contributions.
