### ISSUE TITLE
请问这个加载中得状态如何更改，使用的是xgplayer-hls

### ISSUE THREAD

**Issue by 718087538** [bytedance/xgplayer#441]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.11.3",
    "xgplayer-hls": "^2.3.29",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
 windows10  chrome84 

**如何复现问题？ What did you do?**
获取播放地址满时就会出现。或者视频地址慢也会出现。

**您期望的播放器正常行为是？ What did you expect to happen?**
如何更改这个加载中的状态？想更改样式
![image](https://user-images.githubusercontent.com/40202702/93325238-94256080-f849-11ea-9e7a-eb2181433e0b.png)

**实际播放器的表现是？ What actually happened?**
出现了一个不符合网站风格的加载状态，想更改一下。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

这是我的相关配置：
import xgplayer from "xgplayer";
import HlsPlayer from "xgplayer-hls";

      let xgplayer = new HlsPlayer({
        id: "mse",
        useHls: true,
        url: "http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4",
        // url: url,
        playsinline: true,
        whitelist: [""],
        // poster:
        //   "https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3606455796,1434121632&fm=26&gp=0.jpg",
        volume: 0.5,
        autoplay: true,
        lang: "zh-cn",
        // fluid: true,
        playbackRate: [0.5, 1, 1.5, 2],
        keyShortcut: "on",
        // ignores:['loading'],//忽略一些配置
        "x5-video-player-fullscreen": "false"
      });

**Comment by zhangxin92** [comment]
可以通过自定义样式功能实现样式UI自定义
https://v2.h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
