### ISSUE TITLE
Is the video cache based on the browser? If the video is too big, there will be a problem

### ISSUE THREAD

**Issue by Sunny-kai** [bytedance/xgplayer#445]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
The browser will automatically remove the buffer to avoid exceeding the buffering quota.
