### ISSUE TITLE
双击事件响应冒泡到父元素

### ISSUE THREAD

**Issue by miaomiaoG** [bytedance/xgplayer#448]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.11.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS  chrome

**如何复现问题？ What did you do?**
基于 video触发dblclick事件后进入/退出全屏，可通过closeVideoDblclick关闭
设置  closeVideoDblclick:true ,关闭双击全屏和退出全屏，在父元素上绑定了双击事件

**您期望的播放器正常行为是？ What did you expect to happen?**
双击视频位置事件，事件冒泡到父元素，父元素的双击事件进行响应

**实际播放器的表现是？ What actually happened?**
关闭双击进入/退出全屏后 双击视频没有反应

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可在最新版本（2.17.0）配置 closeVideoStopPropagation:true 实现
