### ISSUE TITLE
初始化配置音量为0，但是实际点击播放后有1-2秒是有声音的，然后才静音

### ISSUE THREAD

**Issue by miaomiaoG** [bytedance/xgplayer#449]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.11.6
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS  chrome浏览器

**如何复现问题？ What did you do?**
配置volume:0,点击播放

**您期望的播放器正常行为是？ What did you expect to happen?**
静音播放

**实际播放器的表现是？ What actually happened?**
有1-2秒的声音后才开始静音播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by wzs28150** [comment]
设置"autoplayMuted": true

**Comment by zhangxin92** [comment]
@miaomiaoG 用最新版本（2.16.2）试了下，没有复现，如果还有问题的话可以贴下相关使用代码
