### ISSUE TITLE
更多可供用户配置的一些优化项

### ISSUE THREAD

**Issue by xiaolongyuanzi** [bytedance/xgplayer#45]
在使用插件的过程中，发现几个我需要改动的地方没法用配置项的方式去修改插件默认的配置。比如视频不自动播放时：中间位置上的播放，暂停，重播按钮，我想替换成新的样子，就没法直接改配置去替换。如果下个版本能支持这个简单配置的话，对我来说那就很棒了

**Comment by zhangxin92** [comment]
Supported by [2b47a5](https://github.com/bytedance/xgplayer/commit/2b47a5afd48e6a391e00c2dc9d077eff76abfe5d).
