### ISSUE TITLE
请问视频最开始加载的西瓜视频的页面可以隐藏吗？

### ISSUE THREAD

**Issue by Cynthia0329** [bytedance/xgplayer#451]
![image](https://user-images.githubusercontent.com/30437028/95833386-21d36d80-0d6e-11eb-9fe8-20b126ca8403.png)

这个页面

**Comment by zhangxin92** [comment]
使用最新版本xgplayer@2.12.0不会有这个UI

**Comment by zhaohengheng123** [comment]
自己css换个图片就可以了
