### ISSUE TITLE
IE11环境下BUG

### ISSUE THREAD

**Issue by zhaohengheng123** [bytedance/xgplayer#455]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.12

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 +IE11

**如何复现问题？ What did you do?**
1、正常播放完毕，重播
2、全屏显示问题

**您期望的播放器正常行为是？ What did you expect to happen?**
1、重播，页面正常显示
2、全屏显示，点播放进度条，跳转到对应进度
3、长期播放正常显示

**实际播放器的表现是？ What actually happened?**
1、重播之后，页面残留有新增播放按钮
2、全屏，点选进度，js报错
3、长期播放，页面无法播放，需重启浏览器

**Comment by zhangxin92** [comment]
Fixed in xgplayer@2.17.8
