### ISSUE TITLE
移动H5页面  flv直播  播放器报错

### ISSUE THREAD

**Issue by stywell** [bytedance/xgplayer#456]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer@2.13.0  xgplayer-flv@2.3.36

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
魅族16s andriod9  QQ浏览器8.7  X5 038723GPU-MM   /   iphone7p ios13.7 safari

**如何复现问题？ What did you do?**
http://h5player.bytedance.com/examples/   >>  直播 > flv > 西瓜flv   >>  播放器报错: 请 刷新 试试

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常播放flv直播

**实际播放器的表现是？ What actually happened?**
播放器报错: 请 刷新 试试~  这是您官方使用PC可以正常播放的,在手机下有问题~ 我们的视频云服务使用的阿里云视频

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
暂无

**Comment by leonardoFu** [comment]
移动端不一定支持MSE，建议使用hls格式直播

**Comment by stywell** [comment]
> 移动端不一定支持MSE，建议使用hls格式直播

主要是flv.js可以的~  好吧
