### ISSUE TITLE
如何在播放中切换视频源

### ISSUE THREAD

**Issue by 718087538** [bytedance/xgplayer#457]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.11.3",
    "xgplayer-hls": "^2.3.29",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win10

**您期望的播放器正常行为是？ What did you expect to happen?**
播放中切换视频源

**实际播放器的表现是？ What actually happened?**
无法在播放中切换，报错
![image](https://user-images.githubusercontent.com/40202702/97132088-e038be80-1780-11eb-89ba-32e8422806d9.png)

我的相关代码：
```
<template>
  <div class="box">
    <div id="mse"></div>
  </div>
</template>

<script>
import xgplayer from "xgplayer";
import HlsPlayer from "xgplayer-hls";
import { ChannelRecordCtrol } from "@/api";
import { CUSTOM_EVENT_TYPE } from "../../utils/const_value";

export default {
  data() {
    return {
      count: 0,
      xgplayer: null,
      playList:[],
    };
  },
  methods: {
    //使用HLS播放器
    addPlay(url) {
      this.xgplayer = new HlsPlayer({
        id: "mse",
        useHls: true,
        url: url,
        playsinline: true,
        whitelist: [""],
        volume: 0.5,
        autoplay: true,
        lang: "zh-cn",
        playbackRate: [0.5, 1, 1.25, 1.5, 2],
        keyShortcut: "on",
        controls: true,
        "x5-video-player-fullscreen": "false"
      });
    },
    //使用MP4播放器
    useMp4Play(url) {
      console.log("使用mp4播放器")
      this.xgplayer = new Player({
        id: "mse",
        url: url,
        playsinline: true,
        whitelist: [""],
        volume: 0.5,
        autoplay: true,
        lang: "zh-cn",
        playbackRate: [0.5, 1, 1.25, 1.5, 2],
        keyShortcut: "on",
        controls: true,
      });
    },
    getVideoUrl() {
      ChannelRecordCtrol.getRecordInfoList({
        params: {
          // recordId: "755082227963920384",
          recordCode: "PKC2020101509552",
          appType:2
          // recordId: this.getQueryVariable("recordId")
        }
      }).then(res => {
        this.playList = res.result.recordList;

        this.$store.dispatch( "rePlay/setChapterList", res.result.recordList);
        this.$store.dispatch( "rePlay/setNotice", res.result.announcement);
        let playUrl = res.result.recordList[0].fileUrl;

        let index = playUrl.indexOf("mp4");
        if (index > -1) {
          this.useMp4Play(playUrl);
        } else {
          this.addPlay(playUrl);
        }
      });
    },
    //取url参数
    getQueryVariable(variable) {
      var query = window.location.search.substring(1);
      var vars = query.split("&");
      for (var i = 0; i < vars.length; i++) {
        var pair = vars[i].split("=");
        if (pair[0] == variable) {
          return pair[1];
        }
      }
      return false;
    },
   
   //改变播放的章节,即播放地址
    changeReplay(n){
      let playUrl = this.playList[n].fileUrl;

      console.log("改变播放地址",playUrl);
      this.xgplayer.src = playUrl;
    }
  },
  mounted() {
    this.getVideoUrl();
    this.$bus.$on(CUSTOM_EVENT_TYPE.CHANGE_REPLAY,this.changeReplay);
  }
};
</script>
```

**Comment by 718087538** [comment]
这是切换时的一些报错提示：
index.min.js?9376:1 Uncaught TypeError: Cannot read property 'downloaded' of undefined
    at i.value (index.min.js?9376:1)
    at i.value (index.min.js?9376:1)
    at y (index.min.js?9376:1)
    at d.emit (index.min.js?9376:1)
    at e.value (index.min.js?9376:1)
value @ index.min.js?9376:1
value @ index.min.js?9376:1
y @ index.min.js?9376:1
d.emit @ index.min.js?9376:1
value @ index.min.js?9376:1
timeupdate (async)
value @ index.js?5392:1
eval @ index.min.js?9376:1
Promise.then (async)
set @ index.min.js?9376:1
changeReplay @ rePlayer.vue?ea02:96
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
play @ ReChapter.vue?c37c:38
click @ ReChapter.vue?1ea2:17
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
4index.min.js?9376:1 Uncaught TypeError: Cannot read property 'downloaded' of undefined
    at i.value (index.min.js?9376:1)
    at i.value (index.min.js?9376:1)
    at y (index.min.js?9376:1)
    at d.emit (index.min.js?9376:1)
    at e.value (index.min.js?9376:1)

**Comment by 718087538** [comment]
我先destroy，然后1s后在重新生成播放器，暂时解决了这个问题。
   //改变播放的章节,即播放地址
    changeReplay(n){
      let playUrl = this.playList[n].fileUrl;
      this.xgplayer.destroy();
      // console.log("改变播放地址",playUrl);
      // this.xgplayer.src = playUrl;
      this.index =n;
      setTimeout(()=>{
         this.getVideoUrl();
      },1000)
    }

**Comment by leonardoFu** [comment]
请升级xgplayer-hls到2.4.1版本，src切换功能已经稳定，不会出现js报错。

**Comment by alleniverson33** [comment]
xgplayer-hls.js   src切换也有问题

**Comment by lfzs** [comment]
> xgplayer-hls.js src切换也有问题

https://github.com/bytedance/xgplayer/blob/687b4f6a2e1ca67a9428e82a91a9add60c3c809f/packages/xgplayer-hls.js/src/index.js#L62

切换 src 后会自动 autoplay

如果是通过点击行为触发的，切换正常，反之在浏览器不允许自动播放的情况下，切换 src 可能会不成功

可以手动修改源码注释掉切换 src 后 autoplay，在切换 src 成功后，调用 play() 触发播放
