### ISSUE TITLE
拖动控制条，剩余视频不足15s会误触发ended事件

### ISSUE THREAD

**Issue by 718087538** [bytedance/xgplayer#458]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
   "xgplayer": "^2.11.3",
    "xgplayer-hls": "^2.3.29",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
WIN10 chrome84

**如何复现问题？ What did you do?**
使用的是HlsPlayer播放m3u8，拖动进度条，剩余进度不足15s会误触发ended事件

**您期望的播放器正常行为是？ What did you expect to happen?**
期望播放完毕才触发ended事件。

**实际播放器的表现是？ What actually happened?**
误触发ended事件

相关代码：
```
    //使用HLS播放器
    addPlay(url) {
      this.xgplayer = new HlsPlayer({
        id: "mse",
        useHls: true,
        url: url,
        playsinline: true,
        whitelist: [""],
        volume: 0.5,
        autoplay: true,
        lang: "zh-cn",
        playbackRate: [0.5, 1, 1.25, 1.5, 2],
        keyShortcut: "on",
        controls: true,
        "x5-video-player-fullscreen": "false"
      });
      this.xgplayer.on("ended",()=>{
        console.log("播放结束");
      })
    },
```
表现：点击拖动进度条到尾部，不足15s时，多次触发ended事件。
![image](https://user-images.githubusercontent.com/40202702/97145271-e6d72e00-17a0-11eb-87fc-c93f8b43106b.png)

**Comment by leonardoFu** [comment]
请更新xgplayer-hls版本到最新版本（2.4.1）即可解决此问题。
