### ISSUE TITLE
修改currentTime后，播放器seek到了指定的时间，但是进度条已播放的部分没同步变化。

### ISSUE THREAD

**Issue by JohnhanLiu** [bytedance/xgplayer#459]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
`3.0.0-alpha.55-1`

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
OS: `Mac OS Catalina 10.15.7`
Browser: `Google Chrome Version 86.0.4240.111 (Official Build) (x86_64)`

**如何复现问题？ What did you do?**
直接修改播放器实例的currentTime
eg. `player.currentTime = 50`

**您期望的播放器正常行为是？ What did you expect to happen?**
进度条的已播放部分，应该跳到`50`处。

**实际播放器的表现是？ What actually happened?**
进度条的已播放部分没变化。
![image](https://user-images.githubusercontent.com/24789328/97557471-c8c63380-1a15-11eb-8d6e-753feeb4da66.png)

**Comment by JohnhanLiu** [comment]
@hongqiongxing-b

**Comment by zhangxin92** [comment]
这个属于内测版本，请根据文档使用latest版本

**Comment by slj0917** [comment]
求助：请问问题处理了吗 @JohnhanLiu
