### ISSUE TITLE
请问有没有nuxt使用西瓜播放器的示例

### ISSUE THREAD

**Issue by 965390267** [bytedance/xgplayer#460]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by wangyh-quuo** [comment]
可以使用cdn引入,在nuxt.config.js中配置script
```js
head: {
    script: [
      { src: '//cdn.jsdelivr.net/npm/xgplayer@2.9.6/browser/index.js' },
      { src: '//cdn.jsdelivr.net/npm/xgplayer-hls/dist/index.min.js' },
      { src: '//cdn.jsdelivr.net/npm/xgplayer-flv/dist/index.min.js' }
    ]
  }
```
然后就按照西瓜视频文档操作了

**Comment by balck-paint** [comment]
@wangyh-quuo 请问只能使用cdn的方式引入吗

**Comment by wangyh-quuo** [comment]
> @wangyh-quuo 请问只能使用cdn的方式引入吗

可以判断一下当前环境是不是client，仅在client下导入组件。
`
if (process.client) {
  const player =  require('xgplayer')
}
`
参考nuxt文档: [https://nuxtjs.org/docs/concepts/server-side-rendering#window-or-document-undefined](https://nuxtjs.org/docs/concepts/server-side-rendering#window-or-document-undefined)
