### ISSUE TITLE
xgplayer-dash 视频源链接拼接错误

### ISSUE THREAD

**Issue by DirectLinkSs** [bytedance/xgplayer#462]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

xgplayer-dash@1.1.7
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

widows10 chrome
**如何复现问题？ What did you do?**

加载mpd文件
**您期望的播放器正常行为是？ What did you expect to happen?**

正常加载BaseURL
**实际播放器的表现是？ What actually happened?**

BaseURL链接拼接错误，当BaseURL链接为绝对地址时，依然错误拼接地址。
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
![QQ截图20201105230444](https://user-images.githubusercontent.com/17827407/98258842-5082e380-1fbc-11eb-8877-857b95dd5433.png)

**Comment by zhangxin92** [comment]
对于特殊mpd格式可以使用xgplayer-shaka插件，兼容性更好；xgplayer-dash插件的特点是更轻量
