### ISSUE TITLE
能让控制条一直显示吗？

### ISSUE THREAD

**Issue by Yuriuh** [bytedance/xgplayer#463]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
^2.13.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS 和 chrome

**如何复现问题？ What did you do?**
常规使用即可复现

**您期望的播放器正常行为是？ What did you expect to happen?**
控制条一直显示

**实际播放器的表现是？ What actually happened?**
控制条会自动隐藏，点击 视频控件 的空白区域控制条显示，过几秒自动隐藏

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
可在最新版本（2.16.2）通过设置 closeInactive: true 使播放器控制栏常驻不隐藏
