### ISSUE TITLE
destroy之后，再new 一个player ，controlBar 会消失

### ISSUE THREAD

**Issue by imricky** [bytedance/xgplayer#466]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer：2.13.1
xgplayer-hls.js： 2.2.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS 10.15.5

**如何复现问题？ What did you do?**
destroy之后，再手动new一个新的player，控制条controlBar会消失

**您期望的播放器正常行为是？ What did you expect to happen?**
destroy之后，再手动new一个新的player，控制条controlBar不会消失

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
destroy之后需要至少在下个宏任务里重新实例化
