### ISSUE TITLE
直播视频流在正常加载，视频却一直loading。

### ISSUE THREAD

**Issue by HUGY1** [bytedance/xgplayer#467]
描述：当播放一条直播流只有音频（画面是蓝屏），不断进入loading状态，流数据是正常加载的
ps: flvjs查看没问题，依然流畅直播

您使用的西瓜播放器版本是多少？ What version of xglayer are you using?
xgplayer-flv.js 2.1.2

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
win10
Browser: Google Chrome

如何复现问题？ What did you do?
播放一条没有画面（我的是蓝屏）的视频直播流

您期望的播放器正常行为是？ What did you expect to happen?
视频直播正常进行

实际播放器的表现是？ What actually happened?
不断在loading。偶尔会正常播放1秒左右，然后又进行loading。（视频流在正常加载中）

**Comment by HUGY1** [comment]
xgplayer-flv升级到最新版本 3.5.47后没问题了。原因未知

**Comment by guidetheorient** [comment]
使用 flv.js 和 nodemedia.js 都可以播放，但是用 xgplayer + xgplayer-flv 一点反应页没有，拿官网的 demo 换个地址都没用？？:cry:

**Comment by leonardoFu** [comment]
贴一下拉流地址我们看下？
