### ISSUE TITLE
视频在后端已被设置为可跨域，但是截图失败

### ISSUE THREAD

**Issue by wj20160318** [bytedance/xgplayer#468]
截图模块中是对图片设置crossOrigin为anonymous，但是drawImage的第一个参数是video，所以是不是应该给video设置crossOrigin为anonymous才对。我改完之后测试是ok的。
![image](https://user-images.githubusercontent.com/25459133/100561197-14108200-32f3-11eb-800e-c98d951c53e9.png)

**Comment by zhangxin92** [comment]
最新版本（2.17.0）已优化，感谢反馈
