### ISSUE TITLE
IOS断网重连后播放时，loading圈一直存在

### ISSUE THREAD

**Issue by honal** [bytedance/xgplayer#469]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.13.1"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios微信自带浏览器和safari

**如何复现问题？ What did you do?**
正常播放断网，待缓冲数据播放完后会显示loading圈，恢复网络后开始播放，loading圈就一直存在了（断开和恢复网络是通过切换飞行模式实现的）

**您期望的播放器正常行为是？ What did you expect to happen?**
恢复播放后loading圈消失

**实际播放器的表现是？ What actually happened?**
恢复播放后loading圈一直在

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by XFJ712** [comment]
请问此问题如何处理的？
