### ISSUE TITLE
页面播放控制icon就会消失

### ISSUE THREAD

**Issue by xiaopengtang** [bytedance/xgplayer#471]
版本：v2.14.4
步骤：如果视频播放完毕之后，直接重新实例化当前播放器，页面icon就消失
排查：player.root该dom元素当中className为replay的类名没有被释放，而xgplayer-ended类名却被释放，破坏replay功能的完整性

**Comment by zhangxin92** [comment]
最新版本(2.16.2)有优化replay类名没有被释放的问题，可以试下还能否复现
