### ISSUE TITLE
npm包太大，有没有简易版的？

### ISSUE THREAD

**Issue by Drowned-fish** [bytedance/xgplayer#473]
npm包太大，有没有简易版的？

**Comment by aepay** [comment]
貌似没有, 我也是头疼,  一个js300kb了, 单独拿出来打包都大. .   不知道怎么设置延迟加载..  现在直接在首屏加载,, 卡的一B

**Comment by zhangxin92** [comment]
已支持轻量级使用方式，详见官网 “快速上手”->“轻量级使用”
https://v2.h5player.bytedance.com/gettingStarted/#%E8%BD%BB%E9%87%8F%E7%BA%A7%E4%BD%BF%E7%94%A8
