### ISSUE TITLE
西瓜播放器flv拉流重试创建多个拉流地址

### ISSUE THREAD

**Issue by wenjing111** [bytedance/xgplayer#474]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer-flv": "^2.3.48", "xgplayer-hls.js": "^2.3.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows  chrome
**如何复现问题？ What did you do?**
rtmp://58.200.131.2:1935/livetv/cctv2 使用这个地址 在一段时间内没有拉到流,会重试创建新的拉流地址,导致资源占用,销毁后只能停止最后一次的拉流地址
**您期望的播放器正常行为是？ What did you expect to happen?**
在重试时,结束上一次的拉流尝试

**实际播放器的表现是？ What actually happened?**
每一个新创建的拉流地址都会拉流

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
804607505@qq.com

**Comment by leonardoFu** [comment]
请使用http协议拉流地址？
