### ISSUE TITLE
在手机浏览器播放器ui表现不一致

### ISSUE THREAD

**Issue by chenguzhen87** [bytedance/xgplayer#478]

**Comment by chenguzhen87** [comment]
oppo微信打开
![image](https://user-images.githubusercontent.com/28331609/103201435-dcfdb280-492a-11eb-8ec5-273cbde6ec6b.png)
oppo自带浏览器打开
![image](https://user-images.githubusercontent.com/28331609/103201465-ed159200-492a-11eb-8f16-ce2179e7df4a.png)

为什么会出现表现不一样呢？

**Comment by trtrtr6** [comment]
国产浏览器会劫持video标签，替换成自己的video播放器，甚至有的可能还会在播放结束后添加广告

**Comment by chenguzhen87** [comment]
谢谢
