### ISSUE TITLE
视频为播放状态，修改URL后自动播放新的视频，点击暂停新的视频播放时间又回到了初始位置0

### ISSUE THREAD

**Issue by wangyh-quuo** [bytedance/xgplayer#479]
当前视频为播放状态，使用player.src = ‘new url’后自动播放新的视频，点击暂停新的视频播放时间又回到了初始位置0

**Comment by zhangxin92** [comment]
这是默认逻辑，要实现你描述的需求可以这样处理：
let currentTime = player.currentTime
player.once('playing', () => {
    player.currentTime = currentTime
})
player.src = 'new url'
