### ISSUE TITLE
为什么两个flv地址一个能播放一个不能播放？不能播放显示please try to，是因为FLV不是标准的吗?其中一个是SRS存储的FLV

### ISSUE THREAD

**Issue by dunkboy** [bytedance/xgplayer#480]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.11

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10
Google
**如何复现问题？ What did you do?**
西瓜示例播放
正常播放的时候浏览器响应是这样的
![image](https://user-images.githubusercontent.com/26020957/104268514-0a239680-54cf-11eb-9e8c-c544510fd8ac.png)
不能播放的时候 浏览器是这样的
![image](https://user-images.githubusercontent.com/26020957/104268567-2aebec00-54cf-11eb-8dc8-1af40cd0309a.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
please try to 

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
chrome对于大于5M的内容不提供preview，可能是这个原因。可以确认下该flv文件是否有效？
