### ISSUE TITLE
注销事件不起作用

### ISSUE THREAD

**Issue by wangyh-quuo** [bytedance/xgplayer#484]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**如何复现问题？ What did you do?**
watch: {
  url() {
    player.off('pause', () => {
        console.log('off pause')
      })
    this.player.src = this.url
    player.on('pause', () => {
       // ...
        console.log('pause')
    })
   }
}

**您期望的播放器正常行为是？ What did you expect to happen?**

注销事件

**实际播放器的表现是？ What actually happened?**

切换播放源没有注销事件，会触发多个pause事件。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
这样试下

let onPause = function() {
    console.log('off pause')
}
player.on('pause', onPause)
//......
player.off('pause', onPause)
