### ISSUE TITLE
当flv流一直pending无数据推送时，会重新尝试请求流，并且已pending的请求不会停止，没有事件捕捉到。

### ISSUE THREAD

**Issue by HUGY1** [bytedance/xgplayer#485]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.3.47

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chorme

**如何复现问题？ What did you do?**
整一条不太正常的流，我也不知道服务端出什么错，只要一直pengding无数据推送

**您期望的播放器正常行为是？ What did you expect to happen?**
可以规则地触发onError事件

**实际播放器的表现是？ What actually happened?**
不规则触发onError事件，有时不触发一直重发请求。

虽然说流有一定问题。但是不稳定的onError事件让业务变得难以处理。而且重发flv请求导致多个flv请求同时pending感觉很怪异。希望可以改善

**Comment by HUGY1** [comment]
ps： 西瓜demo也会如此

**Comment by leonardoFu** [comment]
错误的逻辑是这样的：
1. 播放器会有拉流10S超时的逻辑，10S未拉到流就会重发拉流请求
2. 可以传入retry: { count: 重试次数, delay: 重试间隔 } 调整重试的逻辑
3. 应该找CDN调整降低下，降低pending到下发错误码的时长
4. 我们调研下flv拉流重发请求能不能把之前的请求主动断开

**Comment by leonardoFu** [comment]
确认了一下，pending状态下的请求似乎不能用abortController进行中断，请从降低重试次数与服务端的pending超时时长方面解决问题。
