### ISSUE TITLE
我想隐藏掉下方控制栏里面的某些按钮，比如“播放/暂停”、“进度条”、“播放时间/总时间”，应该怎么做？

### ISSUE THREAD

**Issue by EricShen-ESStudio** [bytedance/xgplayer#487]
我想隐藏掉下方控制栏里面的某些按钮，比如“播放/暂停”、“进度条”、“播放时间/总时间”，应该怎么做？

覆盖css？还是重新继承覆盖原有插件？
如果是css覆盖的话，请问应该覆盖哪些css？

谢谢

**Comment by zhangxin92** [comment]
播放器配置 ignores: ['play', 'progress', 'time']

**Comment by EricShen-ESStudio** [comment]
> 播放器配置 ignores: ['play', 'progress', 'time']

已经找到了，谢谢
