### ISSUE TITLE
安全问题-资源注入

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [bytedance/xgplayer#488]
你好，这里存在一处安全问题，可能会导致资源注入的问题：
https://github.com/bytedance/xgplayer/blob/d22d2b427a5ed779d627165841d840aa9df26253/packages/xgplayer/src/utils/util.js#L289-L298

289行为污点，298行为爆发点，建议对url添加白名单进行校验

参考：https://cwe.mitre.org/data/definitions/99.html

**Comment by zhangxin92** [comment]
这个工具方法目前没有在播放器使用，后续代码更新会考虑移除，感谢反馈！
