### ISSUE TITLE
画中画有时候无法拖动是怎么回事？

### ISSUE THREAD

**Issue by EricShen-ESStudio** [bytedance/xgplayer#489]
画中画有时候无法拖动是怎么回事？

无法拖动时也没有报错，请问有哪些可能导致画中画无法拖动的情况，谢谢

**Comment by EricShen-ESStudio** [comment]
同一个页面中有两个西瓜播放器，其中一个可以在画中画模式下自由拖动，另外一个打开画中画后，点击这个画中画但是拖动不了？
使用原生的video标签就都可以自由拖动

**Comment by zhangxin92** [comment]
试下 xgplayer@2.17.7 版本
