### ISSUE TITLE
请问mp4到FMP4是怎么实现的呢

### ISSUE THREAD

**Issue by Guohjia** [bytedance/xgplayer#49]

**Comment by oldmtn** [comment]
1. 提取mp4中的moov并解析得到一系列的samples的映射表；
2. 根据此表，获取一系列的samples；
3. 下载一系列的samples，然后组装成fmp4的segment（moof，mdat）；
4. 直接塞给MSE来播放；

**Comment by zhangxin92** [comment]
First you should know the format of mp4 and fmp4 in detail. Then read the source code of xgplayer and xgplayer-mp4 :smile:

**Comment by Guohjia** [comment]
感谢两位，但是对于一个无音视频底层基础的前端开发来说，想要使用MSE，学习成本就这么高吗 @zhangxin92 @oldmtn

**Comment by zhangxin92** [comment]
@Guohjia  If you have already used the html5 video or xgplayer, you satisfy the basic requirements for studying or using MSE. With the open source code, the difficulty of studying depends on yourself.
