### ISSUE TITLE
hls断流请求404后不会触发ended或者error，应该怎样捕获？

### ISSUE THREAD

**Issue by anfenglei9527** [bytedance/xgplayer#491]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.17.3",
"xgplayer-hls.js": "^2.4.0",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows chrome

**如何复现问题？ What did you do?**
使hls获取的直播流 断流

**您期望的播放器正常行为是？ What did you expect to happen?**
断流后能够 捕获错误 触发事件

**实际播放器的表现是？ What actually happened?**
断流后没反应

` this.playerHls = new HlsJsPlayer({
        //初始化实例对象HlsJsPlayer
        id: "hlsmse",
        autoplay: true,
        url: this.playerConfig.url,
        poster: this.playerConfig.poster,
        useHls: true,
        height: window.innerHeight * (5 / 7),
        width: window.innerWidth * (4 / 7),
        crossOrigin: false,
        cors: false,
        errorTips: `请<span>刷新</span>试试`,

        networkState: [
          () => {
            config.log("报错1");
          },
        ],
        playbackRate: [0.5, 0.75, 1, 1.5, 2], // 当前播放速度
        error: [
          () => {
            config.log("报错");
          },
        ],
      });
      this.playerHls.on("play", function () {
        //注册并监听播放事件
        console.log("播放了");
      });
      this.playerHls.on("pause", function () {
        //注册并监听暂停事件
        console.log("暂停了");
      });
      this.playerHls.on("error", function () {
        //注册并监听错误事件
        console.log("报错了");
      });
      this.playerHls.once("complete", () => {
        console.log("complete");
      });
      this.playerHls.once("ready", () => {
        console.log("ready");
      });`

**Comment by leonardoFu** [comment]
建议使用xgplayer-hls来进行直播，断流会触发ended

**Comment by 88xu** [comment]
> this.playerHls.on("play", function () {
>     //注册并监听播放事件
>     console.log("播放了");
>   });
>   this.playerHls.on("pause", function () {
>     //注册并监听暂停事件
>     console.log("暂停了");
>   });

在mac os系统中没有触发ended事件
