### ISSUE TITLE
 Cannot read property 'addEventListener' of null     at replay.js:34  自定义样式引入js没有出现视频

### ISSUE THREAD

**Issue by Carrie999** [bytedance/xgplayer#492]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

2.15.0
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

chrome
**如何复现问题？ What did you do?**
px xgplayer eject [targetDir] 
import './.xgplayer/skin/index.js';

**您期望的播放器正常行为是？ What did you expect to happen?**
不报错，出现视频

**实际播放器的表现是？ What actually happened?**

报错，不出现视频
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

抖音

**Comment by zhangxin92** [comment]
没有配置好 raw-loader

**Comment by Carrie999** [comment]
> 没有配置好 raw-loader

添加 loader后好了，但是样式还是紊乱

**Comment by Carrie999** [comment]
传入的宽度和高度不起作用了

**Comment by zhangxin92** [comment]
你是bytedance员工吗？

**Comment by Carrie999** [comment]
是啊

**Comment by zhangxin92** [comment]
内部直接沟通吧 zhangxin.frontend

**Comment by Carrie999** [comment]
样式紊乱添加全局 global ，问题已解决

**Comment by pocketChao** [comment]
> 样式紊乱添加全局 global ，问题已解决

麻烦问下如何配置好的呢
