### ISSUE TITLE
closeVideoPreventDefault 参数不在 types 中

### ISSUE THREAD

**Issue by fly3949** [bytedance/xgplayer#493]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
v2.3.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows 10, Chrome 87

**如何复现问题？ What did you do?**
使用 TypeScript，新建 Player 对象时使用 `closeVideoPreventDefault` 属性报错，提示：
```
import XGPlayer from 'xgplayer'
const player = new XGPlayer({
  ......
  closeVideoPreventDefault: true, // TS2345: 'closeVideoPreventDefault' does not exist in type 'IPlayerOptions'
  ......
})
```

**Comment by zhangxin92** [comment]
Fixed in xgplayer@2.17.6
