### ISSUE TITLE
IE11 http-flv问题

### ISSUE THREAD

**Issue by Aidot** [bytedance/xgplayer#497]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.14.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 ，IE11

**如何复现问题？ What did you do?**
请求播放HTTP-FLV直播资源

****
未引入promise、fetch polyfill前，提示： Headers未定义
***
引入后：
require('es6-promise').polyfill();
require('isomorphic-fetch')

F12调试——网络栏：FLV GET 请求被挂起。
响应正文：此资源没有响应负载资源
请求正文：此资源没有请求负载资源

复制FLV URL地址到VLC播放器中可正常播放。

**Comment by leonardoFu** [comment]
请提供一下flv播放地址。以及，在其他浏览器中是否正常播放？
