### ISSUE TITLE
lang option doesn't work in xgplayer-hls.js

### ISSUE THREAD

**Issue by leexikang** [bytedance/xgplayer#498]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**
let player = new HlsJsPlayer({
  id: 'xg',
  url: '//abc.com/**/*.m3u8',
 lang: 'en',
})

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

I tried to initialize the xgplayer-hls.js with lang: 'en' option. But it's still showing '正在直播'  in the player.  Also jp is not working either.

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
Fixed in xgplayer-hls.js@2.4.1
Thank you for your contributions
