### ISSUE TITLE
addProgressDot 相关问题

### ISSUE THREAD

**Issue by chenguzhen87** [bytedance/xgplayer#500]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.8

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window 10, chrome

**如何复现问题？ What did you do?**
情况1：
1、获取标记列表，通过遍历列表调用addProgressDot添加时间和文字
2、点击播放，进度条上没有出现ProgressDot
情况2：
1、点击播放，点击一个添加标记button，输入标记时间和描述，保存，调用获取标记列表，通过遍历列表调用addProgressDot添加时间和文字，有标记点，移到标记点怎么显示标记文本

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
试下最新版本 xgplayer@2.17.11
因和视频时长有关，需要在起播后(即监听到canplay或playing事件)才能调用该方法
player.addProgressDot(time, text, duration, style) 参数含义分别是展示标记的时间、鼠标hover在标记时展示的文字、标记段长度、标记样式，即传入text参数即可实现你的需求
