### ISSUE TITLE
FLV H5的在线播放器，在IOS的原生浏览器不支持

### ISSUE THREAD

**Issue by mooczhou** [bytedance/xgplayer#501]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

在线播放器demo
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

IOS 系统 浏览器Safari
**如何复现问题？ What did you do?**

使用flv的在线视屏流播放：https://ks3-cn-beijing.ksyun.com/ksplayer/h265/outside_demo/v1.1.3/720P2M30fpsh265-wasmtest.flv
**您期望的播放器正常行为是？ What did you expect to happen?**

浏览器可以正常播放
**实际播放器的表现是？ What actually happened?**

不支持的音频、视屏格式
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
h5播放器

**Comment by zhangxin92** [comment]
iOS系统不支持MediaSource使用，播不了flv
