### ISSUE TITLE
MP4预加载无效（MacOS Chrome下）

### ISSUE THREAD

**Issue by PromiseSLC** [bytedance/xgplayer#502]
**1. 您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer：2.17.10
xgplayer-react： 2.3.1 
xgplayer-mp4：1.2.2

**2. 您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS 11.1  
Chrome  88

**3. 如何复现问题？ What did you do?**

案例1：
```javascript
import Xgplayer from 'xgplayer-react';
import 'xgplayer-mp4';

let config = {
  id: 'mse',
  url: '阿里云OSS链接，类型为mp4',
  preloadTime: 30,
};
let Player = null;
```
案例2：
```javascript
import Player from 'xgplayer';
import 'xgplayer-mp4';

let player = new Player({
  id: 'mse',
  url: '阿里云OSS链接，类型为mp4',
  preloadTime: 30,
});
```
**4. 您期望的播放器正常行为是？ What did you expect to happen?**
预加载30秒

**5. 实际播放器的表现是？ What actually happened?**
案例1：使用了xgplayer的react组件，预加载无效，任意选择某个节点，content-range都是从当前字节到结尾字节。
案例2：直接使用xgplayer，部分MP4资源预加载有效，部分需要全部加载完才能播放。

**6. 疑问**

针对案例一：
- xgplayer-react中如何使用插件xgplayer-mp4，才会使预加载生效。
- xgplayer-react初始化时，会忽略mp4player，是否有影响？源码如下：
```javascript
props.config.ignores = props.config.ignores ? props.config.ignores.concat(['mp4player', 'hlsplayer']) : ['mp4player', 'hlsplayer'];
```
针对案例二：
- npm引入xgplayer-mp4后，需要全部加载完才能播放，原因可能是视频元数据不在第一帧，而是最后一帧。后面是否有优化的计划呢？

### 非常期待您的回复。

**Comment by zhangxin92** [comment]
xgplayer-react@2.4.0版本支持xgplayer-mp4使用；需要使用转码后的mp4资源
