### ISSUE TITLE
西瓜播放器直播的时候touch bar会有进度条

### ISSUE THREAD

**Issue by hongrunhui** [bytedance/xgplayer#505]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

mac 11.0.1 Safari浏览器， UA是"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko)  Infoflow/macOS SysVersion/10.16 AppID/0 AppVersion/2.3.2.4"

**如何复现问题？ What did you do?**

西瓜播放器在直播的时候会有touch bar进度条

**您期望的播放器正常行为是？ What did you expect to happen?**

我希望直播的时候没有touch bar进度条

**实际播放器的表现是？ What actually happened?**

![image](https://user-images.githubusercontent.com/9162319/109122895-3562fc00-7784-11eb-8802-93b3070f1c71.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

百度

**Comment by leonardoFu** [comment]
观察了一下，应该是safari的一个bug，只要用了video，不区分直播点播都会出进度条

**Comment by hongrunhui** [comment]
好像点播不会
