### ISSUE TITLE
咨询视频格式问题

### ISSUE THREAD

**Issue by wusopp** [bytedance/xgplayer#509]
readme中，没有详细描述支持的视频格式，
所以请问在dash，flv，以及hls协议中是否支持HEVC格式的视频文件呢？
音频文件都支持哪些呢？

**Comment by zhangxin92** [comment]
可以看下官网文档的兼容性说明 https://v2.h5player.bytedance.com/gettingStarted/#%E5%85%BC%E5%AE%B9%E6%80%A7
编码格式方面视频支持H.264，音频支持AAC和MP3
