### ISSUE TITLE
按文档配置的播放速度控件，为什么会出现2次按钮？

### ISSUE THREAD

**Issue by wgf4242** [bytedance/xgplayer#510]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.18.3",

和文档一样的配置。
```
import Xgplayer from './VueXgplayer.vue'
import {volume, playbackRate} from 'xgplayer/dist/controls'
const config = {
  id: 'vs',
  url: 'http://127.0.0.1:8080/1.mp4',
  lang: 'zh-cn',
  controlPlugins: [
    playbackRate
  ],
  playbackRate: [0.5, 0.75, 1, 1.5, 2]
}
```

![Snipaste_2021-03-17_22-28-08](https://user-images.githubusercontent.com/3336626/111483788-1696ca80-8770-11eb-96a1-98594ac0f946.png)

**Comment by zhangxin92** [comment]
VueXgplayer.vue是什么？可以尝试
import Player from 'xgplayer/dist/simple_player';

**Comment by wgf4242** [comment]
其实就是xgplayer-vue, 在线演示。求解决。

https://codesandbox.io/s/vue3-xgplayer-i78c8

**Comment by zhangxin92** [comment]
简易模式暂不支持xgplayer-vue方式，可按照文档使用 https://v2.h5player.bytedance.com/gettingStarted/#%E4%BD%BF%E7%94%A8%E7%AE%80%E6%98%93%E7%89%88%E6%9C%AC
