### ISSUE TITLE
flv 重播一直加载中

### ISSUE THREAD

**Issue by ifanday** [bytedance/xgplayer#511]
xgplayer 所有版本
xgplayer-flv.js 所有版本
对下面这个地址的 flv 播放结束后, 点击重播一直加载中, 官网在线生成示例中可测试
https://sgkt.xyjyyun.cn/storage/420ca03f-0183-4b6c-90df-c1f9e19c2be4.flv

**Comment by webywz** [comment]
大佬，解决了吗

**Comment by ifanday** [comment]
> 大佬，解决了吗

目前只能自己写一个按钮覆盖上去重播
