### ISSUE TITLE
如何修改hls预加载时间

### ISSUE THREAD

**Issue by ness403** [bytedance/xgplayer#512]
现在使用xgplayer-hls.js播放视频大约会加载7分钟的视频。如何修改这个时长，或者设置播放器销毁后不再继续加载

**Comment by zhangxin92** [comment]
这样配置试下
new HlsJsPlayer({
    id: 'xx',
    url: 'xxx',
    hlsOpts: {
       maxBufferLength: 5, //最大缓冲时长，单位秒
    }
})
