### ISSUE TITLE
将destroy之后再new，反复几次之后，视频无法播放，实际上视频流仍在推数据

### ISSUE THREAD

**Issue by EricLye** [bytedance/xgplayer#513]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.16.2",
    "xgplayer-flv": "^2.3.61"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10+google

**如何复现问题？ What did you do?**
在一个页面创建了4个播放器，正常播放；destroy之后再new四个，如此反复几次，视频就无法播放了。而实际上，视频流一直在推数据

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
无法播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by mhqpx** [comment]
destroy时调用destroy(false) 可以解决
