### ISSUE TITLE
xgplayer-hls.js调用destroy之后还会继续播放，回退到旧版本不会播放了但是还会加载数据。如何让其停止加载

### ISSUE THREAD

**Issue by ote888** [bytedance/xgplayer#514]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.18.3",
"xgplayer-hls.js": "^2.4.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows
chrome

**如何复现问题？ What did you do?**
vue里面加入了xgplayer-hls.js，页面销毁的时候调用了destroy方法
destroyed() {
        console.log("destroy")
        /*销毁播放器*/
        this.videoObj.destroy(true);
    }

**您期望的播放器正常行为是？ What did you expect to happen?**
destroy之后不再继续播放，且不再继续加载数据

**实际播放器的表现是？ What actually happened?**
2.4.2 版本 destroy之后还会播放。有时会出现，需多试几次
2.2.1 版本 destroy不会自动播了但是还会加载数据

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by ote888** [comment]
测试的是h5，pc未试过

**Comment by leonardoFu** [comment]
您使用的是h5还是PC？h5的话不需要使用xgplayer-hls.js播放直播流的

**Comment by Pangnz** [comment]
我也遇到了同样的问题，**切换不通清晰度的m3u8，然后调用destory**，network仍然在**不断的请求m3u8还可以听到声音**

**Comment by cjiulong96** [comment]
> > 我也遇到了同样的问题，在vue里面加入了xgplayer-hls.js，播放hls，在beforeDestroy()中调用了player.destroy()，在pc浏览器中调试，跳转到其它页面后，还是会定时请求m3u8的数据，插件版本如下 "xgplayer": "^2.31.1", "xgplayer-hls.js": "^2.5.2",
> 
> 目前找到一种修复方案，就是在destroy()之前，把src设置为'' 即：this.player.src = '' 这样退出后后台就不会继续请求m3u8的地址了

这个方法可以的，感谢，已解决。

**Comment by gemxx** [comment]
#760
