### ISSUE TITLE
请问 xgplayer-hls.js 要怎么设置请求头呢？

### ISSUE THREAD

**Issue by songxingguo** [bytedance/xgplayer#516]

**Comment by zhangxin92** [comment]
new HlsJsPlayer({
    id: 'vs',
    url: 'XXX.m3u8',
    hlsOpts: {
      xhrSetup: function(xhr, url) {
          xhr.withCredentials = true;
        }
    }
})

**Comment by songxingguo** [comment]
thank you

**Comment by pocketChao** [comment]
> 

             你好 麻烦问下是这样设置么  设置完header需要重新xhr.open么
              xhr.withCredentials = true;
              // header 添加参数
              xhr.setRequestHeader('mobile', t);
