### ISSUE TITLE
小白一枚，url设置本地视频路径无效显示，请教一下引入本地视频url要怎么设置呢

### ISSUE THREAD

**Issue by raojianw** [bytedance/xgplayer#517]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xyyojl** [comment]
url 设置本地视频路径，无法正常播放，这种一般是你填写的视频路径有问题，找不到对应的视频，可以参考下面的例子，有一个文件夹 player-demo，下面有 index.html 和 demo.mp4，就可以参考下面的截图这样，另外可以了解一下“相对路径”
![image](https://user-images.githubusercontent.com/32906942/114727153-8b115900-9d70-11eb-86f7-6011d57a2db9.png)
