### ISSUE TITLE
播放结束同时出现重播和播放按钮

### ISSUE THREAD

**Issue by qingwufong** [bytedance/xgplayer#518]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.19.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows10，Chrome，360

**如何复现问题？ What did you do?**
初始化设置宽高，缩放浏览器重新设置宽高。播放结束中间同时出现播放和重播按钮

**您期望的播放器正常行为是？ What did you expect to happen?**
播放结束只显示重播，并且可以点击

**实际播放器的表现是？ What actually happened?**
重播不能点击，点击播放会出现多一个视频画面。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
Web端短视频播放
![xg_playend_bug](https://user-images.githubusercontent.com/6860888/114648510-8d909600-9d11-11eb-817a-af6a9b826f17.png)

**Comment by zhangxin92** [comment]
是不是对播放器的样式做了处理？“设置宽高”的操作具体是指？

**Comment by zhangxin92** [comment]
问题无法复现，可以尝试更新到最新版本xgplayer@2.31.1
