### ISSUE TITLE
Replay button style bug in IE 11

### ISSUE THREAD

**Issue by savokiss** [bytedance/xgplayer#52]
![default](https://user-images.githubusercontent.com/5608189/43838586-61ea36b8-9b4e-11e8-9fd5-a3ead177f476.png)

Open this link in IE 11 to see: <http://h5player.bytedance.com>

**Comment by zhangxin92** [comment]
Fixed by [7a8d4b](https://github.com/bytedance/xgplayer/commit/7a8d4b74bd2d7896911560b015b7e67c79c70662).

**Comment by hthmh** [comment]
最新版好像又出现这个问题了，而且默认语言是英文

**Comment by zhangxin92** [comment]
已在2.1.11版本修复，感谢反馈！
