### ISSUE TITLE
请问西瓜播放器支持直接的fmp4流播放吗？

### ISSUE THREAD

**Issue by huxiaoyingying** [bytedance/xgplayer#522]
因为我已经在服务器端将摄像机的码流实时封装成fmp4流了，塞到我自己写的简易播放器可以正常播流，但是视频窗口的中间会不断出现视频加载的那个圈圈出来，所以想试一下西瓜播放器

**Comment by zhangxin92** [comment]
xgplayer支持播放fmp4

**Comment by fanybook** [comment]
@zhangxin92 

> xgplayer支持播放fmp4

请问，播放 fmp4 如果跳转时（能拿到要跳转的时间么），如何修改 src 的 startTime
