### ISSUE TITLE
ios 微信浏览器，同层播放下，退出全屏事件监听

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#523]
微信浏览器，同层播放下，退出全屏事件监听，exitFullscreen 无效，获取 video addEventListener 也没有作用

**Comment by zhangxin92** [comment]
可以在监听到退出全屏事件后延时调用player.play()方法

player.on('exitFullscreen', () => {
    setTimeout(() => {
        player.play()
    }, 500)
})
