### ISSUE TITLE
xgplayer-hls.js插件播放地址404时,无法通过on.('error')监听

### ISSUE THREAD

**Issue by renxionghui** [bytedance/xgplayer#525]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer-hls.js": "^2.4.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**
const playbackUrl = 'http://localhost:5000/video/dem.m3u8'; //404地址
this.player = new HlsPlayer({
        el: this.$refs.playbackPlayer,
        url:playbackUrl,
        autoplay:true
})
this.player.on('error',(err)=>{
        console.log(err);
})
**您期望的播放器正常行为是？ What did you expect to happen?**
是否能够通过on error监听到404错误,或者是需要通过其他什么配置.

**实际播放器的表现是？ What actually happened?**
404之后,loadding菊花一直在转,不会给任何的提示,也无法捕获到异常,做其他的操作

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by slinloving** [comment]
我也有相同的问题，请问你如何解决的？

**Comment by zhangxin92** [comment]
可以通过HLS_ERROR事件监听到hls.js抛出的错误信息
player.on('HLS_ERROR', info => { })

**Comment by trry-github** [comment]
> 可以通过HLS_ERROR事件监听到hls.js抛出的错误信息 player.on('HLS_ERROR', info => { })

ios 系统中依然无法监听错误，有其他办法么

**Comment by trry-github** [comment]
> 可以通过HLS_ERROR事件监听到hls.js抛出的错误信息 player.on('HLS_ERROR', info => { })

ios 中使用原生video播放 m3u8 无法，监听到资源加载404，有什么好的方法么

**Comment by trry-hub** [comment]
解决了么 ，我在ios 真机中使用仍然无法获取到404错误
