### ISSUE TITLE
视频时长 infinity NaN

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#526]
默认时长限制是多少？可以手动设置嘛？现在 8000s 的视频时长无法获取

**Comment by zhangxin92** [comment]
点播视频的话视频时长可以正常获取，是不是用了直播流？

**Comment by XFJ712** [comment]
就是，mp4 视频，只不过，有 8000 s ，7000 s 的 mp4 还可以获取到时长的

**Comment by XFJ712** [comment]
> 点播视频的话视频时长可以正常获取，是不是用了直播流？


就是，mp4 视频，只不过，有 8000 s ，7000 s 的 mp4 还可以获取到时长的

**Comment by zhangxin92** [comment]
我们这边测试更长的视频也没有问题，你试试用原生video能否获取到时长？
