### ISSUE TITLE
如何在 h5 同层全屏后添加水印？

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#527]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

最新

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

手机端

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

全屏后水印依旧存在

**实际播放器的表现是？ What actually happened?**

全屏后无水印

**Comment by zhangxin92** [comment]
具体环境是什么手机系统和浏览器？

**Comment by XFJ712** [comment]
> 具体环境是什么手机系统和浏览器？

用于 h5 同层播放下，全屏应该是被原生劫持了
