### ISSUE TITLE
m3u8视频手机端正常，pc端无法播放

### ISSUE THREAD

**Issue by Combox722** [bytedance/xgplayer#529]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

xgplayer 2.20.0
xgplayer-hls.js 2.4.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

windows  chrome

**如何复现问题？ What did you do?**

播放这个视频： https://playback-tx.myhithink.com/9428f57evodcq1300730068/53ac36365285890817460953980/playlist_eof.m3u8

手机端正常播放，pc端无法正常播放， 在官网上面的在线生成中也无法播放

**您期望的播放器正常行为是？ What did you expect to happen?**

正常播放

**实际播放器的表现是？ What actually happened?**

一直转圈加载，无法正常播放
![screenshots](https://user-images.githubusercontent.com/40097307/116179737-6e9af680-a74a-11eb-8405-6246ba38a007.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Sam-Smith-01** [comment]
我不知道这个帖子有什么用
