### ISSUE TITLE
不支持vue3 vite 吗

### ISSUE THREAD

**Issue by daleizi** [bytedance/xgplayer#531]
不支持vue3 vite 吗

**Comment by zhangxin92** [comment]
支持，遇到什么问题了吗

**Comment by AllenForward** [comment]
> 支持，遇到什么问题了吗

(this will be run only when your dependencies or config have changed)
 > node_modules/xgplayer-helper-utils/es/context/index.js:13:9: error: No matching export in "browser-external:events" for import "EventEmitter"
    13 │ import { EventEmitter } from 'events';

**Comment by zhangxin92** [comment]
如果是使用了xgplayer-flv包的话可以升级到xgplayer-flv@2.4.24版本试下
