### ISSUE TITLE
设置src 报错

### ISSUE THREAD

**Issue by LeoHuiyi** [bytedance/xgplayer#538]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.20.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome90

proxy.js中的![image](https://user-images.githubusercontent.com/8001457/117786190-d50a3380-b277-11eb-9760-abc2529555f0.png)
player 变量不存在

**Comment by zhangxin92** [comment]
已在 xgplayer@2.20.5 版本修复，可以稍后试下，感谢反馈！

**Comment by LeoHuiyi** [comment]
@zhangxin92 已修复，感谢！我想问下最新版本代码源码在github的哪个分支？

**Comment by zhangxin92** [comment]
master分支
