### ISSUE TITLE
pip: true，「画中画」模式在微信内置浏览器点击无反应

### ISSUE THREAD

**Issue by renyangmei** [bytedance/xgplayer#541]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.18.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓版本：10

**如何复现问题？ What did you do?**
https://static.tingshubao.net/college_pro_media/tool/files/20210513_091134_xgbug.gif

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
画中画在android端是无法使用的  建议在android端把该插件禁用掉
