### ISSUE TITLE
android webview无法播放fmp4链接

### ISSUE THREAD

**Issue by addriumruss** [bytedance/xgplayer#543]
环境：安卓10, webview控件加载html5页面，采用最新xgplayer。
给了一个有效的fmp4链接，无法播放。
这个链接在PC-WEB上采用相同xgplayer能播放， vlc也能播放。
请问安卓、IOS上, xgplayer是否能播放fmp4？ 是否需要特殊设置？
谢谢！

**Comment by zhangxin92** [comment]
原生video兼容性不一致，建议使用普通mp4格式
