### ISSUE TITLE
开启useHls选项会导致清晰度切换控制栏在ios中不显示当前清晰度，切换清晰度一直waiting,关闭该选项正常

### ISSUE THREAD

**Issue by lpg-kobe** [bytedance/xgplayer#546]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

xgplayer-v2.20.5    xgplayer-hls.js-v2.4.2
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

ios/安卓 任意浏览器
**如何复现问题？ What did you do?**

直播场景使用xgplayer-hls.js创建播放器并开启useHls:true
**您期望的播放器正常行为是？ What did you expect to happen?**

正常切换直播清晰度并且显示当前清晰度
**实际播放器的表现是？ What actually happened?**
开启useHls选项会导致清晰度切换控制栏在ios中不显示当前清晰度文本，切换清晰度一直waiting加载异常

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
iOS端不兼容mediasource，不支持使用useHls:true配置
