### ISSUE TITLE
音乐播放器 更新列表  封面没有更新this.player.updateList()

### ISSUE THREAD

**Issue by xuergo** [bytedance/xgplayer#547]
音乐播放器 更新列表  封面没有更新this.player.updateList(list)

**Comment by xuergo** [comment]
![Uploading image.png…]()

**Comment by xuergo** [comment]
![image](https://user-images.githubusercontent.com/46159623/119212002-4fdd1500-bae8-11eb-9916-b51c368e7c94.png)

**Comment by y377** [comment]
你好，开发者，请问我那个是点击一次音乐文件名称，然后获取到当前url,然后调用西瓜音乐播放，但是可以手动添加多个url是可以点击下一曲，假设：我的音乐曲目有几千首，难道全部手动添加？
问题一：有什么办法自动获取到网页上的音乐url并同时加载到播放列表？
问题二：每当手动点击一次，记录一次，只要被手动点击过的都记录在案，这些可以循环播放
请看我的代码（jQuery）：
```
 else if (dmt == 2) {
            let player = new Music({
                container: document.getElementById('dsgplayer'),
                id: 'dsgplayer',
                url: [{
                    src: dURL,
                    name: title,
                    poster: '',
                }],

            });
            player.add({src:'dURL', name:'title'});
            
            return;
            ```
            
![image](https://user-images.githubusercontent.com/58632405/121136616-703afc80-c868-11eb-870c-2f1b47be2e32.png)

**Comment by xuergo** [comment]
> 你好，开发者，请问我那个是点击一次音乐文件名称，然后获取到当前url,然后调用西瓜音乐播放，但是可以手动添加多个url是可以点击下一曲，假设：我的音乐曲目有几千首，难道全部手动添加？
> 问题一：有什么办法自动获取到网页上的音乐url并同时加载到播放列表？
> 问题二：每当手动点击一次，记录一次，只要被手动点击过的都记录在案，这些可以循环播放
> 请看我的代码（jQuery）：
> 
> ```
>  else if (dmt == 2) {
>             let player = new Music({
>                 container: document.getElementById('dsgplayer'),
>                 id: 'dsgplayer',
>                 url: [{
>                     src: dURL,
>                     name: title,
>                     poster: '',
>                 }],
> 
>             });
>             player.add({src:'dURL', name:'title'});
>             
>             return;
> ```
> 
> ![image](https://user-images.githubusercontent.com/58632405/121137039-dc1d6500-c868-11eb-892c-483c7de9f307.png)

嗯，问题1 ：你网页上的列表怎么来的？如果能拿到就直接放到播放器里面不就行了？如果是点击的时候获取播放地址 那就在change事件里 写获取播放地址方法啊，靠vid 什么的你自己逻辑。
问题2 抱歉我没有理解 你的问题。如果你要保存播放记录 并循环它。 那就在change 事件里保存到一个数组里，然后在切换成循环模式时 替换掉播放列表吧。这是我思路仅供参考

**Comment by y377** [comment]
谢谢你的提醒，我再试试
