### ISSUE TITLE
ios 微信浏览器下，m3u8 流中断无法识别

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#548]
设备：ios 微信浏览器
插件：xgplayer-hls.js
问题：ios 微信浏览器下，m3u8 流中断无法识别，Android/pc 下可以识别到 player.hls.on('hlsError', () => {})；ios 无法识别
配置：useHls：false ，设置为 true 时，无法播放 m3u8 流
不使用 xgplayer 的原因：Android 手机无法正确识别 m3u8 直播片段的时长；ios 手机同样无法识别 xgplayer 的 error 事件

**Comment by my-first-gitHub-account123** [comment]
怎么解决的？
