### ISSUE TITLE
HlsPlayer  首次加载不成功 刷新一次页面就好了 为啥？

### ISSUE THREAD

**Issue by anfenglei9527** [bytedance/xgplayer#549]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
 "xgplayer": "^2.20.12",
    "xgplayer-hls": "^2.4.24",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win7   谷歌

**如何复现问题？ What did you do?**
  vm.HTTPCount--;
        vm.playerHls = new HlsPlayer({
          //初始化实例对象HlsJsPlayer
          id: "hlsmse",
          autoplay: true,
          url: vm.playerConfig.url,
          poster: vm.playerConfig.poster,
          useHls: true,
          height: window.innerHeight * (5 / 7),
          width: window.innerWidth * (4 / 7),
          crossOrigin: false,
          isLive: true,
          screenShot: true,
          // errorTips: `请<span>刷新</span>试试`,

          networkState: [
            () => {
              config.log("报错1");
            },
          ],
          playbackRate: [0.5, 0.75, 1, 1.5, 2], // 当前播放速度
          error: [
            () => {
              config.log("报错");
            },
          ],
        });

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
请提供一下拉流地址

**Comment by night-Magicl** [comment]
解决了吗？我也有同样的问题，暂时没找到原因，不过这个情况也不常出现

**Comment by izhaorui** [comment]
怎么解决的，我这边也有这个问题
