### ISSUE TITLE
西瓜播放器不断请求a.m3u8,但是不请求.ts

### ISSUE THREAD

**Issue by felix-001** [bytedance/xgplayer#550]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
在线的：https://v2.h5player.bytedance.com/

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac/chrome

**如何复现问题？ What did you do?**
https://v2.h5player.bytedance.com/generate/ 在这里播放hls直播

**您期望的播放器正常行为是？ What did you expect to happen?**
一直正常播放

**实际播放器的表现是？ What actually happened?**
播放一会停止，一直转圈

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
hls直播
[961播放停止bug-new.har.zip](https://github.com/bytedance/xgplayer/files/6558681/961.bug-new.har.zip)
![BA7EADC2255C5592A44F102CAFEE09BA](https://user-images.githubusercontent.com/20610281/119938408-f03aaa00-bfbe-11eb-8aee-7d84935e36d5.jpg)

一直在请求a.m3u8,但是不请求.ts,这是为什么呢
m3u8中的地址都是新地址
序列号也是+1的

**Comment by felix-001** [comment]
附件的zip包是一个浏览器导出的.har文件，chrome浏览器打开调试模式，拖进去就可以看了

**Comment by wangyipeng413** [comment]
同问类似问题。
使用video.js播放器请求m3u8时，先是返回的动态列表中EXT-X-MEDIA-SEQUENCE的值不连续(准确说是乱序，比如138，139，142，143，140)；
一小段时间后，就会出现只请求m3u8并返回动态列表，但不去请求对应的ts文件的情景
