### ISSUE TITLE
安卓webview加载时会出现大的三角形按钮

### ISSUE THREAD

**Issue by fanwenfu** [bytedance/xgplayer#551]

**Comment by zhangxin92** [comment]
参考 https://github.com/bytedance/xgplayer/issues/406

**Comment by fanwenfu** [comment]
这个解决办法适合在自己的应用的webview，我目前是在企业微信的webview出现这个问题，还有其他解决办法？

**Comment by zhangxin92** [comment]
这个是webview控制，建议咨询下企业微信官方
