### ISSUE TITLE
有弹幕时，多次点击播放进度条回到弹幕开始播放的时间节点，弹幕出现重复渲染

### ISSUE THREAD

**Issue by zhuyuyi** [bytedance/xgplayer#552]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.6版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10、chrome 90版本

**如何复现问题？ What did you do?**
有弹幕时，点击播放进度条到弹幕开始播放的时间节点，弹幕出现重复渲染

**您期望的播放器正常行为是？ What did you expect to happen?**
弹幕不重复

**实际播放器的表现是？ What actually happened?**
有弹幕时，点击播放进度条到弹幕开始播放的时间节点，弹幕出现重复渲染
![image](https://user-images.githubusercontent.com/41852761/120263212-ce4a6b80-c2cd-11eb-9762-2c45a3211466.png)
我在官方的示例中发现了同样的问题

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
在最新版本xgplayer@2.31.1没有复现，可以更新试下
