### ISSUE TITLE
flv视频，无法正常显示视频时长和当前时间

### ISSUE THREAD

**Issue by Blueria** [bytedance/xgplayer#554]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.20.12

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10和chrome

**如何复现问题？ What did you do?**
使用FlvPlayer播放http://vod.jiagutech.com/asset/a8c420233e91dc3922907b048ed27f77/23212c80cea2daf6f2c0cc19b048cbec.flv 视频（应该跟视频无关吧，视频Response Header中包含Accept-Ranges）

**您期望的播放器正常行为是？ What did you expect to happen?**
正常显示视频时长，要不然也没办法点击进度条播放指定位置的视频

**实际播放器的表现是？ What actually happened?**
![image](https://user-images.githubusercontent.com/7038130/120457997-801a9280-c3c9-11eb-89f5-bc3a0607212f.png)
如图，当前时间显示不正常，并且鼠标放在进度条上也不正常

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
这个flv视频的onMetadata信息中并没有给出视频的时长，应该是录制产生。播放器无法获取整个视频的时长，以下是视频的onMetadata信息：
audiocodecid: 10
audiosamplerate: 16000
copyright: "EasyRTMP"
framerate: 25
height: 720
videocodecid: 7
width: 1280

如果需要作为点播flv来使用的话，请在onMetadata中打入duration信息

**Comment by MaJiaXuan** [comment]
> 

请问下有没有onMetadata示例？
