### ISSUE TITLE
手动改变播放倍速，实际播放倍速改变了但是控制台显现的倍速没变（还是原先默认的倍速）

### ISSUE THREAD

**Issue by lhh-git** [bytedance/xgplayer#556]
this.player = new HlsJsPlayer({
          id: 'xg',
          url: 'http://192.168.100.210/admin/test/42BB19A6-B98F-98E6-07F2-9942F5151C7E.m3u8',
          playbackRate: [0.5, 0.75, 1, 1.5, 2, 16],
          defaultPlaybackRate: 2,
}）

setTimeout(() => {
      this.player.playbackRate = 2
})

**Comment by zhangxin92** [comment]
已在xgplayer@2.31.2版本支持
