### ISSUE TITLE
iPhone 12 录制mov视频，播放器不支持播放

### ISSUE THREAD

**Issue by 1648045459** [bytedance/xgplayer#559]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
  "xgplayer": "^2.17.6",
    "xgplayer-flv.js": "^2.3.0",
    "xgplayer-hls.js": "^2.4.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

操作系统: iPhone12；iPhone 8  ;  MAC ;  WIN10 ; 华为mate40 pro（安卓机）
浏览器：Google Chrome版本 90.0.4430.212（正式版本） （64 位）

**如何复现问题？ What did you do?**
  "xgplayer": "^2.17.6" 
iPhone12录制的视频上传到系统，在win10  Google Chrome版本 90.0.4430.212（正式版本） （64 位）播放不了视频
iPhone8 录制的视频，在win10  Google Chrome版本 90.0.4430.212（正式版本） （64 位）可以正常播放
mac电脑播放  黑屏并能听到声音
华为mate40 pro手机  黑屏并能听到声音

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
检查下视频格式是不是h264，其它格式在浏览器不支持

**Comment by 1648045459** [comment]
好的，谢谢
