### ISSUE TITLE
前台拉去视频流，可以请求头可以携带token么

### ISSUE THREAD

**Issue by z10026393** [bytedance/xgplayer#566]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

"xgplayer": "^2.16.2"
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10
Chrome
**如何复现问题？ What did you do?**
使用new Player创建实例,视频流地址src token验证问题

**您期望的播放器正常行为是？ What did you expect to happen?*
拉取视频流可以设置token

**实际播放器的表现是？ What actually happened?**
拉取视频流不可以设置token

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
使用原生video请求播放视频无法设置请求头
