### ISSUE TITLE
xgplayer-music 播放中，拖动进度条，不够稳定，进度条会来回跳

### ISSUE THREAD

**Issue by amyhuangxbd** [bytedance/xgplayer#567]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
 "xgplayer": "^2.20.12",
  "xgplayer-music": "^2.3.2",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
pc: os , windows
mobile : ios, android

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
xgplayer-music 播放中，拖动进度条时，不要来回跳

**实际播放器的表现是？ What actually happened?**
xgplayer-music 播放中，拖动进度条，不够稳定，进度条会来回跳

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
在最新版本xgplayer@2.31.1没有复现，可以更新试下
