### ISSUE TITLE
关于自定义片头问题

### ISSUE THREAD

**Issue by moRanou** [bytedance/xgplayer#568]
您好，有考虑后期增加类似于自定义片头 or 片尾的功能吗？或者以现有功能如何去实现此类需求呢，谢谢

**Comment by zhangxin92** [comment]
可通过切换视频源的方式实现 https://v2.h5player.bytedance.com/api/#%E5%88%87%E6%8D%A2%E8%A7%86%E9%A2%91%E6%BA%90

**Comment by moRanou** [comment]
> 可通过切换视频源的方式实现 https://v2.h5player.bytedance.com/api/#%E5%88%87%E6%8D%A2%E8%A7%86%E9%A2%91%E6%BA%90

谢谢你的回答，不过在这之前已经解决这个功能需求，我的解决方案是实例化两个播放器，自定义片头使用以及正片内容使用，然后通过切换两个播放器的显隐达到自定义片头的功能
