### ISSUE TITLE
Suggest adding some apis to get status of the controls

### ISSUE THREAD

**Issue by lynnic26** [bytedance/xgplayer#57]
Hi,
now we inspect DOM to see the status of controls, it is not so convenient
can your guys add some apis to get status of controls ?
for example:
**get the status of fullscreen** and **whether the bullet is enabled** and so on via player instance directly

希望能添加一些可以获取控件状态的api, 比如弹幕是否开启、全屏是否开启
现在的方式是用js查看DOM的状态，有点不方便

Thanks  : ）

**Comment by zhangxin92** [comment]
Fixed by [bb8079](https://github.com/bytedance/xgplayer/commit/bb8079e2a49b7ffb1ae1f000c8a8d17d0952d434) with adding fullsceen, bullet, textTrack, picture-in-picture status. Can be used in v1.0.9.
