### ISSUE TITLE
xgplayer-flv.js 可以设置socket连接时长限制吗?

### ISSUE THREAD

**Issue by ccyytt** [bytedance/xgplayer#570]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer-flv.js": "^2.3.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos big sur 11.4

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
能过设置webscoket超时或者一定时间内没有接受到数据emit事件

**实际播放器的表现是？ What actually happened?**
loading

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
flv.js没有开放相应配置的话我们这边暂时也不会提供这个能力。
