### ISSUE TITLE
2.2.5以下的版本出现切换播放源音频叠加问题，2.2.5以上修复了该问题但移动端不能播放，望官方检测修复一下

### ISSUE THREAD

**Issue by scandalYang** [bytedance/xgplayer#572]
**您使用的操作系统和浏览器分别是？ ios14.4.1 iphone11

**如何复现问题？ cdn导入xgplayer-hls.js/browser/index.js使用

**您期望的播放器正常行为是？ 2.2.5以上版本手机端能正常播放

**实际播放器的表现是？ 不能播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持：457308699@qq.com

**Comment by zhangxin92** [comment]
在最新版本xgplayer-hls.js@2.5.2没有复现，建议升级试下
