### ISSUE TITLE
调用screenShot方法 怎样禁止下载

### ISSUE THREAD

**Issue by anfenglei9527** [bytedance/xgplayer#573]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**
点击截图按钮 会自动下载

**您期望的播放器正常行为是？ What did you expect to happen?**
screenShot 监听函数会获取base64 但是不下载

**实际播放器的表现是？ What actually happened?**
点击截图按钮 会自动下载

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
配置
screenShot: {
    saveImg: false
  }
监听事件获取截图数据
player.on('screenShot', screenShotImg => {})
