### ISSUE TITLE
使用xgplayer-mp4

### ISSUE THREAD

**Issue by banckgg** [bytedance/xgplayer#574]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
├── xgplayer-mp4@1.2.2
├── xgplayer-react@2.4.0
├── xgplayer@2.22.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

mac 11.2  
Google Chrome 91.0.4472.114

**如何复现问题？ What did you do?**

    let player = new Player({
        id: 'mse',
        volume: 0.3,
        url: 'https://vjshi-video-test.oss-cn-beijing.aliyuncs.com/27498-vjshi-test.mp4',
        poster: '//s2.pstatp.com/cdn/expire-1-M/byted-player-videos/1.0.0/poster.jpg',
        playsinline: true,
        preloadTime: 20, // 默认预加载 15 秒
    });

   使用该配置就会导致问题。视频文件已经进行了CORS跨域配置

**您期望的播放器正常行为是？ What did you expect to happen?**

没有报错可以正常使用插件

**实际播放器的表现是？ What actually happened?**

运行后报错
index.js:141 Uncaught (in promise) TypeError: Cannot set property 'pluginSrc' of undefined

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
在最新版本没有复现，可以更新试下
xgplayer@2.31.2
xgplayer-mp4@1.2.4
