### ISSUE TITLE
在VUE中使用播放器报错：container id can't be empty

### ISSUE THREAD

**Issue by DonkeyLiao** [bytedance/xgplayer#575]
西瓜播放器版本：2.24.1
操作系统：win10
浏览器：Chrome

按照文档使用npm安装的，选择器用id和el都试过了，一直报container id can't be empty，是啥原因啊

**Comment by 302559295** [comment]
vue中包裹这个容器的父元素或者爷元素有v-if

**Comment by qs991011** [comment]
我也遇到了，不过我放到vue组件的mounted 钩子函数里面执行就不报错了。

**Comment by zhangxin92** [comment]
实例化前检查下播放器容器是否已存在

**Comment by GitACDreamer** [comment]
@zhangxin92 使用vue 在mounted函数里实例化player,在视频播放器容器父组件添加了v-if控制，这种情况下，获取到了视频资源，但是一直会提示`container id can't be empty`,
```
init() {
      if (this.url && this.url !== "") {
        this.player = new Player({
          id: 'mse',
          with: 400,
          height: 300,
          ignores: ["play", "volume"],
          whitelist: [
            (ua) => {
              return /Android/gi.test(ua);
            },
          ],
          controlsList: [],
          videoInit: true,
          fitVideoSize: true,
          fluid: true,
          url: this.url,
          "x5-video-player-type": "h5",
        });
        this.$emit("player", this.player);
      }
    }
```
通过调试发现错误如下：
![image](https://user-images.githubusercontent.com/19402747/147871482-93a8fa54-c58d-42f1-aeea-099164734dc7.png)

为何要使用v-if控制显示，是因为提供视频上传功能，上传成功之后，显示xgplayer组件，来播放视频

**Comment by wbkearly** [comment]
用了v-if的话
```javascript
 this.$nextTick(() => {//初始化});
```

**Comment by ananasTete** [comment]
播放容器本身或父元素设置了 v-if / v-show
即在实例化 Player 时找不到播放容器
解决：
setTimeout(() => {
      let player = new Player({
        id: '__video_player__',
        url: this.url
      });
}, 0);
