### ISSUE TITLE
文档不完善

### ISSUE THREAD

**Issue by RRDAWLX** [bytedance/xgplayer#579]
你们的官方文档太不完善了，播放器 error 事件回调函数入参是什么，我翻来覆去地在文档里面找也没找到，官网还没有反馈入口。

**Comment by zhangxin92** [comment]
不同场景下error事件回调入参的格式可能不同，直接使用xgplayer的情况下入参格式可参考 https://github.com/bytedance/xgplayer/blob/master/packages/xgplayer/src/error.js#L45
除了github issue，也可以在QQ群交流和反馈，QQ群信息在 https://v2.h5player.bytedance.com/about/

**Comment by RRDAWLX** [comment]
我指的是这里的错误回调 https://v2.h5player.bytedance.com/api/#%E4%BA%8B%E4%BB%B6。
`player.on('error', callback)`  
callback 的入参是什么？
首先，我觉得这个问题的答案应该是能够在文档中找到的，不应该去看源码或qq群里问，这样很低效。而且我相信很多人都会关注到错误回调的入参问题。
其次，上面贴的这个代码是错误类型的定义，没有说明错误回调的入参有几个，分别是什么。
