### ISSUE TITLE
app内嵌h5 ios 默认全屏播放

### ISSUE THREAD

**Issue by woSihaizi** [bytedance/xgplayer#580]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios操作系统

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
期望只在可以范围播放，不是手机全屏

**实际播放器的表现是？ What actually happened?**
手机默认全屏播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
配置 playsinline: true

**Comment by woSihaizi** [comment]
> 配置 playsinline: true

好的，还有一个就是红米手机，点击全屏按钮没反应

**Comment by zhangxin92** [comment]
播放器内部是调用系统全屏API，检查下相关环境系统全屏API是否有效
