### ISSUE TITLE
在pc端个别MP4视频会报请刷新试试

### ISSUE THREAD

**Issue by zgnation** [bytedance/xgplayer#581]
![image](https://user-images.githubusercontent.com/35555735/124932996-19c30880-e036-11eb-80c3-5a36caeb87c0.png

**Comment by zgnation** [comment]
什么情况下会直接报请刷新试试

**Comment by zgnation** [comment]
![error](https://user-images.githubusercontent.com/35555735/125008968-34c56500-e096-11eb-87aa-30bbcfcf03c7.png)
是上面的错误出现刷新试试

**Comment by zgnation** [comment]
> ![error](https://user-images.githubusercontent.com/35555735/125008968-34c56500-e096-11eb-87aa-30bbcfcf03c7.png)
> 是上面的错误出现刷新试试
视频是好的，可以播放

**Comment by zhangxin92** [comment]
1. 检查视频资源请求是否正常；2.检查编码格式是否兼容浏览器环境使用，需要是H.264   3. 尝试对视频转码后是否能正常播放
