### ISSUE TITLE
部分安卓手机点击全屏按钮无反应

### ISSUE THREAD

**Issue by woSihaizi** [bytedance/xgplayer#582]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
红米

**如何复现问题？ What did you do?**
点击全屏按钮

**您期望的播放器正常行为是？ What did you expect to happen?**
点击全屏按钮可以正常全屏
**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
> 2.9.5
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 红米
> 
> **如何复现问题？ What did you do?**
> 点击全屏按钮
> 
> **您期望的播放器正常行为是？ What did you expect to happen?**
> 点击全屏按钮可以正常全屏
> **实际播放器的表现是？ What actually happened?**
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.**
安卓的webview默认不支持html元素的全屏显示，而且前端捕获不到任何异常，无法检测当前环境是否支持全屏， 如果想要支持，需要webView容器做一些兼容，具体可参考https://blog.csdn.net/A498930275/article/details/116047578
