### ISSUE TITLE
xgplayer-flv 暂停播放后 再次点击播放 会长时间加载 一直loading

### ISSUE THREAD

**Issue by zhaosheng808** [bytedance/xgplayer#587]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer@2.25.1
xgplayer-flv@2.4.25

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 Chrome

**如何复现问题？ What did you do?**

使用xgplayer + xgplayer-flv播放 .flv格式直播流 点击播放按钮 播放器正常播放直播流 且加载速度很快。点击暂停播放按钮，播放器画面暂停，再次点击播放按钮，播放器画面全黑，出现loading加载动画，且保持长时间加载动画（20s左右），和第一次播放的速度相比慢了很多。
![image](https://user-images.githubusercontent.com/26834525/126249089-74a08f24-c8ff-44de-8b6f-b7fa409f1160.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
暂停后再次点击播放 希望 响应时间缩短 ，和第一次播放的画面的响应时间相差太大。

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by leonardoFu** [comment]
可以提供一下直播流地址么？
