### ISSUE TITLE
使用xgplayer-hls时引入了未导出的变量

### ISSUE THREAD

**Issue by Zephyrrro** [bytedance/xgplayer#588]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer@2.25.0
xgplayer-hls@2.4.25

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Mac OS
Chrome

**如何复现问题？ What did you do?**
```js
import 'xgplayer'
import HlsPlayer from 'xgplayer-hls'

// ...正常使用
```
```bash
# 使用vite进行构建
$ vite
```

![image](https://user-images.githubusercontent.com/43735265/126258096-8de3c90b-464e-423d-880c-cb943b4b6766.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
正常使用

**实际播放器的表现是？ What actually happened?**
构建出错

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Beipy** [comment]
咋样解决了吗？同样遇到该问题vue3.0

**Comment by zhangxin92** [comment]
已在 xgplayer-hls@2.4.32 版本修复，可以测试下
