### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by zhaosheng808** [bytedance/xgplayer#589]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"webpack": "4.8.3",
xgplayer@2.25.1,

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 Chrome

**如何复现问题？ What did you do?**
在项目中导入
```
 import Player from 'xgplayer';
```
![image](https://user-images.githubusercontent.com/26834525/126267728-090f06f7-ee02-4449-8133-95a0e0c544cf.png)
dev环境正常
build以后就会提示`TypeError: Super expression must either be null or a function, not undefined`
![image](https://user-images.githubusercontent.com/26834525/126267747-6ea8f97e-a072-48a2-9061-b468109ba92b.png)

其他代码全部注释掉，只保留 `import Player from 'xgplayer'`,打包后还是提示`TypeError: Super expression must either be null or a function, not undefined`，页面不能正常访问。

注释掉`import Player from 'xgplayer';`这段代码，再次打包项目访问正常！请问这个是什么原因导致的，项目中导入其他的包都够正常打包发布，添加这个包以后打包完毕就不能访问了。

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by pengweibin** [comment]
请问解决了吗

**Comment by EltonYi** [comment]
请问解决了吗？我们也遇到了同样的问题，
dev环境正常
build以后就会提示TypeError: Super expression must either be null or a function, not undefined

**Comment by zhangxin92** [comment]
最新版本已解决 xgplayer@2.31.3

**Comment by Littlombie** [comment]
2.31.6版本也遇到这样的问题
dev环境运行正常，
build 之后就会提示上述问题

**Comment by xiaoTeng6** [comment]
2.32.2版本也有这个问题 请问一下现在那个版本是好的
