### ISSUE TITLE
请问下，如何控制播放器控制条的显示时长

### ISSUE THREAD

**Issue by lightersss** [bytedance/xgplayer#590]
我想要控制播放器控制条的显示时长，以及鼠标移除播放器时控制条的维持时间的时长。请问下有相关的参数可以控制吗

**Comment by hongqx** [comment]
playerConfig = {
   leavePlayerTime: 3000, // 离开播放器范围的时候隐藏的延迟时间，单位 ms
   inactive: 3000, // 正常自动隐藏的延迟事件，单位 ms
}

**Comment by hongqx** [comment]
> 我想要控制播放器控制条的显示时长，以及鼠标移除播放器时控制条的维持时间的时长。请问下有相关的参数可以控制吗

playerConfig = {
    leavePlayerTime: 3000, // 离开播放器范围的时候隐藏的延迟时间，单位 ms
    inactive: 3000, // 正常自动隐藏的延迟事件，单位 ms
}
