### ISSUE TITLE
怎么设置自动播放 autoplay不起作用

### ISSUE THREAD

**Issue by dlj0906** [bytedance/xgplayer#591]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xuergo** [comment]
这个播放器限制吧，一般都不行的

**Comment by zhangxin92** [comment]
播放器的 autoplay 行为会受到浏览器规则限制
可参考 https://developer.chrome.com/blog/autoplay/

**Comment by ArthurMiao** [comment]
尝试使用play().catch后提示打开声音用户有了交互再自动播放呢

**Comment by dlj0906** [comment]
设置了autoplayMuted和 autoplay后自动播放生效了，但是声音会被禁掉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/xgplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月27日(星期一) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/xgplayer] 怎么设置自动播放 autoplay不起作用 (#591)





 
尝试使用play().catch后提示打开声音用户有了交互再自动播放呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
