### ISSUE TITLE
设置muted时音量图标展示异常

### ISSUE THREAD

**Issue by CracKerMe** [bytedance/xgplayer#592]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
version:"1.4.20"
CDN 方式引入
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
browser: "Edge"
device: "PC"
engine: "Blink"
language: "zh_CN"
os: "Mac OS"
osVersion: "10.15.7"
version: "91.0.864.37"

**如何复现问题？ What did you do?**
播放器实例 通过 设置 player.muted= true; 

**您期望的播放器正常行为是？ What did you expect to happen?**
当muted 为true 是，音量按钮应该显示为静音icon

**实际播放器的表现是？ What actually happened?**
当前音量的icon只根据 音量控件本身的值来显示的

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

版权视频素材站点使用的 西瓜播放器

**Comment by zhangxin92** [comment]
已在xgplayer@2.31.2版本支持
