### ISSUE TITLE
xgplayer-flv 插件跨域

### ISSUE THREAD

**Issue by wtz-henshuai** [bytedance/xgplayer#593]
xgplayer-flv 设置参数 isLive 为flase 会报跨域错误  二设置参数isLive 为true 则不会有此问题

**Comment by leonardoFu** [comment]
isLive: false会启用**range**方式请求数据，对于开启了**range**参数的请求，会被浏览器认定为复杂请求，同时会发起options预检请求，请确认一下错误信息，是哪个环节导致了请求跨域。
