### ISSUE TITLE
关于使用xgplayer-mp4插件导致切换清晰度时视频卡死一直loding状态

### ISSUE THREAD

**Issue by banckgg** [bytedance/xgplayer#595]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
    "xgplayer": "^2.27.3",
    "xgplayer-mp4": "^1.2.2",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
系统：mac 
浏览器：Chrome  92.0.4515.131

**如何复现问题？ What did you do?**
条件：引入xgplayer-mp4插件后并且可以分片加载播放。
操作：切换清晰度，就就会导致视频卡死但拖动下进度条后就可以正常播放。
            如果回退至卡死帧后播放至卡死帧还是会卡死。

**您期望的播放器正常行为是？ What did you expect to happen?**
能够无缝无感切换清晰度。

**实际播放器的表现是？ What actually happened?**
会出现卡死帧。导致系统无法正常播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
参考文档使用试下最新版本 xgplayer@2.31.2  xgplayer-mp4@2.0.0
https://v2.h5player.bytedance.com/plugins/#xgplayer-mp4
