### ISSUE TITLE
设置rotateFullscreen后  requestCssFullscreen 以及 exitCssFullscreen 事件不回调

### ISSUE THREAD

**Issue by pocketChao** [bytedance/xgplayer#596]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.26.5

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOs chrome

**如何复现问题？ What did you do?**
设置rotateFullscreen后点击全屏以及退出全屏按钮

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常走requestCssFullscreen以及exitCssFullscreen的事件回调或者提供新的回调

**实际播放器的表现是？ What actually happened?**
并没有走回调

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
最新xgplayer@2.27.3版本监听getRotateFullscreen和exitRotateFullscreen事件
