### ISSUE TITLE
进度条拖拽事件如何监听

### ISSUE THREAD

**Issue by LLilith** [bytedance/xgplayer#599]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS和Chrome

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
可以监听进度条事件

**实际播放器的表现是？ What actually happened?**
没有该事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
监听seeked事件
https://v2.h5player.bytedance.com/api/#%E4%BA%8B%E4%BB%B6
