### ISSUE TITLE
能否手动触发清除拉流请求?

### ISSUE THREAD

**Issue by okssq** [bytedance/xgplayer#601]
当前使用的是xg-flvplayer.js 2.4.x,
当手动调用player.destroy时，若拉流请求处于正常状态便不会再持续请求，
若拉流状态为pending是调用destroy，则拉流请求会持续请求数据！！
请问有什么办法解决吗？

**Comment by leonardoFu** [comment]
收到，这个问题我们确认一下，如果存在的话近期发版处理

**Comment by okssq** [comment]
> 收到，这个问题我们确认一下，如果存在的话近期发版处理

好的，谢谢！
