### ISSUE TITLE
反复出现刷新，刷新后也没用

### ISSUE THREAD

**Issue by 3026546679** [bytedance/xgplayer#603]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
<script src="//cdn.jsdelivr.net/npm/xgplayer@2.9.6/browser/index.js" charset="utf-8"></script>
<script src="//cdn.jsdelivr.net/npm/xgplayer-hls/dist/index.min.js" charset="utf-8"></script>

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
谷歌浏览器最新版 mac系统 win也出现一样的问题

**如何复现问题？ What did you do?**
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-53aebf66-c1dd-41a2-bc07-db6afd0d5330/e3f026ee-7508-419b-8615-7c2751ccf424.mov](url)这是问题出现时录制的

**Comment by 3026546679** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
> 
> <script src="//cdn.jsdelivr.net/npm/xgplayer@2.9.6/browser/index.js" charset="utf-8"></script> <script src="//cdn.jsdelivr.net/npm/xgplayer-hls/dist/index.min.js" charset="utf-8"></script>
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
> 谷歌浏览器最新版 mac系统 win也出现一样的问题
> 
> **如何复现问题？ What did you do?**
> [https://vkceyugu.cdn.bspapp.com/VKCEYUGU-53aebf66-c1dd-41a2-bc07-db6afd0d5330/e3f026ee-7508-419b-8615-7c2751ccf424.mov](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-53aebf66-c1dd-41a2-bc07-db6afd0d5330/e3f026ee-7508-419b-8615-7c2751ccf424.mov)这是问题出现时录制的

**Comment by 3026546679** [comment]
有大佬解答么

**Comment by wwh1248** [comment]
试试升级最新版本
