### ISSUE TITLE
流数据正常下载，xgplayer-flv无法播放

### ISSUE THREAD

**Issue by okssq** [bytedance/xgplayer#604]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.27.3"
 "xgplayer-flv": "^2.4.32",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 / chrome 92.0.4515.131

**如何复现问题？ What did you do?**
再官网demodemo中，有两种播放http-flv视频格式，选用自己的流地址，xgplayer-flv无法播放，xgplayer-flv.js可以播放，
但是如果使用xgplayer肯定是用官方维护的xgplayer-flv比较好！
如果能帮忙测下问题需要我的http-flv流地址可以加下我qq525151053或者在此回复（可能没法及时回复），万分感谢！

**您期望的播放器正常行为是？ What did you expect to happen?**
可以正常播放

**实际播放器的表现是？ What actually happened?**
一直出于loading状态

**Comment by okssq** [comment]
[这是流数据一直加载却无法播放视频的图片](
![image](https://user-images.githubusercontent.com/52643522/129137374-10f974a9-ff48-49ed-8ed3-ac3690af083b.png)
)

**Comment by zyf540860996** [comment]
你解决了么？我们也遇到一直加载，但是无法播放，xgplayer-flv.js可以正常播放，xgplayer-flv不行

**Comment by okssq** [comment]
> 你解决了么？我们也遇到一直加载，但是无法播放，xgplayer-flv.js可以正常播放，xgplayer-flv不行

后面用了mpegts库
