### ISSUE TITLE
流加载错误后点击刷新按钮，可否暴露刷新按钮点击事件

### ISSUE THREAD

**Issue by fanwenfu** [bytedance/xgplayer#608]
作者大大，我这因为业务需要，只要流加载错误后，都需要重新获取流的地址，所以点击刷新按钮，可否暴露刷新按钮点击事件

**Comment by fanwenfu** [comment]
目前是在react中使用，因react事件处理特殊，手动添加点击监听无效

**Comment by zhangxin92** [comment]
支持设置自定义错误文字提示HTML内容，可给自定义DOM添加点击等事件
https://v2.h5player.bytedance.com/config/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%99%E8%AF%AF%E6%8F%90%E7%A4%BA
