### ISSUE TITLE
iOS手机首次加载m3u8文件，加载时间过长直至失败，失败后刷新才可播放。

### ISSUE THREAD

**Issue by guodong01** [bytedance/xgplayer#609]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
  xgplayer: 2.22.1
  xgplayer-hls.js: 2.4.2
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
  iOS系统 webview加载

**如何复现问题？ What did you do?**
  首次播放会有问题，之后打开比较迅速

**您期望的播放器正常行为是？ What did you expect to happen?**
  首次快速加载并可以播放

**实际播放器的表现是？ What actually happened?**
  首次加载慢并且失败，刷新后可播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
移动web端播hls直接基于原生video，反馈的问题可能与资源请求缓存有关
