### ISSUE TITLE
如何实现ABS自适应流，根据网速自动切换码率

### ISSUE THREAD

**Issue by jiangyi1985** [bytedance/xgplayer#611]
m3u8 已经实现了用户手动切换不同码率
如何实现自动切换码率，而不是用户手动切换？

**Comment by zhangxin92** [comment]
自适应码率切换功能没有开源，需要开发者自己实现。

**Comment by miroku-y** [comment]
@zhangxin92 请问现在开源了吗？ 还是要自行实现？
