### ISSUE TITLE
xgplayer-flv.js 页面失活状态下会触发 pause 事件!

### ISSUE THREAD

**Issue by ccyytt** [bytedance/xgplayer#612]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer 2.25.0  xgplayer-flv.js 2.3.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macos 及 window

**如何复现问题？ What did you do?**
 播放实时流时,浏览器失活状态(切换 浏览器 tab 页面) 会触发 pause 事件. 

**您期望的播放器正常行为是？ What did you expect to happen?**
不触发.

**实际播放器的表现是？ What actually happened?**
会触发 pause 事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
无法复现反馈的问题。
