### ISSUE TITLE
在MacOS Big Sur 11.2-11.4的Safari浏览器上，用xgplayer-flv播放直播时，一直有呲呲啦啦的噪音

### ISSUE THREAD

**Issue by zhangc20** [bytedance/xgplayer#613]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS Big Sur  11.4
Safari

**如何复现问题？ What did you do?**
xgplayer-flv播放直播时，一直有呲呲啦啦的噪音

**您期望的播放器正常行为是？ What did you expect to happen?**
没有噪音

**实际播放器的表现是？ What actually happened?**
一直有呲呲啦啦的噪音

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by xiyuyizhi** [comment]
目前我们定位是个别safari浏览器的实现问题，对flv转封装成fmp4 音频采用timescale:1000 音频播放会有问题。我们近期会调整这块，对音频采用音频采样率为时间单位来封装fmp4

**Comment by hongrunhui** [comment]
请问，这个解决了吗？我也有这个问题
