### ISSUE TITLE
mp4和m3u8怎么自动识别

### ISSUE THREAD

**Issue by 2dan** [bytedance/xgplayer#615]
mp4是 let player=new Player
hls是 let player = new HlsPlayer
可以统一一下，自动识别吗？

**Comment by xiyuyizhi** [comment]
流格式不同，需要使用不同的播放插件，参数格式是类似的

**Comment by xuesongde** [comment]
同求，我们这业务场景需要切换视频源，视频源是mp4和m3u8混合的，总是切的时候再去new一次感觉怪怪的，如果url能接受对象或者数组就完美了

**Comment by youngchou1997** [comment]
我目前处理是做文件类型判断，m3u8就用hls否则用常规的
![image](https://user-images.githubusercontent.com/16507306/141890660-4e2a403f-955d-4a97-9365-372cf935a5ce.png)

**Comment by zhangxin92** [comment]
建议通过链接后缀或者链接前N数据来进行判断使用不同的插件
