### ISSUE TITLE
移动端直播播放hls频繁闪屏

### ISSUE THREAD

**Issue by xiaoshuaikang** [bytedance/xgplayer#616]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

 2.20.12

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Android、微信浏览器

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放直播

**实际播放器的表现是？ What actually happened?**
直播播放大概五六秒频繁闪屏

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by sunny-wanghaiqing** [comment]
哈喽  解决了不

**Comment by xiaoshuaikang** [comment]
> 哈喽 解决了不

好像是版本问题
