### ISSUE TITLE
全屏事件 requestFullScreen 和 getFullscreen 无效 

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#617]
终端：PC 端（iPhoneX）
问题：全屏事件 requestFullScreen 和 getFullscreen 无效 ；退出全屏可以监听到

**Comment by hongqx** [comment]
移动端全屏api不能通过js直接调用，必须要要用户行为触发，也就是说要在dom的事件回调中才能调用，否则会包异常

**Comment by hongqx** [comment]
https://stackoverflow.com/questions/9454125/javascript-request-fullscreen-is-unreliable
具体原因描述可参考
