### ISSUE TITLE
播放器封面尾图无法设置,重播和开始一起出现

### ISSUE THREAD

**Issue by 18801214376lk** [bytedance/xgplayer#618]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

"xgplayer": "^2.29.1"
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows10
Chrome 88.0.4324.182

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

可以设置封面 有重播按钮开始按钮消失
**实际播放器的表现是？ What actually happened?**

播放器封面尾图无法设置,重播和开始一起出现
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
没有复现反馈的问题，建议升级最新版本试下 xgplayer@2.31.1
