### ISSUE TITLE
急～xgplayer-hls.js 安卓监听到playing事件后出现10s左右的黑屏才开始播放画面

### ISSUE THREAD

**Issue by foolish-boy** [bytedance/xgplayer#620]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer-hls.js@2.5.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓 版本10  内核版本 4.19.181

**如何复现问题？ What did you do?**
直接请求m3u8的直播流

**您期望的播放器正常行为是？ What did you expect to happen?**
加载结束后 直接出现画面，不要黑屏等待

**实际播放器的表现是？ What actually happened?**
加载结束后 会出现控制条 但是画面黑屏 等10s左右才出现画面

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
云监控

在chrom浏览器测试同样地址是ok的，监听到playing事件后里面开始播放画面，但是安卓手机会继续黑屏一段时间
我猜可能是在做视频流解析？但是此时不应该回调到playing事件啊！我也没有在官方文档里找到视频解析中的事件

**Comment by zhangxin92** [comment]
安卓场景下可通过useHls: true配置使用hls.js相关能力来控制加载过程 https://github.com/video-dev/hls.js/blob/master/docs/API.md
