### ISSUE TITLE
困扰了很久的大Bug：切换视频源的同时切换弹幕内容

### ISSUE THREAD

**Issue by mrjianggg** [bytedance/xgplayer#621]
this.player.danmu.comments = danmu2;
this.player.src = src2;
视频源切换成功了，但是弹幕还是上一个视频里面的弹幕，danmu2打印出来是第二视频里面的弹幕为更新到播放器上

**Comment by zhangxin92** [comment]
试下xgplayer@2.30.1版本
player.danmu.updateComments (comments, isClear) //更新弹幕数据（isClear默认为true，表示清空旧数据）

**Comment by mrjianggg** [comment]
有效 可以了，谢谢
