### ISSUE TITLE
iOS 设备播放视频时点击画中画悬浮播放之后，点击悬浮播放器窗口的左上角关闭之后，出现了无法再次全屏

### ISSUE THREAD

**Issue by llftt** [bytedance/xgplayer#623]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iPhone 8 系统版本14.6
iPhone 12 系统版本14.7

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**
可以全屏

**实际播放器的表现是？ What actually happened?**
全屏后无法再全屏

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
问题已经收到，我们会尽快修复
