### ISSUE TITLE
安卓手机调整播放速度没有效果

### ISSUE THREAD

**Issue by foolish-boy** [bytedance/xgplayer#626]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
xgplayer-hls@2.5.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓 版本10 内核版本 4.19.181

**如何复现问题？ What did you do?**
设置playbackRate：[0.5,1,2,4] 然后手动切换倍速，实际效果都是1倍

**您期望的播放器正常行为是？ What did you expect to happen?**
按照选择的倍速来播放

**实际播放器的表现是？ What actually happened?**
全是1倍速度播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
云监控

**Comment by zhangxin92** [comment]
倍速播放功能是基于原生video提供的API实现，安卓环境部分场景系统没有支持这个API能力
