### ISSUE TITLE
error事件监测不到url报错，network error，404等

### ISSUE THREAD

**Issue by taojunnan** [bytedance/xgplayer#627]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
"xgplayer": "^2.27.3",
"xgplayer-flv.js": "^2.3.0",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows，chrome

**如何复现问题？ What did you do?**
用一个无法正常播放的flv url

**您期望的播放器正常行为是？ What did you expect to happen?**
player.on('error')能正常监测到

**实际播放器的表现是？ What actually happened?**
无限loading，player.on('error')监测不到

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
。

**Comment by wwh1248** [comment]
xgplayer: 2.31.1
xgplayer-hls.js: 2.6.0
同样的现象
无论是一开始的m3u8视频链接错误还是后续分段的ts链接报错（403/404等等）都只是一直loading
ts片段报错还导致无限重试，造成公司内部监控系统上针对该ts片段http资源链接疯狂报警
期望：触发onError事件，停止loading

**Comment by taojunnan** [comment]
+1
