### ISSUE TITLE
移动端浏览器加载m3u8，我的每个ts文件是10s的，但是播放了2、30s，却已经加载（缓冲）了7 8分钟的视频了（0001.ts ~ 0042.ts），有没有加载的规则可以手动设置？

### ISSUE THREAD

**Issue by mrchzh** [bytedance/xgplayer#628]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.30.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios13.3  safari浏览器

**如何复现问题？ What did you do?**
找一个m3u8 找一个ios手机，然后直接用new Player初始化即可，因为移动端都支持加载m3u8,所以不需要特殊处理 hls

**您期望的播放器正常行为是？ What did you expect to happen?**
可以自己设置缓冲行为，不能播放了20s 却加载了 7 8分钟的视频...

**实际播放器的表现是？ What actually happened?**
浏览器加载m3u8，我的每个ts文件是10s的，但是播放了2 30s，却已经加载（缓冲）了7 8分钟的视频了（0001.ts ~ 0042.ts），用fiddler抓包能看到，下面我也放抓包的图了

![image](https://user-images.githubusercontent.com/33919096/133734362-439b216f-44b0-4220-8bc4-220055380714.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by mrchzh** [comment]
刚才试了    <script src="//cdn.jsdelivr.net/npm/xgplayer-hls.js/browser/index.js" charset="utf-8"></script><script>
      let player = new HlsJsPlayer({
在移动端浏览器中报错  
![image](https://user-images.githubusercontent.com/33919096/133741071-1075eb66-09fd-447a-8fd0-7b6cb3215080.png)
但是在pc的模拟器中好使
所以还得用
new Player()
又回到刚才的问题了  观看了20来s 然后加载了 7 8分钟的视频。。。怎么解决

**Comment by lfzs** [comment]
可以尝试配置下 hlsOpts ，hlsjs 提供了一些预加载策略，如 maxBufferSize、maxBufferLength 等

**Comment by zhangxin92** [comment]
iOS系统的浏览器中是直接使用原生video播放hls视频，无法控制ts分片的加载；PC场景可通过配置hlsOpts实现
