### ISSUE TITLE
样式全屏与浏览器全屏冲突 Bug 导致播放器消失

### ISSUE THREAD

**Issue by zhenzhenChange** [bytedance/xgplayer#629]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.30.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Win 11 + Chrome 93.0.4577.82（正式版本） （64 位）

**如何复现问题？ What did you do?**
- 先点击`进入样式全屏`
- 再点击`进入全屏`
- 点击`退出全屏`
- 播放器消失

**您期望的播放器正常行为是？ What did you expect to happen?**
退出全屏后是不是应该回到样式全屏或者直接退出所有的全屏模式？

**实际播放器的表现是？ What actually happened?**
播放器消失了，不过声音还在，视频还在播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhenzhenChange** [comment]
盲猜可能是这里的问题：https://github.com/bytedance/xgplayer/blob/687b4f6a2e1ca67a9428e82a91a9add60c3c809f/packages/xgplayer/src/controls/fullscreen.js#L92

**Comment by zhangxin92** [comment]
在最新版本xgplayer@2.31.1无法复现，可以更新试下
