### ISSUE TITLE
建议支持自定义按钮图标，比如旋转按钮

### ISSUE THREAD

**Issue by wqjiao** [bytedance/xgplayer#632]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
v2.29.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS、Chrome

建议提供一个自定义按钮图标的入口，比如替换 旋转按钮的图标等

**Comment by zhangxin92** [comment]
正在内部测试的新版本会支持该能力，目前版本可通过自定义样式方式解决

**Comment by jialinNEU** [comment]
您使用的西瓜播放器版本是多少？ What version of xglayer are you using?
v2.31.3

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
macOS、Chrome

我看了下源码，src/skin/controls/start.js 这个文件里定义播放器正中央的播放按钮，是写死的，似乎不可以通过自定义配置方式来解决？还是说是直接改变特定class类名的DOM节点的样式？
