### ISSUE TITLE
ios 微信频繁 loading

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#633]
使用 xgplayer-hls.js 插件在 ios 的微信端播放时，会频繁进行 loading，在 PC 端和 Android 端均无此现象

**Comment by zhangxin92** [comment]
ios场景播hls是基于原生video实现解析播放，建议检查下视频资源请求情况

**Comment by XFJ712** [comment]
> 发一下用的插件版本

"xgplayer": "^2.6.15",
"xgplayer-hls.js": "^2.4.2"

**Comment by XFJ712** [comment]
> ios场景播hls是基于原生video实现解析播放，建议检查下视频资源请求情况

请问应该如何查看视频资源请求情况，我在手机端打开调试模式的时候，在network 里仅能看到其他的请求，无法看到请求流的详细信息
