### ISSUE TITLE
请问各位，如何在播放结束的时候重置poster封面图呢

### ISSUE THREAD

**Issue by codedart2018** [bytedance/xgplayer#636]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.30.1

```
      player.on('ended', function() {
        console.log('end');
        // player.poster = 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/111756/18/17471/490792/61395c96E7da0b7ee/f6229351750acc30.jpg!q80.dpg.webp';
      });
```
我通过文档查看到
![image](https://user-images.githubusercontent.com/12706830/136259114-ab5ec703-a952-4502-8000-bd9015cc14ca.png)
不是一个有效的参数，播放结束后并没有效果。

**Comment by zhangxin92** [comment]
播放结束后会展示视频最后一帧画面，不会显示海报图，建议通过销毁重建播放器实现
