### ISSUE TITLE
请问怎么让视频内容填满全部控件区域, 忽略分辨率

### ISSUE THREAD

**Issue by addriumruss** [bytedance/xgplayer#638]
请问怎么让视频内容宽高自适应控件宽高，就是不管视频分辨率多少，播放时候让视频宽高总是填满全部控件区域.
谢谢!

**Comment by addriumruss** [comment]
@hongqx 感谢回应！  只是xgplayer示例都是用的div, 没有用video， 
<body>
    <div id="player"></div>
  </body>

请问这个div能被换成video吗

**Comment by zhangxin92** [comment]
不支持传video，播放器会在div内部创建video、播控UI等元素
