### ISSUE TITLE
西瓜播放器支持移动端手势操作音量和亮度吗？

### ISSUE THREAD

**Issue by MarcoBeer** [bytedance/xgplayer#640]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.9.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
微信浏览器，安卓8.0，h5平台

**如何复现问题？ What did you do?**
无法通过手机手势调整音量与屏幕亮度

**您期望的播放器正常行为是？ What did you expect to happen?**
可以通过手机手势调整音量与屏幕亮度

**实际播放器的表现是？ What actually happened?**
无法通过手机手势调整音量与屏幕亮度

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
移动端h5平台

**Comment by hongqx** [comment]
当前版本不能调节，原因如下：
1.  h5无法控制系统亮度
2. 音量的调节在移动端兼容性不好，不同app、不同系统差异较大，例如， ios端对音量调节是没有相应的
