### ISSUE TITLE
使用xgplayer-hls.js播放m3u8格式视频一直在加载，不出现视频

### ISSUE THREAD

**Issue by zzzwwwwww** [bytedance/xgplayer#642]
this.player = new HlsPlayer({
        id: 'mse',
        url: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
        autoplay: true,
        playsinline: true,
        fluid: true
      })

**Comment by zhangxin92** [comment]
xgplayer-hls.js@2.6.0版本已支持播放
