### ISSUE TITLE
lastPlayTime属性设置了无法断点续播，视频还是从头播放

### ISSUE THREAD

**Issue by oyeaono** [bytedance/xgplayer#648]
安卓h5，2.31.1版本，设置了lastPlayTime属性，无法断点续播，视频还是从头开始播放

**Comment by PaulChess** [comment]
我这边也试了一下，单纯地设 `lastPlayTime` 确实无法断点续播，只会出现文字提示，  
  
但是设置了如下两个属性就好了:  
```javascript
autoplay: true,
autoplayMuted: true,
```  
  
猜想也是受到了浏览器的限制  
  
@oyeaono

**Comment by zhangxin92** [comment]
测试没复现问题。可能与不同环境原生video的事件触发逻辑不同有关。开发者可检测相应环境起播是否触发canplay/play/playing等事件，首次触发时设置currenTime属性即可实现断点续播
player.once('canplay', () => { player.currentTime = 10; //设置从第10秒起播 })
