### ISSUE TITLE
移动端播放，显示please try to refresh，不能正常播放

### ISSUE THREAD

**Issue by XiangHengYi** [bytedance/xgplayer#653]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
https://cdn.jsdelivr.net/npm/xgplayer@2.9.6/browser/index.js
https://cdn.jsdelivr.net/npm/xgplayer-hls/dist/index.min.js

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
HarmonyOs 2.0.0（华为nova8）
Chrome Nightly 86.0.4240.99（微信中，通过链接打开H5页面）

**如何复现问题？ What did you do?**
移动端正常播放即出现

**您期望的播放器正常行为是？ What did you expect to happen?**
播放视频

**实际播放器的表现是？ What actually happened?**
please try to refresh

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by zhangxin92** [comment]
移动web端可直接使用xgplayer播放hls视频
