### ISSUE TITLE
HlsPlayer在ios微信浏览器中播放m3u8视频，一直显示loading

### ISSUE THREAD

**Issue by mengxiao-ac** [bytedance/xgplayer#654]
xgplayer:2.31.0
xgplayer-hls:2.4.32

错误信息:
`
undefined is not a constructor (evaluating 'new self.MediaSource')
value@http://192.168.81.87:1024/h5/static/js/xgplayer-hls.min.js:1:20162 value@http://192.168.81.87:1024/h5/static/js/xgplayer-hls.min.js:1:137416 value@http://192.168.81.87:1024/h5/static/js/xgplayer-hls.min.js:1:16694 value@http://192.168.81.87:1024/h5/static/js/xgplayer-hls.min.js:1:147246 i@http://192.168.81.87:1024/h5/static/js/xgplayer.min.js:1:51810 o@http://192.168.81.87:1024/h5/static/js/xgplayer.min.js:1:40658 r@http://192.168.81.87:1024/h5/static/js/xgplayer.min.js:1:22711 value@http://192.168.81.87:1024/h5/static/js/xgplayer.min.js:1:22889 http://192.168.81.87:1024/h5/static/js/xgplayer.min.js:1:53613
`

相同的流在安卓微信浏览器里面是没有问题，不知道什么原因。
使用的视频源：
https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8

**Comment by weiyang45** [comment]
我之前也遇到了，把xgplayer-hls换成#xgplayer-hls.js就可以了

**Comment by mengxiao-ac** [comment]
嗯嗯我后面换了，是可以了，但是不知道xgplayer-hls为啥不行

**Comment by fengxinming** [comment]
请问一下有没有类似cacheEncryptionKeys这个参数可以设置不用每次都去获取密钥

**Comment by zhangxin92** [comment]
移动web端可直接使用xgplayer播放hls视频
