### ISSUE TITLE
移动端隐藏下载

### ISSUE THREAD

**Issue by QQOQ** [bytedance/xgplayer#662]
移动端会显示下载视频按钮，怎么隐藏？download设置为false无效

**Comment by zhangxin92** [comment]
> 

使用的xgplayer版本是多少？播放器是否被劫持？

**Comment by QQOQ** [comment]
> > 
> 
> 使用的xgplayer版本是多少？播放器是否被劫持？

最新版的，你用小米手机浏览器打开你们官网的视频看看就知道了，video.js就可以

**Comment by zhangxin92** [comment]
> > > 
> > 
> > 
> > 使用的xgplayer版本是多少？播放器是否被劫持？
> 
> 最新版的，你用小米手机浏览器打开你们官网的视频看看就知道了，video.js就可以

小米手机自带浏览器会把播放器劫持，替换成自己的UI和控件，前端播放器控制不了
