### ISSUE TITLE
xgplayer-hls.js 使用 useHls: true ，视频源问题

### ISSUE THREAD

**Issue by sdandroid** [bytedance/xgplayer#663]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
最新

**如何复现问题？ What did you do?**

xgplayer-hls.js 使用 useHls: true ，在视频没有播放是，调用start(url),再调用play(),播放的视频源还是，播放器初始化的视频源

**您期望的播放器正常行为是？ What did you expect to happen?**
播放start(url)，传入的url

**Comment by zhangxin92** [comment]
这样试下
player.start();
player.src = 'new url';

**Comment by sdandroid** [comment]
可以，谢谢。
