### ISSUE TITLE
播放器正中央的播放/暂停按钮支持自定义

### ISSUE THREAD

**Issue by jialinNEU** [bytedance/xgplayer#672]
您使用的西瓜播放器版本是多少？ What version of xglayer are you using?
v2.31.3

您使用的操作系统和浏览器分别是？ What OS and browser are you using?
macOS、Chrome

我看了下源码，src/skin/controls/start.js 这个文件里定义播放器正中央的播放按钮，是写死的，似乎不可以通过自定义配置方式来解决？还是说是直接改变特定class类名的DOM节点的样式？

**Comment by Jiujiuou** [comment]
最近刚好碰到类似的需求，正中间的按钮是支持配置的
`
const player = new Player({
      id: [your video wrapper id],
      url: [your video url],
      icons: {
           startPlay: `<img style="width: 50px" src="${[your icon url]}"/>`,
           startPause: `<img style="width: 50px" src="${[your icon url]}"/>`,
      },
    });
`
版本 "xgplayer": "^3.0.0-alpha.92-4"
