### ISSUE TITLE
QQ浏览器ios下播放器被劫持，白名单也没有什么用啊，并且看了我们的播放器，也没有找到对whitelist处理的地方，但是西瓜视频在qq浏览器下ios没有被劫持，是如何做到的呢

### ISSUE THREAD

**Issue by Zwahxf** [bytedance/xgplayer#680]
**您使用的西瓜播放器版本是多少？ What version of xglayer are you using?**
2.31.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iPhone QQ浏览器

@zhangxin92

**Comment by Zwahxf** [comment]
QQ浏览器ios下播放器被劫持，白名单也没有什么用啊，并且看了我们的播放器，也没有找到对whitelist处理的地方，但是西瓜视频在qq浏览器下ios没有被劫持，是如何做到的呢

**Comment by Mr-prudent** [comment]
试着开启内联模式：
`new Player({
  el:document.querySelector('#mse'),
  url: 'video_url',
  playsinline: true
});`

**Comment by Zwahxf** [comment]
> 试着开启内联模式： `new Player({ el:document.querySelector('#mse'), url: 'video_url', playsinline: true });`

playsinline是解决全屏的问题吧，qq浏览器劫持的不行，这个是加的有
