### ISSUE TITLE
微信端自动播放问题

### ISSUE THREAD

**Issue by XFJ712** [bytedance/xgplayer#684]
播放器版本：
"xgplayer": "^2.6.15",
"xgplayer-hls.js": "^2.4.2"

播放器设置：
autoplay: true,
autoplayMuted: true,

期望效果：
可以在微信端自动播放

实际表现：
仅在 PC 端自动播放
在移动端，保持展示中间播放按钮的页面，需要用户点击播放按钮，才可播放

**Comment by lishaoxin123** [comment]
可通过监听网络在播放，微信自动播放

**Comment by huogui** [comment]
解决了吗？我移动端浏览器都不能自动播放，只有pc可以

**Comment by clz1024** [comment]
> 解决了吗？我移动端浏览器都不能自动播放，只有pc可以

我这里是浏览器可以就微信内嵌的不行
