### ISSUE TITLE
m3u8视频在iphone上无法播放

### ISSUE THREAD

**Issue by rubine413** [bytedance/xgplayer#691]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer@2.27.3
xgplayer-hls.js@2.6.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iphone xr

**如何复现问题？ What did you do?**
有的m3u8视频在安卓手机端可以播放，但iphone的微信和任意浏览器内访问无法播放

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Reymonded** [comment]
移动web端可直接使用xgplayer播放hls视频

**Comment by lfzs** [comment]
配置不要开启 useHls
