### ISSUE TITLE
hls视频无法播放，一直转圈

### ISSUE THREAD

**Issue by MaoSource** [bytedance/xgplayer#693]
版本
"vue": "2.5.17",
"xgplayer": "^2.31.4",
"xgplayer-hls.js": "^2.6.1"

hls视频无法播放项目无任何报错，切片也能加载就是不播放
![image](https://user-images.githubusercontent.com/56857029/147726199-6efb8210-0639-4a38-8296-0a3d967104c4.png)
![image](https://user-images.githubusercontent.com/56857029/147726265-17d71223-12ed-471c-8792-f6ae282c252d.png)

代码：
`<template>
  <div>
    <div id="mmid" ref="video"/>
  </div>
</template>

<script>
import HlsJsPlayer from 'xgplayer-hls.js'
export default {
  data() {
    return {
      videoPlayer: null
    }
  },
  mounted() {
    this.getVideo()
  },
  methods: {
    getVideo() {
      this.videoPlayer = new HlsJsPlayer({
        el: document.querySelector('#mmid'),
        url: 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8',
        width: '100%',
        height: '240px',
        volume: 0.6, // 初始音量
        autoplay: true, // 自动播放
        playsinline: true,
        isLive: true,
        cors: true
      })
    }
  }
}
</script >

`

**Comment by yellowimg** [comment]
老哥你这个hls切片加载成功但是不播放一直转圈的解决了吗能不能分享下解决方案，求求了

**Comment by lishaoxin123** [comment]
> efault { data() { return { videoPlayer: null } }, mounted() { this.getVideo() }, methods: { getVideo() { this.videoPlayer = new HlsJsPlayer({ el: document.querySelector('#mmid'), url: 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8', width: '100%', height: '240px', volume: 0.6, // 初始音量 autoplay: true, // 自动播放 playsinline: true, isLive: true, cors: true }) } } }

没有去播放。你设置了autoPlay但是自动播放还需要在设置一个autoplayMuted

**Comment by cleoTang** [comment]
同问怎么解决的呢

**Comment by EnL14U** [comment]
h265编码格式的视频吧，你这是

**Comment by JacksionGT** [comment]
我遇到了你的问题。说下我的情况：
- 代码与你的类似
- 程序运行的表现也是与你描述的相似
  - m3u8和ts文件都可以加载成功
  - 调用video.play()无法播放
  - 拖动进度条可以播放
- 换了其他的在线m3u8文件的url可以顺利播放
经过一系列折腾，我发现：既然同样的代码只要有m3u8可以播放，那么肯定是我的视频文件m3u8或者ts分片文件有问题。当然这不是前端开发者负责的工作范围，如果你想获得一个可供调试的hls列表文件和分片文件，可以使用ffpmeg重现生成。

示例命令如下：
``` shell
ffmpeg -i input.mp4 -c:v h264 -flags +cgop -g 30 -hls_time 2 -hls_list_size 0 -hls_segment_filename output%03d.ts output.m3u8
```

**Comment by JacksionGT** [comment]
> 我遇到了你的问题。说下我的情况：
> 
> * 代码与你的类似
> * 程序运行的表现也是与你描述的相似
>   
>   * m3u8和ts文件都可以加载成功
>   * 调用video.play()无法播放
>   * 拖动进度条可以播放
> * 换了其他的在线m3u8文件的url可以顺利播放
>   经过一系列折腾，我发现：既然同样的代码只要有m3u8可以播放，那么肯定是我的视频文件m3u8或者ts分片文件有问题。当然这不是前端开发者负责的工作范围，如果你想获得一个可供调试的hls列表文件和分片文件，可以使用ffpmeg重现生成。
> 
> 示例命令如下：
> 
> ```shell
> ffmpeg -i input.mp4 -c:v h264 -flags +cgop -g 30 -hls_time 2 -hls_list_size 0 -hls_segment_filename output%03d.ts output.m3u8
> ```

这个命令将输入的`input.mp4`文件转换为HLS格式，并输出`output.m3u8`的M3U8文件和一系列的`.ts`分段文件。其中，
- `-c:v h264`指定使用H.264编码器
- `-flags +cgop -g 30`设置关键帧间隔为30帧
- `-hls_time 2`设置每个分段的时长为2秒
- `-hls_list_size 0`表示不限制M3U8文件中的分段数
- `-hls_segment_filename output%03d.ts`指定分段文件的命名规则
