### ISSUE TITLE
下载功能有问题

### ISSUE THREAD

**Issue by Hunlongyu** [bytedance/xgplayer#696]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
最新版本

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows11 edge

**如何复现问题？ What did you do?**
https://v2.h5player.bytedance.com/generate/
官网案例，1分30秒的视频 点击下载需要等待20秒，才会弹出是否下载询问框，如果我替换成1小时的视频，等了几分钟都不会出现下载提示框。

视频测试地址：https://edu-ciqtek.oss-cn-beijing.aliyuncs.com/video/%E7%AC%AC%E4%B8%80%E8%AE%B2%20%E7%A5%9E%E7%A7%98%E7%9A%84%E5%85%89%E9%87%8F%E5%AD%90.mp4

**您期望的播放器正常行为是？ What did you expect to happen?**
只要视频能正常播放，按理来说点击下载按钮，就应该立即下载

**实际播放器的表现是？ What actually happened?**
等待很久，或者不出现下载提示

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by chenuvi** [comment]
我也遇到了相同的问题，同样的链接，使用浏览器原生 video 标签的下载很快，用 插件就很慢，只要视频稍微大点超过40mins
