### ISSUE TITLE
自动播放时，会触发页面聚焦，自动滚动到视频所在位置

### ISSUE THREAD

**Issue by Zhangchi123456** [bytedance/xgplayer#698]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
播放器触发play事件时触发video focus，可通过closePlayVideoFocus关闭
