### ISSUE TITLE
android系统播放m3u8视频设置currentTime无效

### ISSUE THREAD

**Issue by iBlackPi** [bytedance/xgplayer#700]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^2.31.2",
"xgplayer-hls.js": "^2.6.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
android 任何浏览器

**如何复现问题？ What did you do?**
在播放m3u8视频时，赋值currentTime无效，断点续播无效

**您期望的播放器正常行为是？ What did you expect to happen?**
currentTime赋值时能从指定时间开始播放

**实际播放器的表现是？ What actually happened?**
赋值currentTime和lastPlayTime都是无效的

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by MeQingJe** [comment]
碰到了同样的问题，希望早些解决

**Comment by yiwen03** [comment]
这个我在华为手机上测试没有问题，在小米上不行，播放开始触发playing事件的时候设置currentTime无效，setTimeout500ms后就可以了，这个应该是小米手机的bug。

**Comment by fyibin** [comment]
有些手机需要在canplay事件后才能设置currentTime，需要将设置currentTime放在事件处理函数中
```
videoPlayer.once('canplay',function() {
    // 设置当前播放时间，获取视频时长等等操作
       
});
```

**Comment by MeQingJe** [comment]
你好，按照你的方法，可能因为网络的缘故，我这边有时会加到700到800ms，延迟就相对较大了，有时还是会出现无效的情况，有没有其他可行的方法呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/xgplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/xgplayer] android系统播放m3u8视频设置currentTime无效 (Issue #700)





 
这个我在华为手机上测试没有问题，在小米上不行，播放开始触发playing事件的时候设置currentTime无效，setTimeout500ms后就可以了，这个应该是小米手机的bug。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
