### ISSUE TITLE
ios 上 waiting 和 canPlay事件永远只在开始的时候触发一次，导致不能监听到到视频loading 没播放时的状态

### ISSUE THREAD

**Issue by lebornjose** [bytedance/xgplayer#703]
****

**您使用的操作系统和浏览器分别是？ios 15.2.1 **

**如何复现问题？ios 上设置弱网环境，视频自动播放，同时监听这2个事件，会发现永远只触发一次**

**您期望的播放器正常行为是？ 如chrome浏览器标表现，在视频卡顿的时候触发这2个事件，不是只触发一次?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by Lee-Jp** [comment]
我也有这个问题，无法根据这个事件状态做定制开发，希望官方能够解决或者给出替代方案
