### ISSUE TITLE
部分视频使用xgplayer或者原生video可以播放，使用xgplayer-mp4插件报错，急需解决

### ISSUE THREAD

**Issue by KIKIWU** [bytedance/xgplayer#707]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer@1.1.7 ，xgplayer-mp4@1.2.4  尝试官方最新2.0.0也是会报错

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac os / chrome

**如何复现问题？ What did you do?**
这是问题视频https://j1.58cdn.com.cn/arthurupload/zhiyou/webplayer/errParse.mp4 ，使用xgplayer-mp4插件播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
停留在loading，浏览器报错, 报错信息如图
https://j1.58cdn.com.cn/arthurupload/zhiyou/webplayer/msg20220219.png

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
58

**Comment by KIKIWU** [comment]
> **您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** xgplayer@1.1.7 ，xgplayer-mp4@1.2.4 尝试官方最新2.0.0也是会报错
> 
> **您使用的操作系统和浏览器分别是？ What OS and browser are you using?** mac os / chrome
> 
> **如何复现问题？ What did you do?** 这是问题视频https://j1.58cdn.com.cn/arthurupload/zhiyou/webplayer/errParse.mp4 ，使用xgplayer-mp4插件播放
> 
> **您期望的播放器正常行为是？ What did you expect to happen?** 正常播放
> 
> **实际播放器的表现是？ What actually happened?** 停留在loading，浏览器报错, 报错信息如图 https://j1.58cdn.com.cn/arthurupload/zhiyou/webplayer/msg20220219.png
> 
> **可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer, for helping us provide better technical support.** 58

@[llftt](https://github.com/llftt)
@zhangxin92

**Comment by yiwen03** [comment]
使用xgplayer-mp4的时候，要求访问的mp4数据允许跨域。需要服务端设置一下

**Comment by yiwen03** [comment]
因为视频当中有两个音频轨道，有一个是ac3的，目前web端不支持这个音频格式

**Comment by yiwen03** [comment]
这个问题是因为mp4带的音频是mp3和ac-3编码的，目前不支持。可以转成aac的
