### ISSUE TITLE
哪里可以看到更新日志？

### ISSUE THREAD

**Issue by AnaniZhu** [bytedance/xgplayer#710]
目前都不知道每一个版本新增或修复了哪些内容。
release 板块没有，tag 板块也很久没更新了，是不是应该维护一个 CHANGELOG?

**Comment by wells1013** [comment]
+1

**Comment by gemxx** [comment]
我们会在v3版本开始维护changelog，目前v2暂停迭代，仅处于维护状态，感谢反馈

**Comment by KeJunMao** [comment]
@gemxx v3来了，有日志了吗

**Comment by gemxx** [comment]
> @gemxx v3来了，有日志了吗

可以看下各package内，会有一个changelog
