### ISSUE TITLE
移动端播放器download功能无效

### ISSUE THREAD

**Issue by estoi** [bytedance/xgplayer#714]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
`^2.31.4`

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
`Android11`

**如何复现问题？ What did you do?**
<img width="561" alt="image" src="https://user-images.githubusercontent.com/44252820/156963493-5b359104-fc64-4ab1-a9d6-d977665df115.png">

混合开发引入播放器，配置`download`功能，点击下载无反应

**您期望的播放器正常行为是？ What did you expect to happen?**
下载视频保存到系统相册

**实际播放器的表现是？ What actually happened?**
无反应,通过调试发现报跨域

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
使用capacitor+vue开发的app

**Comment by yiwen03** [comment]
download只能在PC端使用，移动端不支持
