### ISSUE TITLE
在iphone手机上，使用xgplayer播放中，拖动进度条，不够稳定，进度条会来回跳

### ISSUE THREAD

**Issue by fyibin** [bytedance/xgplayer#717]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "2.31.4"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Iphone手机IOS系统上均会出现，测试发现chrome浏览器，safari浏览器以及webview中wkwebview

**如何复现问题？ What did you do?**

在iphone手机上移动web页面中，播放视频中，拖拽进度条至将来的某一刻，然后拖回至前面的时刻，然后又往后拖一下。

这时候会出现进度条会先跳回至前面所在的时刻，然后再跳至目的地时刻。

另外发现拖动一次，会出2次seeking事件，一次seeked事件。

**您期望的播放器正常行为是？ What did you expect to happen?**

拖动至视频中的某一时刻，进度条直接跳至对应的时刻去，而不是先跳回至前一时刻再跳至目的时刻。

**实际播放器的表现是？ What actually happened?**

在iphone手机上移动web页面中，播放视频中，拖拽进度条至将来的某一刻，然后拖回至前面的时刻，然后又往后拖一下。

这时候会出现进度条会先跳回至前面所在的时刻，然后再跳至目的地时刻。这样的体验非常不好，期待大佬修复。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

希沃教育-课堂质量分析相关项目中应用

**Comment by yiwen03** [comment]
试下2.31.6版本，修复了拖动一次，seeking2次的问题。拖动的问题，在ios上测是正常的。
