### ISSUE TITLE
最新版本，支持哪些视频编码与格式？

### ISSUE THREAD

**Issue by wangzihao10086** [bytedance/xgplayer#721]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
mp4, mov, hls, flv, mpeg-dash, mp3, mp4a

**Comment by leonardoFu** [comment]
编码的话，目前主要支持H264

**Comment by Feafortecsy** [comment]
> mp4, mov, hls, flv, mpeg-dash, mp3, mp4a

补充几个格式，我测试过可以播放的，mkv,m4v,webm 。这个信息建议**添加到文档里面**。
另外，hls/flv应该要通过插件才能播放，直接使用xgplayer是不行的。版本是 `^2.32.2`
