### ISSUE TITLE
能添加个记忆位置直接集成到js里面吗？

### ISSUE THREAD

**Issue by aruoop** [bytedance/xgplayer#722]
能添加个记忆位置直接集成到js里面吗？然后直接在配置文件开启或关闭

**Comment by yiwen03** [comment]
可以看下这个文档 https://v2.h5player.bytedance.com/config/#%E8%AE%B0%E5%BF%86%E6%92%AD%E6%94%BE

**Comment by aruoop** [comment]
> 可以看下这个文档 https://v2.h5player.bytedance.com/config/#%E8%AE%B0%E5%BF%86%E6%92%AD%E6%94%BE

看了这个时间是固定的，有没有办法从浏览器缓存读取上次停止的时间，继续播放呢？

**Comment by yiwen03** [comment]
那这个可以自己写一个插件。

**Comment by aruoop** [comment]
> 那这个可以自己写一个插件。

菜鸟不懂写嘛，所以想着直接集成到官方的js里面，直接在配置文件开启或者关闭就完美了
