### ISSUE TITLE
关于重连

### ISSUE THREAD

**Issue by lishaoxin123** [bytedance/xgplayer#725]
2.31.6 What version of xgplayer are you using?**

市面上主流 What OS and browser are you using?**

流断了 What did you do?**

流断了 What did you expect to happen?**

流断了手动触发reload无效 What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

请问西瓜视频怎么实现重新连，假设我流没推上去一开始还是404这时候我自己去reload但是没效果，url ='  ' 然后在url =xx，在去play依旧没有效果，必须得重新new 一个实例？

**Comment by leonardoFu** [comment]
直播播放器如果使用xgplayer-flv/hls插件，本身会重拉的。然后如果您需要手动重拉的话可以player.src = url就行

**Comment by lishaoxin123** [comment]
> 直播播放器如果使用xgplayer-flv/hls插件，本身会重拉的。然后如果您需要手动重拉的话可以player.src = url就行

并不会重拉假设流还没推上是404的时候这时候直接就err掉了，还有个问题就是destroy没有把上一次的请求给注销了，假设我先设置url=null再去destroy这时候会诡异的new 多一个视频出来。

**Comment by leonardoFu** [comment]
您使用的直播插件及版本是多少？

**Comment by lishaoxin123** [comment]
> 您使用的直播插件及版本是多少？

分别是 "xgplayer": "^2.31.6", "xgplayer-hls.js": "^2.6.1"，还有个奇怪的问题在微信上不管是使用改变src的方式还是重新init来做重连都会很诡异的无效

**Comment by leonardoFu** [comment]
建议使用xgplayer-hls哈，xgplayer-hls.js的逻辑主要还是hls.js的，我们不会去改动。微信浏览器是在安卓上么？

**Comment by lishaoxin123** [comment]
> 
好的，微信浏览器实在ios上的安卓没试过

**Comment by trry-github** [comment]
> > 
> 
> 好的，微信浏览器实在ios上的安卓没试过

你现在可以用了么

**Comment by lishaoxin123** [comment]
> 

没用了，后面hls.js 自己搞了个播放

**Comment by trry-github** [comment]
> > 
> 
> 没用了，后面hls.js 自己搞了个播放

自己搞的可以监听错误么，可以看下怎么实现的么
