### ISSUE TITLE
DASH码率问题

### ISSUE THREAD

**Issue by Kurokitu** [bytedance/xgplayer#728]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Chrome

**如何复现问题？ What did you do?**
播放DASH协议的视频时存在多个清晰度的源但无法自适应切换码率

**您期望的播放器正常行为是？ What did you expect to happen?**
目前所了解到的是shaka在默认情况下是支持码率自适应切换的

**实际播放器的表现是？ What actually happened?**
网络速度达标的情况下清晰度并没有切换至最高

另：在dash协议能否支持单mpd多码率源的情况下支持自适应网络码率切换以及手动切换码率的列表

**Comment by yiwen03** [comment]
目前dash模块不支持abr功能
