### ISSUE TITLE
播控插件清晰度位置错位

### ISSUE THREAD

**Issue by zyn926** [bytedance/xgplayer#737]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
v2.13.6
在vue中使用，清晰度插件的名字错位了
![image](https://user-images.githubusercontent.com/37466122/168205911-abfba1a6-51a0-4724-8f86-724babf8efde.png)

**Comment by yiwen03** [comment]
是v2.31.6的版本？可以看下是不是css被覆盖了。

**Comment by zyn926** [comment]
![image](https://user-images.githubusercontent.com/37466122/169928725-ab4f7b15-26e9-402c-a1f1-a40055f718e2.png)
没有发现有样式覆盖问题，我在<p class="name">标清</p>加了个 left:0 就正常了

**Comment by zyn926** [comment]
![image](https://user-images.githubusercontent.com/37466122/169929824-57a27740-4438-4d47-b94b-7e5eb3a2712d.png)
没有发现样式问题，我在 “<p class="name">标清</p>” 加了个 left:0 就正常了

**Comment by zyn926** [comment]
![image](https://user-images.githubusercontent.com/37466122/169929956-9e48f544-2597-4531-956a-1f348ffb892e.png)
没有发现样式覆盖问题，在 ```<p class="name">标清</p>```上加了个 left:0 正常了
