### ISSUE TITLE
mp4插件对于视频最后的缓冲请求出错，会出现没有最后一点没有缓存完，以及缓存接口错误

### ISSUE THREAD

**Issue by xhl592576605** [bytedance/xgplayer#739]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
  "xgplayer": "2.31.6",
  "xgplayer-mp4": "2.0.0"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
微软，chrome

**如何复现问题？ What did you do?**
- 代码
<img width="661" alt="image" src="https://user-images.githubusercontent.com/43491624/169001035-d019394d-b5b2-45e6-a9bd-d9b869c08bd2.png">

- 缓冲没有全部走完，视频播不下去，报错“请刷新试试”
视频地址：https://devppublic.ecoach.evideo.tech/resource_center/official/20220518/-vc-upload-1652839283113-2.mp4

![image](https://user-images.githubusercontent.com/43491624/169001689-9bbb0e32-0d32-472a-af74-05278542a538.png)
![image](https://user-images.githubusercontent.com/43491624/169001720-d818fe26-8e07-4c39-8900-ace8c94a09da.png)

- 最后的缓冲接口的切片大小请求出错，导致视频停止不了，进度条不走，黑屏
视频地址：https://devppublic.ecoach.evideo.tech/resource_center/official/20211221/%E9%87%8E%E8%9C%82%E9%A3%9E%E8%88%9E_%E9%A9%AC%E5%85%8B%E8%A5%BF%E5%A7%86-vc-upload-1640065496723-10.mp4

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/43491624/169002949-a3074df4-69d4-42f7-b058-a26f9845997f.png">
![image](https://user-images.githubusercontent.com/43491624/169003006-9f40a4ef-dc80-4b36-a603-83d26b2f28a0.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
希望能正常播放结束

**实际播放器的表现是？ What actually happened?**
并未正常的播放结束

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by cs529519717** [comment]
xgplayer-mp4 2.0.3了 还是有这个问题

**Comment by jiuyuetianjiuyuetian** [comment]
抱歉，确认在xgplayer-mp4 2.0.4修复了这个问题
