### ISSUE TITLE
Replacing the Buffer constructor with Buffer.from(...)

### ISSUE THREAD

**Issue by gabrielschulhof** [bytedance/xgplayer#74]
`new Buffer(...)` is deprecated and unsafe. It is being used in [a few places](https://github.com/bytedance/xgplayer/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22). Can it be replaced with `Buffer.from(...)`?

**Comment by zhangxin92** [comment]
It is not the Buffer of nodejs, but a [custom class](https://github.com/bytedance/xgplayer/blob/master/packages/xgplayer-mp4/src/fmp4/buffer.js).
