### ISSUE TITLE
浏览器内存持续增加，最后浏览器报错并崩溃

### ISSUE THREAD

**Issue by pineappleok** [bytedance/xgplayer#740]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?** 2.31.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**  Google Chrom 101.0.4951.64

**如何复现问题？ What did you do?**  使用component的is属性频繁切换播放flv文件和m3u8文件

**您期望的播放器正常行为是？ What did you expect to happen?**  正常播放且浏览器不崩溃

**实际播放器的表现是？ What actually happened?**  报错并浏览器崩溃
报错信息：Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at MSEController._needCleanupSourceBuffer
报错截图：
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/11623842/169250941-ee89fd4c-2c9a-4246-890d-d204723f11a2.png">

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
是如何切换flv和m3u8视频的呢？如果是flv和m3u8格式互相切换，建议销毁播放器实例后，在新建新的实例
