### ISSUE TITLE
断网重连问题

### ISSUE THREAD

**Issue by Subload** [bytedance/xgplayer#743]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^2.31.2",
"xgplayer-hls",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows chrome 101.0.4951.67

**如何复现问题？ What did you do?**
直播过程中，断掉本地网络10秒以上，没触发error和ended，会持续loading，重联网络后还是会持续loading，不会恢复播放，也没有尝试去自动获取视频流；
而断网10秒以内就可以自动获取续播

**您期望的播放器正常行为是？ What did you expect to happen?**
重联网络后可以继续复播，或者可以触发error或ended

**实际播放器的表现是？ What actually happened?**
断流10秒以上会持续loading，不触发error和ended，也没有复播

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
会议管家，线上会议

**Comment by yiwen03** [comment]
升级到这个版本试下https://unpkg.byted-static.com/xgplayer-hls/2.5.2/dist/index.min.js
我本地测试，如果直接断网，是可以触发error的
