### ISSUE TITLE
标记功能在 vue中无效   "version": "2.31.6"

### ISSUE THREAD

**Issue by smallyaohailu** [bytedance/xgplayer#745]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
  "version": "2.31.6"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

chrome 

**如何复现问题？ What did you do?**

http://edu.jeegit.com/#/dashboard/viewarticle 
![image](https://user-images.githubusercontent.com/718669/170449660-30d8d3df-b55f-460b-b122-15915d334416.png)

**您期望的播放器正常行为是？ What did you expect to happen?**

含有标记功能

![image](https://user-images.githubusercontent.com/718669/170449777-1cf2802d-564e-45fa-a1ec-c751e9372c12.png)

**实际播放器的表现是？ What actually happened?**

无标记功能 
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

jeegit 企业级快速开发平台  apache 2.0 开源

吉林省正崇科技有限责任公司

**Comment by yiwen03** [comment]
能发下，标记文字这块，是如何进行的配置吗？

**Comment by smallyaohailu** [comment]
用 的官方的demo 

 progressDot: [
              {
                time: 10, //展示标记的时间
                text: '标记文字', //鼠标hover在标记时展示的文字
                duration: 8, //标记段长度（以时长计算）
                style: {
                  //标记样式
                  background: 'blue',
                },
              },
              {
                time: 22,
                text: '标记文字',
              },
              {
                time: 56,
                duration: 8,
              },
              {
                time: 76,
              },
            ],

**Comment by smallyaohailu** [comment]
`<template>
  <PageWrapper>
    <template #headerContent>
      <a-menu mode="horizontal" theme="dark">
        <a-menu-item key="alipay7">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">学习路线</a>
        </a-menu-item>
        <a-menu-item key="mail">
          <template #icon>
            <mail-outlined />
          </template>
          入门基础
        </a-menu-item>
        <a-menu-item key="app">
          <template #icon>
            <appstore-outlined />
          </template>
          面试职场
        </a-menu-item>
        <a-sub-menu key="sub1">
          <template #icon>
            <setting-outlined />
          </template>
          <template #title>全栈工程师</template>
          <a-menu-item-group title="Item 1">
            <a-menu-item key="setting:1">Option 1</a-menu-item>
            <a-menu-item key="setting:2">Option 2</a-menu-item>
          </a-menu-item-group>
          <a-menu-item-group title="Item 2">
            <a-menu-item key="setting:3">Option 3</a-menu-item>
            <a-menu-item key="setting:4">Option 4</a-menu-item>
          </a-menu-item-group>
        </a-sub-menu>
        <a-menu-item key="alipay16">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">软考认证</a>
        </a-menu-item>
        <a-menu-item key="alipay17">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">考研读博</a>
        </a-menu-item>
        <a-menu-item key="alipay">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">商业源码</a>
        </a-menu-item>

        <a-menu-item key="alipay3">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">菜鸟文档</a>
        </a-menu-item>

        <a-menu-item key="alipay33">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">益智游戏</a>
        </a-menu-item>

        <a-menu-item key="alipay35">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">图书推荐</a>
        </a-menu-item>
        <a-menu-item key="alipay8">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">少儿编程</a>
        </a-menu-item>
        <a-menu-item key="alipay88">
          <template #icon>
            <setting-outlined />
          </template>
          <a href="https://antdv.com" target="_blank" rel="noopener noreferrer">商用资源</a>
        </a-menu-item>
      </a-menu>
      <a-row :gutter="16">
        <a-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24">
          <p class="jeegit_bread">
            <LayoutBreadcrumb />
            <span><h1>[第六版]2022年 JeeSite4 快速入门教程</h1></span>
          </p>
        </a-col>
      </a-row>

      <a-row
        :gutter="16"
        style="
          min-height: 500px;
          max-height: 500px;
          overflow-y: auto;
          background: #0f0f0f;
          display: flex;
        "
      >
        <a-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24">
          <a-row :gutter="16">
            <a-col :xs="8" :sm="8" :md="8" :lg="8" :xl="8">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px"
              >
                <a-skeleton class="">当前播放：06-数据库设计(下)</a-skeleton>
              </a-col>
            </a-col>

            <a-col :xs="12" :sm="12" :md="12" :lg="12" :xl="12">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px"
              >
                <a-skeleton class="">考后估分提前预约 知晓答案快人一步>></a-skeleton>
              </a-col>
            </a-col>
            <a-col :xs="4" :sm="4" :md="4" :lg="4" :xl="4">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px"
              >
                <a-skeleton class="">热门课程排行榜</a-skeleton>
              </a-col>
            </a-col>
          </a-row>
          <a-row :gutter="16">
            <a-col :xs="8" :sm="8" :md="8" :lg="8" :xl="8">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px; max-height: 450px; overflow-y: auto"
              >
                <a-collapse v-model:activeKey="activeKey">
                  <a-collapse-panel key="1" header="01-第一章 JeeSite4 环境搭建与快速入门">
                    <a-list size="small" bordered :data-source="data">
                      <template #renderItem="{ item }">
                        <a-list-item>
                          <a-col :xs="22" :sm="22" :md="22" :lg="21" :xl="21">
                            <span>
                              <a-button type="link" size="small"
                                ><template #icon>
                                  <Icon icon="ant-design:play-circle-outlined" /></template
                                >{{ item }}
                              </a-button>
                            </span>
                            <a-button
                              type="primary"
                              target="_blank"
                              href="https://www.baidu.com"
                              size="small"
                            >
                              <template #icon>
                                <Icon icon="ant-design:file-word-outlined" />
                              </template>
                            </a-button>
                          </a-col>
                          <a-col :xs="2" :sm="2" :md="2" :lg="3" :xl="3">
                            <span>05:16:47 </span>
                          </a-col>
                        </a-list-item>
                      </template>
                      <template #header>
                        <div>含课件+含源码 05:16:47</div>
                      </template>
                    </a-list>
                  </a-collapse-panel>
                  <a-collapse-panel key="2" header="02-第二章 JeeSite4 代码生成器">
                    <p>第二章 开发环境搭建</p>
                  </a-collapse-panel>
                  <a-collapse-panel key="3" header="03-第三章 JeeSite4 Entity 实体层">
                    <p>第一章 jeesite 快速入门教程</p>
                  </a-collapse-panel>
                  <a-collapse-panel key="4" header="04-第四章 JeeSite4 Dao 数据访问层">
                    <p>第一章 jeesite 快速入门教程</p>
                  </a-collapse-panel>
                  <a-collapse-panel
                    key="4"
                    header="05-第五章 JeeSite4 Service 业务逻辑层含课件"
                    disabled
                  >
                    <p>第一章 jeesite 快速入门教程</p>
                  </a-collapse-panel>
                </a-collapse>
              </a-col>
            </a-col>

            <a-col :xs="12" :sm="12" :md="12" :lg="12" :xl="12">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px"
              >
                <a-card>
                  <div id="mse" class="mse"></div>
                </a-card>
              </a-col>
            </a-col>
            <a-col :xs="4" :sm="4" :md="4" :lg="4" :xl="4">
              <a-col
                :xs="24"
                :sm="24"
                :md="24"
                :lg="24"
                :xl="24"
                class="jeegit-video-current-play"
                style="color: #fff; margin-top: 5px; max-height: 450px; overflow-y: auto"
                >ddddd</a-col
              >
            </a-col>
          </a-row>
        </a-col></a-row
      >
    </template>

    <template #default>
      <br />

      <Result title="帮助中心" subTitle="Help center">
        <template #icon> </template>
        <template #extra>
          <a-row :gutter="16">
            <a-col :xs="24" :sm="24" :md="4" :lg="4" :xl="4">
              <a-card title="公司" :bordered="false">
                <p>关于我们</p>
                <p>一键导航</p>
              </a-card>
            </a-col>
            <a-col :xs="24" :sm="24" :md="24" :lg="4" :xl="4">
              <a-card title="帮助与支持" :bordered="false">
                <p>知识中心</p>
                <p>联系我们</p>
                <p>高级支持</p>
                <p>赞助</p>
                <p>定制开发</p>
                <p>在线问答</p>
              </a-card>
            </a-col>
            <a-col :xs="24" :sm="24" :md="4" :lg="4" :xl="4">
              <a-card title="法律" :bordered="false">
                <p>条款和条件</p>
                <p>隐私政策</p>
              </a-card>
            </a-col>
            <a-col :xs="24" :sm="24" :md="4" :lg="4" :xl="4">
              <a-card title="资源" :bordered="false">
                <p>免费赠品</p>
                <p>溢价</p>
                <p>获得优惠券</p>
              </a-card>
            </a-col>
            <a-col :xs="24" :sm="24" :md="4" :lg="4" :xl="8">
              <a-card title="全球咨询热线" :bordered="false">
                <p> 0431-81727230 </p>
                <p class="jeegit-center">
                  <img src="https://kefu.jeegit.com/qrcode.jpg" style="width: 45%" />
                </p>
              </a-card>
            </a-col>
          </a-row>
        </template>
      </Result>
    </template>
  </PageWrapper>
</template>
<script lang="ts">
  import { MailOutlined, AppstoreOutlined, SettingOutlined } from '@ant-design/icons-vue';
  import { defineComponent, onMounted, ref } from 'vue';
  import {
    Menu,
    SubMenu,
    MenuItem,
    Result,
    Card,
    Row,
    Col,
    Collapse,
    Button,
  } from 'ant-design-vue';
  import { PageWrapper } from '/@/components/Page';
  import demoImg from '/@/assets/images/022.png';
  import demoImg2 from '/@/assets/images/033.png';
  import { Tabs, Tag, Image } from 'ant-design-vue';
  import Icon from '/@/components/Icon/index';
  import { BasicForm } from '/@/components/Form/index';
  import { actions, searchList, schemas } from './datasearch';
  import { List } from 'ant-design-vue';
  import { freeList, hotList, classifyList, projectList } from './data';
  import { LayoutBreadcrumb } from '/@/layouts/default/header/components';
  const data: string[] = [
    '01-Windows 环境搭建与快速入门.',
    '02-Windows 环境下安装Java SDK 1.8.',
    '03-Apache Maven 3.6+ 环境的安装与配置.',
    '04-MySql8.0的安装与配置.',
    '05-Maven 快速安装与启动JeeSite4.',
    '06-Eclipse 快速安装与启动JeeSite4.',
    '07-Idea 快速安装与启动JeeSite4',
  ];
  import Player from 'xgplayer/dist/simple_player';
  import progress from 'xgplayer/dist/controls/progress';
  import volume from 'xgplayer/dist/controls/volume';
  import pip from 'xgplayer/dist/controls/pip';
  import flex from 'xgplayer/dist/controls/flex';
  import playbackRate from 'xgplayer/dist/controls/playbackRate';
  import makeBullet from 'xgplayer/dist/controls/danmu';
  import screenShot from 'xgplayer/dist/controls/screenShot';
  import playNext from 'xgplayer/dist/controls/playNext';
  import rotate from 'xgplayer/dist/controls/rotate';
  import airplay from 'xgplayer/dist/controls/airplay';

  let player;
  export default defineComponent({
    components: {
      MailOutlined,
      AppstoreOutlined,
      SettingOutlined,
      Result,
      PageWrapper,
      Icon,
      AButton: Button,
      ACard: Card,
      ATabs: Tabs,
      ACollapse: Collapse,
      ACollapsePanel: Collapse.Panel,
      ATabPane: Tabs.TabPane,
      Tabs,
      TabPane: Tabs.TabPane,
      ARow: Row,
      ACol: Col,
      LayoutBreadcrumb,
      AMenu: Menu,
      AMenuItem: MenuItem,
      ASubMenu: SubMenu,
      AMenuItemGroup: Menu.ItemGroup,
      Icon,
      Tag,
      BasicForm,
      AImage: Image,
      [List.name]: List,
      [List.Item.name]: List.Item,
      AListItemMeta: List.Item.Meta,
    },
    setup() {
      const current = ref<string[]>(['mail']);
      // mounted
      onMounted(() => {
        player = new Player({
          el: document.querySelector('#mse'),
          //lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4
          //sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8
          url: 'https://static.yizao2025.com/company.mp4',
          controlPlugins: [
            volume,
            playNext,
            playbackRate,
            progress,
            pip,
            flex,
            makeBullet,
            screenShot,
            rotate,
            airplay,
          ],
          airplay: true,
          rotate: {
            //视频旋转按钮配置项
            innerRotate: true, //只旋转内部video
            clockwise: false, // 旋转方向是否为顺时针
          },
          pip: true,
          width: '100%',
          screenShot: {
            saveImg: true,
            quality: 1,
            type: 'image/png',
            format: '.png',
          },
          disableProgress: false,
          playNext: {
            urlList: [
              'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4',
              'https://static.yizao2025.com/company.mp4',
              'lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4',
            ],
          },
          lastPlayTime: 20, //视频起播时间（单位：秒）
          lastPlayTimeHideDelay: 5, //提示文字展示时长（单位：秒）
          playbackRate: [0.5, 0.75, 1, 1.5, 2], //传入倍速可选数组
          defaultPlaybackRate: 1.5,
          poster: 'https://kefu.jeegit.com/1230327099403280386.jpg',
          autoplay: true, // 自动播放
          cors: true,
          lang: 'zh-cn',
          danmu: {
            comments: [
              //弹幕数组
              {
                duration: 15000, //弹幕持续显示时间,毫秒(最低为5000毫秒)
                id: '1', //弹幕id，需唯一
                start: 3000, //弹幕出现时间，毫秒
                prior: true, //该条弹幕优先显示，默认false
                color: true, //该条弹幕为彩色弹幕，默认false
                txt: '长弹幕长弹幕长弹幕长弹幕长弹幕长弹幕长弹幕长弹幕长弹幕长弹幕', //弹幕文字内容
                style: {
                  //弹幕自定义样式
                  color: '#ff9500',
                  fontSize: '20px',
                  border: 'solid 1px #ff9500',
                  borderRadius: '50px',
                  padding: '5px 11px',
                  backgroundColor: 'rgba(255, 255, 255, 0.1)',
                },
                mode: 'top', //显示模式，top顶部居中，bottom底部居中，scroll滚动，默认为scroll
                // el: DOM //直接传入一个自定义的DOM元素作为弹幕，使用该项的话会忽略所提供的txt
                // eventListeners: [{ //支持自定义DOM设置DOM监听事件
                //   event: 'click',
                //   listener: function (e) {
                //     console.log('click')
                //   },
                //   useCapture: false,
                // }]
              },
            ],
            area: {
              //弹幕显示区域
              start: 0, //区域顶部到播放器顶部所占播放器高度的比例
              end: 1, //区域底部到播放器顶部所占播放器高度的比例
            },
            closeDefaultBtn: false, //开启此项后不使用默认提供的弹幕开关，默认使用西瓜播放器提供的开关
            defaultOff: true, //开启此项后弹幕不会初始化，默认初始化弹幕
            keyShortcut: 'on',
            keyShortcutStep: {
              //设置调整步长
              currentTime: 15, //播放进度调整步长，默认10秒
              volume: 0.2, //音量调整步长，默认0.1
            },
            errorTips: `请<span>刷新</span>试试，或者联系客服叭姐QQ:3211247533 反馈bug！`,
            progressDot: [
              {
                time: 10, //展示标记的时间
                text: '标记文字', //鼠标hover在标记时展示的文字
                duration: 8, //标记段长度（以时长计算）
                style: {
                  //标记样式
                  background: 'blue',
                },
              },
              {
                time: 22,
                text: '标记文字',
              },
              {
                time: 56,
                duration: 8,
              },
              {
                time: 76,
              },
            ],
          },
        });
        console.log('Component is mounted!');
        player.on('rotate', function (deg) {
          console.log(deg); // 旋转时会触发rotate事件，角度有四个值90，180，270，0
        });
        player.addProgressDot(3, 'jeegit 企业级低代码平台', 2000, 'color:red'); //添加标记（参数含义同上，后3项可选传入）
      });
      return {
        activeKey: ref('1'),
        prefixCls: 'list-search',
        current,
        schemas,
        list: projectList,
        classifyList,
        demoImg,
        demoImg2,
        freeList,
        hotList,
        data,
        listSearch: searchList,
        actions,
        player,
      };
    },
  });
</script>

<style lang="less" scoped>
  .jeegit-center {
    display: flex;
    justify-content: center;
  }

  .jeegit_bread {
    display: flex;
    align-items: left;
    justify-content: left;
    cursor: pointer;
    position: relative;
    line-height: 50px;
    height: 50px;
  }

  .jeegit-h1 {
    font-weight: bolder;
  }

  .result-success {
    height: 600px;
    padding: 48px 32px;
    background-color: @component-background;

    &__content {
      padding: 24px 40px;
      background-color: @background-color-light;
      color: #02063d;
    }

    .ant-result-subtitle {
      width: 30%;
    }

    #lowcode ul {
      list-style: none;
      margin: 0px;
    }

    #lowcode ul li {
      float: left;
    }
  }

  .jeegit-left-category {
    position: relative;
    width: 100%;

    &:hover {
      .classify-list {
        display: block;
      }
    }

    h2 {
      background-color: #001529;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      position: relative;
      color: white;
      line-height: 36px;
    }

    .classify-list {
      margin-top: 2px;
      background-color: #001529;
      position: relative;
      z-index: 999;
      width: 100%;
      color: white;
      height: calc(100% - 32px);

      .item {
        position: relative;

        &:nth-last-child(1) {
          .item-list {
            top: auto;
            bottom: 0;
          }
        }

        &:nth-last-child(2) {
          .item-list {
            top: auto;
            bottom: 0;
          }
        }

        &:nth-last-child(3) {
          .item-list {
            top: auto;
            bottom: 0;
          }
        }

        &:nth-last-child(4) {
          .item-list {
            top: auto;
            bottom: 0;
          }
        }

        &:nth-last-child(5) {
          .item-list {
            top: auto;
            bottom: 0;
          }
        }

        &:hover {
          .item-title {
            background-color: #0960bd;
            color: white;
          }

          .item-list {
            display: block;
          }
        }

        .item-title {
          padding: 11px 20px 6px;
          font-size: 14px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          line-height: 1;
          cursor: pointer;

          & > span {
            width: 100%;
            border-bottom: 1px dashed #e5e5e5;
            padding-bottom: 8px;
          }
        }

        .item-list {
          top: 0;
          position: absolute;
          left: 100%;
          width: 500px;
          background-color: rgba(0, 0, 0, 0.5);
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          display: none;

          .list-main {
            flex-wrap: wrap;
            display: flex;
            padding: 10px;

            .items {
              padding: 10px 15px;
              height: 35px;
              line-height: 15px;
              cursor: pointer;
              width: 50%;

              &:hover {
                color: white;
                background-color: #0960bd;
              }
            }
          }
        }
      }
    }
  }

  .list-search {
    &__header {
      &-form {
        margin-bottom: -16px;
      }
    }

    &__container {
      padding: 12px;
      background-color: @component-background;
    }

    &__title {
      margin-bottom: 12px;
      font-size: 18px;
    }

    &__content {
      color: @text-color-secondary;
    }

    &__action {
      margin-top: 10px;

      &-item {
        display: inline-block;
        padding: 0 16px;
        color: @text-color-secondary;

        &:nth-child(1) {
          padding-left: 0;
        }

        &:nth-child(1),
        &:nth-child(2) {
          border-right: 1px solid @border-color-base;
        }
      }

      &-icon {
        margin-right: 3px;
      }
    }

    &__time {
      position: absolute;
      right: 20px;
      color: rgb(0 0 0 / 45%);
    }
  }

  .ant-list-sm .ant-list-item {
    padding: 8px 16px 8px 0px;
  }
</style>
`

**Comment by smallyaohailu** [comment]
![image](https://user-images.githubusercontent.com/718669/170472599-f490d598-a734-46b3-9ba9-73db6d95398e.png)

调试报错

**Comment by yiwen03** [comment]
测试了一下，使用xgplayr-vue，配置progressDot，可以生效。
<img width="620" alt="image" src="https://user-images.githubusercontent.com/25165143/171994183-d42be162-6e98-4834-bcbf-89b7740002f9.png">
