### ISSUE TITLE
xgplayer-hls.js 直播断流后同时发送大量m3u8请求（100+），销毁不起作用只是变量变为null，依然会发送请求，dom也没有销毁

### ISSUE THREAD

**Issue by my-first-gitHub-account123** [bytedance/xgplayer#748]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^2.31.1",
   "xgplayer-hls.js": "^2.4.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
w11，edge浏览器

**如何复现问题？ What did you do?**
xgplayer-hls.js 直播断流后，即会出现发送大量m3u8请求。这时销毁播放器，会出现变量变为null，依然会发送请求，dom也没有销毁

**您期望的播放器正常行为是？ What did you expect to happen?**
直播断流不会同时发送大量请求（100+）

**实际播放器的表现是？ What actually happened?**
loading状态未销毁，同时还会有请求

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
直播

**Comment by yiwen03** [comment]
xgplayer-hls.js用2.6.1的版本试下，或者能不能提供一个在线示例，或者对应代码也可以。我试了下，调用destory方法，可以销毁
