### ISSUE TITLE
IOS下部分浏览器无法正常播放m3u8视频

### ISSUE THREAD

**Issue by joney888999** [bytedance/xgplayer#750]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer 2.31.6
xgplayer-hls.js2.2.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
IOS 14.7
UC浏览器  QQ浏览器

**如何复现问题？ What did you do?**
使用UC浏览器和QQ浏览器打开播放器页面，播放m3u8的hls视频，无法正常播放，
Safari浏览器和百度浏览器能够正常播放

**您期望的播放器正常行为是？ What did you expect to happen?**
能够正常播放视频

**实际播放器的表现是？ What actually happened?**
播放器一直在转圈圈

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
无

**Comment by joney888999** [comment]
官方页面的示例在ios的UC浏览器和qq浏览器也是无法播放（切换到hls）下，https://v2.h5player.bytedance.com/examples/

**Comment by yiwen03** [comment]
我看了，在uc下，有一些dom的方法不支持，报错了。我看下

**Comment by yiwen03** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25165143/176110661-a8a630d3-9fa0-4398-8b24-7633ebc522c2.png">

**Comment by yiwen03** [comment]
在ios系统下，直接使用xgplayer播放就可以，设置url为m3u8地址
