### ISSUE TITLE
切换清晰度

### ISSUE THREAD

**Issue by aGaoC** [bytedance/xgplayer#752]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

2.31.6
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓 安卓app内嵌webveiw

**如何复现问题？ What did you do?**
切换清晰度，

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**
切换清晰度之后， 出现未知图片 暂定

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
能提供一下播放器相关的代码吗？

**Comment by yiwen03** [comment]
安卓webview会显示一个灰色播放按钮，这个由webview来控制的，https://stackoverflow.com/questions/18271991/html5-video-remove-overlay-play-icon可以看下这个链接

**Comment by aGaoC** [comment]
https://v2.h5player.bytedance.com/examples/ 

demo也会出现上述问题， 切换清晰度之后，重置player.on('definitionChange',function(i){
          player.config.poster = 'xxxxxxx'
        }) 也没有，这个是需要安卓去处理嘛？

**Comment by yiwen03** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/25165143/176170348-a50db75b-4234-49f5-a720-baba722eea4a.png">
如果是这个灰色图标的话，就需要app来处理

**Comment by aGaoC** [comment]
感谢大佬～
