### ISSUE TITLE
播放失败，提示

### ISSUE THREAD

**Issue by chenhengxin** [bytedance/xgplayer#753]
**您使用的西瓜播放器版本是多少？ 2.31.1   "xgplayer-hls.js": "~2.5.2"**

**您使用的操作系统和浏览器分别是？ 华为p20  鸿蒙2.0.0 手机自带浏览器**

**如何复现问题？ 点击播放后提示失败**

**您期望的播放器正常行为是？ 正常播放**

**实际播放器的表现是？ 点击播放后提示失败**

**问题手机可以播放示例提供的m3u8格式的视频，但是用我们自己的m3u8播放不了，换其他播放插件可以播放 有两台播放不了的都是鸿蒙系统的 怀疑是不是可以鸿蒙系统有关系**

**Comment by yiwen03** [comment]
看下http请求，看ts数据有没有成功请求。如果ts请求成功了，仍然不能不能播放，有可能和数据格式有关系。监听下error事件，看错误提示是什么？

**Comment by chenhengxin** [comment]
> 看下http请求，看ts数据有没有成功请求。如果ts请求成功了，仍然不能不能播放，有可能和数据格式有关系。监听下error事件，看错误提示是什么？
错误提示 ： 不支持的音频/视频格式   。 没有请求ts

**Comment by chenhengxin** [comment]
找到原因了
`注意

移动端原生video支持直接播放hls，所以xgplayer-hls.js在移动端环境下关闭了hls.js相关解析功能；如果需要在移动端环境下打开hls.js解析功能，可使用配置项 useHls: true`
