### ISSUE TITLE
在播放器加载直播视频的时候会出现西瓜视频的logo字样

### ISSUE THREAD

**Issue by czl0325** [bytedance/xgplayer#754]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer: 1.10.14
xgplayer-hls: 2.6.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
macOS, chrome

**如何复现问题？ What did you do?**
在播放器加载直播视频的时候会出现西瓜视频的logo字样

**您期望的播放器正常行为是？ What did you expect to happen?**
如何隐藏西瓜视频logo

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
能提供一个截图，或者你的播放器配置吗？播放器本身没有添加logo的

**Comment by czl0325** [comment]
> 能提供一个截图，或者你的播放器配置吗？播放器本身没有添加logo的

之前用xgplayer 1.10.14版本会有这个问题，后面升级到2.31.2就没出现了
