### ISSUE TITLE
设置音频播放器频谱，柱状频谱的背景颜色无效

### ISSUE THREAD

**Issue by stefansky** [bytedance/xgplayer#755]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10, google100.0.4896.127

**如何复现问题？ What did you do?**
设置音频播放器频谱，柱状频谱的背景颜色无效，查看了源码，发现bgColor没有生效
 let an = player.analyze(document.querySelector('canvas'));
      an.style.bgColor= "#0037ff"; //bgColor设置无效
      an.style.color="#000000";        
      an.mode = "bars";
      an.size = 512;
      an.status = "on"
![test-150901](https://user-images.githubusercontent.com/8034909/176843032-25f79a9a-d0f7-4c6f-a531-6c51b403f2af.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
能够修改柱状频谱的柱状背景颜色

**实际播放器的表现是？ What actually happened?**
无法修改柱状频谱的柱状背景颜色

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
发布了2.3.3版本，可以试下
