### ISSUE TITLE
closeInactive: true（使播放器控制栏常驻不隐藏），不起作用

### ISSUE THREAD

**Issue by morning-evening** [bytedance/xgplayer#761]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window，chrome

**如何复现问题？ What did you do?**
 this.player = new Player({
      id: 'mse',
      url: '//sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4',
      height: 196,
      width: 343,
      controls: true,
      closeInactive: true
    });

**您期望的播放器正常行为是？ What did you expect to happen?**
播放器控制栏常驻不隐藏

**实际播放器的表现是？ What actually happened?**
播放器控制栏不常驻

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
我试了下，没有问题，可以常驻

**Comment by morning-evening** [comment]
> 我试了下，没有问题，可以常驻

有没有什么配置能让控制栏在初始化的时候就常驻显示？现在只有在点击播放后才常驻

**Comment by morning-evening** [comment]
有没有什么配置能让控制栏在初始化的时候就常驻显示？现在只有在点击播放后才常驻
















在 2022-08-10 16:13:51，"yiwen" ***@***.***> 写道：

我试了下，没有问题，可以常驻
