### ISSUE TITLE
miniplay如何添加视频右上角的关闭按钮

### ISSUE THREAD

**Issue by babydada** [bytedance/xgplayer#763]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
微信

**如何复现问题？ What did you do?**
player.getMiniplayer()后显示的迷你播放器

**您期望的播放器正常行为是？ What did you expect to happen?**
能够自己添加一个关闭按钮

**实际播放器的表现是？ What actually happened?**
暂无此功能

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
目前没有提供添加关闭按钮的能力，如果需要，可以自己写一个对应的miniplayer的插件

**Comment by yiwen03** [comment]
player.on('miniplayerBtnClick', function(){
        let root = player.root
        let dragDiv = root.querySelector('.xgplayer-miniplayer-lay')
        // 原来的click事件失效
        dragDiv.style.pointerEvents = 'none'
        
        let isMini = root.classList.contains('xgplayer-miniplayer-active')
        if (isMini) {
          let div = document.createElement('div')
          div.style.width = '50px'
          div.style.height = '50px'
          div.style.position = 'absolute'
          div.style.right = 0
          div.style.top = 0
          div.style.backgroundColor = 'red'
          root.appendChild(div)
          div.onclick = function() {
            player.exitMiniplayer()
            root.removeChild(div)
          }
        }
      })
可以按照这个来试下，最好还是自己写一个miniplayer的插件，这样好维护
