### ISSUE TITLE
safari浏览器，播放m3u8格式视频，截图是空白的

### ISSUE THREAD

**Issue by chenhengxin** [bytedance/xgplayer#767]
**您使用的西瓜播放器版本是多少？ 2.31.6**

**您使用的操作系统和浏览器分别是？ mac。safari**

**如何复现问题？播放m3u8格式视频 然后截图**

**您期望的播放器正常行为是？ 正常显示截图**

**实际播放器的表现是？ 截图是透明空白的**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
safari浏览器下，如果通过mse'播放视频，通过canvas无法截图

**Comment by SuperChrisliu** [comment]
有没有大兄弟有解决办法

**Comment by chenhengxin** [comment]
> 有没有大兄弟有解决办法

safari浏览器隐藏了截图功能

**Comment by SuperChrisliu** [comment]
> > 有没有大兄弟有解决办法
> 
> safari浏览器隐藏了截图功能

兄弟你最后怎么解决的，实在不行只能用ffmpeg了
