### ISSUE TITLE
[Feature Request] 希望能获得类似 flv.js 中的 statistics event，提供播放网络质量的检测

### ISSUE THREAD

**Issue by aweffr** [bytedance/xgplayer#768]
** 背景 **
目前在做的是播放直播流的业务, 后端提供 flv 和 hls 两种流格式。
希望能在观众端检测用户的播放网络状况，针对卡顿等异常。辨别是否是网络的问题，给予用户友好的提示。

**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.6

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window，chrome

**如何复现问题？ What did you do?**
[无]

**您期望的播放器正常行为是？ What did you expect to happen?**
播放时能从播放器对象监听events, 当中包含 **statistics 信息**， 如：**speed**， **currentSegmentIndex**, **totalSegmentCount**。

参考flv.js的定义:

```typescript
interface FlvPlayerReportStatisticsInfo {
        url: string;
        hasRedirect: boolean;
        redirectedURL?: string;
        speed: number; // KB/s
        loaderType: string;
        currentSegmentIndex: number;
        totalSegmentCount: number;
    }

interface FlvPlayerStatisticsInfo extends Partial<FlvPlayerReportStatisticsInfo> {
        playerType: 'FlvPlayer';
        decodedFrames?: number;
        droppedFrames?: number;
}
```

更好的话希望能有接口来实现类似youtube的播放监控的面板, 如图所示:
![image](https://user-images.githubusercontent.com/17469534/180693072-08e2760e-b850-4797-909e-014a6ec724e4.png)

**实际播放器的表现是？ What actually happened?**
从目前的文档和插件实例中，未能找到相关统计信息的获取方式。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
[无]

**Comment by yiwen03** [comment]
监听一下statistics_info事件。
player.on('statistics_info', function(data){

})
