### ISSUE TITLE
[BUG] v1.1.0 playbackRate undefined

### ISSUE THREAD

**Issue by FrankFang** [bytedance/xgplayer#77]
http://jsbin.com/noqakog/3/edit?html,output

Click 1x, then you get 'undefined'

点击 1x 按钮，会看到 undefined

**Comment by zhangxin92** [comment]
Duplicate of [#76](https://github.com/bytedance/xgplayer/issues/76)

See: [#76](https://github.com/bytedance/xgplayer/issues/76#issuecomment-418335891)

**Comment by FrankFang** [comment]
是的，你们修复了这个问题，但是你们的 v1.1.0 和 v1.1.0-beta 并没有发布这个修复。
目前 v1.1.0 和 v1.1.0-beta 都存在这个 BUG。
请问什么时候发布这次修复？
我目前只能自己打包 xgplayer/dist/index.js

**Comment by zhangxin92** [comment]
You can see the new version no later than next week.

**Comment by FrankFang** [comment]
OK, thanks.
