### ISSUE TITLE
xgplayer支持h265编码格式的视频吗？

### ISSUE THREAD

**Issue by EastLee** [bytedance/xgplayer#770]

**Comment by yiwen03** [comment]
不支持H265编码的视频，编码主要取决于浏览器是否支持

**Comment by pedoc** [comment]
> 不支持H265编码的视频，编码主要取决于浏览器是否支持

@yiwen03 如果我自己编译chrome并加入h265编码支持(也就是video元素本身就支持h265)后,xgplayer也就能支持h265解码了?请问是这个意思吗?

**Comment by xhwgood** [comment]
> > 不支持H265编码的视频，编码主要取决于浏览器是否支持
> 
> [@yiwen03](https://github.com/yiwen03) 如果我自己编译chrome并加入h265编码支持(也就是video元素本身就支持h265)后,xgplayer也就能支持h265解码了?请问是这个意思吗?

是的
