### ISSUE TITLE
点击播放后， 大概三秒后会自动带上xgplayer-inactive  类名， 请问这个如何关闭

### ISSUE THREAD

**Issue by H-Sven** [bytedance/xgplayer#772]
开始播放后， 大概秒后自动添加了xgplayer-inactive
然后单击视频区域可以切换xgplayer-inactive， 但是大概3秒后又自动添加上去了。 请问这个是被什么给控制了

**Comment by yiwen03** [comment]
这个是视频容器在onBlur的时候会添加这个class，如果想关闭，可以配置closeInactive: true,不过这样，control会一直显示

**Comment by H-Sven** [comment]
> 这个是视频容器在onBlur的时候会添加这个class，如果想关闭，可以配置closeInactive: true,不过这样，control会一直显示

我观察到每次单击视频的时候都会切换这个class， 我想实现类似的功能， 每次单击视频添加一个自定义class，目前通过监听touchstart能实现，但是在双击视频时也会触发， 所以想请问一下你们这个切换xgplayer-inactive的方法在哪个文件下，我想参考一下，解决双击的问题

**Comment by yiwen03** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/25165143/182318109-34afdd19-bb47-4c70-95e8-2ece7e5abced.png">
在player.js里，你可以搜下这个class名称
