### ISSUE TITLE
Mp4Player出现 “请刷新试试”之后无法切换视频

### ISSUE THREAD

**Issue by maclessmjb** [bytedance/xgplayer#775]
**您使用的西瓜播放器版本是多少？ Mp4Player版本2.0.0；Xgplayer版本2.31.6*

**您使用的操作系统和浏览器分别是？ Edge，360极速，google*

**如何复现问题？播放一个不完整或者错误格式的mp4视频的时候出现“请刷新试试”，然后无法切换视频**

**您期望的播放器正常行为是？ 出现错误提示之后能继续切换正常的视频**

**实际播放器的表现是？ 无法切换视频**

**Comment by yiwen03** [comment]
请问下是报什么错误呢？应该是播放器内部报错了，阻碍了后续代码的执行。或者把报错的视频发给我们看下
