### ISSUE TITLE
Iphone8上QQ内置浏览器视频播放器操作元素渲染两个

### ISSUE THREAD

**Issue by stefansky** [bytedance/xgplayer#776]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
  "xgplayer": "^2.31.6",
    "xgplayer-hls.js": "^2.6.1"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
  Iphone 8Plus  , QQ版本8.5

**如何复现问题？ What did you do?**
在IPhone8Plus的qq8.5版本上打开带视频播放器的网页

**您期望的播放器正常行为是？ What did you expect to happen?**
播放器样式正常

**实际播放器的表现是？ What actually happened?**
播放器进度条圆点复现两个，底部控制蒙版时间都出现了两份

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
![qq](https://user-images.githubusercontent.com/8034909/182996940-d90d6752-4cc4-4c21-9d42-ac5c08639e3e.png)

**Comment by yiwen03** [comment]
看下dom节点，是不是有两个xgplayer-time节点
