### ISSUE TITLE
能添加自定义播放插件吗，比如我想添加一个播放按钮，用于循环播放某一片段视频

### ISSUE THREAD

**Issue by tss0823** [bytedance/xgplayer#779]
能添加自定义播放插件吗，比如我想添加一个播放按钮，用于循环播放某一片段视频，我看了目前这些播放插件都是定义好的，我能添加一个自己的吗？该怎么做，多谢了。

**Comment by yiwen03** [comment]
https://v2.h5player.bytedance.com/plugins/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6可以看下这个文档

**Comment by tss0823** [comment]
好的，多谢啦，我再仔细看看
