### ISSUE TITLE
[feature request] Support keyboard shortcuts

### ISSUE THREAD

**Issue by FrankFang** [bytedance/xgplayer#78]
Hey, our team are using xgplayer now, and we believe xgplayer is awesome.
Do you have any play to add keyboard shortcuts, like
1. → to forward by 10 seconds
2. ← to backward by 10 seconds
3. space to pause or resume
4. ↑ to increase volume
5. ↓ to decrease volume

**Comment by FrankFang** [comment]
By the way, our site: https://xiedaimala.com/tasks/9db07b35-0322-4e5f-ab50-77793c76829f/video_tutorials/7ddd568d-fbaf-4595-a6bb-c46cb480dee8

**Comment by zhangxin92** [comment]
Supported by [d62ba8](https://github.com/bytedance/xgplayer/commit/d62ba86742f73ac62306e8a9248c7d2ff9027034). You can use it in v1.1.1. Thanks for your suggestion.
