### ISSUE TITLE
video标签添加的tabindex属性导致在swiper中使用时video获得焦点后swiper无法切换

### ISSUE THREAD

**Issue by F-OlO-Y** [bytedance/xgplayer#780]
希望tabindex属性可以根据配置选择性添加

**Comment by yiwen03** [comment]
https://v2.h5player.bytedance.com/config/#%E5%85%B6%E5%AE%83%E4%BA%A4%E4%BA%92%E9%85%8D%E7%BD%AE
试试关闭播放时触发video focous

**Comment by Sc-6-23** [comment]
单纯的关闭播放时触发video focus不能完全解决问题  希望能手动控制是否添加tabindex属性
