### ISSUE TITLE
引入多个xgplayer视频组件导致浏览器奔溃问题

### ISSUE THREAD

**Issue by EnL14U** [bytedance/xgplayer#784]
播放器销毁时占用浏览器内存不释放，在重新加载其他视频时（多个播放器），浏览器就崩了（cpu   100%）

**Comment by gemxx** [comment]
> 销毁时占用浏览器内存不释放，在重新加载其他视频时（多个播放器），浏览器就

提供一下可复现的例子吧，只有描述很难对齐场景
