### ISSUE TITLE
mode为“top”的弹幕无法消失

### ISSUE THREAD

**Issue by shu-da-wang** [bytedance/xgplayer#796]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.32.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 11,chrome105/安卓手机,chrome

**如何复现问题？ What did you do?**

添加mode为“top”的弹幕
**您期望的播放器正常行为是？ What did you expect to happen?**

mode为“top”的弹幕在超过时间之后消失
**实际播放器的表现是？ What actually happened?**
mode为“top”的弹幕一直显示没消失

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
创思远

**Comment by guest6379** [comment]
复议，mode是`bottom`和`top`的弹幕都无法在duration到期后自动消失
版本2.32.0

**Comment by guest6379** [comment]
复议，**版本2.32.0** mode是`bottom`和`top`的弹幕都无法在duration到期后自动消失


但2.31.7版本可以自动消失

**Comment by gemxx** [comment]
@shu-da-wang  @guest6379 2.32.1已经修复了此问题

**Comment by startjava** [comment]
> @shu-da-wang @guest6379 2.32.1已经修复了此问题

https://github.com/bytedance/xgplayer/issues/1373

@gemxx
