### ISSUE TITLE
切换清晰度后，视频会重新播放

### ISSUE THREAD

**Issue by leadingGo** [bytedance/xgplayer#798]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^2.32.0"
"xgplayer-hls.js": "^2.6.3"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
华为手机mate40pro

**如何复现问题？ What did you do?**
微信里通过链接打开页面

**您期望的播放器正常行为是？ What did you expect to happen?**
切换完清晰度后继续播放，不要重新播放

**实际播放器的表现是？ What actually happened?**
播放视频，播放一段时间后切换清晰度后会重新播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
有可能是currentTime的设置没有生效，在一些移动浏览器上，播放之后，立即设置currentTime不生效
