### ISSUE TITLE
Dev按步骤执行后，页面Not Found。

### ISSUE THREAD

**Issue by jingdianii** [bytedance/xgplayer#801]
执行
$ git clone --recurse-submodules -j8 git@github.com:bytedance/xgplayer.git # 或者：git clone git@github.com:bytedance/xgplayer.git
$ cd xgplayer
$ npm install
$ npm run dev

然后访问http://localhost:9090/examples/index.html

页面Not Found，请问examples文件夹以及里面的文件是需要自己创建吗。

**Comment by villers3** [comment]
这垃圾都没人维护，我去yt-dlp 问，几个小时就有人回答了。
还是去用video.js

**Comment by gemxx** [comment]
该问题已经修复，按文档步骤重新操作即可，感谢反馈
