### ISSUE TITLE
m3u8 地址延迟太高，几分钟都无法播放出来，同一地址 vlc 可以比较快播放成功。

### ISSUE THREAD

**Issue by Feafortecsy** [bytedance/xgplayer#802]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

```json
"xgplayer": "^2.31.4",
"xgplayer-flv.js": "^2.3.0",
"xgplayer-hls.js": "^2.6.1"
```

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
- mac 12.5 (21G72)
- chrome 104.0.5112.79

**如何复现问题？ What did you do?**
[官网示例](http://v2.h5player.bytedance.com/examples/)，配置 => 直播 - hls - hls.js，官方示例就无法播放。

业务url存在有效期，就不在这里给出了 。

**您期望的播放器正常行为是？ What did you expect to happen?**

m3u8 地址延迟在4s内。

**实际播放器的表现是？ What actually happened?**

m3u8 地址延迟在 5 min 以上 甚至无法播放成功，长时间loading 之后变回 暂停状态 (默认不播放，URL过期了)。

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

![image](https://user-images.githubusercontent.com/31724313/192499657-789de097-4c0e-4aa5-b7f0-a84506486758.png)

**Comment by yiwen03** [comment]
可以看下m3u8和第一个ts的http请求耗时，看是不是http请求被阻塞了
