### ISSUE TITLE
自研外挂字幕样式无法生效

### ISSUE THREAD

**Issue by guest6379** [bytedance/xgplayer#805]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.32, 2.31.6 等等

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome

**如何复现问题？ What did you do?**
```<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
    <meta name="referrer" content="no-referrer">
    <title>xgplayer</title>
    <style type="text/css">
      html, body {width:100%;height:100%;margin:auto;overflow: hidden;}
    </style>
  </head>
  <body>
    <div id="mse"></div>
    <script src="//unpkg.byted-static.com/xgplayer/2.31.6/browser/index.js" charset="utf-8"></script>
      <script>
      let player = new Player({
		"id": "mse",
		"url": "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4",
		"playsinline": true,
		"whitelist": [
				""
		],
		"textTrack": [
				{
						"src": "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-1.vtt",
						"label": "字幕1",
						"default": true
				},
				{
						"src": "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-2.vtt",
						"label": "字幕2",
						"default": false
				}
		],
		"textTrackStyle": {
				"font-size": "36px",
				"color": "#ff0000",
				"background-color": "transparent"
		}
      });
      
          </script>
  </body>
</html>
```

**您期望的播放器正常行为是？ What did you expect to happen?**
样式如配置

**实际播放器的表现是？ What actually happened?**
外挂字幕样式无法生效

**但将textTrack替换成nativeTextTrack以后样式正常**
```
"nativeTextTrack": [
				{
						"src": "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-1.vtt",
						"label": "字幕1",
						"default": true
				},
				{
						"src": "//lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-2.vtt",
						"label": "字幕2",
						"default": false
				}
		],
		"textTrackStyle": {
				"font-size": "36px",
				"color": "#ff0000",
				"background-color": "transparent"
		}
```

**Comment by yiwen03** [comment]
textTrack的样式配置文档上写的不对，我们修改下文档

**Comment by kazegh** [comment]
> 最新版3.0.9（测试3.0.1以上）无法加载字幕

<html>
  <head>
    <meta charset="utf-8">
    <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
    <meta name="referrer" content="no-referrer">
    <title>xgplayer</title>
    <style type="text/css">
      html, body {width:100%;height:100%;margin:auto;overflow: hidden;}
    </style>
  </head>
  <body>
    <div id="mse"></div>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/xgplayer/dist/index.min.js" charset="utf-8"></script>
      <script>
      let player = new Player({
		"id": "mse",
		"url": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4",
		"playsinline": true,
		"whitelist": [
				""
		],
		"textTrack": [
				{
						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-1.vtt",
						"label": "字幕1",
						"default": true
				},
				{
						"src": "https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/textTrack-2.vtt",
						"label": "字幕2",
						"default": false
				}
		],
		"textTrackStyle": {
				"font-size": "36px",
				"color": "#ff0000",
				"background-color": "transparent"
		}
      });
      
          </script>
  </body>
</html>
