### ISSUE TITLE
hls切换无缝分辨率问题

### ISSUE THREAD

**Issue by LeoonLiang** [bytedance/xgplayer#809]
求问！
用的是hls.js版。
一定要在第一个m3u8就写好所有分辨率的m3u8，才可以无缝吗。
如下面，不定义下面这个多分辨率的m3u8。后续手动切换url如何无缝
<img width="878" alt="image" src="https://user-images.githubusercontent.com/34993268/195535274-15212997-d974-49bd-a95d-c788be0ef957.png">

**Comment by yiwen03** [comment]
hls.js是支持的标准hls，图上这种写法是标准hls多码流的方式，如果不支持这个标准，应该是不支持的，这个要看hls.js的能力。
