### ISSUE TITLE
In the mobile version of Google browser, play MP4 format, the player has no voice.

### ISSUE THREAD

**Issue by he2014** [bytedance/xgplayer#81]
In the mobile version of Google browser, play MP4 format, the player has no voice.

**Comment by zhangxin92** [comment]
If you config 'autoplay: true', the player will be muted for ensuring autoplay success.

**Comment by savokiss** [comment]
@zhangxin92 Is there a legacy reason for this behavior？

**Comment by savokiss** [comment]
#44 Found it here, never mind~
