### ISSUE TITLE
用同一个手机拍摄的mp4格式视频，使用xgplayer-mp4，几十兆的可以正常播放，700多兆的无法正常播放，控制台会报错。使用xgplayer可以正常播放

### ISSUE THREAD

**Issue by tmxjiayou** [bytedance/xgplayer#810]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer-mp4@2.0.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Windows 10, 浏览器版本：chrome 106.0.5249.103（正式版本） （64 位）

**如何复现问题？ What did you do?**
使用xgplayer-mp4@2.0.3，播放大几百兆的mp4的视频，分辨率1280P

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
以下是在官网测试的表现
![image](https://user-images.githubusercontent.com/31396117/195583109-8b16d89c-f0b6-4d1d-bf0c-aa2e1e2bae82.png)
视频信息如下：
![image](https://user-images.githubusercontent.com/31396117/195585769-7fd1854d-0563-4133-805d-16d97da0417b.png)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by tmxjiayou** [comment]
![image](https://user-images.githubusercontent.com/31396117/195586158-27525334-35f1-45ec-85a9-2c4f27d85eb7.png)

**Comment by yiwen03** [comment]
能提供一个报错的mp4文件吗？

**Comment by yiwen03** [comment]
我测试了一下你提供的mp4，可以播放呢
