### ISSUE TITLE
rotateFullscreen: true 属性 是可以实现样式横屏显示  但是在页面中他并不是全屏的 页面还会保留导航和底部

### ISSUE THREAD

**Issue by tuonioooo** [bytedance/xgplayer#812]
**您使用的西瓜播放器版本是多少？ 

最新版本

**您使用的操作系统和浏览器分别是？ 

安卓

**如何复现问题？ What did you do?**

随便一个官方demo 都可以复现

**您期望的播放器正常行为是？ What did you expect to happen?**

rotateFullscreen: true 实现全屏的横屏模式

**实际播放器的表现是？ What actually happened?**

rotateFullscreen: true 仅是横屏模式，播放器并没有全屏展示 ，页面还会保留导航和底部

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yiwen03** [comment]
rotateFullscreen不是调用系统api实现的全屏，是通过前端添加css来实现，所以无法处理浏览器的导航和底部

**Comment by tuonioooo** [comment]
@yiwen03 是呀 ，但是使用 系统Api后，视频播放进入全屏模式，在配合如下属性
`rotate: {   //视频旋转按钮配置项
        innerRotate: true, //只旋转内部video
        clockwise: false // 旋转方向是否为顺时针
}`
进行旋转，进度条不跟随旋转 ，如果改成如下：

`rotate: {   //视频旋转按钮配置项
        innerRotate: false, //只旋转内部video
        clockwise: false // 旋转方向是否为顺时针
}`
进度条是可以跟随旋转，但只适用于非全屏模式下，如果是全屏 无任何效果

**Comment by 948489458** [comment]
这个问题还没有解决,为什么及关闭了呢
![111](https://github.com/user-attachments/assets/9c01650e-f398-4ba7-9d39-8aed2e678ab1)

![222](https://github.com/user-attachments/assets/f693759f-a4e8-4e24-b5a9-17ef99221909)

**Comment by 948489458** [comment]
h5 用   screen.orientation.lock('landscape'); 强制

player.on(Events.FULLSCREEN_CHANGE, async (isFullscreen) => {

    if (screen.orientation && screen.orientation.lock) {
      try {
        await screen.orientation.lock('landscape'); // 强制横屏
      } catch (error) {
        console.error('屏幕锁定失败:', error);
      }
    }
  })
