### ISSUE TITLE
缩小浏览器窗口，弹幕会变成一行并且重叠

### ISSUE THREAD

**Issue by rongcl9219** [bytedance/xgplayer#833]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.7

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows 10， Google Chrome  105.0.5195.127

**如何复现问题？ What did you do?**
开启弹幕，缩小浏览器窗口，弹幕会变成一行并且重叠

**您期望的播放器正常行为是？ What did you expect to happen?**
弹幕正常显示

**实际播放器的表现是？ What actually happened?**
弹幕会变成一行并且重叠

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
升级到最新版 [2.32.1](https://github.com/bytedance/xgplayer/commit/cf71780a8b482b5cf141944921eca57a9936c464) 已经修复了此问题
