### ISSUE TITLE
弹幕设置closeDefaultBtn(不使用默认提供弹幕开关)为true时会导致video点击事件失效

### ISSUE THREAD

**Issue by B-wells** [bytedance/xgplayer#836]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.32.1

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 & Google Chrome

**如何复现问题？ What did you do?**
![image](https://user-images.githubusercontent.com/17328531/201528327-5dcfb9f2-86fe-454a-bb4d-92ae6b4c649a.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
closeDefaultBtn为true时video点击事件正常

**实际播放器的表现是？ What actually happened?**
closeDefaultBtn为true时video点击事件失效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
xgplayer@2.32.2 版本修复了此问题，官网版本我会稍晚更新一下
