### ISSUE TITLE
xgplayer-hls.js播放m3u8遇错帧闪烁xgplayer-hls会跳过错误帧

### ISSUE THREAD

**Issue by webtanghuiliang** [bytedance/xgplayer#837]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^2.32.1",
    "xgplayer-hls": "^2.5.2",
    "xgplayer-hls.js": "^2.6.3"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
mac  chrome

**如何复现问题？ What did you do?**
使用https://video.ai.cdn.luonet.com/20221111_64036627979_7164658387437751081/64036627979_7164658387437751081.m3u8
视频链接
**您期望的播放器正常行为是？ What did you expect to happen?**
xgplayer-hls.js和xgplayer-hls一样会跳过错误帧

**实际播放器的表现是？ What actually happened?**
xgplayer-hls.js不会闪烁卡顿占满CPU

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
该流问题较多建议重转，大部分开源播放器也播放经常出错，建议至少保证ffmpeg等工具解码没有太多的报警

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/576737/201820457-248e5d9d-fa1c-4c04-872c-cf32a3cd47fa.png">

**Comment by webtanghuiliang** [comment]
视频报错直接停掉也行。现在是一直重复调起闪烁。占用内存

**Comment by webtanghuiliang** [comment]
> 该外露的问题播放器也建议重转，错误提示等工具不提供任何建议
> 
> <img alt="图片" width="1133" src="https://user-images.githubusercontent.com/576737/201820457-248e5d9d-fa1c-4c04-872c-cf32a3cd47fa.png">

视频报错停掉也行。现在是一直重复调起目标占用。直接内存占用
