### ISSUE TITLE
xgplayer-hls.js  加载m3u8文件失败

### ISSUE THREAD

**Issue by guodong01** [bytedance/xgplayer#839]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer 2.32.1
xgplayer-hls.js 2.6.3

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
iOS15.2  Safari

**如何复现问题？ What did you do?**

初始化HlsJsPlayer： useHls: true     视频加载失败，不支持mse的原因，持续loading？
                                    useHls: false    视频首次大概率失败并需要刷新才能播放，报错Media failed to decode，解码失败怎么办？

 多分辨率：emit('resourceReady', []) 切换分辨率时，中途会有暂停的黑屏闪现，有什么解决方案吗？

**您期望的播放器正常行为是？ What did you expect to happen?**
视频开头正常播放
多分辨率无缝切换

**实际播放器的表现是？ What actually happened?**
iOS系统下初次加载失败并需要刷新，PC及安卓无此问题

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
1. iOS下不支持MSE，无需使用xgplayer-hls.js 插件，原生video既可以播放m3u8
2. 不支持MSE的情况下，无法实现无缝切换码流，必然会有黑场
