### ISSUE TITLE
一个页面上有多个播放器时，在空白处按下空格全部视频同时播放

### ISSUE THREAD

**Issue by z764069592** [bytedance/xgplayer#842]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.32.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MAC 谷歌浏览器

**如何复现问题？ What did you do?**
一个页面放多个播放器

**您期望的播放器正常行为是？ What did you expect to happen?**
鼠标移入播放器上时才能触发键盘操作，否则不触发

**实际播放器的表现是？ What actually happened?**
在任意位置都能触发键盘操作，并且是多个播放器同时触发

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
v2 版本不提供区分页面和播放器的事件。您可以试用v3测试版本 3.0.0-next.*，并查看[keyboard相关配置](https://v3.h5player.bytedance.com/plugins/internalplugins/keyboard.html#config)，通过keyboard插件配置`disableBodyTrigger: true`禁用全局监听
