### ISSUE TITLE
播放器UI无法正常加载

### ISSUE THREAD

**Issue by MarushiruDonato** [bytedance/xgplayer#843]
我在Ant Design Pro中尝试添加一个带有播放器的页面
添加之后播放器的UI无法正常显示

> version: 3.0.0-alpha.102-5-0
OS: Windows 11 专业版 21H2
Browser: Microsoft Edge 107.0.1418.62 (正式版本) (64 位)

实际显示的页面: 
<img width="907" alt="屏幕截图_20221202_142144" src="https://user-images.githubusercontent.com/21275170/205229057-60f9739a-b8b7-4446-a752-7a4253f642f5.png">

这是我的页面代码
```tsx
import {PageContainer} from "@ant-design/pro-components";
import Player from "xgplayer";
import React from "react";

const VideoPlayer: React.FC = () => {
 const container_id = "videos-container"
  setTimeout(() => {
    new Player({
      id: container_id,
      url: "http://192.168.1.5:9000/taki/7899474bf41e4b5bf9fc7686df2a54db.mp4",
      playbackRate: [0.75, 1.25, 1.5, 2],
      enableContextmenu: true,
      pip: true
    });
  }, 0)


  return (
    <PageContainer>
      <div id={container_id}></div>
    </PageContainer>
  )
};
```

**Comment by gemxx** [comment]
请重装一下latest版本再试验一下，该问题应由 #848 引入
PS. 3.x的版本需要单独引入CSS，目前3.x还未正式对外开放。

**Comment by GloryOfTheKing** [comment]
请问目前3.0.7版本还出现这个，UI无法正常显示，请问是还需要单独引入css吗？
