### ISSUE TITLE
toFixed处理小数，精度有问题

### ISSUE THREAD

**Issue by mxluomx** [bytedance/xgplayer#844]
传的是4.0055，tofixed之后就变成了4.005499
传的是2.066667，tofixed之后就变成了2.066666

**Comment by mxluomx** [comment]
设置currentTime的时候，我看时间处理都是toFixed

**Comment by gemxx** [comment]
这个具体是指播放器内哪里的toFixed？

**Comment by mxluomx** [comment]
设置player.currentTime = 4.0055的时候就会复现
