### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'currentURL')  ，如何消除这个错误？

### ISSUE THREAD

**Issue by unconstraint23** [bytedance/xgplayer#847]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.32.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
windows

**如何复现问题？ What did you do?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
2.32.2未复现到该问题，建议贴一下可复现代码，以及具体环境
