### ISSUE TITLE
webview下播放含有key的m3u8失败

### ISSUE THREAD

**Issue by wenzheng-yi** [bytedance/xgplayer#851]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^2.32.2",
    "xgplayer-hls.js": "^2.6.3"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
安卓系统 webview

**如何复现问题？ What did you do?**
播放含有key的m3u8，且xhrSetup中设置了authorization。

**您期望的播放器正常行为是？ What did you expect to happen?**
能正常播放

**实际播放器的表现是？ What actually happened?**
在pc端的大多数浏览器上都可以播放，但是安卓手机app内嵌h5中播放不了

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by LoveMuZiLi** [comment]
> 能给出一个可以复现问题的dome吗

**Comment by wenzheng-yi** [comment]
> > 能给出一个可以复现问题的dome吗

你好，感谢你的回复。这个问题，我这边已经通过基础video组件及hls.js依赖解决了。
视频源是别人的，我这边不方便提供，但就是普通的带有key的m3u8，没有做其他处理。
h5是内嵌在uniapp的webview组件中的，如下是封装过的播放器代码。
`<template>
  <view class="player-wrap">
    <view id="mse"></view>
  </view>
</template>

<script>
import 'xgplayer'
import HlsJsPlayer from 'xgplayer-hls.js'
export default {
  name: 'player',
  props: {
    src: {
      required: true,
      type: String,
    },
  },
  data() {
    return {
      player: null,
    }
  },
  watch: {
    src: {
      handler(val) {
        // 监听并对应修改视频源
        if (val) {
          if (this.player && this.player.hasStart) {
            this.player.src = this.src
          } else {
            this.initPlayer(val)
          }
        }
      },
      immediate: true,
    },
  },
  mounted() {},
  methods: {
    initPlayer(url) {
      this.player = new HlsJsPlayer({
        el: document.querySelector('#mse'),
        autoplay: false,
        url: url,
        fluid: true,
        hlsOpts: {
          xhrSetup: function (xhr, url) {
            xhr.setRequestHeader('authorization', '项目的token')
          },
        },
      })
    },
  },
}
</script>

<style lang="scss" scoped>
.player-wrap {
  width: 100vw;
  height: 600rpx;
}
</style>
`
