### ISSUE TITLE
IOS搜狗浏览器极速版ended事件触发异常

### ISSUE THREAD

**Issue by bjxujiang** [bytedance/xgplayer#857]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.0-alpha.102-5-0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios 搜狗浏览器极速版 13.4.0.5245

**如何复现问题？ What did you do?**
播放任一mp4视频

**您期望的播放器正常行为是？ What did you expect to happen?**
在视频播放结束时触发ended事件

**实际播放器的表现是？ What actually happened?**
在开始播放的时候就触发了ended事件，实际视频播放结束时无法触发该事件

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
iOS搜狗极速版浏览器播放时对系统播放器做了劫持，实际播放用的是自己开发的播放器。该播放器有很多状态均不正确：

1. ended事件触发确实是有问题的，只有开始触发，实际结束不触发。
2. video.ended状态不准
3. video.duration 播放时为 NaN，获取不到准确的结束位置

因此，针对该浏览器西瓜播放器暂没有解决方案
