### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.

### ISSUE THREAD

**Issue by Gongn1ng** [bytedance/xgplayer#859]
使用xgplayer-mp4播放.mov类型的视频时会报错（Uncaught (in promise) DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.），并在播放器中出现请刷新重试字样，请问这个如何解决?

**Comment by gemxx** [comment]
xgplayer-mp4仅支持播放mp4文件类型的解析，不支持mov
