### ISSUE TITLE
项目的flv地址切换时播放器会暂停,使用西瓜直播的地址不会出现这个问题

### ISSUE THREAD

**Issue by qqfei1858** [bytedance/xgplayer#861]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
xgplayer: 2.32.2, xgplayer-flv.js: 2.3.0

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
系统: windows11  Chrome: 108.0.1462.54 (正式版本) (64 位)

**如何复现问题？ What did you do?**
项目中的flv地址会出现切换标签或者焦点不在可视区中,会触发播放器的暂停事件,并且视频也会暂停播放,
但是我使用西瓜官方直播flv地址则不会出现此问题,请问此问题是出在接口上还是?

西瓜直播地址: https://pull-flv-l26.douyincdn.com/third/stream-112307220042744294_hd.flv?expire=63c8f52a&sign=b7343df9c43b16cc7cf8a7adb8ae32e0&abr_pts=-1800

**您期望的播放器正常行为是？ What did you expect to happen?**
 

**实际播放器的表现是？ What actually happened?**
 

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
自动暂停和流本身无关
