### ISSUE TITLE
开启画中画后，字幕还在原视频框，没有到小视频框里面

### ISSUE THREAD

**Issue by PaleWhiteDot** [bytedance/xgplayer#865]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
最新版

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
google 109.0.5414.120

**如何复现问题？ What did you do?**
打开画中画，添加外挂字幕

**您期望的播放器正常行为是？ What did you expect to happen?**
字幕跟着画中画走

**实际播放器的表现是？ What actually happened?**
打开画中画后，字幕位置不动

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
[画中画](https://developer.mozilla.org/zh-CN/docs/Web/API/Picture-in-Picture_API)目前只能对video创建一个浮动的视频，最终展示的是一个系统级别的播放器UI，无法带上自定义的UI字幕

Chrome计划在[未来的版本](https://chromestatus.com/feature/5755179560337408)支持[document-picture-in-picture ](https://wicg.github.io/document-picture-in-picture/)，已允许增加自定义UI
