### ISSUE TITLE
字幕样式background-position设置没有生效

### ISSUE THREAD

**Issue by PaleWhiteDot** [bytedance/xgplayer#866]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
最新版

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
google 109.0.5414.120

**如何复现问题？ What did you do?**
textTrackStyle: {
    "background-color": "#ff0",
    "color": "#000",
    "background-position": "bottom 20px",
  },

**您期望的播放器正常行为是？ What did you expect to happen?**
希望字幕距离下边框有一段距离

**实际播放器的表现是？ What actually happened?**
设置没有生效，字幕在视频框最底部

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hongqx** [comment]
使用的xgplayer的版本是2.x还是3.x?r 如果使用的2.x, texttrack的样式是无法 修改的；如果使用的3.x, 字幕本质就是dom节点，而且也支持底部 边距配置http://h5player.bytedance.com/plugins/internalplugins/texttrack.html#config， 配置项style
