### ISSUE TITLE
自定义样式不能正常显示

### ISSUE THREAD

**Issue by Jinmoli** [bytedance/xgplayer#867]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^2.32.2",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome浏览器 版本 109.0.5414.120（正式版本） （64 位）

**如何复现问题？ What did you do?**
import Player from 'xgplayer';
import "@/assets/.xgplayer/skin/index.js"

vue配置:
const {defineConfig} = require('@vue/cli-service')
module.exports = defineConfig(
    {
        transpileDependencies: true,
        lintOnSave: false,
        publicPath: './',
        devServer: {},
        chainWebpack: config => {
            const svgRule = config.module.rule('svg')
            // 清除已有的所有 loader。
            // 如果你不这样做，接下来的 loader 会附加在该规则现有的 loader 之后。
            svgRule.uses.clear()
            // 添加要替换的 loader
            svgRule
                .use('raw-loader')
                .loader('raw-loader')
        },
    })

**您期望的播放器正常行为是？ What did you expect to happen?**
正常显示播放

**实际播放器的表现是？ What actually happened?**
vue.runtime.esm.js?c320:3049 TypeError: Cannot read properties of null (reading 'addEventListener')

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
个人调试

**Comment by Jinmoli** [comment]
怎么搞??//

**Comment by Jinmoli** [comment]
issue不维护了吗?

**Comment by gemxx** [comment]
问题描述的场景有很多不确定性，比如vue的版本，以及错误放生的时机。建议您用 [codepen](https://codepen.io/) 或者 [codesandbox](https://codesandbox.io/) 还原一下问题，这样方便我们快速定问题
