### ISSUE TITLE
ShakaJsPlayer播放器销毁后，仍请求

### ISSUE THREAD

**Issue by waylon233** [bytedance/xgplayer#868]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer-shaka": "^1.1.5"
"xgplayer": "^2.32.2"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome最新版  vue3

**如何复现问题？ What did you do?**
let player = new ShakaJsPlayer({
        id: 'mse',
        url: props.url,
        width: 624,
        height: 351,
        lang: 'en',
        fitVideoSize: 'auto',
        autoplay: true,
        ignores: ['progress', 'time'] 
  })
正常播放时的请求
![image](https://user-images.githubusercontent.com/97018607/218410127-92b046be-425c-49ab-a999-7db2c04f8497.png)
尝试了issues里提供的销毁方法: 
        player.src = ' '
        player.destroy(true)
发现组件样式销毁，但是还会一直请求xxxx.mpd这个url
![image](https://user-images.githubusercontent.com/97018607/218410391-0612094b-b25a-4efd-9d91-2361728fb769.png)

**您期望的播放器正常行为是？ What did you expect to happen?**
不再请求mpd

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by llftt** [comment]
更新下版本，问题已修复 xgplayer-shaka@1.1.6

**Comment by waylon233** [comment]
xgplayer-shaka@1.1.6  .mpd流无法播放，几个月前使用是正常的，服务器配置没有改变，报错信息如下:
![image](https://github.com/bytedance/xgplayer/assets/97018607/113032c0-d775-435f-b8ca-f8f2f1f50148)

![image](https://github.com/bytedance/xgplayer/assets/97018607/e8f26d2a-faeb-43d5-bef0-864db57f8eba)
