### ISSUE TITLE
中文文档中邮箱地址失效了

### ISSUE THREAD

**Issue by hughfenghen** [bytedance/xgplayer#870]
https://github.com/bytedance/xgplayer/blob/master/README.zh-CN.md?plain=1#L105

退信原因	未知原因
host mx1.bytedance.com[220.243.190.140] said: 550 Your message wasn't delivered to infra-fe@bytedance.com. Because you have no permission to send to this email address (in reply to RCPT TO command)

**Comment by gemxx** [comment]
很抱歉，该邮箱暂时无法使用了

> https://github.com/bytedance/xgplayer/blob/master/README.zh-CN.md?plain=1#L105
> 
> 退信原因 未知原因 host mx1.bytedance.com[220.243.190.140] said: 550 Your message wasn't delivered to [infra-fe@bytedance.com](mailto:infra-fe@bytedance.com). Because you have no permission to send to this email address (in reply to RCPT TO command)
