### ISSUE TITLE
iOS原生的样式无法修改

### ISSUE THREAD

**Issue by lmq352489099** [bytedance/xgplayer#873]
iOS原生的样式无法修改

_Originally posted by @gemxx in https://github.com/bytedance/xgplayer/issues/871#issuecomment-1430884464_

**Comment by lmq352489099** [comment]
加入fluid: true 是解决了的...  没有出现,请问知道什么原因吗

**Comment by gemxx** [comment]
该问题迁移至讨论区追踪吧
