### ISSUE TITLE
xgplayer-hls.js在mac系统流中断没有触发error事件

### ISSUE THREAD

**Issue by 88xu** [bytedance/xgplayer#874]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

2.5.2
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

mac os(ios)
**如何复现问题？ What did you do?**

hls直播流正常播放的过程中突然不能使用（流断了）
**您期望的播放器正常行为是？ What did you expect to happen?**
抛出error事件，通知给开发者

**实际播放器的表现是？ What actually happened?**
没有触发error事件；在windows下会触发HLS_ERROR，但是在mac系统中没有触发事件通知

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
企业中多个hls流需要容灾需求，一个流不能正常使用，换下一个流继续播；但是现在播放器没有事件通知到我流中断了

**Comment by 88xu** [comment]
补充一下，window下使用xgplayer.js，视频流断了是会触发error事件的；希望在xgplayer-hls.js中也可以触发error事件，而不是无限重试

**Comment by coderwlin** [comment]
我也遇到了同样的问题
