### ISSUE TITLE
画中画模式下, 返回标签页事件 和 按钮关闭的事件 都是同一个效果: 返回标签页.  怎么才能做到点击关闭按钮直接关闭, 而不是返回标签页吗?

### ISSUE THREAD

**Issue by 11039850** [bytedance/xgplayer#877]
![1676691258259](https://user-images.githubusercontent.com/12879617/219829537-80bef385-3bcf-4ee5-b6f8-d2987b8212f5.png)

**Comment by gemxx** [comment]
目前画中画浏览器显示的样式是浏览器的UI，因此无法控制自定义这些按钮及其事件

**Comment by gemxx** [comment]
[Document picture-in-picture](https://chromestatus.com/feature/5755179560337408) 支持画中画自定义，目前尚在Orginal Trial 阶段（chrome version 111-> 115），下一阶段会将特性ship到浏览器（预计是在chrome 116）
