### ISSUE TITLE
typescript 类型

### ISSUE THREAD

**Issue by pipi1ei** [bytedance/xgplayer#879]
2.23.2 版本中的类型文件和实际的方法不对应。
比如文档中给的监听播放事件的方法是：player.on('play', () => {}); 但类型文件中的声明是 onPlay

![图片](https://user-images.githubusercontent.com/46306727/220543756-8623b682-b2b4-49f3-99b2-7c04e0346614.png)

![图片](https://user-images.githubusercontent.com/46306727/220543718-65b515b4-a8b6-4143-b9ad-182b4fa5a796.png)

**Comment by gemxx** [comment]
onPlay 不是对外的事件接口，以文档为准

**Comment by pipi1ei** [comment]
> onPlay 不是对外的事件接口，以文档为准

所以2.x版本的类型文件声明有问题，player.on 监听事件 ts 会报错，说没有这个方法。内置的类型声明文件却写的是 onPlay。这个有在后续版本支持 ts 吗

**Comment by gemxx** [comment]
> 

后续3.x版本会有基于JSDoc产出的类型声明，但还不是完全使用typescript编码
