### ISSUE TITLE
xgplayer-hls 播放加密m3u8文件时，不请求ts文件

### ISSUE THREAD

**Issue by ichenhua** [bytedance/xgplayer#880]
xgplayer-hls 播放加密m3u8文件时，加载完key文件后，就没有动静了。

**Comment by gemxx** [comment]
可以提供下可复现的流吗？

**Comment by ichenhua** [comment]
这个地址：
http://m3u8.81f7.com/b726309681c8406417c2c8f1f90573b5_1.m3u8?pm3u8/0&e=1677561103&token=ZXu-8X7lkt65iqaYoHrPHmyr5oB0kyuxFHxdr1Az:wtNXPlQoYFyO5AxESEz-hlPp5lc=

**Comment by ichenhua** [comment]
完整代码：
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
    <meta name="referrer" content="no-referrer">
    <title>播放器</title>
    <style type="text/css">
      html, body {width:100%;height:100%;margin:auto;overflow: hidden;}
      body {display:flex;}
      #mse {flex:auto;}
    </style>
    <script type="text/javascript">
      window.addEventListener('resize',function(){document.getElementById('mse').style.height=window.innerHeight+'px';});
    </script>
  </head>
  <body>
    <div id="mse"></div>
    <script src="http://unpkg.byted-static.com/xgplayer/2.31.6/browser/index.js" charset="utf-8"></script>
    <script src="http://unpkg.byted-static.com/xgplayer-hls/2.5.2/dist/index.min.js" charset="utf-8"></script>
    <script type="text/javascript">
      let player = new HlsPlayer({
          id: 'mse',
          url: 'http://m3u8.81f7.com/b726309681c8406417c2c8f1f90573b5_1.m3u8?pm3u8/0&e=1677561103&token=ZXu-8X7lkt65iqaYoHrPHmyr5oB0kyuxFHxdr1Az:wtNXPlQoYFyO5AxESEz-hlPp5lc=',
          autoplay: true,
          playsinline: true,
          height: window.innerHeight,
          width: window.innerWidth
      });
    </script>
  </body>
</html>
```

**Comment by modstart** [comment]
遇到了相同的问题，关注解决办法

**Comment by gemxx** [comment]
我这边也复现到了，这周我处理下这个问题

**Comment by pocketChao** [comment]
请问这个问题解决了么  我们也遇到了同样的问题 带加密的视频 无法播放  GET <video> error: https://wxtest.xuesee.net/sfs/volcano/resource/volbeacon/resource/20230325/m3u8/1cf2076e-6f3a-4077-996f-61ee2a91a420/1cf2076e-6f3a-4077-996f-61ee2a91a420.m3u8

**Comment by pocketChao** [comment]
> 

其他诸如小程序 app 都无法播放

**Comment by pocketChao** [comment]
> 

https://wxtest.xuesee.net/sfs/volcano/resource/volbeacon/resource/20230325/m3u8/1cf2076e-6f3a-4077-996f-61ee2a91a420/1cf2076e-6f3a-4077-996f-61ee2a91a420.m3u8

**Comment by pocketChao** [comment]
小程序\app都可以播放该视频

**Comment by pocketChao** [comment]
> 请问这个问题解决了么 我们也遇到了同样的问题 带加密的视频 无法播放 GET
 
文件结构如下
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:17
#EXT-X-KEY:METHOD=AES-128,URI="https://volbeacon.xuesee.net/volbeacon/common/videoKey/d294b794-6afe-426b-8b52-d2f1b812abd2.do",IV=0xd294b7946afe426b8b52d2f1b812abd2
#EXTINF:10.080000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0000.ts
#EXTINF:14.520000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0001.ts
#EXTINF:12.360000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0002.ts
#EXTINF:8.480000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0003.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0004.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0005.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0006.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0007.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0008.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0009.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0010.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0011.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0012.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0013.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0014.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0015.ts
#EXTINF:8.960000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0016.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0017.ts
#EXTINF:12.840000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0018.ts
#EXTINF:4.840000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0019.ts
#EXTINF:9.040000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0020.ts
#EXTINF:10.680000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0021.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0022.ts
#EXTINF:16.080000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0023.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0024.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0025.ts
#EXTINF:4.320000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0026.ts
#EXTINF:10.000000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0027.ts
#EXTINF:8.560000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0028.ts
#EXTINF:9.320000,
1cf2076e-6f3a-4077-996f-61ee2a91a420-0029.ts
#EXT-X-ENDLIST

**Comment by boomfruit** [comment]
https://blog.csdn.net/JaneLittle/article/details/126511710 问题已解决
