### ISSUE TITLE
mp4进度条拖动后，会重新从初始开始播放，在在线生成例子中也是这样

### ISSUE THREAD

**Issue by limyxi** [bytedance/xgplayer#882]
测试视频链接：http://121.37.229.254:8084/sys/file/new/download?id=1630774482870255618

**Comment by gemxx** [comment]
服务这个地址的server不支持 Content-Range 请求，请更换成对流媒体支持良好的视频服务器，比如nginx

**Comment by hijjl** [comment]
果然  我也遇到了这个问题。。。
