### ISSUE TITLE
How to integrate vast?

### ISSUE THREAD

**Issue by JonasWater** [bytedance/xgplayer#883]
This project is awesome. But I had problems with vast and how to integrate vast?

**Comment by gemxx** [comment]
VAST can be integrated with xgplayer's [custom-plugin](https://v2.h5player.bytedance.com/en/plugins/#custom-plugin), just like how the [xgplayer-hls](https://github.com/bytedance/xgplayer/blob/master/packages/xgplayer-hls-vod/src/index.js) plugin implements the hls flow
