### ISSUE TITLE
vite项目，xgplayer-hls.js包，mu38格式视频加载异常

### ISSUE THREAD

**Issue by xxyGoTop** [bytedance/xgplayer#884]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^2.32.2",
    "xgplayer-hls.js": "^2.6.4"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10
chrome111

**如何复现问题？ What did you do?**
初始化vite项目，npm init vue@3

**您期望的播放器正常行为是？ What did you expect to happen?**
mu38视频正常播放

**实际播放器的表现是？ What actually happened?**
mu38视频播放不正常，module加载xgplayer-hls.js异常，
异常信息： Uncaught TypeError: Cannot read properties of undefined (reading 'call')，
__webpack_require__4， ./src/demux/transmuxer-worker.ts
猜测：xgplayer-hls.js包是否依赖了webpack全局变量，导致引入依赖异常

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by 15202079229** [comment]
xgplayer-hls.js包里有webpack.config.js，这个应该是不生效的，直接下载编译好的js或者引入cdn可以解决问题

import '//unpkg.byted-static.com/xgplayer/2.31.2/browser/index.js'; // window.Player
import '//unpkg.byted-static.com/xgplayer-hls.js/2.2.2/browser/index.js'; //window.HlsJsPlayer

**Comment by 15202079229** [comment]
xgplayer-hls.js包里有webpack.config.js，这个应该是不生效的，直接下载编译好的js或者引入cdn可以解决问题
`
<script setup  lang="ts">
import '//unpkg.byted-static.com/xgplayer/2.31.2/browser/index.js'; // window.Player
import '//unpkg.byted-static.com/xgplayer-hls.js/2.2.2/browser/index.js'; //window.HlsJsPlayer

mp4Player.value = new window.Player({ id: 'mp4Player', ...options })
hlsPlayer.value = new window.HlsJsPlayer({ id: 'hlsPlayer', ...options })
`

**Comment by 15202079229** [comment]
xgplayer-hls.js包里有webpack.config.js，这个应该是不生效的，直接下载编译好的js或者引入cdn可以解决问题

```
<script setup lang="ts"> 
import '//unpkg.byted-static.com/xgplayer/2.31.2/browser/index.js'; // window.Player 
import '//unpkg.byted-static.com/xgplayer-hls.js/2.2.2/browser/index.js'; //window.HlsJsPlayer 
mp4Player.value = new window.Player({ id: 'mp4Player', ...options }) 
hlsPlayer.value = new window.HlsJsPlayer({ id: 'hlsPlayer', ...options }) 
</script>
```

**Comment by zhoupeihuang** [comment]
npm uninstall xgplayer  xgplayer-hls.js // 先卸载最新版 应该是alpha 版本
npm install xgplayer@2.31.2   xgplayer-hls.js@2.2.2 // 再安装稳定版 
问题解决
