### ISSUE TITLE
播放器能否拉伸铺满父容器，不保持比例？

### ISSUE THREAD

**Issue by 502315278** [bytedance/xgplayer#885]
播放器能否拉伸铺满父容器，不保持比例？

**Comment by gemxx** [comment]
可使用播放器的[流式布局配置](https://v2.h5player.bytedance.com/config/#%E6%B5%81%E5%BC%8F%E5%B8%83%E5%B1%80)
`{
  fluid: true
}`

**Comment by 502315278** [comment]
> 可使用播放器的[流式布局配置](https://v2.h5player.bytedance.com/config/#%E6%B5%81%E5%BC%8F%E5%B8%83%E5%B1%80)`{ fluid: true }`

但是这种视频画面还是按照比例播放(两侧或上下有黑边)，能否让视频画面拉伸铺满整个播放器？

**Comment by gemxx** [comment]
> > 可使用播放器的[流式布局配置](https://v2.h5player.bytedance.com/config/#%E6%B5%81%E5%BC%8F%E5%B8%83%E5%B1%80)`{ fluid: true }`
> 
> 但是这种视频画面还是按照比例播放(两侧或上下有黑边)，能否让视频画面拉伸铺满整个播放器？

可以试一下 css [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit), fill & cover 可以达达到效果，但分别会拉伸或者裁剪画面。

这个问题本身没有特别完美的答案。要么让video内容进行拉伸或者裁剪，要么是video容器根据video内容进行自适应
