### ISSUE TITLE
README的开发环境启动命令修正

### ISSUE THREAD

**Issue by HeGangSZ** [bytedance/xgplayer#886]
参照README的环境命令是有误的，执行到后面报module不存在，启动不起来。不止要在根目录npm i，还需要到packages/xgplayer && npm install

原命令
`$ cd xgplayer`
`$ npm install`
`$ npm run build:player`
`$ npm run dev`

修正命令
`$ cd xgplayer`
`$ npm install`
`$ cd packages/xgplayer && npm install && cd .. && cd ..`
`$ npm run build:player`
`$ npm run dev`

**Comment by gemxx** [comment]
v2 的启动命令README内已经更新：https://github.com/bytedance/xgplayer/tree/v2#dev
PS. v2目前基本处于不维护状态，建议切换至V3版本 @HeGangSZ
