### ISSUE TITLE
vite+vue3无显示画面

### ISSUE THREAD

**Issue by Hiram-Wong** [bytedance/xgplayer#890]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.0-alpha.110-12",
"xgplayer-hls": "^3.0.0-next.36",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**如何复现问题？ How to reproduce the problem?**
https://stackblitz.com/edit/vitejs-vite-nlxvfj
直接使用index.html.bak这个文件缺可以正常播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常显示画面

**实际播放器的表现是？ What actually happened?**
不断拉取数据流，却没有画面

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by turnmind** [comment]
可能是插件的问题，兼容性不怎么样，有些流解析不了，试试 tcplayer

**Comment by MrPluto0** [comment]
遇到了同样的问题，降低版本为2.x就可以了

**Comment by gemxx** [comment]
更新一下版本到最新正式版本3.0.1，您提供的版本中xgplayer和xgplayer-hls配合会有问题。

版本更新后的代码请查看：
https://stackblitz.com/edit/vitejs-vite-7hhbm2?file=yarn.lock,package-lock.json,package.json
