### ISSUE TITLE
window is not defined in Nextjs

### ISSUE THREAD

**Issue by HiChen404** [bytedance/xgplayer#893]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

2.32.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

Window/Chrome

**如何复现问题？ How to reproduce the problem?**
使用 Next.js 初始化播放器即可复现

```tsx
 useEffect(() => {
    new Player({
      id: 'xgplayer',
      url: '',
    })
  }, [])
```

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

```
Server Error
ReferenceError: window is not defined
```

**Comment by gemxx** [comment]
西瓜播放器在V3支持了SSR，请升级到V3版本吧。
