### ISSUE TITLE
ios钉钉不支持flv

### ISSUE THREAD

**Issue by why91113** [bytedance/xgplayer#895]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
2.31.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
ios 钉钉内嵌H5

**如何复现问题？ How to reproduce the problem?**
使用ios钉钉访问示例页面  https://v2.h5player.bytedance.com/examples/ 
选择flv格式播放地址，视频不能正常播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放flv视频

**实际播放器的表现是？ What actually happened?**
西瓜flv一直加载中；flv.js提示：请刷新试试

**Comment by gemxx** [comment]
iOS webkitwebview 均不支持MediaSource，因此无法支持flv文件转封装播放
