### ISSUE TITLE
小米浏览器上设置controls: false,但是依然有控制条

### ISSUE THREAD

**Issue by keepzouba** [bytedance/xgplayer#897]
**您使用的西瓜播放器版本是多少？ 2.31.6

**您使用的操作系统和浏览器分别是？ 安卓10,小米浏览器

**如何复现问题？ 使用小米手机自带的浏览器打开

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
请确认下小米浏览器是否为浏览器劫持后的UI，这种劫持后的video无法控制UI展示
