### ISSUE TITLE
如何增加fetch-loader.js的headers

### ISSUE THREAD

**Issue by fandudu** [bytedance/xgplayer#898]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

    "xgplayer": "^2.32.2",
    "xgplayer-hls": "^2.5.2",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
no care

**如何复现问题？ How to reproduce the problem?**
您好，由于我的url需求在请求时增加类似token的鉴权头，我调试了代码好像没有地方可以传入headers，求帮助如何解决
![image](https://user-images.githubusercontent.com/15722726/231698893-74da36d1-fb16-4806-b55c-693595e34688.png)

**Comment by fandudu** [comment]
@gemxx 请问是否有类似xgplayer-hls.js里的hlsOpts配置

**Comment by gemxx** [comment]
V2的xgplayer-hls没有对外开放修改fetch参数的配置
