### ISSUE TITLE
无法播放qq录屏

### ISSUE THREAD

**Issue by LinyuNB** [bytedance/xgplayer#904]

**Comment by gemxx** [comment]
请提供一下录屏文件

**Comment by LinyuNB** [comment]
qq截屏的录屏功能

________________________________
发件人: gemstone ***@***.***>
发送时间: 2023年5月4日 23:22
收件人: bytedance/xgplayer ***@***.***>
抄送: LinyuNB ***@***.***>; Author ***@***.***>
主题: Re: [bytedance/xgplayer] 无法播放qq录屏 (Issue #904)


请提供一下录屏文件

―

**Comment by gemxx** [comment]
使用的xgplayer-mp4版本是多少？您最好还是提供下demo，不要只描述现象

**Comment by LinyuNB** [comment]
https://hehu.zjwater.com:10443/files-oss/files/QQ录屏.mp4
"xgplayer": "^2.27.3",
"xgplayer-mp4": "^2.0.0"

**Comment by jiuyuetianjiuyuetian** [comment]
你提供的视频的编码是mp4v, audio/mp4; codecs="mp4v,mp4a.40.2"; profiles="isom,iso2,mp41"，浏览器目前不支持
