### ISSUE TITLE
playNext设置点击播放下一集报错

### ISSUE THREAD

**Issue by itzhi** [bytedance/xgplayer#905]
**您使用的西瓜播放器版本是多少？ "xgplayer": "^3.0.1",
		"xgplayer-hls.js": "^3.0.0-alpha.1",
		"xgplayer-mp4": "^3.0.1"

配置信息如下:
new Player({
        el: this.$refs.video,
        url: 'http://xxxxx/test.m3u8',
        fluid: true, 
        fitVideoSize: 'auto', 
        volume: 0.6, 
        autoplay: false,
        loop: true,
        videoInit: false,
        poster: '', 
        playbackRate: [0.5, 0.75, 1, 1.5, 2],
        defaultPlaybackRate: 1, 
        startTime: 20, 
        playNext: {
          urlList: [
            'http://xxxx/9s.m3u8',
            'http://xxxxx/test.mp4'
          ]
        },
        plugins: [HlsJsPlugin, Mp4Plugin]
      })

报错信息如下:Cannot read properties of undefined (reading 'url')
TypeError: Cannot read properties of undefined (reading 'url')

错误代码在es/player.js文件中的788行, 经调试显示to就是地址, 并没有to.url, 所以想请教下需要怎么解决

**Comment by gemxx** [comment]
playNext调用参数是怎么传入？

**Comment by itzhi** [comment]
playNext: {
  urlList: [
  'http://xxxx/9s.m3u8',
  'http://xxxxx/test.mp4'
  ]
},在配置中直接写入的

**Comment by itzhi** [comment]
1. 方法里面设置 player.currentSrc = url 的时候提示报错信息为只能获取不能设置
2. 方法里面设置 player.src = url 的时候和点击下一集播放的错误是一样的

**Comment by gemxx** [comment]
我尝试复现了一下，没有看到有描述中的报错，辛苦贴一个复现的demo。https://codepen.io/ 或者 https://codesandbox.io/ 或其他代码展示方式

**Comment by gemxx** [comment]
> https://codepen.io/itzhi/pen/eYPrrpM

这个demo不是完整可运行的，只贴了一下JS代码，没有版本以及其他信息。希望整体demo能复现到您最开始提的问题

**Comment by itzhi** [comment]
我是在vue2里面当成组件运行的在js里面有贴安装的版本
