### ISSUE TITLE
如何手动调整缓存大小？某些场景下需要

### ISSUE THREAD

**Issue by chrischjh** [bytedance/xgplayer#913]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
**实际播放器的表现是？ What actually happened?**
**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

在远程控制摄像头的场景下，比如要转动摄像头，在网络通畅的情况下，转动指令发出后，大概4秒左右视频才有反应，但实际上可以控制在1～2秒内体验会比较好。

对比了多个播放器，应是缓存设置长短的问题。请问xgplayer如何手动调整缓存？

**Comment by gemxx** [comment]
具体用了哪些xgplayer库或者插件？

**Comment by chrischjh** [comment]
用的xgplayer-flv

**Comment by gemxx** [comment]
v3版本可以设置一下targetLatency，具体可以看看官网文档中参数描述： https://h5player.bytedance.com/plugins/extension/xgplayer-flv.html#api
