### ISSUE TITLE
vue3 引入 xgplayer-hls-3.0.1 版本出现

### ISSUE THREAD

**Issue by zhaoxiangning** [bytedance/xgplayer#914]
TypeError: Cannot read properties of null (reading 'text')  pluginsManager.js:219
直播没有自动的去播放 只能手动

**Comment by gemxx** [comment]
请提供下可复现的流，以及播放器部分的代码

**Comment by zhaoxiangning** [comment]
我是通过 npm 下载  HlsPlayer 报错

**Comment by zhaoxiangning** [comment]
我是通过npm下载 HlsPlayer 插件报错 但是使用 cdn 就没事了 vue3
