### ISSUE TITLE
uniaapp 引入v3xgplayer 视频容器大于父容器

### ISSUE THREAD

**Issue by Gs19990801** [bytedance/xgplayer#916]
代码
![597e18210b6804ce2cbb3cd1e81ee8d](https://github.com/bytedance/xgplayer/assets/81606230/d5d906f4-fe0e-4a43-8bb0-ab799197bd37)

**Comment by gemxx** [comment]
提供一下包括uni版本，播放器版本等信息。另外用codepen 或者 codesandbox等所见即所得代码工具写一个最小demo，否则我们不太容易还原这个场景

**Comment by Gs19990801** [comment]
> 流体： true，使用这个就可以了不过大小好了但是内容黑屏

是的 用了这个会黑屏

**Comment by Gs19990801** [comment]
> 提供一下包括uni版本，播放器版本等信息。另外用codepen 或者 codesandbox等所见即所得代码工具写一个最小demo，否则我们不太容易还原这个场景

官方大大 demo 就是图中那么多东西 其他啥都没 安装方式 npm  然后我试了 vue项目是可以的 uni项目就是这样

**Comment by vuejsstudy** [comment]
我也出现了这个问题，怎么解决的

**Comment by Gs19990801** [comment]
> 我也出现了这个问题，怎么解决的

换了一个插件
