### ISSUE TITLE
视频缓冲动画隐藏

### ISSUE THREAD

**Issue by dbc1129** [bytedance/xgplayer#917]
视频缓冲的时候有一个加载的转圈动画，类名是xgplayer-isloading,我不想要这个缓冲动画，但当我用这个类名把css样式改为display：none的时候，没有了那个缓冲动画，但是会出现黑屏，缓冲的时候是一闪一闪的，所以我应该怎么样合理的隐藏掉这个缓冲动画

**Comment by gemxx** [comment]
缓冲的时候有闪烁具体描述下是什么现象，可以录一个视频吗？

**Comment by gemxx** [comment]
> 
xgplayer-loading 只是一个icon，并且是很小的一个区域loading动画，不会影响整个播放器画面闪出蓝色画面。感觉像是你的视频流画面问题
![image](https://github.com/bytedance/xgplayer/assets/576737/bcde61e2-9ae2-46d8-aae4-76804b96d8c1)

**Comment by dbc1129** [comment]
是xgplayer-isloading,在video这个元素外面的那个载体上的一个类名，我给您发的视频里就有这部分多次触发添加消除“xgplayer-isloading”这个类名，您可以仔细再看一下
![MUFPZ_E@J@1KZT`2I%%9F78](https://github.com/bytedance/xgplayer/assets/131576988/c07d3827-1ac8-4aaa-bcc4-bf0f11cd0f32)

**Comment by dbc1129** [comment]
我只是加了一个这个样式
![@R4FE(Q$OOSJGDH{UZ@T2RG](https://github.com/bytedance/xgplayer/assets/131576988/ca32a094-25ce-44af-9374-e0d6bcff193d)
![B1@})150SAEZL$CIVRCV3LP](https://github.com/bytedance/xgplayer/assets/131576988/8c28a3ea-4799-4216-bdd7-338c1a58bfdf)

**Comment by woodyRoyal** [comment]
楼主你最后怎么解决这个问题的
