### ISSUE TITLE
视频码率过大，播放不了

### ISSUE THREAD

**Issue by weipengcheng1** [bytedance/xgplayer#921]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^2.32.1",
    "xgplayer-hls.js": "^2.6.3"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
操作系统：win10
浏览器：谷歌浏览器

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**
视频码率在1800kbps情况下能正常播放

**实际播放器的表现是？ What actually happened?**
视频码率在1800kbps情况下，m3u8格式加载不出来，一直转圈，没有报错
在mp4个格式下，只加载了音频，未加载出图像。
使用qq影音播放器可以正常播放该视频，视频信息如下图
<img width="661" alt="image" src="https://github.com/bytedance/xgplayer/assets/49983314/a241beb7-f2d4-4d61-9ba5-2647da44a15b">

**Comment by hongqx** [comment]
这个问题播放解决不了，17s的视频，200多M，码率实在过高了，建议自己装一下ffmpeg做一下转码压缩之后再做播放

**Comment by weipengcheng1** [comment]
这个是17分钟的视频

**Comment by weipengcheng1** [comment]
> 这个问题播放解决不了，17s的视频，200多M，码率实在过高了，建议自己装一下ffmpeg做一下转码压缩之后再做播放

这个是17分钟视频
