### ISSUE TITLE
H265编码的hls视频流地址无法播放

### ISSUE THREAD

**Issue by liujingjing233** [bytedance/xgplayer#932]
H264编码的hls视频流可以播放，h265的测试后发现无法播放，但也不会报错！

**Comment by gemxx** [comment]
有可复现的视频地址吗？

**Comment by wxqweb** [comment]
此地址是h265编码，无法播放，麻烦帮忙看下，感谢。
https://lf3-record-tos.bytefcdn.com/obj/fcdn-dy/9821465475876905304/push-rtmp-hs-f5.douyincdn.com_stage_stream-689771234154250922_1688457761_1688458274_record.m3u8?psm=ad.platform.live_console

**Comment by gemxx** [comment]
https://codepen.io/gem-stone/pen/YzReKpK

我这里看播放是正常的。看下你的浏览器版本

> 此地址是h265编码，无法播放，麻烦帮忙看下，感谢。 https://lf3-record-tos.bytefcdn.com/obj/fcdn-dy/9821465475876905304/push-rtmp-hs-f5.douyincdn.com_stage_stream-689771234154250922_1688457761_1688458274_record.m3u8?psm=ad.platform.live_console
