### ISSUE TITLE
startTime 不生效

### ISSUE THREAD

**Issue by jahem** [bytedance/xgplayer#939]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

3.0.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

安卓uniapp

**如何复现问题？ How to reproduce the problem?**

<web-view ref="myVideo" class="myVideo" :src="'/hybrid/html/xgplayer.html'
				+ '?src=' + encodeURIComponent(xiguaurl) 
				+ '&autoplay=' + autoplay 
				+ '&video_muted=' + video_muted 
				+ '&initialTimeVal=' + encodeURIComponent(initialTimeVal)" @onPostMessage="onPostMessage" allow="fullscreen"
				v-if="destroyed_state == false" fullscreen />

**您期望的播放器正常行为是？ What did you expect to happen?**

生效

**实际播放器的表现是？ What actually happened?**

不生效，每次都从0开始，当前实现
player.on('play', function() {
   setTimeout(function() {
     player.seek(config.startTime)
  }, 3000)
})
必须要3000之后，不然一直不生效

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
目前startTime配置逻辑依赖的是video canplay事件，在事件内设置video.currentTime以实现startTime逻辑，具体逻辑[点击这里](https://github.com/bytedance/xgplayer/blob/main/packages/xgplayer/src/player.js#L1637-L1643)见代码。猜测可能是canplay事件未发导致，请提供一下手机型号，android版本以及浏览器版本
