### ISSUE TITLE
不支持的音频/视频格式

### ISSUE THREAD

**Issue by Hiram-Wong** [bytedance/xgplayer#940]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
"xgplayer": "^3.0.3-alpha.3",
"xgplayer-hls": "^3.0.3-alpha.3",

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome 113.0.5672.126

**如何复现问题？ How to reproduce the problem?**
m3u8 地址：https://s1.bfzycdn.com/video/aomenfengyun3/hd%E5%9B%BD%E8%AF%AD%E7%89%88/index.m3u8

web 播放器@vime/vue-next就可以播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
提示不支持的音频/视频格式

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
**https://s1.bfzycdn.com/video/aomenfengyun3/hd%E5%9B%BD%E8%AF%AD%E7%89%88/index.m3u8**, 这个流地址404了，再提供一下新的地址

**Comment by wxqweb** [comment]
https://lf3-record-tos.bytefcdn.com/obj/fcdn-dy/9821465475876905304/push-rtmp-hs-f5.douyincdn.com_stage_stream-689771234154250922_1688457761_1688458274_record.m3u8?psm=ad.platform.live_console

**Comment by Hiram-Wong** [comment]
> **https://s1.bfzycdn.com/video/aomenfengyun3/hd%E5%9B%BD%E8%AF%AD%E7%89%88/index.m3u8**, 这个流地址404了，再提供一下新的地址

http://139.159.239.156:88/api/video?xiaochengziyuan=RFpoZ3hUcXZoSnY2TytTeDRXN2tHRzFqWHZiN1NObGtwVk9XU1NGcmhYem43Uy8xOEQxVTFvSVE1VVp1ODlTKzBqUXhpdExoTXgvV200dVEyY1ZrOFpFRlJQVDRRMXU2OEp4dUhYN2pmd3lYUEY0VFRYa2F3RnVqaWNNbkdJc1FLV3hQVHVBSTgrS3F2UEVRYVljS2I4TTRXOWJwVDR2U09ueXFpZ1pYN2tWTmxHVlhsb1NPano2TkwvaUhuN0FK/video.m3u8
用腾讯播放器和阿里播放器的 web 播放器均可播放，用西瓜播放器和火山播放器均无法播放
