### ISSUE TITLE
不支持的视频格式

### ISSUE THREAD

**Issue by skypanpan** [bytedance/xgplayer#941]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

    <link rel="stylesheet" href="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.css" />
    <script charset="utf-8" src="https://unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.js"></script>

    <script charset="utf-8" src="https://unpkg.byted-static.com/xgplayer-flv/3.0.1/dist/index.min.js"></script>
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
谷歌，最新版本

**如何复现问题？ How to reproduce the problem?**
    打开直接提示不支持的格式  flv格式，是否只支持h.264?

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
提示不支持的格式

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
flv是支持的，贴一下能复现的流以及使用方式
