### ISSUE TITLE
浏览器开启硬件加速会导致播放器报解码错误

### ISSUE THREAD

**Issue by LxbNNN** [bytedance/xgplayer#950]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
	"xgplayer": "^3.0.0-next.56",
		"xgplayer-flv": "^3.0.1",
		"xgplayer-hls": "^3.0.1"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

mac 谷歌浏览器
**如何复现问题？ How to reproduce the problem?**
开启硬件加速 播放flv流 播放一会儿会报错  报错信息："PIPELINE_ERROR DECODE: Failed to parse H.265 stream'

**您期望的播放器正常行为是？ What did you expect to happen?**
直播长时间稳定播放

**实际播放器的表现是？ What actually happened?**
播放一会儿断开 

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
@LxbNNN 贴一下可复现问题的流地址

**Comment by zhoupeihuang** [comment]
npm uninstall xgplayer  xgplayer-hls.js // 先卸载最新版 应该是alpha 版本
npm install xgplayer@2.31.2   xgplayer-hls.js@2.2.2 // 再安装稳定版 
问题解决

**Comment by gemxx** [comment]
xgplayer-hls.js 底层使用的 hls.js 库，不确定其对265的支持性。
可以试试3.x版本的 xgplayer  & xgplayer-hls

**Comment by LxbNNN** [comment]
@gemxx  内网环境不能提供  用的海康摄像头 设置成265，用zlm流媒体转出来，播放flv和hls就会有这个问题
