### ISSUE TITLE
引入的插件有什么差异

### ISSUE THREAD

**Issue by dbc1129** [bytedance/xgplayer#953]
<script src="//unpkg.byted-static.com/xgplayer/2.31.2/browser/index.js" charset="utf-8"></script>
    <script src="//unpkg.byted-static.com/xgplayer-flv.js/2.1.2/browser/index.js" charset="utf-8"></script>
    
    
     <script src="//unpkg.byted-static.com/xgplayer/3.0.1/dist/index.min.js" charset="utf-8"></script>
    <script src="//unpkg.byted-static.com/xgplayer-flv.js/3.0.0-alpha.1/dist/index.min.js" charset="utf-8"></script>
    
    上述两种插件有什么不同？在vue中可以引用第一种插件吗？我只在npm里找到的是"xgplayer": "^3.0.4",
    "xgplayer-flv.js": "^3.0.4"这两个，

**Comment by dbc1129** [comment]
为什么使用
"xgplayer": "^3.0.4",
"xgplayer-flv.js": "^3.0.4"
这两个插件，然后如下使用会报错：

<img width="198" alt="fe10752d84914a0efb27413ae1acd4c" src="https://github.com/bytedance/xgplayer/assets/131576988/4200fd9a-d1bf-4831-b910-d6004906b4d2">
<img width="317" alt="5cb18de640d1f43ac26892178e265e3" src="https://github.com/bytedance/xgplayer/assets/131576988/bfd456de-05c1-44f8-a9da-7735376de28c">
<img width="268" alt="fc8be665bd94efe4eb4d1935ecc17b3" src="https://github.com/bytedance/xgplayer/assets/131576988/b5c09b93-0150-4982-8579-1550fbc430b8">
<img width="339" alt="05bb2d7cd6159e5fbc303fd16633a3d" src="https://github.com/bytedance/xgplayer/assets/131576988/e7d1c64a-4154-478f-9025-b20ce7c1b9fe">

**Comment by gemxx** [comment]
提供下vue的版本

**Comment by dbc1129** [comment]
3.2.36

**Comment by gemxx** [comment]
截图中flv插件代码初始化的方式还是2.x的初始化方法。3.x版本参见官网文档中[第三方插件flv.js的描述](https://h5player.bytedance.com/plugins/extension/third-party-plugin.html#xgplayer-flv-js)。另外也可以看下[示例代码中](https://h5player.bytedance.com/examples/)的初始化方法
<img width="1632" alt="image" src="https://github.com/bytedance/xgplayer/assets/576737/e8be7574-db90-4c4f-b1e1-3dee87b00851">

```javascript
import Player from 'xgplayer'
import 'xgplayer/dist/index.min.css'
import FlvJsPlugin from 'xgplayer-flv.js'

const player = new Player({
      id: 'vs',
      url: '../xgplayer-demo.hls',
      plugins: [FlvJsPlugin],
      flvJsPlugin: {} // config for plugin FlvJsPlugin
      // If use CDN loading,you can Get the plugin through window.FlvJsPlugin
})
```

**Comment by dbc1129** [comment]
<img width="209" alt="314b7e624a84c99a9d4474b688fde28" src="https://github.com/bytedance/xgplayer/assets/131576988/93461447-fadf-423b-bf1c-f806f0b0c5fb">
<img width="325" alt="fb43fb48d575d8d9243cb75c4d989c5" src="https://github.com/bytedance/xgplayer/assets/131576988/63925ef4-e896-48f3-8259-5283efd920c6">
<img width="548" alt="e3a1d53ce0c3848d638179ddae48d20" src="https://github.com/bytedance/xgplayer/assets/131576988/a5a70d24-5a9e-43b0-93b9-756fe1ad3b92">
<img width="469" alt="b64c4649f0e3b7ddb467ebf57f527fe" src="https://github.com/bytedance/xgplayer/assets/131576988/274218e8-357c-4cf6-af86-61ae0847b5c6">
采用plugins导入FlvJsPlugin的方法还是会报这个错，但是采用plugins导入FlvPlugin的方法就不会报错

**Comment by gemxx** [comment]
试一下这个版本 `xgplayer-flv.js@3.0.5-alpha.1`
