### ISSUE TITLE
flv视频流的拖动问题

### ISSUE THREAD

**Issue by dbc1129** [bytedance/xgplayer#954]
<img width="698" alt="12e24ab112618c660365c4a2293c790" src="https://github.com/bytedance/xgplayer/assets/131576988/d3e457da-7f1a-414d-98ad-75f912a5775b">
<img width="459" alt="fcec22003ebcea5977211557202c12d" src="https://github.com/bytedance/xgplayer/assets/131576988/7373dbd9-4a0e-4e45-aa44-3a31039263dc">
如上述图片，使用(plugins: [window.FlvJsPlugin])这样的形式使用flv就无法进行拖动，应该怎么配置实现拖动

**Comment by dbc1129** [comment]
<img width="379" alt="9063187d964990f44fd15d1a12bae3b" src="https://github.com/bytedance/xgplayer/assets/131576988/fd907418-44b9-429b-ab5b-fb0e5dd6a7ad">
拖动视频会报这个错误，应该怎么解决

**Comment by gemxx** [comment]
URL配置的是直播流吗？

**Comment by dbc1129** [comment]
不是实时的视频，是之前的视频，里面还有个begin和end的起始和终止的时间

**Comment by dbc1129** [comment]
https://rtmp01open.ys7.com:9188/v3/openlive/J79588289_1_2.flv?expire=1686377513&id=587282726444535808&t=5ebd0ba1073b4da4acf6e9bb082723ffedcdc9bd252d80230476433b5c3ecef5&ev=100
这个是直播流

https://rtmp01open.ys7.com:9188/v3/openpb/J79588289_1_2.flv?begin=20230605152603&end=20230605160651&expire=1686377484&id=587282606475714560&rec=local&t=927905a383bdffb9f204bfdd30231c232a65eb765beec03eaa5ad574d2a0e5a5&ev=100
这个是用来回放的流

**Comment by gemxx** [comment]
看了下回放流的编码，缺少了flv scriptdata tag 。flv.js 依赖该信息返回回放流的总时长(duration)，回放流的编码加一下信息就可以展示总时长了。

**Comment by dbc1129** [comment]
能不能再具体说明一下回放流上应该怎么加一下flv scriptdata tag这个信息

**Comment by gemxx** [comment]
可以看下[video_file_format_spec_v10.pdf](https://rtmp.veriskope.com/pdf/video_file_format_spec_v10.pdf)规范中，对于scriptdataobject的描述，结合代码中需要的信息添加。具体的编码器如何设置这里不给出指引

**Comment by dbc1129** [comment]
回放的视频流是萤石云提供的，询问之后他们给的回复是不支持，没办法在回放流上添加这个信息，可以直接在xgplayer这里直接给他设置总时长吗？这样会不会也可以实现拖动问题

**Comment by gemxx** [comment]
除了duration，如果需要seek还需要返回keyframes信息，seek时需要找到所在点的关键帧开始推送音视频数据。所以最好的方式，还是在编码时就返回完整的meta信息，用以播放点播数据
