### ISSUE TITLE
清晰度切换配置有问题，默认是360p切换成720仍然显示360p

### ISSUE THREAD

**Issue by gitcyh** [bytedance/xgplayer#959]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
提供下播放器的配置

**Comment by ryuujo1573** [comment]
这个问题 [官网 demo ](https://h5player.bytedance.com/generate/)就可以复现。

**Comment by gitcyh** [comment]
> 提供下一个播放器的配置

就是最新版才有这个问题

**Comment by gitcyh** [comment]
> 这个问题[官网演示](https://h5player.bytedance.com/generate/)就可以复现。

是的官网就可以复现，希望尽快解决

**Comment by ryuujo1573** [comment]
@gitcyh 
As for now, you can try this patch:
```ts
import { Events } from 'xgplayer'
```
```ts
player.on(Events.DEFINITION_CHANGE, (e) => {
  const def = document.querySelector('.xgplayer-definition .icon-text')!
  def.textContent = e.to.name
})
```
