### ISSUE TITLE
播放m3u8出现buffer错误Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

### ISSUE THREAD

**Issue by susanforme** [bytedance/xgplayer#964]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

    "xgplayer": "^3.0.4",
    "xgplayer-flv": "^3.0.4",
    "xgplayer-hls": "^3.0.4",
    "xgplayer-mp4": "^3.0.4",
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
chrome 最新版本

**如何复现问题？ How to reproduce the problem?**
播放m3u8一段时间后
![image](https://github.com/bytedance/xgplayer/assets/51266600/9fbad35f-6fd8-4296-8581-df274f9a3c1a)

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**
播放一段时间后抛出错误
![image](https://github.com/bytedance/xgplayer/assets/51266600/79ff5994-24da-4729-addf-bc56012d4bff)

配置
```js
        {
 id: id ?? 'videoElement',
          // isLive: true,
          playsinline: true,
          url: origins[0].url,
          autoplay: true,
          autoplayMuted: true,
          lang: 'zh-cn',
          pip: true,
          fluid: true,
          //@ts-ignore 官方类型错误
          playbackRate: false,
          cssFullscreen: false,
          screenShot: {
            saveImg: true,
            quality: 0.92,
            type: 'image/png',
            format: '.png',
          },
          plugins,
          height: '100%',
          width: '100%',
}
```

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
方便提供下测试流地址吗？看起来和流码率过高有关

**Comment by susanforme** [comment]
> 方便提供下测试流地址吗？看起来和流码率过高有关
码率388849 ,流地址是内网没法提供

**Comment by gemxx** [comment]
编码是264，分辨率1080P是吗？另外再提供下HlsPlugin的配置

**Comment by susanforme** [comment]
> 编码是264，分辨率1080P是吗？另外再提供下HlsPlugin的配置

流信息如下
![image](https://github.com/bytedance/xgplayer/assets/51266600/acfe7b4e-032c-4863-a538-85256110cb8b)

```js
{
          hls: {
            retryCount: 3, // 重试 3 次，默认值
            retryDelay: 1000, // 每次重试间隔 1 秒，默认值
            loadTimeout: 10000, // 请求超时时间为 10 秒，默认值
            fetchOptions: {
              // 该参数会透传给 fetch，默认值为 undefined
              mode: 'cors',
            },
            targetLatency: 10, // 直播目标延迟，默认 10 秒
            maxLatency: 20, // 直播允许的最大延迟，默认 20 秒
            disconnectTime: 0, // 直播断流时间，默认 0 秒，（独立使用时等于 maxLatency）
            // fixAudioTimestampGap: false, //填充静默音频帧以避免检测大音频时间戳间隙时A / V
            // enableWorker: true, // 是否多线程工作
            // enableStashBuffer: true, //启用IO Stash缓冲区。 如果您需要实时（最小延迟），则设置为false，但如果有网络抖动可能会停止
            // stashInitialSize: 10240, // 缓存大小(kb)  默认384kb 128kb
            // reuseRedirectedURL: true, //重用301/302重定向url，用于随后的请求，如查找、重新连接等。
            // autoCleanupSourceBuffer: false, //自动清除缓存
            // lazyLoad: false, //如果有足够的数据用于播放，则中止 http 连接
            // deferLoadAfterSourceOpen: false, //在MediaSource sourceopen事件触发后加载。在Chrome上，在后台打开的标签页可能不会触发sourceopen事件，除非切换到该标签页。
          },
}
```

**Comment by amihhs** [comment]
这个问题是`QuotaExceededError`导致，我们可能需要一个像`flvPlugin`中类似的处理。我不太确定HlsPlugin中现在是否包含了相关内容 @gemxx 
![image](https://github.com/bytedance/xgplayer/assets/59364234/d7741c67-1750-47ed-a05e-c6ca714df3be)

**Comment by amihhs** [comment]
这个问题触发后，会导致SoureBuffer数据无法正常的remove（即使缓存的数据已经播放完成也无法remove），同时会导致后续视频无法再继续缓存，从而带着视频基本只能播放现存的SoureBuffer数据。

**Comment by twoer** [comment]
我最近播放 flv 视频时，也遇到了这个错误！

**Comment by xiyuyizhi** [comment]
@susanforme @amihhs 更新下最新版本

**Comment by bbhxwl** [comment]
我也是这样，播放一会以后，出这个错误，倒不是一直这个错误。很奇怪。
