### ISSUE TITLE
hls播放m3u8的源，同样的配置，期望静音在IOS中没生效，在安卓中正常

### ISSUE THREAD

**Issue by wxamlzm** [bytedance/xgplayer#966]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.1",
    "xgplayer-hls": "^3.0.4"

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
  IOS16.5中企业微信浏览器下

**如何复现问题？ How to reproduce the problem?**
 new Player({
        plugins: [HlsPlugin],
        id: `mse`,
        url,
        fluid: true,
        volume: 0,
        enableContextmenu: true,
        closeVideoClick: true,
        disableProgress: false,
        allowSeekPlayed: true,
        autoplay: true,
        controls: true
      })配置volumn为0，然后在安卓和IOS中分别打开

**您期望的播放器正常行为是？ What did you expect to happen?**
  期望自动播放但默认静音

**实际播放器的表现是？ What actually happened?**
 安卓端正常实现了，IOS端有自动播放同时在volume配置为0的时候，有声音播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
ios 设置 volume 不起作用。可以通过播放器实例静音 `player.muted = true` 或者增加配置 `autoplayMuted: true`

关于autoplayMuted: https://h5player.bytedance.com/config/#autoplaymuted

**Comment by wxamlzm** [comment]
已按回复解决，谢谢
