### ISSUE TITLE
记忆播放配置没生效或者配置冲突

### ISSUE THREAD

**Issue by wxamlzm** [bytedance/xgplayer#973]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
    "xgplayer": "^3.0.1",
    "xgplayer-hls": "^3.0.4"
**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
   windows10; chrome114;

**如何复现问题？ How to reproduce the problem?**
  new的时候按文档配置了视频起播时间

```
new XGPlayer({
        plugins: [HlsPlugin],
        id: 'detailVideo',
        url,
        fluid: true,
        volume: 0.6,
        enableContextmenu: true,
        disableProgress: false,
        allowSeekPlayed: true,
        autoplay: true,
        lastPlayTime: 20, // 视频起播时间（单位：秒）
        lastPlayTimeHideDelay: 5 // 提示文字展示时长（单位：秒）
      })
```

**您期望的播放器正常行为是？ What did you expect to happen?**
  按文档描述，我的理解是从20秒的位置开始播放视频

**实际播放器的表现是？ What actually happened?**
 依旧是从0开始播放

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by wxamlzm** [comment]
用这个方法是可以实现的，https://github.com/bytedance/xgplayer/issues/259#issuecomment-546284787
但还是想了解下为啥按文档的配置没能生效

**Comment by gemxx** [comment]
v3版本的启播时间点配置是 `startTime`，单位为秒。参见：https://h5player.bytedance.com/config/#starttime
 ```
new window.Player({
      id: 'mse',
      url: '//sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8',
      autoplay: true,
      playsinline: true,
      startTime: 9,
      plugins: [HlsPlugin]
  });
```

**Comment by wxamlzm** [comment]
感谢，已按回复处理成功

**Comment by chenyanwen1993** [comment]
设置startTime，再ios上无论怎么拖动进度条，视频没有变化
