### ISSUE TITLE
android webview视频无法全屏播放

### ISSUE THREAD

**Issue by aurora-lch** [bytedance/xgplayer#974]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.2

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
android webview

**如何复现问题？ How to reproduce the problem?**
正常视频播放，点击全屏播放

**您期望的播放器正常行为是？ What did you expect to happen?**
正常播放

**实际播放器的表现是？ What actually happened?**
webview、播放器卡住，控制台无任何报错。调试显示 窗口处于非活跃状态

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
Android Webview 需要进行配置才能进行横屏，大致原理可以参看这个[stackoverflow issue](https://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview/56186877#56186877)。需要结合您的webview实际情况进行改造配置

**Comment by aurora-lch** [comment]
好的，感谢
