### ISSUE TITLE
v3文档部分内容错误

### ISSUE THREAD

**Issue by hanyanjun** [bytedance/xgplayer#976]
您使用的西瓜播放器版本是多少？

3.0.4

您使用的操作系统和浏览器分别是？

OS Chrome

问题如下 ：

问题截图
<img width="1400" alt="image" src="https://github.com/bytedance/xgplayer/assets/20179986/48fe549c-8906-45ef-983d-ce8903eb3d03">

地址： http://h5player.bytedance.com/plugins/extension/third-party-plugin.html#xgplayer-flv-js

描述：关于 xgplayer-hls.js 的安装部分文档的install 命令 （npm istall xgplayer-hls.js@alpha） install拼写错误

**Comment by gemxx** [comment]
感谢指正，已修复
