### ISSUE TITLE
可以播放m4s的切片吗？貌似不行，但是VLC播放器可以播放这种视频流

### ISSUE THREAD

**Issue by gitcyh** [bytedance/xgplayer#988]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**

**如何复现问题？ How to reproduce the problem?**

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by gemxx** [comment]
您是想播放 Dash 格式的码流吗？我们有 https://www.npmjs.com/package/xgplayer-dash 可以支持
