### ISSUE TITLE
v3 版本文档错误

### ISSUE THREAD

**Issue by itchaox** [bytedance/xgplayer#991]
问题：v3 版本文档错误

位置：插件 -> 扩展插件 -> xgplayer-hls

![image](https://github.com/bytedance/xgplayer/assets/81410510/93ab74c5-db75-43d7-8577-242c0c866d51)

**Comment by gemxx** [comment]
感谢指正，已修复

**Comment by itchaox** [comment]
问题：v3 版本文档图片展示失效

位置：插件 -> 内置插件挂载配置 -> 枚举值
@gemxx 
![image](https://github.com/bytedance/xgplayer/assets/81410510/ac81b5fc-587f-4f38-a0ff-d22d1831417b)
