### ISSUE TITLE
引用本地css时，播放器全黑、不显示视频内容

### ISSUE THREAD

**Issue by passcar** [bytedance/xgplayer#992]
开发环境：
    1、node v16.17.1；
    2、HBuilder v3.8.7.20230703构建的vue3项目；
    3、npm install xgplayer@3.0.5
    4、Firefox Developer Edition v115.0b9 (64 位)；Google Chrome v114.0.5735.199（64 位）；Microsoft Edge v116.0.1938.1 dev (64 位)
 存在的问题：
    引用本地css时，播放器全黑、不显示视频内容；
    使用@import url('https://unpkg.byted-static.com/xgplayer/3.0.0-next.42/dist/index.min.css')这种方式引入css则无异常。

[videoPlayer.txt](https://github.com/bytedance/xgplayer/files/11943585/videoPlayer.txt)

**Comment by gemxx** [comment]
试试把scoped属性去掉

**Comment by passcar** [comment]
> 试试把scoped属性去掉

谢谢，这个方法也解决不了

**Comment by hongqx** [comment]
> > 试试把scoped属性去掉
> 
> 谢谢，这个方法也解决不了

是不是打包工具的配置中，css-loader把node_moudules给exclude了，尝试一下将node_moudules/xgplayer 配置成include试试
