### ISSUE TITLE
播放器获取累计播放时长cumulateTime不准确，并且文档中存在错误

### ISSUE THREAD

**Issue by yuguaa** [bytedance/xgplayer#996]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
V3.0.4

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
win10 chrome最新版

**如何复现问题？ How to reproduce the problem?**
通过timeUpdate的监听中打印cumulateTime即可看到

**您期望的播放器正常行为是？ What did you expect to happen?**

**实际播放器的表现是？ What actually happened?**

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by yuguaa** [comment]
![image](https://github.com/bytedance/xgplayer/assets/58333667/7a9cb621-9399-44d0-ac13-93c02e8da8f7)
![image](https://github.com/bytedance/xgplayer/assets/58333667/da38a3df-49c8-48a7-95b5-356109b7062a)

**Comment by hongqx** [comment]
> cumulateTime

该问题已经在3.0.9中修复，辛苦check一下
