### ISSUE TITLE
flv支持h265播放问题

### ISSUE THREAD

**Issue by fengyunyang** [bytedance/xgplayer#998]
我使用的是最新版的西瓜播放器，且用的是google最新的浏览器，也检查了浏览器支持h265解码。

下面是视频直播流地址：
https://rtmp03open.ys7.com:9188/v3/openlive/J72654322_1_2.flv?expire=1719755846&id=597184359736279040&t=49f99f2cd947182a7cc871215dc14b14bfb24f840f8b3e86486553e165f1b7fc&ev=100

请问具体是什么问题？

**Comment by gemxx** [comment]
需要配合 xgplayer-flv 插件播放flv格式，请参考[官网flv插件的使用方式](https://h5player.bytedance.com/plugins/extension/xgplayer-flv.html)。以下为播放器初始化方法：

```JS
let player = new window.Player({
    id: 'mse',
    isLive: true,
    playsinline: true,
    url: 'https://rtmp03open.ys7.com:9188/v3/openlive/J72654322_1_2.flv?expire=1719755846&id=597184359736279040&t=49f99f2cd947182a7cc871215dc14b14bfb24f840f8b3e86486553e165f1b7fc&ev=100',
    autoplay: true,
    height: window.innerHeight,
    width: window.innerWidth,
    plugins: [window.FlvPlayer]
});
```

**Comment by fengyunyang** [comment]
https://rtmp01open.ys7.com:9188/v3/openlive/J94623434_1_2.flv?expire=1721986665&id=606541092862566400&t=def6a07381f9481486766839ae37c63fb5f775eeeb92d408be49998db6c64e03&ev=100
您看一下这个，我这里按照您的方式加载进去，是这样的。这是萤石云的问题吗？
![image](https://github.com/bytedance/xgplayer/assets/50264528/fe889e4d-7d63-4725-8966-7206e280d93f)

**Comment by gemxx** [comment]
是的，目前你的流已经能播放了，只不过返回画面如你截图所示

**Comment by fengyunyang** [comment]
好的好的
